### ISSUE TITLE
Opravit Right Message text

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#101]
http://kramerius.mzk.cz/search/api/v5.0/info
Odkaz na obrazek je uveden relativne:
`<img src="samolepka.jpg">`
Tohle bude fungovat jen v K4 klientovi.
Zmenit na
`<img src=http://kramerius.mzk.cz/search/samolepka.jpg">`

Mozna bude lepsi obrazek presunout na www.mzk.cz a linkovat tam.

**Comment by leiblix** [comment]
Hotovo. Nechal jsem to na kramerius.mzk.cz, ale nevidím v tom problém.
