### ISSUE TITLE
Neverejny rocnik

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#102]
www.digitalniknihovna.cz/mzk/periodical/uuid:259f2cc0-973f-11e4-b7ae-001018b5eb5c
Proc je rocnik 1916 neverejny, kdyz vsechny mladsi (i starsi) rocniky jsou verejne?

**Comment by Jenyk** [comment]
Zveřejněno

**Comment by LenkaKravecova** [comment]
Odpoved je jednoducha. Prisel do Krameria jako neverejny a neprisla jsem na to.
