### ISSUE TITLE
veřejná monografie s neveřejnými stránkami

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius#103]
http://www.digitalniknihovna.cz/mzk/view/uuid:6ee6c380-4dc5-11e3-9c86-005056827e51?page=uuid:8a333be0-8cf0-11e3-bbb0-5ef3fc9bb22f
Při hledaní a filtrování "jen veřejné" se titul zobrazí, ale stránky veřejné nejsou.

**Comment by Jenyk** [comment]
Dostupnost ve fedoře a v solr neseděla, po reindexaci je to ok (neveřejné).
Ale možná by to mělo být veřejné, @LenkaDamborska ?
