### ISSUE TITLE
RSS a digitalniknihovna.cz

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#104]
Upravit RSS dle konfigurace Krameria tak aby neukazovalo na /search ale na nového klienta, ať je to kterýkoli.

**Comment by leiblix** [comment]
A fakt RSS ještě dnes používá :-)? 

Jinak je pravda, že na ta RSS je je odkaz i v API a můžou to používat ostatní klienti. Těžké by to být nemělo.

**Comment by LenkaKravecova** [comment]
Po dohodě s @zabak to nebudeme dělat.
