### ISSUE TITLE
sklízení obálek a obsahů pro obálky knih

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#105]
Budeme k tomu muset udělat schůzku s programátory obálek knih. 
Cílem je předat bibliografický záznam (resp. identifikátory) a stránky obálky a obsahu (případně titulní list - resp. reprezentativní stránku) a pokud jsou označené tak i stránky s rejstříkem. Včetně OCR. U časopisů i obálky jednotlivých čísel a případně obsahy, pokud existují. Měli bychom ale rozlišit noviny a časopisy (podle počtu čísel v ročníku?)
Bude nutno řešit:
- jak obálky knih získají seznam titulů (je lepší OAI nebo obdoba replikace pro ČDK, nebo jiný postup?). Musí se pravidelně aktualizovat, protože nám docházejí čísla periodik do Krameria v náhodném pořadí.
- jak přenášet obrázky samotné? Asi se to bude brát z imageserveru. 
- mělo by se zároveň v Krameriu řešit odemknutí obálek a obsahů (v souladu s autorským zákonem)
- z metadat musí být jasné, jestli je dokument volný (nebo částečně volný ale dostatečně k tomu, aby mělo smysl ho linkovat z jiných knihoven)

**Comment by leiblix** [comment]
> jak obálky knih získají seznam titulů (je lepší OAI nebo obdoba replikace pro ČDK, nebo jiný postup?). Musí se pravidelně aktualizovat, protože nám docházejí čísla periodik do Krameria v náhodném pořadí.

Přes API Krameria

> jak přenášet obrázky samotné? Asi se to bude brát z imageserveru. 

IIIF API image, jednoduchým dotazem je možné získat jpeg v plném rozlišení, stačí to?

> mělo by se zároveň v Krameriu řešit odemknutí obálek a obsahů (v souladu s autorským zákonem)

Je nějaký způsob jak poznám, že se jedná o obálku nebo o obsah?

**Comment by zabak** [comment]
Je to uvedeno v typu stránky. Zatím není označovaná reprezentativní stránka dokumentu, takže bude těžké poznat, kdy je vhodné použít místo obálky titulní list.

**Comment by LenkaKravecova** [comment]
Jak moc do budoucna to má být řešeno? Budeme to muset zařadit do fronty. Odhad, kdy se k tomu dostaneme, dodám později.

**Comment by honza-rychtar** [comment]
U toho odemknuti obalek a obsahu. Tohle je potreba promyslet! Koliduje to se soucasnym postupem, kdy by se mel dokument (nebo jeho cast) oznacit jako verejny, pokud obsahuje alespon jednoho verejneho potomka.
Jakmile zverejnite obalky, tak budou vsechny dokumenty oznacene jako verejne.
To by se dalo vyresit tim, ze "alespon jeden verejnym potomek" by se nevztahoval na stranky.

Druha vec je urcita zmatenost pro uzivatele, kdy by se mu u kazdeho dokumentu zobrazovala obalka a obsah a jakmile by zalistoval, tak by mu vyskocia hlaska "dokument neni verejne dostupny".
Lepsi je zobrazit hlasku hned i na ukor nezobrazeni obalky (pripadne by na to byla nejaka akce - "zobrazit obsah a obalku neverejneho dokumentu)".

Zverejneni obalek neverejnych dokumentu nema pro uzivatele prakticky zadny prinos. Takze mysleme na to, abychom kvuli teto moznosti (ktera je uzivatelum k nicemu) zbytecne nezkomplikovali stavajici chovani.

**Comment by zabak** [comment]
Autorský zákon říká že mohou být zpřístupněny a u obsahu má zpřístupnění i smysl. Ale není to priorita. Důležité je domluvit vhodný postup jak Kramerius sklízet.

**Comment by honza-rychtar** [comment]
Ano, autorsky zakon to rika. Ano, ma to smysl. Jen je potreba si promyslet co se stane, kdyz se obalky zpristupni.
Honza spousti skripty, ktere meni priznak verejnosti z neverejneho na verejny takovym dokumentum, ktere maji alespon jednoho verejneho potomka 
Pokud by se bez dalsiho premysleni zpritupnily obalky a obsahy, tak to sice bode cool, ze jsou viditelne pro uzivatele, ale kompletne se rozbije funkcionalita.
Tady by se pak melo pravidlo nastavit presne naopak - primy rodic obsahujici stranky je neverejny, pokud obsahje alespon jednu neverejnou stanku.
Jinymi slovy. Oznacit noviny jako verejne, kdyz obsahuji nejaky verejny rocnik je dobre.
Oznacit dokument za verejny, pokud obsahuje jen par verejnych stranek je spatne.
Dal narazime na chovani klientu - hlaska je vetsinou "Tento DOKUMENT neni verejne pristupny" - tady se uz ale dostavame na urovne konkretnich stranek. 
Jako prioritu bych opravdu videl zpristupneni periodik a ricniku, ktere jsou autorsky volne a stale jsou oznaceny za neverejne (to neni jen v MZK, to je vsude!) Tady jde o miliony stran ucelenych autorsky vonlych dokumentu! Resit zverejneni jednotek stran u tisicu nevejnych dokumentu je vuci tomu nic ....

**Comment by leiblix** [comment]
> Honza spousti skripty, ktere meni priznak verejnosti z neverejneho na verejny takovym dokumentum, ktere maji alespon jednoho verejneho potomka 

Řekl bych, že @Jenyk to stejně nejspíš neprochází dolu až na úroveň stránek, nemělo by to smysl a bylo by to pomalé. @Jenyk Je to tak?

> Jako prioritu bych opravdu videl zpristupneni periodik a ricniku, ktere jsou autorsky volne a stale jsou oznaceny za neverejne (to neni jen v MZK, to je vsude!) 

Souhlasím

Ale proti schůzce s programátory obálek nic nemám, víme vlastně co po nás chtějí a jestli to potřebují? Vím, že mi od nich dříve občas přistál mail a řešili jsme API, ale jestli z toho něco použili, to už nevím.

**Comment by zabak** [comment]
Víme co potřebují - obsahy a obálky včetně OCR. Loni se začalo analýzou, letos se (snad) bude programovat.

**Comment by Jenyk** [comment]
Náš skript na zpřístupňování rodičů kontroluje jen první stránku a hlavně jsem ho spouštěl jen nad periodiky.
Není problém stránky ignorovat úplně, případně bych se mohl dívat na jednu stránku někde uprostřed.
Ale Honza má pravdu že by se v tomhle dala lehce udělat chyba a zpřístupnit něco, co má být neveřejné.

**Comment by leiblix** [comment]
> Víme co potřebují - obsahy a obálky včetně OCR. Loni se začalo analýzou, letos se (snad) bude programovat.

@zabak Nevíš, jestli budou něco potřebovat?

**Comment by leiblix** [comment]
Bylo vyřešeno. Je to v distribuci a u nás zapnuto.
