### ISSUE TITLE
Problémy Krameria (nejspíš nové verze)

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#108]
Nevím, jestli vše souvisí s přechodem na Kramerius 5.3.3, ale děje se následující:
- nefunguje generování PDF  !! Už se ozvalo několik lidí.
- nefunguje editor uživatelů 
- často procesy se stavem NOT RUNNING 
- něco dalšího?

@MartinRumanek, @jirikrepl, @Jenyk - vyhlašuju stav nouze. Je to potřeba co nejdřív opravit. Dejte, prosím vás, hlavy dohromady. S těmi procesy nemůžeme prakticky nic dělat, všechno musíme dokola spouštět znova a ještě ani nevíme, nad jakým uuid se to spustilo. Negenerování PDF je hodně blbé. Jestli je to na Incad, tak mi dejte vědět - založím issue. Díky!

**Comment by LenkaKravecova** [comment]
@Jenyk Pamatuješ si, co to bylo za problém s tím stavem Not running tehdy na FSV? Dnes už je to tam zas.

**Comment by LenkaKravecova** [comment]
Generování PDF zprovozněno použitím čisté instalace bez úprav pro MZK. Editor uživatelů zprovozněn (včetně problému s postgresem, kvůli kterému nefungovala registrace uživatelů).
Zbývají procesy se stavem Not running.

**Comment by Jenyk** [comment]
Not running: už se to děje delší dobu (už před upgradem na 5.3.3)
V jednu chvíli začnou všechny nově spuštěné procesy přecházet do stavu not running a na čas pomůže jen restart tomcatu. Kramerius dává stav not running procesům, které mají být spuštěné, ale nemají v DB PID.
Spouštění procesů: kramerius periodicky kontroluje stavy procesů - doběhlo něco? je potřeba něco spustit? atd. Při plánování se do DB uloží parametry procesu, PID je v tu dobu prázdné. Když kramerius proces spustí, přepne ho do stavu running. První, co proces dělá, je že uloží svůj PID (fakt pid procesu běžícího na stroji, kde běží kramerius) do DB. Když kramerius při další periodické kontrole zjistí, že proces běží, ale PID v DB je pořád null, přepne ho do stavu not running. 
Běžně se to stává když proces čeká na připojení debuggeru - kramerius už ho spustil a očekává pid, ale proces zatím fakticky neběží a pid neuložil.
V případě tohohle problému se procesy přestanou spouštět - pro krameria jsou spuštěné, ale fakticky neběží, nemají tedy pid a ani se nedají debugovat (na daném portu nic neběží, nečeká).
