### ISSUE TITLE
Zprávy z gmail účtu chodí bez diakritiky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#109]
Při změně hesla, registraci atp.
Např.:
Pro aktivaci u?ivatele (....) je nutn? kliknout na n?sleduj?c? link

**Comment by LenkaKravecova** [comment]
A teď zas přišel s diakritikou :/ takže jak kdy

**Comment by jirkadev** [comment]
V listopadu mi diakritika nefungovala. Teď 'Aktivační email' i 'email při vygenerování nového hesla' má diakritiku v pořádku. Funguje v pořádku na seznam.cz gmail.com i webmail.mzk.cz

Zatím zavírám
