### ISSUE TITLE
API: pridat dotaz na verzi API a dalsi informace

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#11]
Data: nazev knihovny, gps souradnice knihovny, nejaky popis co digitalni knihovna obsahuje. email spravce, verzi API, .....
Tohle info by pak vyplnil admin konkretniho Krameria.
A dalo se na ty informace zeptat napr. pres kramerius.mzk.cz/search/api/v5.0/info

Ted knihovny pisou nejake dodatecne texty, ktere jsou ve starem klientovi pod zalozkou "informace".
Pokud by to bylo pristupne pres API, pak by se to dalo automaticky generovat vsude - Android/iOS/Web

**Comment by honza-rychtar** [comment]
Zkuste protlacit do dalsi verze krameria ten dotaz na verzi API
Rostouci funkcionalita uz bude zavisla na verzi - v tuhle chvili je bud verze < 5.1.1, pak to cele nefunguje nebo verze 5.1.1, pak to cele funguje.

Treba nahlasovani chyb v datech se bude delat pres nejake tlacitko na vetsine obrazovkach - tak at tam nevisi i pokud nema prohlizeny Kramerius dostatecnou verzi.
Pokud bych se hned pri spusteni klienta (a pri prepnuti na jineho krameria) zeptal na verzi, tak bych podle toho dal prizpusobil zobrazeni a funkcionalitu.
Kdyby to bylo uz v pristi verzi, pak bych rozlisil vsechny verze - pokud dostanu 404, tak verze 5.1.1, jinak obsah VERZE {"version" : VERZE}

Taky by se podle toho zobrazovalo tlacitko pro user profile/login - od verze kdy se povoli Authorization hlavicka a zahodi session id .... a dalsi nove veci.

**Comment by leiblix** [comment]
GPS souřadnice tam chceš jedny, nebo umožníme správci jich nastavit více? Např. předpokládám, že Praha má Krameria přístupného z více budov, které jsou roztroušené....

**Comment by leiblix** [comment]
> nejaky popis co digitalni knihovna obsahuje
> Informace o knihovnách jsou lokalizovatelné, je ok, když to vrátíme rovnou všechno (CZ_cs i En_en)_

Dále má administrátor Krameria možnost upravovat "security" text, který se zobrazí u nepřístupného dokumentu (k vidění například zde http://kramerius.mzk.cz/search/i.jsp?pid=uuid:8537a8c6-ad67-480e-b83c-af9fc97358db). Myslím, že to má taky smysl, aby to měl každý jinak - například naše Kramerius počítače jsou polepené speciální nálepkou. 

Z toho vyplývá další otázka, co s obrázky a formátováním...Teď se oba texty zadávají v HTML, ale použít markdown language by bylo možná lepší (administrátorům zůstane možnost základního formátování a vkládání obrázků) a zároveň si to bude moci každý klient naformátovat dle vlastních konvencí. Nebo zakážem formátovat, ale ten obrázek u naší security message je důležitý.

Jak to pojmem?

Testovat je to možné na https://docker.mzk.cz/search/api/v5.0/info, zatím je tam jenom verze, která je jasná a zásadní.

**Comment by honza-rychtar** [comment]
GPS jedny, tohle bych bral spis jako umisteni provozovatele Krameria.
Pokud jde o lokaci, kde se nachazi konkretni dokument, tak to udelam pres sgilu.
Ted mam mapovani SIGLA -> nazev instituce. Pokud pridam i GPS a adresu, tak muzu odkazat uzivatele do konretni budovy pro kazdy dokument zvlast.
Mohla by existovat sluzba, ktera pres siglu vrati info o instituci (jeji casti). Ale teoreticky si to muze kazdy klient resit sam. 
Tohle neni tak dulezite, hlavni je ted ta verze.

Pokud jde o security texty, tak problem s html muze byt treba barva - jeden klient ma tmavy motiv, druhy svetly. Na jednom z nich to nepujde precist. 
Muzem to udelat jako html, ale admini si musi hlidat sami, ze muzou pouzivat jen nektere tagy a nemaji pouzivat styly. h1, ..,h4, p, a, br, hr, img na formatovani staci (nastyluje to pak klient). Adminum budeme duverovat, takze nemusime resit, ze tam bude nejaky skodlivy kod.

To same udelame pro text - informace : http://kramerius.mzk.cz/search/#intro7

**Comment by zabak** [comment]
Existuje autoritativní databáze knihoven  http://aleph.nkp.cz/F/?func=direct&doc_number=000000732&local_base=ADR
tam je spousta těchto informací v Alephu, i ty souřadnice, byť jen jedny.

**Comment by leiblix** [comment]
> Ted mam mapovani SIGLA -> nazev instituce. Pokud pridam i GPS a adresu, tak muzu odkazat uzivatele do konretni budovy pro kazdy dokument zvlast.

To co píše @zabak je zajímavé, ten dotaz se dá položit i přes x-services http://aleph.nkp.cz/X?op=find-doc&doc_num=000000732&base=ADR

Možná se dá ten dotaz poskládat tak, aby se dotaz položil přímo přes siglu, protože minimálně v GUI to jde (http://aleph.nkp.cz/F/?func=direct&doc_number=&local_base=ADR)

@jirislav nevíš, jak takovýto dotaz položit přes x-services? http://aleph.nkp.cz/F/JQK23DS7MNHTDYL9354S12ETQCUK56X8KELN23UGPTX2H52AEL-48441?func=find-b&find_code=WKA&x=0&y=0&request=BOA001&adjacent=N

**Comment by jirislav** [comment]
@MartinRumanek podívám se na to v pátek večer nebo v sobotu ráno, snad to počká ;-)

**Comment by leiblix** [comment]
Maličko jsem s tím pohnul, je tam i ten intro text (další věci přidám později). Je lokalizovaný podle hlavičky prohlížeče. Pokud je to tak v souladu s rest principy, tak bych to tak už nechal.

https://docker.mzk.cz/search/api/v5.0/info

**Comment by jirislav** [comment]
Ok takže jsem na to přišel - zadáš http://aleph.nkp.cz/X?op=find&find_code=wrd&base=ADR&request=sig=boa001
a pak zadáš 
http://aleph.nkp.cz/X?op=present&set_entry=000000001&format=marc&set_no=013401 podle set_number které ti vyhodí první request

**Comment by honza-rychtar** [comment]
V souladu s REST principy to je - vraci se stejny zdroj a ruzna reprezentace, takze lokalizace pres Accept-Language je ok.

Melo by to fungovat stejne napric API.
Lokalizace virtualnich sbirek http://kramerius.mzk.cz/search/api/v5.0/vc/ se resi primo v odpovedi:
"descs":{"en":"Brno Regional Museum","cs":"Muzeum Brněnska"}
Vyhoda tohoto pristupu je, ze pri zmene jazyka se nemusim znova ptat serveru na vysledek, anglickou i ceskou verzi si ulozim hned.

Accept-Language taky asi naboura cachovani, ale to je problem klienta.
Jinak jsem to zkousel volat s Accept-Language: en a vratilo mi to zase popis v cestine. Mas tam ted anglickou verzi?

**Comment by leiblix** [comment]
@honza-rychtar Je to defaultní instalace Krameria, myslím, že nějaký anglický text to default vrací, tak je chyba asi v něčem jiném. Dořeším to s dalšími věcmi nejspíš v úterý.

@jirislav Díky!

**Comment by honza-rychtar** [comment]
@jirislav super!

Tohle muzem pouzit pri verejne nepristupnem dokumentu. Vypise se Nazev instituce, adresa, kontakt, pripadne zobrazeni na mape. To se pak doplni o text, ktery bude specificky pro vybrany Kramerius, ktery se ziska pres to /info

Mohli bychom to pouzit i pro popis instituce u vybraneho Krameria. I kdyz muze mit Kramerius dokumenty z vice fondu, tak se pro kazdeho Krameria vybere primarni sigla.

**Comment by jirislav** [comment]
Rádo se stalo ;)

**Comment by leiblix** [comment]
@honza-rychtar Pokud by tam nebyl CORS, nebo se ti nelíbilo, že se to vrací v XML, tak to můžeme zapracovat do API (kdybys to chtěl, založ mi k tomu issue prosím)

**Comment by honza-rychtar** [comment]
@MartinRumanek uz jsem to mel skoro hotove, ale zapomnel jsem na CORS (testuju v Chrome s --disable-web-security). CORS tam povoleny neni.

Nevim jestli toto patri do API Krameria. Ale byla by fajn nejaka sluzba, ktera by tyhle informace nabizela - aby mela povoleny CORS a vracela vysledky v nejakem lepsim formatu - ne XML a ne MARC. Nejaky lip strukturovany JSON.

Zalozim k tomu issue.

**Comment by leiblix** [comment]
https://docker.mzk.cz/search/api/v5.0/info

Jsou tam patřičné texty a i ten limit na PDF. V případě, že je limit vyplý, vrátí se místo čísla "unlimited".

Může to tak být?

Btw. rightMsg přeložené je, info ne. To je bug krameria, který se projevuje i jinde. Nebudu to řešit jako součást tohoto issue.

**Comment by honza-rychtar** [comment]
Jo, super.
A je to teda tak, ze v "intro" bude toto:
http://kramerius.mzk.cz/search/#intro7
a v rightMsg bude zprava v html, ktere se zobrazi pri neverejnem dokumentu?
Administrator kazdeho Krameria si tyhle dve zpravy nastavuje sam a bude si vedom, kde se v klientovi (klientech) budou vyskytovat - administrator si spravne zobrazeni otestuje sam!

A jeste s tou verzi - "5.1.1-SNAPSHOT" - bude i verze 5.1.1 nebo bude nasledovat 5.1.2?
At to muzu pak porovnavat. Muze tam byt i neco jineho nez "SNAPSHOT"?
Nejlepsi by byla i interni ciselna verze. Ale staci, kdyz budu vedet co se vsechno v nazvu verze muze vyskytnout, aby se to v budoucnu spatne nevyhodnocovalo.
Neco jako vzdy jen x.y.z, pripadne x.y.z-A, kde 
x.y.(z-1) < -x.y.z-A1 < x.y.z-A2 < x.y.z-A3 < x.y.z < x.y.(z+1)*

**Comment by leiblix** [comment]
> A je to teda tak, ze v "intro" bude toto:
> http://kramerius.mzk.cz/search/#intro7
> a v rightMsg bude zprava v html, ktere se zobrazi pri neverejnem dokument

jo, je to tak

> A jeste s tou verzi - "5.1.1-SNAPSHOT" - bude i verze 5.1.1 nebo bude nasledovat 5.1.2?

To presne nevim, ted se to ma tak, ze oficialne 5.1.1 jeste nevysla, tak ocekavam, ze oficailni 5.1.1 teprve bude (zatim to tak driv vzdy bylo, ale snapshoty si nikdo krome nas nenasazoval]. To snapshot tam je, kdyz se to buildi ze zdrojaku a nic jineho by tam byt nemelo.

**Comment by honza-rychtar** [comment]
Ok, ale tim padem nemusi byt SNAPSHOT jako SNAPSHOT :) - Vybuildim si verzi 5.1.1-SNAPSHOT, pak se prida nova ficura a nekdo jiny si vybuildi 5.1.1-SNAPSHOT, nazev verze mame stejny, ale u me tam chybi vlastnost, kterou ten druhy uz ma ...

5.1.1-SNAPSHOT ma ted KNAV, Usti nad Labem, Hradec Kralove a Olomouc (MZK a NDK nepocitam), takze vlastni buildy uz jsou nejspis bezne.
Tyhle knihovny uz maji povoleny CORS.
Zatim to asi budu hlidat, ale az se to ustali, tak budu delat prevod:
x.y.z-SNAPSHOT --> x.y.(z-1) ...takto se zaruci, ze se nebude pristupovat k vecem, ktere jeste dana verze nema, ale za cenu toho, ze ztrati nejakou funkcionalitu, na kterou uz je diky SNAPSHOTu ready.

**Comment by leiblix** [comment]
mergnuto v distribuci (https://github.com/ceskaexpedice/kramerius/pull/252)
