### ISSUE TITLE
Stav not_running

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#110]
Problém s nastavením debuggeru je vyřešený, ale stav not_running se stále vyskytuje. Při snaze indexovat některé kolekce nahrávek (u kterých byly opraveny vazby a je potřeba je reindexovat), se objevuje stav not_running.
Třeba Oh, Kay: http://kramerius.mzk.cz/search/handle/uuid:59e708b6-c462-4610-90c5-ac5ca030050a nebo Pohřeb presidenta osvoboditele: http://kramerius.mzk.cz/search/handle/uuid:206aac01-e915-4806-a828-324d3d8ee525

Tahla rozbitá kolekce se ale indexovat podařila: http://kramerius.mzk.cz/search/handle/uuid:7345298e-1a44-4deb-9cb8-a2b27ad4ae9e

**Comment by LenkaDamborska** [comment]
#108

**Comment by LenkaKravecova** [comment]
Řešilo se v #108, zakládám nové issue. 
@Jenyk psal:
Not running: už se to děje delší dobu (už před upgradem na 5.3.3)
V jednu chvíli začnou všechny nově spuštěné procesy přecházet do stavu not running a na čas pomůže jen restart tomcatu. Kramerius dává stav not running procesům, které mají být spuštěné, ale nemají v DB PID.
Spouštění procesů: kramerius periodicky kontroluje stavy procesů - doběhlo něco? je potřeba něco spustit? atd. Při plánování se do DB uloží parametry procesu, PID je v tu dobu prázdné. Když kramerius proces spustí, přepne ho do stavu running. První, co proces dělá, je že uloží svůj PID (fakt pid procesu běžícího na stroji, kde běží kramerius) do DB. Když kramerius při další periodické kontrole zjistí, že proces běží, ale PID v DB je pořád null, přepne ho do stavu not running.
Běžně se to stává když proces čeká na připojení debuggeru - kramerius už ho spustil a očekává pid, ale proces zatím fakticky neběží a pid neuložil.
V případě tohohle problému se procesy přestanou spouštět - pro krameria jsou spuštěné, ale fakticky neběží, nemají tedy pid a ani se nedají debugovat (na daném portu nic neběží, nečeká).
