### ISSUE TITLE
Rovnost - prázdný ročník 1945

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#111]
Prázdný ročník 1945 http://kramerius.mzk.cz/search/handle/uuid:2f3eafe4-cc29-490d-9d54-e12223a27cd2 asi stále obsahuje vazby na čísla, které jsou v tom "správném" ročníku 1945. Nemůžu tento ročník smazat. 
@Jenyk, asi není jiná možnost, než ty vazby ručně smazat ve Fedoře, co? Už jsem to reindexovala, obávám se ale, že ty vazby tam furt jsou. Díky.

**Comment by Jenyk** [comment]
Ročník byl v pořádku bezdětný, smazal jsem ho z krameria a všechno je ok.
