### ISSUE TITLE
UUID ke zveřejnění

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#115]
Další pěkný seznam z NK ke zveřejnění - jsou to novinky i starší věci. 
[uuid_NK_zverejnit.txt](https://github.com/moravianlibrary/kramerius/files/303046/uuid_NK_zverejnit.txt)

**Comment by jirkadev** [comment]
Musíme počkat na stabilní verzi Krameria.

**Comment by xburda4** [comment]
Ďaľší pekný zoznam z NK je zverejnený.
