### ISSUE TITLE
První strana v generovaném PDF

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#116]
Odkud se bere první informační strana v generovaném pdfku? Upravila jsem všechny tyto soubory: first_page, first_page_CZ_cs, first_page_html, first_page_html_CZ_cs, first_page_xml, first_page_xml_CZ_cs, ale ani u jednoho se změna neprojevila. Odněkud se to brát musí, potřebuji zjistit odkud :)

**Comment by leiblix** [comment]
Tento text se mění v souborech

```
first_page_nolines_xml
first_page_nolines_xml_CZ_cs
first_page_nolines_xml_EN_en
```

Soubory jsem v naší instalaci založil.

**Comment by LenkaKravecova** [comment]
Super, upravila jsem to a funguje to. Díky.
