### ISSUE TITLE
Chybí kolekce nahrávek Zločin a trest [1] 

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#117]
Kolekce s tímhle uuid:86943124-5a4a-4679-a887-787ae0006b26 by měla být v Krameriu, ale není. Dokonce jsem ji nenašla ani ve Fedoře. V Krameriu jsem našla nejspíš její prázdné potomky - 2x soundunit a 2x track, které ve Fedoře taky nejsou:
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:df6c2a49-d9f6-40fe-9533-8c96f67fa229&q=
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:e3628025-ed1d-42ef-8d48-ceb6e4037be3&q=
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:02a8cdfd-1536-4278-bf69-a4bd61edd37e&q=
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:8d32d6d3-4e81-4ab3-8b9f-d3b95335d25c&q=

Dá se ještě nějak ověřit, že to ve Fedoře fakt není? Doufám, že to někde je - @Jenyk 
Nemám to ještě potvrzené, ale myslím, že v dubnu to v K5 bylo.

**Comment by Jenyk** [comment]
Ve fedoře to fakt není. Smažu to z indexu?

**Comment by LenkaKravecova** [comment]
Udělala jsem to..

**Comment by LenkaKravecova** [comment]
Zpracováno znovu, obnovení ze zálohy by bylo na dlouho: http://kramerius.mzk.cz/search/handle/uuid:2eb02ddc-335d-40c7-baab-035bdb8b2e0c
