### ISSUE TITLE
Proklik do našeho Alephu

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#118]
Změnit proklik přes čČNB do našeho Alephu. Teď odkaz vede do NK Alephu.  
![proklik_do_katalogu](https://cloud.githubusercontent.com/assets/11834597/16035870/a356ec4a-3219-11e6-925f-e8a6680865a5.jpg)

**Comment by LenkaKravecova** [comment]
V konfiguráku to máme nastaveno dobře. Napíšu issue na Krameria.

**Comment by LenkaKravecova** [comment]
@Jenyk, cože jsi s tím udělal? Zdá se, že už je to ok. Vše, na co jsem teď klikla, mě odkázalo do MZK alephu :) Před těmi 11 dny to ještě odkazovalo do NK.

**Comment by LenkaKravecova** [comment]
Teď mě vše zas odkazuje do alephu NK.

**Comment by LenkaKravecova** [comment]
@Jenyk tak bude to chtít opět opravit, aby to odkazovalo k nám :)

**Comment by LenkaKravecova** [comment]
https://github.com/ceskaexpedice/kramerius/issues/433 
Zatím si to musíme upravovat pokaždé sami v defaultním konfiguračním souboru v rozbaleném warku.

**Comment by leiblix** [comment]
> Zatím si to musíme upravovat pokaždé sami v defaultním konfiguračním souboru v rozbaleném warku.

To už není tak úplně možné, ale postačí upravit kód v branchi https://github.com/moravianlibrary/kramerius/tree/hotfixapi, součástí této větve bude zmíněný konfigurační soubor. Z této větve nyní buildíme Krameria na naši produkci.

**Comment by xburda4** [comment]
V hotfixapi aj v master branchi som to prepísal, v ďalšom builde by sa to malo prejaviť.

**Comment by Jenyk** [comment]
Je nasazený hotfix + máme přesměrování na klienta, takže zavírám.
