### ISSUE TITLE
API: prazdny root_title

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#12]
Narazil jsem na prazdny root_title u newest feedu - konkretne u Krameria z Ceskych Budejovic - http://kramerius.cbvk.cz/search/api/v5.0/feed/newest/
V SOLR taky chybi - http://kramerius.cbvk.cz/search/api/v5.0/search?q=PID:%22uuid:16b224a0-c66b-11e4-8731-1681e6b88ec1%22

Pokud je to nejaky zmatek v jejich datech, tak to neresme. Ale stavat by se to nemelo. Pokud je znamy nazev monografie/mapy/... pak by vzdy mel byt uveden v root_title.
Jinde jsem se s tim nesetkal, v klientovi to udelalo trochu zmatek v zobrazeni. To jsem opravil.

Odkud se bere root_title v SOLR/API?
Je mozne, ze se tyhle pripady budou dal nekde vyskytovat?

**Comment by leiblix** [comment]
Bere se to z DC objektu, který je v root_pid. V DC ten title je, ale jednou prázdný, to nejspíš způsobuje ten problém.

http://kramerius.cbvk.cz/search/api/v5.0/item/uuid:16b1f37c-c66b-11e4-8731-1681e6b88ec1/streams/DC

Že se to bude vyskytovat dál je možné, Kramerius při importu DublinCore nijak nevaliduje.

**Comment by leiblix** [comment]
Můj předpoklad byl správný. CBVK si dokumtny opravili nástrojem xmlstarlet (podobně jako jsem popisoval na https://github.com/moravianlibrary/kramerius/issues/13) a následnou reindexací.
