### ISSUE TITLE
Znemožnění tisku hudebnin na studovnách

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#120]
Viz https://github.com/ceskaexpedice/kramerius/issues/406 
Nám jde jen o chráněné hudebniny (sheetmusic)... Jak by to šlo udělat?

**Comment by jirkadev** [comment]
Díky https://github.com/ceskaexpedice/kramerius/issues/406 máme tři nové akce: `PDF_RESOURCE`, `SHOW_CLIENT_PRINT_MENU` a `SHOW_CLIENT_PDF_MENU`.

Tyto akce chceme zakázat pouze u podmnožiny dokumentů, které jsou `private` a mají model `sheetmusic`.

U podmnožiny dokumentů `private sheetmusic` není možné tyto akce zakázat globálně (v _Nastavení práv globáních akcí_). Práva by se musely nastavit jednotlivě u každého dokumentu.

V Krameriu chybí [podmínka](https://github.com/ceskaexpedice/kramerius/wiki/Prava#krameriem-definovan%C3%A9-dodate%C4%8Dn%C3%A9-podm%C3%ADnky), díky které se mohou tyto akce omezit na výše zmiňovanou podmnožinu dokumentů.

**Comment by jirkadev** [comment]
Knihovna _modelfilter.jar_ byla přidána do nové verze Krameria https://github.com/moravianlibrary/s2i-kramerius/commit/aa0f1d07f0fb39801044c8f28bba029fedb8cde2 (kterou nasadíme místo staré verze)

Na svém PC jsem spustil novou verzi Krameria s knihovnou _modelfilter.jar_ a nastavil pravidla. Vše funguje.

**Comment by LenkaKravecova** [comment]
Toto musíme nastavit v nové instalaci.

**Comment by leiblix** [comment]
Mergnul jsem změnu do s2i-kramerius, mohl by to prosím někdo otestovat a nasadit? :-)

Tzn. 
1) vybuildit znovu s2i-kramerius (z naší branch hotfixapi)
2) otestovat, že je to ok
3) pushnout to na hub.docker.com
4) udělat pull na server a otočit to

**Comment by leiblix** [comment]
Verze s touto změnou je nasazená, zbývá to nastavit.

**Comment by MarosGrm** [comment]
Nové nastavenie je viac-menej funkčné, pri hudobninách typu private sa stále zobrazuje možnosť tisku, ale samotný tisk už nie je možný pretože po odkliknutí stránka vracia chybu: Access to the specified resource has been forbidden.
Bude ešte treba spraviť aby sa možnosť tisku ani nezobrazovala.

**Comment by leiblix** [comment]
V originálním issue se píše:
> Pokud bude funkcionalita v poradku, pridame filter do standardni distribuce.

@kenji1322 Nevíš jestli tu funcionalitu skutečně zařadili do distribuce? Pokud ano, je na místě odstranit tento `hack` - jinak v tom bude zmatek.

**Comment by MarosGrm** [comment]
Neviem. A ono to vlastne nieje hack, práva sú nastavené tak ako sa spomína v originálnom issue pomocou pridanej funckionality. Na kramerius.mzk.cz to funguje správne, tak že pri private hudobninách sa možnosť tisku ani nezobrazuje. Problém je v tom, že na digitalniknihovna.cz sa táto možnosť zobrazí, ale po odkliknutí vracia vyššie spomínanú chybu.

**Comment by leiblix** [comment]
Omylem jsem nenalinkoval v předchozím postu tento řádek
https://github.com/moravianlibrary/s2i-kramerius/blob/master/Dockerfile#L55

Nelíbí se mi, že tam máme tu jar binárku, ke které jsou zdrojáky kdovíkde - může se to takto rozbít a možná by se to pak blbě opravovalo. Ideální by bylo, aby to začlenili do distribuce, jak bylo po otestování slíbeno.

**Comment by leiblix** [comment]
V nové verzi je to už součástí distribuce, je možné tu knihovnu z našeho s2i odstranit.

**Comment by MarosGrm** [comment]
Knihovna je odstranena  moravianlibrary/s2i-kramerius@41cc533f53ac61994501fb508ebf53939c228063

**Comment by leiblix** [comment]
Díky.
