### ISSUE TITLE
Zobrazování OCR

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/kramerius#121]
V kramerius.mzk.cz (http://kramerius.mzk.cz/search/handle/uuid:1fedb880-4b1b-11e3-ae53-5ef3fc9ae867) Chrome Verze 51.0.2704.103 m, Windows 7 se OCR zobrazuje pouze v malém rámečku (viz příloha)
![ocr](https://cloud.githubusercontent.com/assets/3939406/16518765/e6ba1c78-3f84-11e6-9577-b334c1a394fe.jpg)

**Comment by LenkaKravecova** [comment]
Ahoj Jirko, víme o tom. Dohodli jsme se, že už to řešit nebudeme vzhledem k novému klientovi. Dá se to roztáhnout ručně - to pro administraci bude stačit. Díky za pochopení.
