### ISSUE TITLE
Porovnat změny z grafiky a upstreamem Krameria

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#122]
V naších změnách je např.

`<script src="js/mods.js" type="text/javascript" ></script>`

ale soubor je už smazaný a vrací 404. V nových verzích Krameria se tento soubor už nepoužívá.

**Comment by jirkadev** [comment]
Nebudeme to řešit, tak jak jsme se dohodli. Bude se upouštět od větve _mzkgrafika_
