### ISSUE TITLE
Otestovat skript na zpřístupnění dokumentů

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#124]
Skript od P. Šilhavého (KNAV). Má ho @Jenyk.

**Comment by jirkadev** [comment]
Zde je repozitář se skriptem https://github.com/ceskaexpedice/authority

Bude potřeba vytvořit instalaci Krameria, kam se nahraje tento skript

**Comment by MarosGrm** [comment]
Nahradené procesom Aplly moving wall.
