### ISSUE TITLE
Seznam dokumentů v djvu a jpg 

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#125]
Zjistit, co ještě zbývá ve Fedoře - seznam kořenových uuid. Priorita č. 1.

**Comment by jirkadev** [comment]
# Periodika s obrázky ve Fedoře

uuid:249df07d-f383-11df-8d57-0050569e4b0b
uuid:13f650ad-6447-11e0-8ad7-0050569d679d
uuid:ae876087-435d-11dd-b505-00145e5790ea
uuid:73f3e41a-65c9-11e0-b4ae-0050569d679d
uuid:ae81bb20-435d-11dd-b505-00145e5790ea
uuid:ae74c374-435d-11dd-b505-00145e5790ea
uuid:ae79f31b-435d-11dd-b505-00145e5790ea
uuid:ca016b4e-911b-11e0-9943-0050569d679d
uuid:40e2f4dd-91ad-11e0-bf0c-0050569d679d
uuid:fb0dd004-91b1-11e0-bf0c-0050569d679d
uuid:ae7b52cd-435d-11dd-b505-00145e5790ea
uuid:e9b0d09a-ee53-11e0-b48c-0050569d679d
uuid:00c8384e-d7f0-11e1-967e-0050569d679d
uuid:a61884f0-8cbb-11dc-a584-000d606f5dc6
uuid:ae7add8f-435d-11dd-b505-00145e5790ea
uuid:ae864f12-435d-11dd-b505-00145e5790ea
uuid:ae81e235-435d-11dd-b505-00145e5790ea
uuid:ae7b2bbb-435d-11dd-b505-00145e5790ea
uuid:0a0bd530-c20b-11de-a374-000d606f5dc6
uuid:ae7add91-435d-11dd-b505-00145e5790ea
uuid:4b71d2a0-aec3-11de-86df-000d606f5dc6
uuid:02203ad6-32f0-11de-992b-00145e5790ea
uuid:ae722b4f-435d-11dd-b505-00145e5790ea
uuid:a5909f30-a114-11de-9ddf-0013d398622b
uuid:4eac74b0-e92c-11dc-9fa1-000d606f5dc7
