### ISSUE TITLE
Počet spojení do RiTriples

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#127]
Zvýšit maximální počet spojení do fedory, jde-li to

**Comment by leiblix** [comment]
Mělo by to jít (pravděpodobně konfigurace Tomcatu). Při jakých příležitostech současný počet spojení nedostačuje?

**Comment by Jenyk** [comment]
Už vůbec nevím :( Zavírám, budeme řešit, kdyby se to znova vyskytlo.
