### ISSUE TITLE
Jak hromadně opravit něco v metadatech?

### ISSUE THREAD

**Issue by black23** [moravianlibrary/kramerius#13]
Potřebovali bychom opravit siglu v metadatech, protože pochází ze staženéhých záznamů přes Z39.50 a není správně.
Díky

**Comment by leiblix** [comment]
Co z tohoto je ta sigla?

https://gist.github.com/MartinRumanek/fe0516461a658ad7f1b1

Je to <ns2:physicalLocation>UOG505</ns2:physicalLocation>?

**Comment by black23** [comment]
Spravne by tam opravdu melo byt UOG505, ale v K5 je uvedeno umisteni 
 <ns2:recordContentSource authority="marcorg">HKA001/ns2:recordContentSource
Takze bud je tam spatne nejake mapovani nebo nevim :-) z HKA001 je stazeny puvodni biblio zaznam, ale v detailu objektu v Krameriovy to ukazuje take jako umisteni. Divne.

**Comment by leiblix** [comment]
Aha, tak jsem zrovna trefil dokument, kde je to dobře :horse:

Pokud Fedora používá Legacy FS tak se s tím dá dělat celkem jednoduše (s úložištěm Akubra to asi nepůjde, tak je struktura dat jiná).

Fedora má FOXML uložené přímo na filesystému, v tvém případě jsou ty objekty na lokaci /data/fcrepo/objects. Jsou to normální texťáky, které můžeš jakkoliv upravovat. 

Je to svým způsobem nečisté řešení (správně bys měl dělat všechny změny přes API, takto se ti neuloží historie a můžeš si velmi snadno přepsat spoustu dat, takže je potřeba poctivě zálohovat), ale zároveň je to řešení velmi rychlé a efektivní i na větších datech.

Na úpravu se dají použít standardní unixové nástroje, jako find, grep, sed a na xml je velmi silný nástroj xmlstarlet.

Prvně si teda vypíšem jaké sigly tam vůbec máš:
`find /data/fcrepo/objects -type f  -exec xmlstarlet sel -N mods="http://www.loc.gov/mods/v3" -t -v "//mods:physicalLocation" -n  {} +  | sort | uniq -c`

Find najde všechny soubory a parametrem exec je mu předaný příkaz xmlstarlet, který na základě dotazu xpath `//mods:physicalLocation`, vytáhne vždy siglu. 

Z toho vypadne seznam, který pak předám rourou k seřazení a k příkazu uniq, který to omezí na unikátní výsledky a napočítá to.

Výsledek vypadá takto

   6398 
      1 ABA001
      1 BOA001
     61 HKA001
      4 UOG505

(ten první řádek je počet dokumentů, kde ta sigla vůbec není, to jsou zřejmě stránky)

Ty UOG505 jste asi vyplnili ručně. Chceš teda nahradit všechny HKA001 za vaše UOG505

**Comment by black23** [comment]
Slo by vsude to te fyzicko lokace dat UOG505 i na urovni stranek? A aby se to nadale zapisovalo spravne je nutne neco udelat s tou sbalonou?

**Comment by leiblix** [comment]
Aby se to zapisovalo správně se dá vyřešit tou šablonou. 

Na model:page ta fyzická lokace nepatří, Kramerius to tam ale zobrazí tak či tak - on to zobrazuje vždy rekurzivně nahoru. A asi není fyzicky možné, aby z jednoho čísla byly stránky na různých lokacích :-)
