### ISSUE TITLE
Otestovat shibboleth autentizaci

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#130]
https://github.com/ceskaexpedice/kramerius/issues/405

**Comment by xburda4** [comment]
Shibboleth musí bežať na proxy serveri, my používame Nginx. Pre ten je vyvinutý plugin https://github.com/nginx-shib/nginx-http-shibboleth, https://davidjb.com/blog/2013/04/integrating-nginx-and-a-shibboleth-sp-with-fastcgi/. 

Pre testovanie konfigurácie som používal tento kontajner https://bitbucket.org/hellomatter/shibboleth-nginx, na ktorom je Shibboleth 2.5.3 a starší Nginx 1.7.2. Použil som túto konfiguráciu https://drive.google.com/a/mzk.cz/file/d/0Bx60vPaKmYoyTmhseUYyX2FWRVU/view?usp=sharing nginx a toto https://drive.google.com/a/mzk.cz/file/d/0Bx60vPaKmYoyZzNOYXI2MVBRZk0/view?usp=sharing nakopírované v /etc/shibboleth/.

Zo shibbolethu je najdôležitejšia zložka shibboleth2.xml, kde v uzli RequestMapper pod Host name treba zadať url, pod ktorým sa bude pristupovať na server (ja som používal kramerius.localhost/search/).

Prepojenie Shibbolethu s MZK je v shibboleth2.xml nastavené a pre kontrolu sa treba na adresa/Shibboleth.sso/Login. Prihlásiť sa dá buď pod vlastným prihlasovacím menom a heslom alebo cez testovací účet.

Ideálne by bolo forknúť nginx, ktorý používame a upraviť https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl, tak aby v konfigurácii Nginx pre server Krameria pridal nastavenia pre Shibboleth.

Nakoniec ešte bude treba upraviť Krameria alebo premenné, ktoré sa Krameriu posielajú. Testovací kontajner mi na krameria posielal tieto dve premenné https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/authfilters/src/main/java/cz/incad/kramerius/auth/thirdparty/shibb/utils/ShibbolethUtils.java#L32-L33 malým a Kramerius ich nerozpoznal a tváril sa ako keby mu Shibboleth nič neposiela.
