### ISSUE TITLE
Nové funkce statistik

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#132]
Nasadit a otestovat https://github.com/ceskaexpedice/kramerius/issues/394

**Comment by leiblix** [comment]
Verze s novýma statistikama je už nasazená i na kramerius.mzk.cz

**Comment by LenkaKravecova** [comment]
Otestovala jsem to, funguje to. Ale asi bude potřeba, aby tam Incad ještě něco doladil. Zatím zavírám.
