### ISSUE TITLE
Prázdná hodnota dc:rights u některých dokumentů

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#133]
Některé dokumenty nemají v dc:rights vyplněno policy, což je problém např. pro CPK a sběr dat. Jsou dvě možné hodnoty - policy:private nebo policy:public. Bude potřeba najít dokumenty, které v dc:rights policy nemají a následně ji tam přidat. Policy by měla být ve FOXML. Co jsem se dívala, tak dokument, který policy neměl v DC, tak ve FOXML to bylo. 
Jinak půjde nejspíš pouze o dokumenty z Meditoru.

**Comment by xburda4** [comment]
Hodnoty boli pridané do 110 dokumentov, mali by to byť všetky, ktorým dc:rights chýbalo.
