### ISSUE TITLE
Admin. procesy v Krameriu

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#135]
Admin. procesy mají stav failed nebo batch_failed (místo running), i když teprve probíhají a není u nich žádný chybový výstup. Po dokončení procesu se stav změní na finished. Dřív to tak nebylo a je to divné.

**Comment by LenkaKravecova** [comment]
A ještě je problém diakritika a špatný čas.

**Comment by leiblix** [comment]
1. Špatný čas bude pravděpodobně způsobený špatnou TIMEZONE, dá se nahlédnout do jiných docker-compose.
2. Špatná diakritika - bude se muset někde v tomcatu nastavit UTF-8 (a upravit s2i-kramerius).

**Comment by Jenyk** [comment]
Čas je opravený v docker-compose.yml:

```
environment:
    - "TZ=Europe/Prague"
```

**Comment by LenkaKravecova** [comment]
Ještě je potřeba dořešit, proč se občas procesy nespouští a musí se restartovat Kramerius (restart 7. 11. 10:50).
