### ISSUE TITLE
Editor částí v nové instalaci

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#137]
Zprovoznit, ukázat někomu, jak se to dělá.

**Comment by leiblix** [comment]
Přidá se do https://github.com/moravianlibrary/s2i-kramerius.git aplikace editor.war, podopným způsobem jako rightseditor https://github.com/moravianlibrary/s2i-kramerius/blob/master/Dockerfile#L58

**Comment by MartinRumanek** [comment]
Nasazené a funkční.

**Comment by leiblix** [comment]
Nasazeno, je to funkční. @xburda4 Dík
