### ISSUE TITLE
Proklik do našeho Alephu v nové instalaci

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#138]
Cílem je, aby identifikátory v Popisu dokumentu odkazovaly do našeho Alephu. Více info zde https://github.com/moravianlibrary/kramerius/issues/118 a zde https://github.com/ceskaexpedice/kramerius/issues/433. @Jenyk, ukaž to někomu ;)

**Comment by xburda4** [comment]
V hotfixapi aj v master branchi kramerius repozitára som to prepísal, tak ako to písal @MartinRumanek, v ďalšom builde by sa to malo prejaviť.

**Comment by leiblix** [comment]
Rád bych zrušil branch hotfixapi, zbytečně to komplikuje vývoj.

Je potřeba opravit originální issue, https://github.com/ceskaexpedice/kramerius/issues/433

**Comment by leiblix** [comment]
Aha, stačí ty konfiguraćní direktivy

```
search.aleph.baseURL.ISSN=http://aleph.mzk.cz/F/?func=find-b&find_code=SSN&local_base=STK02&request=
search.aleph.baseURL.ISBN=http://aleph.mzk.cz/F/?local_base=mzk01&func=find-c&ccl_term=SBN=
search.aleph.baseURL.CNB=http://aleph.mzk.cz/F/?func=find-c&local_base=mzk01&ccl_term=cnb=
```

do search.properties (nikoli do configuration.properties), možná to předtím nešlo, ale teď to funguje.

Issue zavřeme, až nasadíme verzi z upstreamu.

**Comment by Jenyk** [comment]
:open_mouth: Tak to se kaji, defaultně je to v https://github.com/ceskaexpedice/kramerius/blob/fecc7c45124cb8b7fc7776a45d4f1d9c5835c085/search/src/java/res/configuration.properties (i když, pravda, nahoře s odkazem na search.properties..)

**Comment by xburda4** [comment]
Preklik je nastavený v search.properties, je nasadená vetva enhanced a vyzerá to tak, že to ide.
