### ISSUE TITLE
Metadata v Popisu dokumentu

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#139]
Do Popisu u dokumentu v Krameriu je potřeba dát autorské, nakladatelské údaje, nějaké identifikátory a další údaje. Klidně tam může být skoro všechno z MODS, pro knihovníky a v rámci administrace se to bude hodit. Předpokládám, že půjde o úpravu zobrazovací xslt šablony.

**Comment by leiblix** [comment]
Ve staré instalaci to bylo v pořádku?

Projevuje se tato změna i v klientu?

**Comment by Jenyk** [comment]
Ve staré instalaci byly změněné xsl soubory, v klientu se to neprojeví. Jestli to bylo 100% jak Lenka chce nevím..

**Comment by leiblix** [comment]
Nahrál jsem šablonu ze staré instalace, která  tam tyto údaje vrací (/docker-compose/kramerius.mzk.cz/.kramerius4/xsl/mods.xsl).

@LenkaDamborska Pokud by tam ještě něco chybělo, tak issue prosím znovu otevři. Doplnilo by se to do zmiňované šablony.

**Comment by LenkaKravecova** [comment]
Díky. Zatím to můžeme nechat podle té staré šablony.
