### ISSUE TITLE
CORS na docker.mzk.cz

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#14]
Zkusit pridat do Response Headers toto:
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization

**Comment by leiblix** [comment]
Je to.

**Comment by honza-rychtar** [comment]
Authorization mi to v hlavicce nevraci, jen:
access-control-allow-headers:x-requested-with

**Comment by leiblix** [comment]
Myslel jsem, že tak jednoduchou nepodělám a nemusím to testovat. Ale nepřečetl jsem si dokumentaci a udělal jsem to blbě. Když se hlavička opakuje, tak se musí použít addHeader místo setHeader.

Nyní je to už ok.

**Comment by honza-rychtar** [comment]
Diky.

**Comment by leiblix** [comment]
Sice jsme to zavřeli, ale ještě jsem to neposílal jako pull-request do Incadu. Má to pro tebe nějaký smysl, než se vyřeší https://github.com/ceskaexpedice/kramerius/issues/246 ?

**Comment by honza-rychtar** [comment]
Dokud se nevyresi session id, tak to nema smysl.
Access-Control-Allow-Headers: Authorization bez session id nefunguje.
Jen at se pridaji obe zmeny spolecne - Authorization hlavicka i odstraneni session id, resp. autorizace pres base auth.

Aby nevysla verze, kde funguje jen jedno.

To session id ted funguje az moc pekne :)
Kdyz mam zapnute --disable-web-security, tak mi prihlasovani funguje, prihlasim se v mem klientovi, pak otevru kramerius.mzk.cz a jsem prihlaseny i tam. A naopak.
