### ISSUE TITLE
Zrušit limit stran pro generování PDF

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#140]
Limit je teď 20 stran podle defaultního nastavení.
Podobných věcí bude víc. Některá nastavení, která jsme měli, chceme pořád. Postupně zjišťuju, čeho všeho se to týká.. @Jenyk a @MartinRumanek, pořešte spolu konfiguraci Kramerius vs. docker.

**Comment by leiblix** [comment]
Vypnuto v konfiguračním souboru configuration.properties.

Jsme schopni zjistit co ostatní potřebujeme překonfigurovat, nebo vezmeme slepě konfigurák ze staré instalace? (to bych nerad)?
