### ISSUE TITLE
Kramerius pády - problém se spojením do databáze

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#146]
Už se to vyskytlo 3x za poslední dny (časy, kdy byl restartovaný Kramerius):
10-28-2016_12:05:11
11-03-2016_09:10:11
11-04-2016_02:15:11

@Jenyk, jaké navrhuješ kroky? Případně ostatní, taky se vyjádřete.

**Comment by Jenyk** [comment]
Sleduju počty spojení do databáze, ještě vydrž

Dne pá 4. 11. 2016 17:44 uživatel LenkaDamborska notifications@github.com
napsal:

**Comment by LenkaKravecova** [comment]
Vydržím ;) Já jen, abychom to někde měli.

**Comment by LenkaKravecova** [comment]
Podařilo se prověřit ty poslední pády?

**Comment by Jenyk** [comment]
Ano, je to pořád to samé.

**Comment by leiblix** [comment]
*removeAbandoned* (https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html)
> If set to true a connection is considered abandoned and eligible for removal if it has been in use longer than the removeAbandonedTimeout Setting this to true can recover db connections from **applications that fail to close a connection.**

Není to ideální, ale mohlo by nám to pomoct. Co myslíš @Jenyk , kolik dáme ms?

**Comment by leiblix** [comment]
@Jenyk díky za úpravu konfiguračního souboru, nasadil jsem to

**Comment by Jenyk** [comment]
Vypadá to dobře, počet spojení se drží kolem 10 :)
