### ISSUE TITLE
Nejdou upravovat globální akce

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#147]
Momentálně v upstream verzi Krameria nejdou měnit globální akce:

protože požadavek:
`http://localhost/search/inc/admin/_display_rights_for_global_actions.jsp?pids={uuid\:1}&securedaction=read`

Vrací kód 400, měli bychom zjistit, kterým commitem se to rozbilo, jinak budeme mít po dalším updatu problém.

**Comment by MartinRumanek** [comment]
Na produkci se mi ta tabulka nyní ani neotevře

**Comment by xburda4** [comment]
Podobne sa u mňa správa aj zapnutie K4 replikácie. Požiadavka hlási v logu Error parsing HTTP request header - "java.lang.IllegalArgumentException: Invalid character found in the request target."

**Comment by xburda4** [comment]
Takže problém je s Tomcatom novšie verzie majú striktnejšiu kontrolu URI požiadavkov, odkazy s {} teda hádžu exception. Tu to riešia http://tomcat.10.x6.nabble.com/Tomcat-8-0-39-and-tomcat-8-5-8-fails-handling-requsest-td5057320.html .

**Comment by leiblix** [comment]
Je to způsobené https://github.com/ceskaexpedice/kramerius/issues/470. Downgrade Tomcatu to dočasně řeší https://github.com/moravianlibrary/s2i-kramerius/commit/2cf249d200d23dfb4ef0821456e1e66fb517b585
