### ISSUE TITLE
Nefunguje registrácia

### ISSUE THREAD

**Issue by MarosGrm** [moravianlibrary/kramerius#148]
Nefunguje registrácia na kramerius, registračný mail sa neodošle a pri vygenerovaní hesla z user's editoru to zlyhá s hláškou: Function result:Chyba při odesílání hesla Could not connect to SMTP host: localhost, port: 25

**Comment by leiblix** [comment]
Nebyl definovaný konfigurační soubor `/data/kramerius.mzk.cz/mail.properties`. Doplnil jsem a funguje to.
