### ISSUE TITLE
Kontrola ročníků periodik

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#149]
Bude potřeba zkontrolovat periodika, jestli jsou u nich zaindexované všechny ročníky. Bylo pár titulů, kde chyběly v indexu ročníky (Vlasta, Květy...). Bude toho možná víc. Kdo si to vezme?

**Comment by xburda4** [comment]
[thoseAreErrored.txt](https://github.com/moravianlibrary/kramerius/files/633972/thoseAreErrored.txt)
Toto boli uuid ročníkov, ktoré boli vo fedore ale neboli v solru, spustil som hromadnú reindexáciu.

**Comment by xburda4** [comment]
Reindexácia vačšiny je spravená, niektoré ale hlásia stav failed, všetky takéto teda prekontrolujem.

**Comment by xburda4** [comment]
Mimo iné treba tieto súbory odstrániť z RiSearch tabuliek. 
[kontrolaPeriodik.txt](https://github.com/moravianlibrary/kramerius/files/637036/kontrolaPeriodik.txt)
Ináč by malo byť všetko v poriadku.

**Comment by xburda4** [comment]
Momentálne je potrebný už len reimport ročníku 1963 periodika uuid:ebd9e3a0-b4c1-11e3-bb86-005056825209 a obnovenie ročníkov 3 a 5 periodika uuid:e58d8492-ef1a-11e0-8914-0050569d679d zo zálohy, na ktoré je otvorené issue #160

**Comment by LenkaKravecova** [comment]
Reimport z LTP proveden. Zavírám.
