### ISSUE TITLE
Chybi MP3 streamy.

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#15]
V seznamu streamu pro zvukove dokumenty, napr:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:9ee4dc24-fcbb-45fd-ae52-e9f4eced0d0e/streams/
je OGG, WAV i MP3.
Dostupne jsou vsak jen OGG a WAV.
MP3 stream:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:9ee4dc24-fcbb-45fd-ae52-e9f4eced0d0e/streams/MP3
vraci jen {"status":404}

**Comment by honza-rychtar** [comment]
Tohle teda nebyla chyba API, ale jen chybejici data v Krameriovi MZK?
Muzu teda pocitat s tim, ze MP3 streamy jsou ve vsech Krameriich dostupne? I kdyz fallback na ogg/wav tam dam, ale jako prvni bych zkousel MP3.

**Comment by leiblix** [comment]
Ano, chyba byla (a jeste je, dokud ji neopravim, po oprave ta data jeste jednou dogeneruju) v MEditoru. V MLP se tato chyba nevyskytuje maji trochu jine worfklow....
