### ISSUE TITLE
Malované mládež - nezobrazují se obrázky

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#150]
jiné knihy fungují. Ale je to takové divné - někdy to hodí že se nepodařilo načíst a někdy se stránky natáhnou.

**Comment by LenkaKravecova** [comment]
Nám to šlo dnes ráno bez problémů, tak nevím. Asi půl hodiny před tímto tvým issue, Kramerius spadl, tak možná to s tím souviselo.
