### ISSUE TITLE
Chybné monografie

### ISSUE THREAD

**Issue by MarosGrm** [moravianlibrary/kramerius#151]
[error.txt](https://github.com/moravianlibrary/kramerius/files/631333/error.txt)
Zoznam poškodených monografií.
Prvých 7 nezobrazuje obrázky.
Ostatné nezobrazuju ani stránky.
Záznamy začínajúce * sú už vymazané z fedory.

**Comment by leiblix** [comment]
Další monografie bez obrázků, je z NDK, rok 2014:

http://kramerius.mzk.cz/search/i.jsp?pid=uuid:6848bdc0-7cfb-11e3-9be6-005056827e52

**Comment by MarosGrm** [comment]
Chyba je v tom, že _Datastream Location_ má v ceste zlé názvy obrázkov. Napríklad, URL smeruje na obrázok s názvom: ***UC_6848bdc0-7cfb-11e3-9be6-005056827e52_0002***. V skutočnosti je názov: ***1_a_0001_2R.tif***.

**Comment by MarosGrm** [comment]
Rovnaký problém, monografia bez obrázkov. Spôsobené zlým odkazom na obrázok.

http://kramerius.mzk.cz/search/handle/uuid:6db39fa0-4435-11e2-b246-005056827e52

**Comment by leiblix** [comment]
Dalsi monografie bez obrazku s uuid:b6a0a4e1-fe8e-432e-b4e6-22442fe8bf15

**Comment by jkremlacek** [comment]
Úplný seznam rozbitých stran (vč. těch zmíněných v tomto issue) je v https://github.com/moravianlibrary/kramerius/issues/254

**Comment by MarosGrm** [comment]
Zatváram, chyby sa riešia v samostaných issues.
