### ISSUE TITLE
Pomalé přihlašování

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#155]
V poslední době Kramerius trpěl na velmi pomalé pŕihlašování, přišel jsem na důvod a to je, že se hromadí záznamy v tabulce:

`session_keys`

Bylo jich tam až 17 mil, myslím, že by je něco mělo odmazávat, ale zřejmě se tak neděje. Po promazání této tabulky `TRUNCATE session_keys CASCADE` (sessions nejsou důležité, pouze udržují  relaci), se přihlašování rapidně zrychlilo.

Bylo by vhodné to teď sledovat.

**Comment by jkremlacek** [comment]
Záznamů je opět 14 241 501, přičemž začínají datem 12.12. 2016 (tedy téměř ihned po posledním truncate-u). 

Záznam vznikne každou (jednotlivou) indexací v rámci dávky, změnou příznaku... při vytvoření má přidělenou proměnnou ACTIVE na 1 (viz. [registerSessionKey()](https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/common/src/main/java/cz/incad/kramerius/users/database/res/database.stg) )

Podle zdrojáků záznamy session maže LoggedUsersSingleton metodou [deregisterLoggedUser()](https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/common/src/main/java/cz/incad/kramerius/users/impl/LoggedUsersSingletonImpl.java) ovšem pouze v případě, že nejsou spojeny s nějakým procesem - pokud jsou, tak pouze nastaví ACTIVE na 0.

Problém je že mazaní ve většině případů není vůbec zahájeno [LoggedUserSessionListener-em](https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/common/src/main/java/cz/incad/kramerius/users/impl/http/LoggedUserSessionListener.java), protože záznamy session mají ACTIVE stále na 1. (celkem 14 237 835).

**Comment by jkremlacek** [comment]
Opraveno v rámci ceskaexpedice#475.

**Comment by xburda4** [comment]
Tabulky opäť premazané (počet sessions 21 262 274) a nasadený nový kramerius s poriešeným mazaním. Počas dňa to ešte budem sledovať.

**Comment by leiblix** [comment]
Možná za to může něco jiného, ale opět je přihlašování pomalé.

**Comment by leiblix** [comment]
A pravděpodobně kvůli tomu je i děsně pomalé replikační API.

**Comment by MarosGrm** [comment]
Vyriešené v https://github.com/ceskaexpedice/kramerius/issues/521
