### ISSUE TITLE
Test migrace na SOLR6

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#157]
V nové verzi Krameria přibyla podpora pro SOLR verze 6.

SOLR nebudeme instalovat klasickou cestou, ale opět bychom ho nechali běžet v kontejneru.

např.
https://hub.docker.com/_/solr/

Zkusíme to rozběhat a odhadnout čas nutný k migraci.

**Comment by leiblix** [comment]
Mám rozběhané testovací prostředí a za minutu se zmigruje cca 2000 zánamů

Takže nám migrace potrvá zhruba 14 dní, během kterých by měl být Kramerius pouze pro čtení.

**Comment by zabak** [comment]
To by bylo ideální, aby proběhlo přes vánoce, aby to neblokovalo linku NDK. Budete to někdo ale schopni hlídat, aby to v průběhu náhodou nespadlo?

**Comment by xburda4** [comment]
Ešte treba doriešiť do-reindexovanie súborov, ktoré sú vo fedore a nie sú v Solr 6 (mám zoznam objektov, takže to tam pomaly dávam) a následne to nasadiť.

**Comment by xburda4** [comment]
Solr6 je nasadený všade. Zostáva teda už len doindexovať chýbajúce veci a issue zavriem, ak bude Solr bežať bez komplikácií.

**Comment by leiblix** [comment]
@xburda4 Pls, ještě tam potom nastav
```
- "VIRTUAL_HOST=solr.dk-back.infra.mzk.cz"
```

jak to bylo u starého, ať je to dostupné i přes proxy (pro naše pc a OpenShift).

**Comment by xburda4** [comment]
V docker-compose by to tak malo byť. Cez ten odkaz by si sa tam mal vedieť dostať. Zajtra sa na to pozriem, ak s tým sú nejaké problémy.

**Comment by leiblix** [comment]
Dnes je to už ok, ale včera to vážně nejelo :-) Nginx mi vracel 502.

**Comment by xburda4** [comment]
Sme na solr 6 a všetko by malo byť zaindexované.
