### ISSUE TITLE
Nefunkční export z krameria

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#158]
Export uuid 15fb89bc-13d4-4e2a-be44-06ee30c50e0d selže a vyhodí chybu:

[stderr](https://gist.github.com/jkremlacek/11c78a11f929da36bf5b849cbdbf86fd#file-stderr-kramerius-export)

[stdout](https://gist.github.com/jkremlacek/aae36b33973026f1f90f65b6ecf21bd3#file-stdout-kramerius-export)

Čas podle process manageru:  2016/14/12 - 13:45:28

**Comment by leiblix** [comment]
špatná práva
`drwxrwx--x  5 kremlacek damborskal   4096 Dec  8 13:31 export`

Hodil jsem ownera tomcat a exportovalo se to.
