### ISSUE TITLE
Mostdesirable velmi vytěžuje postgres

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#159]
REST dotaz http://kramerius.mzk.cz/search/api/v5.0/feed/mostdesirable

velmi vytíží postgres. Je potřeba pročistit tabulku s nejžádanějšími dokumenty a zavést následující konfiguraci (třebas to omezit na 14 dní):

https://github.com/ceskaexpedice/kramerius/issues/318

**Comment by MarosGrm** [comment]
Tabulka je vyčistená. Momentálne je to obmedzené myslím na 100 dní, zatiaľ to tak nechám a uvidíme ako sa to bude správať. Tie dotazy pravdepodobne pochádzajú z kramerius.infra.mzk.cz keďže možnosť zobrazenia najžiadanejších dokumentov tu nieje skrytá.

**Comment by MarosGrm** [comment]
Možnosť zobrazenia najžiadanejších dokumentov bola vypnutá, dotazy už nechodia. Konfiguráciu teda netreba meniť. Tiež som zmazal indexy tabuľky desirable, sú tam momentálne zbytočné.
