### ISSUE TITLE
IIIF presentation API

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#16]
Kramerius by mohl poskytovat manifest.json pro danou věc, odkazující se na imageserver na IIIF verzi dlaždic místo na zoomify.

http://dms-data.stanford.edu/data/reader/m2/

příklad manifestu který bude v Miradoru fungovat (URL manifestu se vloží kliknutím na jedno z těch prázdných oken Miradoru):

z teto knizky: http://www.e-codices.unifr.ch/en/searchresult/list/one/saa/4530 manifest na:
http://www.e-codices.unifr.ch/metadata/iiif/saa-4530/manifest.json

**Comment by leiblix** [comment]
Link od Petra:

> Anyone who runs a IIIF Image API compliant image server but has not implemented the IIIF Metadata API can use "iiifoo" to generate the metadata API endpoints for them and therefore be able to use other applications, eg. Mirador, to use them."

https://github.com/hashimmm/iiifoo

**Comment by leiblix** [comment]
Prvotní implementace http://krameriustest.mzk.cz/search/api/v5.0/item/uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22/manifest

Zatím funguje pouze tato jedna monografie. Částečně protože je to jediná monografie v testovacím imageserveru (upgrade produkčního je už v plánu). A ostatní typy dokumentů jsem zatím neimplementoval.

**Comment by leiblix** [comment]
A taky jsem zatím neimplementoval metadata - ale to těžké asi nebude.

**Comment by LenkaKravecova** [comment]
@zabak co s tím budeme dělat dál?

**Comment by zabak** [comment]
Měsíc počkáme a uvidíme.

**Comment by leiblix** [comment]
Základní IIIF už v Krameriu je. Issue už nemá dále smysl, je moc obecné.
