### ISSUE TITLE
zalozka POPIS

### ISSUE THREAD

**Issue by filipsir** [moravianlibrary/kramerius#161]
Je nekde mozne zmenit/pridat/upravovat zalozku POPIS v dokumentu? Diky

**Comment by leiblix** [comment]
Záložku popis si vymysleli v Olomouci, tak by ti možná mohl odpovědět @FoxKyong jak to řeší.

V MZK na to žádný nástroj nemáme (samotný Kramerius to neumí a Editor taky ne, protože to zatím nikdo nechtěl).

**Comment by filipsir** [comment]
Dobre, diky!  jakym zpusobem tady lze poslat tento dotaz na @FoxKyong ?
