### ISSUE TITLE
Neprochází indexace velkých PDF

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#162]
V Krameriu neprošla indexace dokument uuid:0d884afb-c5f3-469d-9d7d-5932715e4f86 , jedná se o PDF které má 650 MB.

Takových velkých PDF má Zdeněk více ("Prošel jsem jich pár desítek a je tam jedno 460 MB, dvě kolem 100 MB, pár kolem 30 MB a zbytek je pod 10 MB")

Dále bude pravděpodobně se zobrazováním tak velkých PDF, v novém klientu se používá prohlížečka PDF.js od Mozilly, je to potřeba to odzkoušet.

**Comment by LenkaKravecova** [comment]
Vyřešíme indexaci, potom ozkoušet na studovně, jestli se PDF načte.

**Comment by zdenekhruska** [comment]
PDF kolem 100 MB prošla bez problémů. Praktickými pokusy můžeme ověřit, kde je ta hranice velikosti PDF,  za kterou už to bude padat.

**Comment by xburda4** [comment]
Nasadil som novú verziu, v ktorej by to malo ísť. Na kramerius.infra indexácia prebehla, ale mám tam navyše nejaké nastavenia. @zdenekhruska skús niektoré pdf vložiť, ak to neprejde, tak na ostrý kramerius pridám tie nastavenia, čo sú na infre.

Reindexoval som uuid:0d884afb-c5f3-469d-9d7d-5932715e4f86 a uuid:8e6cd211-e855-4b37-9e26-46eb927dfe7e.

**Comment by leiblix** [comment]
Moc díky, bylo by dobré udělat pull-request do Incadu, ale před tím pozor na:

- `java.nio.file` je novinka Javy 7 a před dvěmi lety se ještě v Incadu snažili držet kompatibilitu s JRE 6 (https://github.com/ceskaexpedice/kramerius/issues/306), nevím jak to mají teď (snad už nikdo nemá JRE 6, nevychází na to ani security updaty...)

- na dočasné soubory existuje pěkná metoda https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempFile(java.lang.String,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...), a umí to i `delete on close`. (je to zase to nové nio.file API, ale staré File API bude mít taky něco takového).

- nevím, jaké výhody má IOUtils.closeQuietly(is) oproti použití nativního `fa.close()`, ale je nutné soubory zavírat ve finally bloku - když ti teď vyletí např. pří kopírování streamu výjimka, tak se to nezavře. 

Trochu mě překvapilo, že kolem toho kopírování datastreamu vůbec není try-catch blok, ale to je protože v kontraktu metody je `throws Exceptions`, nevím jestli je k tomu mají nějaký sofistikovaný důvod, ale spíš je to jenom :pig: kód - nenutí tě to ošetřit kontrolované výjimky a uvolňovat správně zdroje.

**Comment by zdenekhruska** [comment]
Dnes prošlo bez problémů PDF o velikosti 535 MB, takže to funguje!

**Comment by xburda4** [comment]
Martinove poznámky sú v kóde, takže by to malo byť dobre aj po tejto stránke.
