### ISSUE TITLE
Importovat Národní listy z ČB

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#164]
Národní listy uuid:ae876087-435d-11dd-b505-00145e5790ea jsou ještě v djvu: získat foxml i data z Budějovic a naimportovat do Krameria, vyexportovat stávající periodikum v djvu a smazat ho. 
S Honzou H. jsme se dohodli, že nebudeme jen vyměňovat obrázky, ale naimportuje se to jako celek kvůli vazbám.

**Comment by zabak** [comment]
Jsou Národní listy už hotové? Ročník 1928 má jen několik málo čísel ze začátku roku.

**Comment by MarosGrm** [comment]
Okrem ročníkov 1920, 1928, 1932 je všetko v poriadku. Tieto tri ročníky majú chybné FOXML.
