### ISSUE TITLE
Generování dvouvrstvého PDF

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#165]
Nakonfigurovat dle https://github.com/ceskaexpedice/kramerius/issues/25 a zjistit, jak se to bude dál chovat (tzn. bude se to generovat všude i v klientech?). Moc díky!

**Comment by leiblix** [comment]
Oni to implementovali zřejmě pouze pro dokumenty, které obsahují obrázky přímo ve Fedoře. Vyvíjeli to v rámci KNAV, ta imageserver myslím vůbec nemá, tak je to asi nenapadlo otestovat.

**Comment by MarosGrm** [comment]
Počkáme na vyjadrenie Incadu https://github.com/ceskaexpedice/kramerius/issues/497

**Comment by LenkaKravecova** [comment]
Ještě ověřím klienty, jinak ok.

**Comment by leiblix** [comment]
Bylo opraveno.
