### ISSUE TITLE
Zprovoznit OAI pro Krameria

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#166]

**Comment by xburda4** [comment]
Momentálne je OAI riešené len na SOLR 4. Písal som Šťastnému, a pozrie sa na to aj pre SOLR 6.

**Comment by xburda4** [comment]
K OAI sa možno dostať cez adresu https://kramerius.mzk.cz/oai/?verb=Identify . Plugin má problém s niektorými objektami, ktoré napríklad sú v Solri a nie sú vo Fedore, okrem toho by to však malo ísť v poriadku. V priebehu dneška ešte pripojím súbor, kde je krátky popis pluginu s nejakými príkladmi.

[popis.txt](https://github.com/moravianlibrary/kramerius/files/1141568/popis.txt)
