### ISSUE TITLE
Moving Wall Process

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#167]
Asi nám nefunguje. Prosím, prošetřit dle https://github.com/ceskaexpedice/kramerius/wiki/MovingWallProcess. Zkoušela jsem to na jednom periodiku s různými časovými parametry a žádná změna nenastala (proces se úspěšně dokončil).

**Comment by xburda4** [comment]
Vyzerá to tak, že príznak sa nastaví, ale ne-reindexuje sa to, takže sa neprejavia zmeny.

**Comment by xburda4** [comment]
Oprava by mala byť nasadená na krameriu, teraz to testujem na periodiku Nové listy. Dodatočne sa pozriem, či by sme to nevedeli spustiť naraz nad viacerými objektami. 

Edit: Vyzerá to tak, že sa neindexuje koreňové xml, takže v klientovi sa celé periodikum tvári ako private, ale po rozkliknutí koreňa sú ročníky a všetko pod nimi public. Nie je problém dodatočne reindexovať (len) koreň ale moving wall, by to malo riešiť samo. V pondelok sa pozriem, či sa to deje aj nad monografiami a zadám issue do Incadu (ak by to ale dlho stálo, môžem sa na to pozrieť aj ja).

**Comment by xburda4** [comment]
Pre periodiká je reindexovanie koreňa vyriešené pre sprístupňovanie, teda pri zmene z private na public.  Moving wall cez typ (monograph, manuscript, atd.) by mal byť implementovaný, no nevyzerá to tak, že to funguje. Po nasadení na ostrého krameria issue zavriem.

**Comment by xburda4** [comment]
Oprava je nasadená a pre periodiká to zdá sa funguje (skúšal som to na jednom čísle Nových Listov a príznak public bol nastavený aj na celej ceste k tomuto číslu).

**Comment by xburda4** [comment]
Prepísať moving wall aby neprechádzalo strany a bolo možné spustiť ju len nad istým typom dokumentu (monograph, periodical, graphic, ...).

**Comment by LenkaKravecova** [comment]
Moving wall proces byl upraven (na periodika) a byl aplikován. Vše je sepsáno na wiki. Zavírám.
