### ISSUE TITLE
HTTPS pro Krameria

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#168]
Konkrétně pro krameriusadmin.mzk.cz, protože to se nepřesměrovává.

**Comment by LenkaKravecova** [comment]
Pro kramerius.mzk.cz taky, jak jsem pochopila z mailů, @honza-rychtar ?

**Comment by zabak** [comment]
Ano, pro Kramerius.mzk.cz taky. Cílem je, aby nakonec vše běželo na http 2.

**Comment by leiblix** [comment]
@dsecik https na Kramerius nasadil. 

Zbývá implementovat malou úpravu do IIIF proxy, ale čekáme teď na malou opravu v imageserveru.

**Comment by leiblix** [comment]
Bylo vyřešeno.
