### ISSUE TITLE
Pád Krameria kvôli Solru

### ISSUE THREAD

**Issue by xburda4** [moravianlibrary/kramerius#169]
V posledných týždňoch sa stáva, že padne Kramerius kvôli problémom so Solrom a skript na reštart kontajneru nepomôže. Myslím, že sa to deje odkedy sme presmerovali virtuálne zbierky z fedory na solr. Bolo by fajn, keby sa na to niekto pozrie a porieši to.

**Comment by xburda4** [comment]
Padlo to najprv na "java.lang.OutOfMemoryError: Java heap space" a neskôr v logoch vyskočilo "GC overhead limit exceeded". Skúsim sa teda pohrať s konfiguráciou a ak to nepomôže, tak poprosím Davida o dodatočné zdroje.

**Comment by zabak** [comment]
Mimo to prosím tam dejte monitorovací a samonahazovací skript speciálně pro solr.

**Comment by xburda4** [comment]
Ešte včera som skopíroval a prepísal Danov skript na reštart krameria a rovnako by to malo fungovať aj na Solr. Uvidíme ako sa to bude správať, keď Solr naozaj spadne.

**Comment by leiblix** [comment]
Padá to teď často? 

Má to nějakou souvislost s https://github.com/moravianlibrary/kramerius/issues/174?

**Comment by xburda4** [comment]
Prechod na Solr6, zdá sa, pomohol. Dva týždne Solr nepadol, kým sa to nebude objavovať znovu, tak to zavriem.
