### ISSUE TITLE
Nejde vygenerovat private PDF dokument

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#17]
Tento konkrétní dokument nelze vygenerovat, přihlášení na to nemá vliv

http://krameriusndktest.mzk.cz/search/api/v5.0/pdf/selection?pids=uuid:4b61c7a0-048c-11e5-91f2-005056825209,uuid:4b729080-048c-11e5-91f2-005056825209,uuid:4b80c150-048c-11e5-91f2-005056825209,uuid:4b916320-048c-11e5-91f2-005056825209,uuid:4ba475f0-048c-11e5-91f2-005056825209

**Comment by popelkatomas** [comment]
Nejsou ošetřeny speciální znaky. Titul obsahuje v názvu "&", za kterým parser očekává validní escape sekvenci a ve výsledku způsobí SAXParseException.
Dokument, který způsobuje chybu: http://pastebin.com/dY0mqArB
Stacktrace: http://pastebin.com/zSeSN5yA

**Comment by LenkaKravecova** [comment]
Opraveno
