### ISSUE TITLE
Pomalé načítání dlaždic

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#170]
V našem Krameriu se hrozně pomalu načítají dlaždice (týká se to IIIF i Zoomify):

**Kramerius.mzk.cz ~700 ms**
http://kramerius.mzk.cz/search/zoomify/uuid:0789cc9d-6fbd-4126-8aa5-46f6ed8205f8/TileGroup0/2-1-0.jpg

**Kramerius4.nkp.cz ~37 ms**
http://kramerius4.nkp.cz/search/zoomify/uuid:84459130-e47f-11e6-9e7e-001018b5eb5c/TileGroup0/2-1-0.jpg

**Kramerius.oc.infra.mzk.cz ~ 55 ms**
http://kramerius.oc.infra.mzk.cz/search/zoomify/uuid:1710071f-a507-4a55-8e4f-a1c8db66b2d0/TileGroup0/2-1-0.jpg

V případě kramerius.oc.infra.mzk.cz jsem zkusil přidat ehcache na autentizaci dlaždic https://github.com/moravianlibrary/kramerius/commit/e229020fdd5b9dc966d1585882cb7d69b46e8a65#diff-a3df1f4f534d1bb96405fa0b36ae75fcR28, ale problém bude zřejmě ještě někde jinde, protože nkp je rychlejší i bez této cache.

Doporučuji otestovat kontejner https://github.com/moravianlibrary/s2i-kramerius (btw. nevím proč, ale v ukázkovém compose se po startu přestalo automaticky importovat Slunéčko),

**Comment by leiblix** [comment]
@xburda4 Autentizace dlaždic (která je pomalá), probíhá např. v této části kódu https://github.com/moravianlibrary/kramerius/blob/master/search/src/java/cz/incad/Kramerius/imaging/IiifServlet.java#L74-L77

**Comment by leiblix** [comment]
Už vím čím to je:

Pravděpodobně při řešení issue https://github.com/ceskaexpedice/kramerius/issues/234 a následném commitu cf13c9e2d34ff884c1f2cf8f1d1947e970220260, došlo k významnému zpomalení načítání dlaždic.

Tento snippet kódu při každém requestu na dlaždici přistupuje do SOLRu a způsobuje zpoždění:
https://github.com/ceskaexpedice/kramerius/blob/cf13c9e2d34ff884c1f2cf8f1d1947e970220260/common/src/main/java/cz/incad/kramerius/security/impl/DatabaseRightsManager.java#L247-L252

**Comment by xburda4** [comment]
Na kramerius.mzk.cz to je nasadené, na infra to hodím, keď mi tam dobehnú reindexácie. Ak k tomu nechceš ešte niečo dorobiť, tak to môžeš zavrieť.

**Comment by leiblix** [comment]
@xburda4 Na infra to není nutné nasazovat, dík.
