### ISSUE TITLE
Kramerius přistupuje na neexistující uuid:1

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#173]
Kramerius pravidelně přistupuje na adresu:
"http://fedora.dk-back.infra.mzk.cz/fedora/get/uuid:1/RELS-EXT"

Přičemž tato adresa nefunguje a do logu pak padají SEVERE záznamy.

viz:
http://dk-kibana.infra.mzk.cz/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(columns:!(_source),index:%27logstash-*%27,interval:auto,query:(query_string:(analyze_wildcard:!t,query:%27%22http:%2F%2Ffedora.dk-back.infra.mzk.cz%2Ffedora%2Fget%2Fuuid:1%2FRELS-EXT%22%27)),sort:!(%27@timestamp%27,desc))

**Comment by xburda4** [comment]
Bude to pravdepodobne spôsobené týmto riadkom https://github.com/ceskaexpedice/kramerius/blob/1c91829bc1f9c109964d7a6d6b57ef10fdfbb7ef/common/src/main/java/cz/incad/kramerius/security/impl/http/AbstractLoggedUserProvider.java#L123, 

kde SpecialObject.REPOSITORY odkazuje na https://github.com/ceskaexpedice/kramerius/blob/6d255fe3112f93104863695d46c21751f67a05b5/common/src/main/java/cz/incad/kramerius/security/SpecialObjects.java#L27. 

Z logov to vyzerá tak, že týmto mal nejak Kramerius zistiť aké má užívateľ práva (jedna z metód v stacktrace je saveRightsIntoSession). Issue by som asi posunul na Incad.

**Comment by xburda4** [comment]
Issue na Incade, https://github.com/ceskaexpedice/kramerius/issues/498.

**Comment by leiblix** [comment]
oprava je zamergována v hotfix (:-D) branchi, prosím o otestování

**Comment by xburda4** [comment]
Obraz už je na docker.hub-e, v priebehu dneška alebo zajtrajška to odskúšam.

**Comment by xburda4** [comment]
Hotfix to opravilo, pri prihlásení už výnimka nevyskakuje.
