### ISSUE TITLE
SOLR dotazy končící v timeoutu

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#174]
V logu je řada SOLR dotazů, které skončili v timeoutu.

`krameriusmzkcz_kramerius_1 17683 - - 07-Apr-2017 08:10:55.393 SEVERE [http-nio-8080-exec-289] cz.incad.kramerius.rest.api.k5.client.search.SearchResource.selectJSON Read timed out`

[Kibana](http://dk-kibana.infra.mzk.cz/app/kibana#/discover/Kramerius-errors-(bez-proflaknutych-chyb)?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(columns:!(_source),filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%27logstash-*%27,key:containername,negate:!f,value:krameriusmzkcz_kramerius_1),query:(match:(containername:(query:krameriusmzkcz_kramerius_1,type:phrase))))),index:%27logstash-*%27,interval:auto,query:(query_string:(analyze_wildcard:!t,query:%27%22cz.incad.kramerius.rest.api.k5.client.search.SearchResource.selectJSON%22%20AND%20%22Read%20timed%20out%22%27)),sort:!(%27@timestamp%27,desc)))

**Comment by xburda4** [comment]
Toto bude súvisieť s https://github.com/moravianlibrary/kramerius/issues/153. Skúsim tam vypnúť logovanie požiadavkov a ak to nepomôže, tak sa konečne pohrám s tou ramkou, ako hovoril Petr.

**Comment by xburda4** [comment]
Prechod na nový Solr to pravdepodobne vyriešil.
