### ISSUE TITLE
Rozbité náhledy u PDF dokumentů s JPEG2000

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#177]
Viz bílá stránka u
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:5336c387-c7e5-46d7-952c-c25ccd9bbd25

**Comment by honza-rychtar** [comment]
@MartinRumanek Co je to PDF dokument s JPEG2000?
Kazdopadne klienti (K5, DK, Android, iOS) nezobrazuji nahledy stranek u PDF dokumentu.

**Comment by leiblix** [comment]
To je PDF dokument, který má embeded obrázek ve formátu JPEG2000 - což není nic divného, většina PDF prohlížeček si s tím poradí.

Do Meditoru už mám nachystaný fix a v Krameriu to zpětně opravíme.

**Comment by leiblix** [comment]
@honza-rychtar Jinak tím náhledem myslím vlastně jen něco jako reprezentativní stránku, viz bílá stránka: http://www.digitalniknihovna.cz/mzk/search/?q=agresivni%20tendence
