### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#178]
V docker-obrazu Krameria umožnit definovat vlastní `robots.txt`

Asi přes env proměnnou?

krameriusdemo.mzk.cz, krameriusdevel.mzk.cz i krameriusadmin.mzk.cz (tady to bude těžší, protože je to momentálně jenom alias) by měly mít zakázané sklízení.

**Comment by xburda4** [comment]
Pri buildení by sa mal pridať na server skript, ktorý tam robots.txt pridá, ak neexistuje.

**Comment by leiblix** [comment]
robots.txt by měl být konfigurovatelný

**Comment by xburda4** [comment]
Ideálnejšie teda v budúcnosti prepísať skript tak, aby sa celý súbor (robots.txt) zobral z env premennej.

**Comment by dsecik** [comment]
Vyriesene  v https://github.com/moravianlibrary/s2i-kramerius/commit/27697eba42cec28f61be24025d579b20b43bbdc1
