### ISSUE TITLE
Zjistit, které dokumenty nemají alto.xml

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#180]
Vytvořit seznam, kde bude: uuid, název, autor, rok vydání, signatura, sysno, čk, sigla. Budou to periodika i monografie, možná i další typy dokumentů.

**Comment by LenkaKravecova** [comment]
Monografie už jsou, ještě periodika. Další typy už ne.

**Comment by LenkaDamborska** [comment]
Je pryč. Díky.
