### ISSUE TITLE
Počty typu dokumentů v jednotlivých rocích

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#183]
Potřebuju pro ty Petrovy statistiky ještě zjistit, kolik je jednotlivých typů dokumentů v jednotlivých rocích. Takže vlastně potřebuju údaje, které jsou v časové ose: 
např. http://kramerius.mzk.cz/search/r.jsp?offset=0&forProfile=facet&fq=document_type:%22periodicalvolume%22

Ideální by byl seznam, kde bude rok a počet dokumentů určitého typu, tak jak je to v té časové ose. Nic víc. Přirozeně to nechci opisovat z časové osy do tabulky v excelu..

Vznikne teda seznam roků pro každý typ dokumentu: monograph, periodical, periodicalvolume, sheetmusic, manuscript, archive, soundrecording, graphic, map.

**Comment by MarosGrm** [comment]
Zoznam je tu:
https://docs.google.com/a/mzk.cz/spreadsheets/d/1yKJGT5jG1eFsyIfGFfeL4bTvEfuR33UCF6s8XP3ZZHM/edit?usp=sharing
