### ISSUE TITLE
Počty stran v rámci typů dokumentů

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#184]
Další věc - je potřeba zjistit, kolik stran celkem je v jednotlivých typech dokumentů a kolik z nich je veřejných a kolik neveřejných. Takže výstup bude vždy:

- typ dokumentu
- počet stran celkem
- počet stran public
- počet stran private

Typy dokumentů: monograph, periodical, periodicalvolume, sheetmusic, manuscript, archive, soundrecording, graphic, map

Moc díky.

**Comment by xburda4** [comment]
Zoznam je tu: https://docs.google.com/a/mzk.cz/spreadsheets/d/18EvjNUikykCotVKuvAsnSdKd0_cXnUmmjGzgZwAXXtA/edit?usp=sharing . Postupne to budem updatovať, ešte tam mám stále ten zoznam toho, čo treba zviditelniť

**Comment by LenkaKravecova** [comment]
periodicalVolume	107239 - toto se mi nějak nezdá, mělo by to být víc, ještě přemýšlím, jestli v některých periodicích nejsou označeny ročníky jako "volume"
