### ISSUE TITLE
client a http/2

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#185]
Porovnával jsem rychlost http vs. http/2 - spustil jsem si paralelně https://kramerius.mzk.cz/client a http://krameriusadmin.mzk.cz/client. Otevřel jsem v obou Národní listy, ročník 1934, 1935 apod. Náhledy čísel se přes http/2 stahují řádově rychleji.

Když ale ročník rozkliknu, tak se skoro vždy stane že se stahování thumbnailů zastaví cca kolem čísla 100-140. Když dám reload, stáhne se vše. Testováno na Opeře pro Mac. Nemyslím, že je nutné toto nějak zvlášť řešit, ale za otestování v jiných browserech by to stálo.

**Comment by dsecik** [comment]
Firefox a IE na win bez problemov, v chrome sa popisovany problem prejavuje (niektore requesty na dlazdice su "canceled" ) po reloade stranky sa nacitaju z cache tie, co sa podarilo nacitat predtym + sa nacitaju tie co boli "canceled". Vzhladom na to, ze toto rozhranie nepouzivame to asi mozeme zavriet ze?

**Comment by zabak** [comment]
Client nebudeme používat. Zavírám.
