### ISSUE TITLE
chybná indexace roků vydání

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#186]
Pokud z MARC záznamu přišel údaj o roku vydání v jiné podobě než čistě číselné, tj. ne RRRR ale např. [RRRR] u starých hudebnin nebo pRRRR u gramodesek tak se to v Solru zaindexovalo asi i s těmito řetězci a pak na to nefunguje filtrace podle časové osy, zdá se. Ve VUFindu se pro účely indexace používá primárně příslušný údaj z pole 008, ale nevím jak se transformuje do MODSu nebo DC a co z toho pak jde do Solru. Pravděpodobně bude potřeba eskalovat na Incad a reindexovat všechny specificky zapsané roky vydání

**Comment by LenkaKravecova** [comment]
Petře, nechceš to zadat i na hlavní github Krameria?

**Comment by zabak** [comment]
Jo, prověř ale prosím, že to co píšu není jen specifikum našeho Krameria.

**Comment by leiblix** [comment]
Do SOLRu by se mělo to mělo ideálně propisovat takto:

MODS:dateIssued point="start" --> SOLR:datum_begin
MODS:dateIssued point="end" --> SOLR:datum_end

čátečně je to issue nahlášené tady https://github.com/ceskaexpedice/kramerius/issues/424

Měli bychom to spravit a následně reindexovat dotčené dokumenty (stejně budeme muset reindexovat skoro vše, viz https://github.com/moravianlibrary/kramerius/issues/190)

**Comment by zabak** [comment]
@LenkaKravecova tohle předpokládám bude řešit @xermak00 ...?

**Comment by kazooo** [comment]
Opraveno v K7
