### ISSUE TITLE
Jednoduché vyhledávání v Krameriu - nefunguje, jak má

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#187]
Přes jednoduché hledání nejdou najít některé tituly - např. Komentář k hospodářskému zákoníku a k zákonu o hospodářské arbitráži se vzory smluv a podání. Přes rozšířené vyhledávání (Název) se to najde.
V Krameriu NK to jde bez problému vyhledat i přes jednoduché hledání - kramerius4.nkp.cz
Co s tím může být?

**Comment by kazooo** [comment]
Jednoduché vyhledávání funguje, je-li název titulu označen uvozovkami.

**Comment by LenkaKravecova** [comment]
Ok, zatím to tak necháme. Používá se to jen v rámci administrace v MZK...

**Comment by leiblix** [comment]
Ale co ostatní knihovny, které přejdou na SOLR6.... Budou mít pravděpodobně stejný problém, bylo by dobré přijít na příčinu.

**Comment by kazooo** [comment]
Pri zakomentovanem defaultOperator (managed-schema, radek 494) vsechno se da vyhledat a to i bez uvozovek v krameriu i primo v solru.

**Comment by kazooo** [comment]
https://github.com/moravianlibrary/osdd-docker-images/blob/master/solr6/kramerius/conf/managed-schema#L435
je nutné změnit typ pole "root_title" na "text_general_not_lemmatized" nebo jiný podobný namísto "string", protože "string" v Solr 6 už je zastaralý a je příčinou špatného vyhledávání. Operator "defaultOperator" nechť funguje i dale.

EDIT: typ "string" je od třídy solr.StrField, a pole takového typu nemá žadné tokenizery a analyzery, takže nezpracovavá dotazy vhodně.

**Comment by kazooo** [comment]
Smazat [line 1](https://github.com/moravianlibrary/osdd-docker-images/blob/master/solr6/kramerius/conf/managed-schema#L492) a [line 2](https://github.com/moravianlibrary/osdd-docker-images/blob/master/solr6/kramerius/conf/managed-schema#L495).
Pridat 
```
<str name="q.op">AND</str>
```
do bloku [line 3](https://github.com/moravianlibrary/osdd-docker-images/blob/master/solr6/kramerius/conf/solrconfig.xml#L840)
Zmenit [line 4](https://github.com/moravianlibrary/osdd-docker-images/blob/master/solr6/kramerius/conf/solrconfig.xml#L841) na "text_lemmatized" (pro vyhledavani v primo v solru, problem s lematizaci)

**Comment by leiblix** [comment]
Schéma je dobře, vypadá to spíše na bug verze SOLR 6.3.

Je tam nějaký problém s oboostovaným polem. Měli bychom náš SOLR aktualizovat. Nebo by se dal přepsat dotaz z `qf` do `df`. To druhé funguje.

**Comment by kazooo** [comment]
Kramerius divně reagije na spojku "a". 
Příklad: 
Se spojkou "a", tedy Investiční rozhodování a dlouhodobé financování není nic nalezeno.
Bez spojky, tedy Investiční rozhodování  dlouhodobé financování, je nalezeno několik publikací které mají název: Investiční rozhodování a dlouhodobé financování.
Pokud je celý název v uvozovkách, tedy  "Investiční rozhodování a dlouhodobé financování", tak se publikace najdou.

**Comment by leiblix** [comment]
To je na produkci nebo s novou verzí SOLRu?

**Comment by kazooo** [comment]
Na produkci i s novou také.

**Comment by LenkaKravecova** [comment]
Co s tím dál? :)

**Comment by kazooo** [comment]
Vypadá jako bug Solru, potřebujeme ho aktualizovat.

**Comment by kazooo** [comment]
S novým Solrem 7.5.0 a lemmatizovanými textami funguje bez problemů.
