### ISSUE TITLE
Nevygeneruje se PDF 

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#188]
U tohoto dokumentu uuid:4edefe10-36ef-11e7-ad2f-005056827e51 nejde vygenerovat PDF ani v Krameriu, ani v klientovi.. Co s tím je?

**Comment by xburda4** [comment]
Je tam nejaký problém, pri nastavení premennej pdfQueue.useAlto na true. To sa nastavovalo kvôli https://github.com/ceskaexpedice/kramerius/issues/25 ,kde to aj tak nepomohlo, takže som to nastavil false a PDF vygenerovať ide.
Edit: Vraj to alto funguje, takže budeme mať chvílu vypnuté dvojvrstvové PDF.

**Comment by xburda4** [comment]
Otestuje sa s ďalším releasom, kde bude alto funkčné.

**Comment by xburda4** [comment]
Takže to vyzerá tak, že chyba je nakoniec s malým názvom ALTO. Ak kramerius nenájde datastream, tak spadne na chybe a kvôli tomu to potom nevygeneruje PDF.
