### ISSUE TITLE
Zapomenuty testovaci dokument

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#189]
http://www.digitalniknihovna.cz/mzk/search/?sort=newest&accessibility=public&doctypes=manuscript&q=test

**Comment by LenkaKravecova** [comment]
Byl ještě zaindexovaný v solru. Už je pryč.

**Comment by honza-rychtar** [comment]
Jeste teda tento
http://www.digitalniknihovna.cz/mzk/search/?sort=newest&accessibility=public&q=test%2520-%2520Olomouc%25202

**Comment by LenkaKravecova** [comment]
Je pryč :) Díky.
