### ISSUE TITLE
Informace i instituci pres siglu

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#19]
Informace o instituci (nazev, kontakt, adresa, souradnice, web, ...) lze ziskat z NKP katalogu pres siglu v XML formatu nasledovne:
Priklad pro MZK (sigla boa001)
http://aleph.nkp.cz/X?op=find&find_code=wrd&base=ADR&request=sig=boa001
Z odpovedi se veme set_number a zavola se:
http://aleph.nkp.cz/X?op=present&set_entry=000000001&format=marc&set_no=SET_NUMBER
Napr. http://aleph.nkp.cz/X?op=present&set_entry=000000001&format=marc&set_no=016585

Problem je, ze na aleph.nkp.cz neni povoleny CORS a volani se neda pouzit ve webovych aplikacich mimo domenu aleph.nkp.cz. Dalsi problem je nevhodny format vysledku (xml/oai marc).

Chtelo by to sluzbu s povolenym CORS, ktera prevadi vysledky do vhodnejsiho formatu.
Otazka je, jestli ma byt sluzba soucasti API Krameria.

**Comment by leiblix** [comment]
Vyřešeno projektem https://github.com/moravianlibrary/adresar-knihoven-api

**Comment by leiblix** [comment]
Poznámka pro další generace, pro hledání BOA lze využít aplikaci http://czech-libraries.herokuapp.com/ kterou naprogramoval @honza-rychtar

**Comment by zabak** [comment]
která se ale přestěhuje na knihovny.cz, až bude hotová
