### ISSUE TITLE
HTTP Status 408 při přihlašování 

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#191]
Objevují se problémy při přihlašování. Já se nemůžu přihlásit ve Firefoxu, někdo jiný zase v Chromu. Cookies jsem mazala, vracela se zpátky přes šipku v prohlížeči, zkoušela se přihlásit víckrát, nic nepomáhá :) 

Hláška: HTTP Status 408 - The time allowed for the login process has been exceeded. If you wish to continue you must either click back twice and re-click the link you requested or close and re-open your browser

**Comment by LenkaKravecova** [comment]
Jinak ta hláška naskočí hned, není to tak, že by přihlašování trvalo dlouho a pak nastala chyba.

**Comment by LenkaKravecova** [comment]
Pomohlo vymazat mezipaměť a cookies. Zatím zavírám.

**Comment by leiblix** [comment]
Další řešení je přistupovat do Krameria striktně přes https://, udělá se přesměrování (viz https://github.com/moravianlibrary/kramerius/issues/168).
