### ISSUE TITLE
Kramerius chyby 500

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#193]
Hodně requestů padá do 500, viz [Kibana](http://bit.ly/2tQsVuq). Nutné průběžně řešit. 

https://blog.codinghorror.com/exception-driven-development/

**Comment by leiblix** [comment]
Selhávalo generování PDF s textovou vrstvou, zatím jsem to vypnul a připsal komentář sem:
https://github.com/ceskaexpedice/kramerius/issues/497

**Comment by leiblix** [comment]
Další časta chyba je skrz https://github.com/honza-rychtar/kramerius-web-client/issues/293

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
