### ISSUE TITLE
Rozpadlá monografie z NDK linky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#195]
Tato monografie se "rozpadla" při importu do K5 (z NDK linky): uuid:187b1c10-30b3-11e7-a38c-005056827e51
Tady je např. poslední strana: uuid:c3fb8e30-4094-11e7-a7ae-001018b5eb5c

Bude nutný reimport z LTP nebo jak se to dá řešit? Je víc případů. Bude potřeba to začít systematicky řešit v K5 a ideálně taky v NDK lince.

**Comment by MarosGrm** [comment]
V admin. rozhraní fedory som zmazal a znovu obnovil v datastreame RELS-EXT pole rdf:Description a potom reindexoval a pomohlo to. Issue nechávam otvorené na ohlasovanie ďaľších takýchto monografií.

**Comment by MarosGrm** [comment]
Zatváram, podobné problémy budú v samostatných issues.
