### ISSUE TITLE
Nedostupná administrace virtuálních sbírek

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#196]
Nelze se dostat do administrace virtuálních sbírek ani přes konkrétní dokument, ani přes hlavní menu.

**Comment by leiblix** [comment]
Mně se to načetlo, akorát to bohužel trvá 3 minuty.

Administrace sbírek volá velmi pomalý dotaz do ritriples vazeb Fedory. Protože se triplety budou přemisťovat do SOLRu, tak bych to neřešil.

**Comment by LenkaKravecova** [comment]
Už mi to taky najelo po nějaké době. Kdy by k tomu přemístění mělo dojít?
