### ISSUE TITLE
Počty stran periodik

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#197]
Můžete někdo zjistit celkové počty stran u těchto periodik? Díky.

uuid:dcc8142a-f3cd-11e0-b9a8-0050569d679d
uuid:87f6e957-90de-11e0-a36c-0050569d679d
uuid:45c17697-3622-11e1-99b6-0050569d679d

**Comment by leiblix** [comment]
Dá se zjištovat dotazem přes solr
`http://solr.dk-back.infra.mzk.cz/solr/kramerius/select?q=root_pid:uuid\:dcc8142a-f3cd-11e0-b9a8-0050569d679d&fedora.model=page` Stačí  vždy zaměnit PID (pozor akorát na prefix před dvojtečkou v uuid). Výsledek je v numfounds.

|  uuid | počet stran  | 
|---|---|
|uuid:dcc8142a-f3cd-11e0-b9a8-0050569d679d | 634|
|uuid:87f6e957-90de-11e0-a36c-0050569d679d21 | 21197|
|uuid:45c17697-3622-11e1-99b6-0050569d679d | 6762|

**Comment by LenkaKravecova** [comment]
Ok, díky!
