### ISSUE TITLE
Změnit buildery pro metadata v generovaném PDF

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#198]
Týká se to builderů:
PublisherBuilder.java
PeriodicalVolumeNumberBuilder.java
PeriodicalIssueNumberBuilder.java
AuthorBuilder.java

Změnit, prosím, podle zadání v https://docs.google.com/document/d/1r2BVqX7oHBs1QnUrNiJGlqUkTE3MNyQwWpEF7OTaOTM/edit. Potřebuju zjistit, jestli se to dá takto nastavit, pak to nahlásím do hlavní vývojové větve.

**Comment by LenkaKravecova** [comment]
Jaký je aktuální stav, @kenji1322 ?

**Comment by MarosGrm** [comment]
Je to už mergnuté na českej expedici, bude to nasadené spolu s novou verziou Krameria.

**Comment by LenkaKravecova** [comment]
@kenji1322 jaký je teď stav, prosím tě?

**Comment by MarosGrm** [comment]
Funkčné
