### ISSUE TITLE
Objekty s chybějícími a zbytečnými vazbami

### ISSUE THREAD

**Issue by kazooo** [moravianlibrary/kramerius#199]
Seznam ročníků a čísel, kterým chybí rodiče a potomky. Periodika už jsou opravená.
[objects.txt](https://github.com/moravianlibrary/kramerius/files/1182457/objects.txt)

**Comment by kazooo** [comment]
Ročníky, čísla a monografie jsou opravené.

**Comment by kazooo** [comment]
Zbývá kontrola a oprava stránek, nějaká půlka už je opravená.

**Comment by kazooo** [comment]
Příkladám seznam uuid stránek a jejich kořeny, ktere propojuji.
[page_links.txt](https://github.com/moravianlibrary/kramerius/files/2960646/page_links.txt)
**EDIT:**
Z tohoto seznamu část jsou sirotky a ještě část jsou neodmazané triplety
[stranky_sirotky.txt](https://github.com/moravianlibrary/kramerius/files/2961353/stranky_sirotky.txt)
[neodmazane_triplety.txt](https://github.com/moravianlibrary/kramerius/files/2961355/neodmazane_triplety.txt)

**Comment by kazooo** [comment]
Ta část stránek ze seznamu **page_links.txt**, které měly informace o rodičích, je opravena.
Stránky z **stranky_sirotky.txt** jsem shlukoval podle cesty do obrazků na imageserveru ve snaze nějak odhadnout rodiče. U části těchto stránek se timto způsobem podařilo najit nadřazené objekty a přípojit je zpět a také najit jejich připojené verze, takže se jedna o duplicity.
[duplicity.txt](https://github.com/moravianlibrary/kramerius/files/2996548/duplicity.txt)

Ze zbyvajících jsem udělal další seznamy, jsou nazvány podle složek, ve kterých jsou obrázky strán umístěny:
[boe801.txt](https://github.com/moravianlibrary/kramerius/files/2996474/boe801.txt)
[mzk01.txt](https://github.com/moravianlibrary/kramerius/files/2996475/mzk01.txt)
[mzk03.txt](https://github.com/moravianlibrary/kramerius/files/2996476/mzk03.txt)
[ndk2013.txt](https://github.com/moravianlibrary/kramerius/files/2996477/ndk2013.txt)
[ndk2015.txt](https://github.com/moravianlibrary/kramerius/files/2996536/ndk2015.txt)
[ndk2012-2014-2016.txt](https://github.com/moravianlibrary/kramerius/files/2996537/ndk2012-2014-2016.txt)
[meditor.txt](https://github.com/moravianlibrary/kramerius/files/2996490/meditor.txt)
V uvědených složkach zkusím vyhledat title page a podívám se jestli zase jde o duplicity, pokud ne, přípojím stránky k rodičům.

Dané stránky nemají ani obrázky, pravděpodobné už nezjistíme nic o nich z metadat, tak je odmažu.
[no_image.txt](https://github.com/moravianlibrary/kramerius/files/2996522/no_image.txt)

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
