### ISSUE TITLE
Rozbite dlazdice

### ISSUE THREAD

**Issue by dsecik** [moravianlibrary/kramerius#20]
Odkaz na dokument: http://krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:fde4bf10-1648-11e3-84ec-5ef3fc9bb22f

HTTP Status 500 - Server returned HTTP response code: 400 for URL: http://krameriusndktest.mzk.cz/imageserver/NDK/2013/9af9b660-fd9f-11e2-9923-005056827e52/UC_9af9b660-fd9f-11e2-9923-005056827e52_0001/TileGroup0/1-1-2.jpg

type Exception report

message Server returned HTTP response code: 400 for URL: http://krameriusndktest.mzk.cz/imageserver/NDK/2013/9af9b660-fd9f-11e2-9923-005056827e52/UC_9af9b660-fd9f-11e2-9923-005056827e52_0001/TileGroup0/1-1-2.jpg

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.io.IOException: Server returned HTTP response code: 400 for URL: http://krameriusndktest.mzk.cz/imageserver/NDK/2013/9af9b660-fd9f-11e2-9923-005056827e52/UC_9af9b660-fd9f-11e2-9923-005056827e52_0001/TileGroup0/1-1-2.jpg
    sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
    cz.incad.Kramerius.AbstractImageServlet.copyFromImageServer(AbstractImageServlet.java:238)
    cz.incad.Kramerius.imaging.ZoomifyServlet.renderIIPTile(ZoomifyServlet.java:348)
    cz.incad.Kramerius.imaging.ZoomifyServlet.renderTile(ZoomifyServlet.java:264)
    cz.incad.Kramerius.imaging.ZoomifyServlet.doGet(ZoomifyServlet.java:140)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
    com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    cz.incad.Kramerius.CORSFilter.doFilter(CORSFilter.java:26)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.32 logs.

Apache Tomcat/7.0.32

**Comment by dsecik** [comment]
V Honzovom krameriu sa zobrazuje korektne http://janrychtar.cz/kramerius/#/ndk/view/uuid:9af9b660-fd9f-11e2-9923-005056827e52?page=uuid:fde4bf10-1648-11e3-84ec-5ef3fc9bb22f 
@honza-rychtar aku prohlizecku pouzivas?

**Comment by honza-rychtar** [comment]
@dsecik Pouzivam prohlizecku na OpenLayers 3.x, stejne jako novy klient od INCADu, kde to taky nedela problemy.
K4 klient pouziva prohlizecku nad Openlayers 2.x

**Comment by Jenyk** [comment]
už je na to issue: https://github.com/ceskaexpedice/kramerius/issues/237

**Comment by Jenyk** [comment]
@LenkaDamborska tohle můžeme zavřít, když už je pro veřejnost klient?
