### ISSUE TITLE
Export Foxml upraví obsah datastreamu s obrázky

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#200]
Při použití Export FOXML dojde k úpravě datastreamů, které odkazují na externí obrázky (v imageserver-u) do podoby s <foxml:binaryContent>.

Testováno na ab39ad75-2134-40b8-9afc-0355c6fa5164

**Comment by LenkaKravecova** [comment]
A co s tím? :)

**Comment by jkremlacek** [comment]
Už si přesně nepamatuju, jaká byla domluva s Martinem, ale mám pocit, že myšlenka byla taková, že by export měl "vyplivnout" foxml tak jak je uložené ve Fedoře, aby byl export použitelný pro zpětný import do Krameria (v současném stavu by zpětný import uložil obrázky do Fedory).

Každopádně vzhledem k tomu, že už je Fedora 4 za dveřmi, tak by asi stálo za to počkat/zjistit jak se chová export tam a pokud by už obrázky nebyly uložené ve foxml (resp jeho ekvivalentu pro F4, protože foxml je věc F3), tak issue zavřít.

**Comment by dsecik** [comment]
Nebude to tym, ze v pripade mapy co uvadzas su tie datasreamy interne? V takom pripade to imho nie je chyba.
```
<foxml:datastream ID="IMG_FULL" STATE="A" CONTROL_GROUP="M" VERSIONABLE="false">
<foxml:datastreamVersion ID="IMG_FULL.0" LABEL="Presentable version of RAW" CREATED="2017-06-26T15:21:52.351Z" MIMETYPE="image/jpeg" SIZE="610628">
<foxml:contentLocation TYPE="INTERNAL_ID" REF="uuid:ab39ad75-2134-40b8-9afc-0355c6fa5164+IMG_FULL+IMG_FULL.0"/>
</foxml:datastreamVersion>
</foxml:datastream>
```
Skusal som to na "slunecku" ktore ma datastreamy externe a foxml sa vygenerovali normalne s odkazmi na imageserver.

```
<foxml:datastream ID="IMG_FULL" STATE="A" CONTROL_GROUP="R" VERSIONABLE="true">
<foxml:datastreamVersion ID="IMG_FULL.0" LABEL="" CREATED="2012-06-28T10:02:25.000Z" MIMETYPE="image/jpeg">
<foxml:contentLocation TYPE="URL" REF="http://imageserver.mzk.cz/mzk01/000/329/646/5b93cdc8-6f6e-4d54-ace0-f084a99e610f/big.jpg"/>
</foxml:datastreamVersion>
</foxml:datastream>

```

**Comment by jkremlacek** [comment]
Toho interního id jsem si nevím proč nevšiml, nicméně ten DS by měl být bokem, protože generování binaryContent od určité velikosti obrázku zkolabuje.

**Comment by zabak** [comment]
Jinými slovy, měli bychom zkontrolovat kolik máme interních DS, všechny extrahovat ven a zamezit tomu, aby interní DS vznikaly. Je to tak? Předpokládám, že před migrací do Fedory 4 to stejně bude muset proběhnout.

**Comment by LenkaKravecova** [comment]
Jo, to by chtělo zkontrolovat, ale moc by tam toho být nemělo. Vše se dávalo do imageserveru.

**Comment by jkremlacek** [comment]
Už existující záznamy s interními DS obrázků, které tam nemají být (tj interně by měl být pouze thumbnail), by se měly opravit - nicméně chtělo by zjistit, jak se zachová migrace Krameria z F3 do F4 nad interním/externím DS a podle toho se rozhodnout jestli tu opravu udělat před anebo po migraci.  

Spolu s tím by asi stálo za to i zkontrolovat jestli externí DS skutečně odkazují do imageserveru a ne někam jinam (např v rámci #152 bylo několik atlasů, které odkazovaly na http://klokan.mzk.cz)

**Comment by zabak** [comment]
Mimochodem, měl jsem za to, že thumbnaily generuje taky imageserver on the fly. Tj. potřebujeme mít ve fedoře thumbnaily? Nebude rychlejší konverze do F4, když tam nebudou?

**Comment by dsecik** [comment]
Ano, myslim ze idealne by bolo vsetky interne DS nahradit odkazmi na imageserver (vratane thumbnail pokial nie je nejaky specialny dovod preco musi byt interne). 

Tento konkretny pripad je zaujimavy v tom, ze obrazok je na imageserveri a v RELS-EXT sa nan odkazuje ale IMG_FULL, IMG_PREVIEW, IMG_THUMB su interne. My ked sme prevadzali interne djvu a jpg na jpeg2000 a nahravali ich na imageserver tak sme menili aj tieto DS na externe takze netusim odkial taketo dokumenty pochadzaju.

Zrejme by to vyzadovalo skontrolovat a pripadne opravit vsetky foxml stranok vo fedore.

**Comment by natal1H** [comment]
Bola vykonaná kontrola všetkých dokumentov, pri ktorej sa kontrolovalo, či nemá nejaká stránka interné IMG_FULL, IMG_PREVIEW alebo IMG_THUMB, ale nebol nájdený žiadny takýto prípad. Počas kontroly avšak boli nájdené ďalšie stránky a pár koreňových dokumentov s nevalidnými uuid a boli zaznačené do samostatného dokumentu. Našli sa aj stránky z NDK digitalizácie, u ktorých chýbal záznam vo fedore a solr a tieto boli nahlásené na reimport. Mnohým stránkam tiež chýbal IMG_PREVIEW datastream a bol doplnený pokiaľ sa jednalo o MZK digitalizáciu.
