### ISSUE TITLE
Dějiny věd a techniky - články

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#201]
Čísla periodika uuid:1e50f842-5fa6-4c6f-97d2-cb2dfa32fb6a obsahují model článek, ale ty asi neodkazují na příslušné strany, protože data nelze zobrazit. Stránky tam jinak jsou a jsou v pořádku.

**Comment by LenkaKravecova** [comment]
Třeba hned první článek https://krameriusadmin.mzk.cz/search/handle/uuid:a35ed369-6bbc-4f65-93af-adc6534a761a

**Comment by kazooo** [comment]
Problem je vyřešen tím, že periodikum byl reimportovan.
