### ISSUE TITLE
Chybné kódování diakritiky v OCR

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#203]
Konkrétně http://krameriusadmin.mzk.cz/search/i.jsp?pid=uuid:73f3e41a-65c9-11e0-b4ae-0050569d679d

Viz též https://github.com/honza-rychtar/kramerius-web-client/issues/18

Předpokládám, že toho bude víc, nevím ale, nakolik spolehlivě se to podaří rozpoznat. Mám ale dojem že to bylo replikované z VKOL, a možná je to ještě txt, nebo ne?

**Comment by LenkaKravecova** [comment]
Ano, bylo to replikované z VKOL a chybí tam ALTO, je to v seznamu na dodělání OCR. 
Bavili jsme se na poradě, že novým uděláním OCR by se kódování opravilo, že ano?
