### ISSUE TITLE
Indexace lokalizovaných názvů

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#204]
viz. https://github.com/honza-rychtar/kramerius-web-client/issues/295
Dalo by se toto upravit už v distribuci?

**Comment by leiblix** [comment]
Dalo :-)

**Comment by zabak** [comment]
A uděláš to?

**Comment by leiblix** [comment]
Jo, stejně budeme asi do indexeru zavádět více změn. Ale nevím kdy se k tomu dostanu. Probereme na schůzce...

**Comment by honza-rychtar** [comment]
Pri zmenach prosim o zaindexovani MODS:subject->geographic (podobne jako subject->topic, ktere jde do SOLR:keywords), tohle by mohlo jit do SOLR:geonames
A taky pridani souradnic do Solrem podporovaneho "geo" typu.
Mate k tomu nejakou schuzku? Mate nekde seznam navrzenych zmen v indexeru?

**Comment by leiblix** [comment]
Nemáme k tomu specifickou schůzku, myslel jsem normální poradu.

Seznam není, jsou jenom jednotlivá issue:
https://github.com/moravianlibrary/kramerius/issues/186
https://github.com/moravianlibrary/kramerius/issues/190
https://github.com/moravianlibrary/kramerius/issues/187

Pokud jich bude víc, vytvořím label.

**Comment by zabak** [comment]
@xermak00 Je už toto vyřešeno?

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
