### ISSUE TITLE
Text o obsahu DK

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#205]
"Ale bylo by dobre, kdyby pribyl dalsi text (napr. CONTENT), kde by se knihovny soustredily na obsah. Popis Krameria, vysvetleni autorskych prav, existenci mobilnich aplikaci atd. pak muze kazdy klient popsat sam a u kazde knihovny stejne - ne ze bude mit uzitatel podle prepnute knihovny 26 ruznych vysvetleni tehoz.
CONTENT text by mel byt napsany bez zavislositi na nejakem klientovi." 
Viz https://github.com/honza-rychtar/kramerius-web-client/issues/265

**Comment by leiblix** [comment]
Pozor, to teď nejde nastavit. Pokud je o to zájem musí se rozšířit API Krameria (ale není to velká změna, už jsme podobné věci dělali).

**Comment by LenkaKravecova** [comment]
Toto budeme řešit pro nové uživ. rozhraní v textu k tomu určenému. Zavírám.
