### ISSUE TITLE
chyba v datech rozbíjí oai provider (oai4solr)

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius#207]
Pro objekt uuid:10cfb93a-4ee0-49da-9122-c549bd4f85ba není odpověď oai-pmh provideru well-build xml kvůli vnitřní chybě, která probublá, kam by neměla:
http://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=uuid:10cfb93a-4ee0-49da-9122-c549bd4f85ba
Taky to rozbije ListRecords:
http://kramerius.mzk.cz/oai/?verb=ListRecords&metadataPrefix=drkramerius4&set=monograph

**Comment by leiblix** [comment]
Původní adresa: http://solr.dk-back.infra.mzk.cz/solr/kramerius/oai
Configy k pluginu: https://github.com/moravianlibrary/osdd-docker-images/tree/master/solr6/oai/oai

osobně bych opravil stránku http://kramerius.mzk.cz/search/oaiExport?pid=uuid:10cfb93a-4ee0-49da-9122-c549bd4f85ba , aby nevracela  500.

**Comment by leiblix** [comment]
Při řešení tohoto issue by se teoreticky mohl vyřešit i požadavek z https://github.com/ceskaexpedice/kramerius/issues/562

Formát drkramerius4 se používá pro registr digitalizace. Zjistím jestli přidání hodnoty public/private nerozbije jeho funkcionalitu.

**Comment by kazooo** [comment]
Chyba vznikla kvuli monografii, ktera neni ve Fedore. OAI provider zadal o xml udajich monografie, ziskaval chybovou hlasku a nemohl ji zpracovat jako xml dokument, proto padal. Opraveno tim, ze chybova hlaska se odesila v tagach <error>.

**Comment by leiblix** [comment]
Změna je nasazená. @rzeh4n Je to pro tebe takto v pohodě?

To https://github.com/ceskaexpedice/kramerius/issues/562 ještě potřebuješ, nebo sis nakonec poradil nějak jinak?

**Comment by rzeh4n** [comment]
@MartinRumanek Jo, můj prolbém se sklízením to řeší, díky.
Pokud jde o https://github.com/ceskaexpedice/kramerius/issues/562, tak to bysme pořád potřebovali kvůli Rezolveru. Protože tam se sklízí přes OAI vždy jeden záznam (tady drkramerius4), který by měl obsahovat všechny důležité informace. Změnit to tak, aby se sklízelo více záznamů, ty se pak nějak mergovaly je zbytečně zesložiťování, více prostorů pro chyby a nečekané situace no a takový postup mi příjde dost nesmyslný a proti filozofii OAI-PMH.

**Comment by leiblix** [comment]
@xermak00 Dobrá práce :-)
