### ISSUE TITLE
Chybějící dokument v krameriusndktest.mzk.cz

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#21]
V Pražském NDK Krameriu je dokument
http://kramerius4.nkp.cz/search/i.jsp?pid=uuid:a1bc5830-0648-11dd-8541-000d606f5dc6

který v našem Krameriu vidět není. Jak se to stalo?

Tento dokument je specifický tím, že má donátora. Potřebuju ho pro otestování API.

**Comment by popelkatomas** [comment]
Dokument byl zpracován jako tzv. importní dávka, což je jeden ze dvou možných způsobů zpracování dat z externího zdroje. Systém NDK v tomto případě odeslání do krameriusndktestu zcela ignoroval. Zjišťuju podrobnosti, zejména jestli jde o izolovaný jev, nebo systémový problém.

**Comment by leiblix** [comment]
> nektery dokumenty muze snad byt nejaka vyjimka z autorskyho zakona a ze z jeho pohledu je to uz "za linkou", na dotaz, kdo by mi k tomu dal blizsi info, me odkazal na Bartone
