### ISSUE TITLE
Chybné prihlásenie vyhadzuje stacktrace

### ISSUE THREAD

**Issue by MarosGrm** [moravianlibrary/kramerius#211]
<pre>
kramerius_1  | 13-Sep-2017 12:14:20.523 WARNING [http-nio-8080-exec-2202] org.apache.catalina.realm.JAASRealm.authenticate Login exception authenticating username "user"
kramerius_1  |  javax.security.auth.login.LoginException: Login Failure: all modules ignored
kramerius_1  | 	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:906)
kramerius_1  | 	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
kramerius_1  | 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
kramerius_1  | 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
kramerius_1  | 	at java.security.AccessController.doPrivileged(Native Method)
kramerius_1  | 	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
kramerius_1  | 	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
kramerius_1  | 	at org.apache.catalina.realm.JAASRealm.authenticate(JAASRealm.java:423)
kramerius_1  | 	at org.apache.catalina.realm.JAASRealm.authenticate(JAASRealm.java:340)
kramerius_1  | 	at org.apache.catalina.authenticator.FormAuthenticator.authenticate(FormAuthenticator.java:259)
kramerius_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:453)
kramerius_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
kramerius_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
kramerius_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
kramerius_1  | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
kramerius_1  | 	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:240)
kramerius_1  | 	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:569)
kramerius_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
kramerius_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
kramerius_1  | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
kramerius_1  | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
kramerius_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
kramerius_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
kramerius_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
kramerius_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
kramerius_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kramerius_1  | 	at java.lang.Thread.run(Thread.java:748)
kramerius_1  | 
</pre>

**Comment by LenkaKravecova** [comment]
Bude se kontrolovat průběžně.

**Comment by leiblix** [comment]
Nejde ani o kontrolu, stacktrace obvykle létají při závažných chybách aplikace, mezi což bych chybné zalogování uživatele nepřidával. 

Mělo by se to maximálně propsat do logu jako jednořádková informace o severitě INFO.

**Comment by leiblix** [comment]
Je to dost tricky :-D

Nenasel jsem k tomu nic v dokumentaci, tak jsem se podival do zdrojaku Tomcatu... (https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/realm/JAASRealm.java#L431)

*Reseni*
1. Upravit metodu login ve tride K4LoginModule.java aby pri spatnem prihlaseni vyhazovala  vyjimku - FailedLoginException.
2. vypnout debug v JAASu https://github.com/moravianlibrary/s2i-kramerius/blob/master/jaas.conf
