### ISSUE TITLE
Oprava ID datastreamu alto na ALTO

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#212]
Zjistit, kolik objektů ve Fedoře je potřeba opravit a vytvořit seznam.
Napsat skript na opravu a spustit proces asi po částech.

**Comment by LenkaKravecova** [comment]
Týká se cca 11 mil. objektů. Odhadovaná doba opravného procestu je 11 týdnů.

**Comment by kazooo** [comment]
11 mil. objektů jsou všechny stránky, které byly zaindexovany v době od roku 2016. Objektů, které reálně potřebují opravu v daný okamžik jsou 7.328.323, a rychlost zpracování cca 250.000 objektů/den, takže už můžeme říct, že oprava bude bežet kolem měsicu.

**Comment by LenkaKravecova** [comment]
hotovo
