### ISSUE TITLE
Import PDF do Krameria

### ISSUE THREAD

**Issue by zdenekhruska** [moravianlibrary/kramerius#215]
Po domluvě s Martinem Rumánkem zakládám issue ohledně importu PDF do Krameria MZK. MEditor postupně přestává vyhovovat, objevují se chyby, které komplikují práci.
Aktuálně se nám stalo, že v MEditoru se zpracovávalo jedno PDF, ale nějak se do Krameria MZK dostala data i metadata jiného (předtím zpracovaného) PDF.  Naimportovalo se toto: http://kramerius.mzk.cz/search/handle/uuid:a7c76468-37ad-435b-830c-101afaa36795 a měl se naimportovat tento dokument: 
2610641399,  CDR-1350.827, Strojírenské technologie I

Ideální by bylo, aby Proarc co nejdříve uměl pracovat s PDF.

**Comment by jkremlacek** [comment]
Co se týče ProArc-u, tak ten umí s PDF pracovat v rámci eČlánku (model article). Pro ostatní modely je již založené issue https://github.com/proarc/proarc/issues/534, které nejdříve musí být schváleno k vývoji (řešeno v rámci rozvoje pro rok 2018).

**Comment by jkremlacek** [comment]
Update: 

ProArc už umí zpracovat PDF, nicméně není podporován export přímo do Krameria - je k dispozici pouze export do PSP balíku. Bude třeba zvážit zda doimplementovat do ProArc-u export PDF do Krameria, anebo jít cestou PSP balíků (kde je ovšem problém, že část zpracovávaných dokumentů nejsou "eborn").

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
