### ISSUE TITLE
Přidání informce policy do OAI záznamu

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#218]
Rozšíření formátu drkramerius4 o dostupnost
viz https://github.com/ceskaexpedice/kramerius/issues/562
a předposlední komentář zde https://github.com/moravianlibrary/kramerius/issues/207

Vyřešit pouze pro oai4solr, starý oaiprovider nemáme v MZK vůbec nasazený - navíc s Fedorou 4 se od něho upustí úplně.

**Comment by leiblix** [comment]
@rzeh4n Vyhovuje ti to takhle?
http://kramerius.mzk.cz/oai/?verb=ListRecords&metadataPrefix=drkramerius4&set=monograph
```
<dr:uuid>1a2d4984-3074-11e0-8e0a-0050569d679d</dr:uuid>
<dr:type>MONOGRAPH</dr:type>
<dr:policy>policy:private</dr:policy>
```

**Comment by rzeh4n** [comment]
@MartinRumanek Jasně, může být, díky!
