### ISSUE TITLE
Články u Lidových novin - rozbité vazby

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#227]
Jsou rozbité vazby mezi stránkami a články u Lidových novin, např. http://krameriusadmin.mzk.cz/search/i.jsp?pid=uuid:ac2cdbe7-4c94-4761-bfbc-e2f9269bcd26&q=&fq=document_type:%22article%22#periodical-periodicalvolume-periodicalitem-article_uuid:ac2cdbe7-4c94-4761-bfbc-e2f9269bcd26

**Comment by kazooo** [comment]
Stejný problem jako v #201, ale reimportovat celé noviny bylo by dost náročně. Zkusím zjistit PID všech članků a potom třeba reindexovat je.

**Comment by LenkaKravecova** [comment]
Díky.

**Comment by kazooo** [comment]
Podařilo se mi zjistit přičinu kvůli čemu se nám nezobrazují stránky v článcích. Na úrovní dat ve Fedoře je všechno v pořádku, ale problem je v Solru: v metadatech stránek v poli pid_path a parent_pid chybí cesta k   článkům a PID článků. 

normální stránka: [uuid:240d5e90-4ec6-11dd-9522-000d606f5dc6](http://solr.dk-back.infra.mzk.cz/solr/kramerius/select?fl=pid_path,%20parent_pid,%20model_path&indent=on&q=PID:%22uuid:24b55f60-4ebb-11dd-b761-000d606f5dc6%22&wt=json)
nezobrazuje se: [uuid:24b55f60-4ebb-11dd-b761-000d606f5dc6](http://solr.dk-back.infra.mzk.cz/solr/kramerius/select?fl=pid_path,%20parent_pid,%20model_path&indent=on&q=PID:%22uuid:24bc8b50-4ebb-11dd-ba9f-000d606f5dc6%22&wt=json)

Po reimportu článků, v metadatech stránek už se objevují chybející data a všechno se krásně zobrazuje. Jednoduchá reindexace nepomáhá, vypadá to tak, že stránky na začatku musí byt připojeny jenom k článkům, a jen potom k číslam.

Celkem článku je 56 369. Popřemýšlím jakým vhodným způsobem by to šlo všechno opravit.

**Comment by kazooo** [comment]
Ještě komplikuje situace to, že několik článků můžou odkazovat na jednu stránku, takže reimport nepomůže také.
Zkusím to řešit pomoci editace metadat Solru, přes Solr API.

**Comment by leiblix** [comment]
Asi ta informace nějak zmizela při migraci SOLRu :-( Nejlepší by bylo samozřejmě upravit indexer, aby to uměl opravit.

**Comment by LenkaKravecova** [comment]
Stejný problém je také u Revolver revue uuid:9d624502-f3f2-4daf-bf7f-010d860546b0, tam to snad reimport vyřeší, ale ty Lidovky, to je problém.

**Comment by kazooo** [comment]
Zkusil jsem přidat potřebná data do Solru, po úprave se všechno normálně zobrazuje, ale když reindexuju stránku, tak všechny změny zmizeji a je to znovu rozbité.
Pokud to dává smysl, můžu zatim vytvořit skript, který nam dočasně (do první reindexace) opraví články, aspoň se budou zobrazovat.
Ale samozřejmě potřebujeme opravit indexer, jak už zmiňoval Martin. Podívám se na to a bylo by dobře kdyby se na to podíval i někdo z autorů indexeru.

**Comment by kazooo** [comment]
Nakonec jsem přišel na to. Indexer funguje správně, při reindexace dotazuje na triplety z Fedory, a je problem ten, že triplety isOnPage pro články Lidových novin zmizely z Fedory. Proto indexer nepřidával k metadatam stránek PID článků, a ty se nam nezobrazovaly.
Reimport pomáhal tím, ze vytvářel potřebné triplety. 
Napíšu skript, který nam vloží triplety do databáze. Revolver revue jsem reimportoval.

**Comment by kazooo** [comment]
Hotovo.
