### ISSUE TITLE
Varování ve Fedoře

### ISSUE THREAD

**Issue by kazooo** [moravianlibrary/kramerius#228]
Pro neexistující objekty ve Fedoře se objevují varování "no path in db registry for uuid" se zbytečně velkým stacktracem.
Také je třeba nejak řešit varování "Relationships API methods" - vzniká docela často.

**Comment by kazooo** [comment]
Příklady:
```
WARN 2017-11-10 12:28:42.554 [http-nio-8080-exec-2554] (DefaultManagement) Relationships API methods:  the 'pid' (uuid:ac2dd7f0-c49b-11e7-bfaa-005056827e52) form of a relationship's subject is deprecated.  Please specify the subject using the info:fedora/ uri scheme.
WARN 2017-11-10 12:29:15.674 [http-nio-8080-exec-2453] (BaseRestResource) Resource not found: no path in db registry for [uuid:94218060-437e-11e2-b246-005056827e52]; unable to fulfill REST API request
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [uuid:94218060-437e-11e2-b246-005056827e52]
	at org.fcrepo.server.storage.lowlevel.DBPathRegistry.get(DBPathRegistry.java:147) ~[fcrepo-server-3.8.1.jar:na]
	at org.fcrepo.server.storage.lowlevel.defaultstore.Store.getFile(Store.java:177) ~[fcrepo-server-3.8.1.jar:na]
	at org.fcrepo.server.storage.lowlevel.defaultstore.Store.retrieve(Store.java:144) ~[fcrepo-server-3.8.1.jar:na]
	at org.fcrepo.server.storage.lowlevel.DefaultLowlevelStorage.retrieveObject(DefaultLowlevelStorage.java:87) ~[fcrepo-server-3.8.1.jar:na]
```

**Comment by leiblix** [comment]
Ty stacktrace jsou otravne (Kibana si s nema neporadi), tak je bude mozna lepsi vypnout - predpokladam, ze je nepotrebujeme.

Melo by stacit pridat tyto radky
```
  <jaxrs:providers>
      <bean class="org.fcrepo.server.rest.cxf.WadlGenerator" />
      <bean class="org.apache.cxf.jaxrs.impl.WebApplicationExceptionMapper">
      </bean>
</jaxrs:providers>
```

do configu `objects-jaxrs.xml`. Muzes se inspirovat zde https://github.com/moravianlibrary/osdd-docker-images/tree/master/fcrepo/3.8.1-mulgara (to pouzivame na proarcu), je to velmi podobne, akorat asi nezapinej  `setAddMessageToResponse`, to by bylo zbytecne, kramerius to nepotrebuje.

Podle Javadocu https://cxf.apache.org/javadoc/latest/org/apache/cxf/jaxrs/impl/WebApplicationExceptionMapper.html#setPrintStackTrace-boolean- jsou potom stacktraces logovany na urovni FINE, takze to zmizi.

_________

Spis by bylo dobre zjistit, odkud se tyto neexistujici PIDs berou. Protoze normalni to neni.

Pokud jsou v SOLRu a nejsou ve Fedore je to problem, ktery by mel Kramerius nejak hezky logovat. Ale Maros mi rikal, ze ty UUID v SOLRu nejsou, tak potom fakt nevim kde se berou (mozna ve vazbach).

**Comment by leiblix** [comment]
Vypadá to, že to nepomohlo :-( Testoval jsi to na lokále?

**Comment by kazooo** [comment]
Na lokále jsem to testoval, ale možno jsem dělal něco jíného, něž co se děje ve Fedoře a vyhazuje chyby. Zjistím kde se ta chyba volá a přepišu na krásnější logování, pokud nejde vypnout.

**Comment by kazooo** [comment]
Zkusil jsem pohrat s parametrem printStackTrace pro WebApplicationExceptionMapper, ale taky to nepomohlo. @MartinRumanek je s tim mozne jeste neco udelat?

Pokud spravne tomu rozumim, chyba vznika, kdyz nekdo dotazuje pres API Krameria na neexistujici dokumenty a jejich datastreamy. Kramerius loguje chybu, ale zaroven vypisuje telo HTML odpovedi, nevim k cemu to je.
Treba
```
04-Dec-2017 13:26:03.448 SEVERE [http-nio-8080-exec-18876] cz.incad.kramerius.utils.RESTHelper.inputStream status code 404
04-Dec-2017 13:26:03.448 SEVERE [http-nio-8080-exec-18876] cz.incad.kramerius.utils.RESTHelper.inputStream 

<html><head>
      <title>Fedora: 404 Not Found</title></head>
   <body>
      <center>
         <table border="0" cellpadding="0" cellspacing="0" width="784">
            <tbody><tr>
				<td height="134" valign="top" width="141"><img src="/fedora/images/newlogo2.jpg" height="134" width="141"></td>
               <td valign="top" width="643">
                  <center>
                     <h2>404 Not Found</h2>
                     <h3>No such object, datastream, or dissemination.</h3>
                  </center>
no path in db registry for [uuid:cf250030-5710-11e5-9a33-5ef3fc9ae868]
               </td>
            </tr>
         </tbody></table>
      </center>
   </body></html>

04-Dec-2017 13:26:03.448 WARNING [http-nio-8080-exec-18876] cz.incad.kramerius.impl.FedoraAccessImpl.processSubtreeInternal could not read RELS-EXT, skipping branch [1] and pid (uuid:cf250030-5710-11e5-9a33-5ef3fc9ae868):java.io.FileNotFoundException: http://fedora.dk-back.infra.mzk.cz/fedora/get/uuid:cf250030-5710-11e5-9a33-5ef3fc9ae868/RELS-EXT
04-Dec-2017 13:26:12.044 INFO [http-nio-8080-exec-19050] cz.incad.Kramerius.ClientClosedRequestFilter.doFilter Client closed request: https://kramerius.mzk.cz/search/api/v5.0/search/
```

**Comment by LenkaKravecova** [comment]
Co s tím dál?

**Comment by kazooo** [comment]
Logování chyby v Krameriu bylo opraveno v https://github.com/ceskaexpedice/kramerius/commit/d7bd7056528af5ec807a6427e202157ba9f626a6
Co se tyká logů ve Fedoře, kdybychom to úplně  vypnuli tak se nám v budoucnu nebudou logovat další i jiné chyby, což není pro nás moc dobře, kdyby se něco stalo neuvidíme to ve Fedoře.
Opravím data podle tých logů, a myslím, že ty logý budou pro nás užitečné.

**Comment by jkremlacek** [comment]
Vzhledem k tomu, že logstash už máme upravený tak, aby se stacktrace-y seskupovaly do jednoho záznamu, tak si myslím, že issue není potřeba dál řešit. @xermak00 souhlas?

Momentálně je v Kibaně těchto logů minimum (řádově jednotky za minutu, vznikají během importů z NDK - nejde o chybu), dají se snadno odfiltrovat, ale přitom už nás několikrát přivedly na stopu chybě, takže vypínání by bylo k ničemu.

**Comment by kazooo** [comment]
@jkremlacek souhlasim se
