### ISSUE TITLE
Indexace geografických názvů

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#229]
Nápad od @honza-rychtar 

V modsu MODS //subject/geographic indexovat podobným způsobem jako klíčová slova. 

Bude to užitečné pro celou Mollovu sbírku (http://www.digitalniknihovna.cz/mzk/search/?sort=newest&accessibility=all&keywords=Mollova%20mapov%C3%A1%20sb%C3%ADrka)

**Comment by leiblix** [comment]
Merguji do distribuce.

**Comment by leiblix** [comment]
Vlastně....nebudu ti to zavírat. Ještě si to budete muset předpokládám přeindexovat :-)

**Comment by leiblix** [comment]
++ se ten merge nějak nepodařil. Soubor v distribuci se trochu změnil a je tam konflikt. Uděláš prosím nový commit do upstreamu (ceskaexpedice)?

**Comment by kazooo** [comment]
Modely typů map a graphic byly zreindexovány na Krameriu 5.4.2, a nyní obsahují geo. názvy a souřadnice.

**Comment by LenkaKravecova** [comment]
Ještě něco zbývá nebo se to může zavřít?

**Comment by zabak** [comment]
Může se zavřít.
