### ISSUE TITLE
rozbitý OAI Provider

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius#231]
Momentálně OAI Provider pro GetRecord nevrací ani validní xml s elementem _error_, hlavně je ale problém ta samotná chyba, která způsobuje nefunkčnost všech záznamů. V těle odpovědi je pak něco takového:
```
<GetRecord><record>
<header>
  <identifier>uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23</identifier>
  <datestamp>2014-01-21T12:05:24Z</datestamp>
  <setSpec>monograph</setSpec>
</header>
<metadata<error code="0">com.sun.org.apache.xalan.internal.xsltc.TransletException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: The element type "hr" must be terminated by the matching end-tag "</hr>".</error>
</GetRecord>
``` 
Dělá to pro všechny formáty, viz:
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=ese&identifier=uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=oai_dc&identifier=uuid:9ebcb206-24b7-4dc7-b367-3d9ad7179c23

Nejspíš za tím bude nějaký překlep v xslt.

**Comment by leiblix** [comment]
Je to kvůli redirectu Krameria z http na https - xslt parser ho nezvládne a místo toho načte redirect stránku, která obsahuje ten neukončený tag `hr`.

**Comment by leiblix** [comment]
Opravené, ale pozor, trochu jsem to zrefaktoroval a opravil jsem OAI identifikátor. Samotné UUID bylo nevalidní!

Nyní OAI identifikátor vypadá takto: `oai:kramerius.mzk.cz:uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22`

**Comment by rzeh4n** [comment]
Super, díky.
