### ISSUE TITLE
OAI Provider - podoba identifikátoru

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius#233]
Podle https://github.com/moravianlibrary/kramerius/issues/231#issuecomment-348171960 má identifikátor vypadat `oai:kramerius.mzk.cz:uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22`, teď tam ale bývá buď `oai:localhost:uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22`, nebo dokonce nevalidní `uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22`.
Viz
http://kramerius.difmoe.eu/solr/oai?verb=Identify
http://kramerius.difmoe.eu/solr/oai?verb=ListRecords&metadataPrefix=ese

Pro drkramerius4 a oai_dc jsou stále identifikátory ve staré nevalidní podobě:
(record/header/identifier)
http://kramerius.difmoe.eu/solr/oai?verb=ListRecords&metadataPrefix=drkramerius4
http://kramerius.difmoe.eu/solr/oai?verb=ListRecords&metadataPrefix=oai_dc
http://kramerius.difmoe.eu/solr/oai?verb=GetRecord&metadataPrefix=drkramerius4&identifier=uuid:a013e884-4594-4d5a-b33a-7daf03869c80
http://kramerius.difmoe.eu/solr/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=uuid:a013e884-4594-4d5a-b33a-7daf03869c80

Dále pro formát ese, kde pro ListRecords se vrací validní identifikátor (s localhost) se GetRecord chytne na nevalidní podobu identifikátoru:
http://kramerius.difmoe.eu/solr/oai?verb=GetRecord&metadataPrefix=ese&identifier=uuid:a013e884-4594-4d5a-b33a-7daf03869c80 (a v hlavičce odpovědi je oai:localhost:uuid:a013e884-4594-4d5a-b33a-7daf03869c80)
Ale na validní už ne:
http://kramerius.difmoe.eu/solr/oai?verb=GetRecord&metadataPrefix=ese&identifier=oai:localhost:uuid:a013e884-4594-4d5a-b33a-7daf03869c80
http://kramerius.difmoe.eu/solr/oai?verb=GetRecord&metadataPrefix=ese&identifier=oai:kramerius.mzk.cz:uuid:a013e884-4594-4d5a-b33a-7daf03869c80

**Comment by rzeh4n** [comment]
Aha, moje chyba, jiný Kramerius.

**Comment by leiblix** [comment]
:-) Konfigurace OAI pro SOLR6 je popsaná zde https://github.com/ceskaexpedice/kramerius/tree/oai4solr6/installation/oai4solr6

Pro změnu prefixu stačí změnit konfigurační soubor https://github.com/ceskaexpedice/kramerius/blob/oai4solr6/installation/oai4solr6/conf/solrconfig.xml#L1463
a pak ještě XSLT šablony.

**Comment by rzeh4n** [comment]
Díky, opravil jsem to pro http://difmoe.u. Mimochodem stejně jsou přijímány i některé neplatné identifikátory. Asi to není problém, ale je dobré o tom vědět. 
Takhle je to správně:
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.cz:uuid:944d0d82-235e-45de-9433-3ea9bffea529

Navíc stejná odpověď je pro tyhle špatné identifikátory.
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.XX:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.yyy.XX:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:zzzzZZZZZ.yyy.XX:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.12:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.-2:uuid:944d0d82-235e-45de-9433-3ea9bffea529

Tohle neprojde:
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.COM:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.MK.cz:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius4.mzk.cz:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:k4.mzk.cz:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:KRAMERIUSMZK.cz:uuid:944d0d82-235e-45de-9433-3ea9bffea529
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:KRAMERIUSMZKCZ:uuid:944d0d82-235e-45de-9433-3ea9bffea529

Takže musí souhlasit počet znaků v segmentech mezi tečkami, ale už ne samotné znaky.

**Comment by leiblix** [comment]
Zajímavé zjištění :-)

projde i toto:
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:thepiratebay.org:uuid:944d0d82-235e-45de-9433-3ea9bffea529

Je to pravděpodobně bug v https://github.com/IISH/oai4solr, ten prefix interně odstraní, ale zřejmě se řídí jen délkou OAI identifieru...
