### ISSUE TITLE
Generované PDF - rozhozená textová vrstva

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#236]
U některých dokumentů je textová vrstva v PDF lehce posunutá mimo obrázek a nevypadá to dobře. Viz třeba uuid:26714400-55bb-11e4-8b11-005056827e51 nebo uuid:b8bf0f00-92e2-11e3-8e84-005056827e51. Ozkoušeno generování PDF jak v Krameriu, tak i v klientovi. Asi to souvisí s atypickými rozměry stran. Dřív jsem si takového problému nevšimla.

**Comment by MarosGrm** [comment]
Mám taký pocit, že už od začiatku ako bolo povolené generovanie dvojvrstvových PDF bola textová vrstva pri niektorých dokumentoch posunutá. Vyššie spomínané dve monografie sú celkom extrémny prípad, kde to je naozaj dosť posunuté. Príklady diel kde nie je posunutie textovej vrstvy až tak výrazné: uuid:13fc6b2f-6447-11e0-8ad7-0050569d679d, uuid:702b06f0-07e6-11e7-9446-005056827e51. 

Skúsim, či pri tých, kde je to posunutie tak výrazne, by nepomohlo znovu vytvoriť OCR a ALTO.

**Comment by LenkaKravecova** [comment]
Díky. Můžeme pak vyzkoušet. Jinak už na to vzniklo issue i zde https://github.com/ceskaexpedice/kramerius/issues/568.

**Comment by leiblix** [comment]
@kenji1322 Zkoušel jsi to nové OCR? Pomohlo to?

Prosím ověř jestli se to týká jen PDF nebo jestli se to projeví i jinde (v prohlížečce).

**Comment by MarosGrm** [comment]
Vytvorenie nového OCR a ALTA nepomohlo, ale ta textová vrstva je rozhodená inak. Týka sa to iba PDF.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
