### ISSUE TITLE
Editor částí - nespustí reindexaci

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#237]
Při snaze uložit upravený objekt v Editoru částí se objeví hláška, že objekt nelze uložit. Skutečnost je ale taková, že změna se uloží ve Fedoře, ale pak je potřeba to ručně reindexovat. A pak už je to ok. 

Editor částí by měl automaticky spustit reindexaci dle https://github.com/ceskaexpedice/kramerius/wiki/MenuAdministrace#editor-po%C5%99ad%C3%AD-%C4%8D%C3%A1st%C3%AD-dokumentu. 

Chybová hláška: 
Cannot save 1 objects:
Besedy lidu: laciný prostonárodní obrázkový časopis(uuid:b6bb1c70-26da-11e5-bcc5-5ef3fc9bb22f)

**Comment by kazooo** [comment]
Není možné také načtení dokumentů na lokálu,
stacktrace:
```
23-Jan-2018 10:45:34.299 SEVERE [http-nio-8080-exec-10] cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute null
 java.io.IOException: Cannot load relations: uuid:abe050fb-e8f6-4239-9877-243ede78c2e5
	at cz.incad.kramerius.relation.impl.RelationServiceImpl.load(RelationServiceImpl.java:64)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.fetchRelations(GetKrameriusObjectQueryHandler.java:161)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute(GetKrameriusObjectQueryHandler.java:95)
	at cz.incad.kramerius.editor.server.GetKrameriusObjectQueryHandler.execute(GetKrameriusObjectQueryHandler.java:64)
```

**Comment by kazooo** [comment]
Logy z Krameria:
```
23-Jan-2018 15:51:46.938 INFO [http-nio-8080-exec-2712] cz.incad.kramerius.service.impl.IndexerProcessStarter.spawnIndexer Spawn indexer: title: ...
23-Jan-2018 15:51:46.995 INFO [http-nio-8080-exec-2712] cz.incad.kramerius.service.impl.IndexerProcessStarter.planIndexProcess authToken :null
23-Jan-2018 15:51:46.995 INFO [http-nio-8080-exec-2712] cz.incad.kramerius.service.impl.IndexerProcessStarter.planIndexProcess token :null
```
v [konfiguraci editora](https://github.com/ceskaexpedice/editor/blob/master/src/main/resources/res/configuration.properties) se pouzivaji prihlasovaci udaje uzivatele krameriusAdmin pro operace v Krameriu, napr. [reindexace](https://github.com/ceskaexpedice/editor/blob/master/src/main/java/cz/incad/kramerius/editor/server/RemoteServicesImpl.java#L78-86), ale tyto udaje nejsou spravne, proto neautorizovany editor nemuze spustit reindexace objektu v krameriu.

**Comment by kazooo** [comment]
Opraveno, uz jde reindexace.

**Comment by leiblix** [comment]
Jak? Přimountovali jste konfigurační soubor, co :-)? Nebylo by to lepší opravit přímo v image?

**Comment by kazooo** [comment]
Editor je samostatny war balicek uvnitr Krameria, nevidim moznosti jak by konfigurak bylo mozne primountovat tak, aby to fungovalo. Proto jsem opravil udaje v konfiguraku, vytvoril novy balik editoru a instaloval znovu na nas Kramerius.

**Comment by leiblix** [comment]
War po deploy tomcatu automaticky rozbali. Muzes to primountovat rozbalene, ale to taky neni spravne reseni.

Davalo by smysl editro upravit tak, aby se ridl env promennyma a do nich nadefinovat uzivatele Krameria.

**Comment by leiblix** [comment]
Heslo do docker image nepatří.

**Comment by LenkaKravecova** [comment]
Tak teď nevím, v jakém je to stavu, ale zkoušela jsem seřadit ročníky u periodika uuid:7753c610-5b5a-11e3-8c6a-005056825209 a znovu vyběhla hláška Cannot save 1 object a reindexace se nespustila. Spustila jsem ji až ručně. Takže oprava se nezdá být úspěšná.

**Comment by kazooo** [comment]
Opravený editor částí je v novém releasu [Krameria 5.4.2](https://github.com/ceskaexpedice/kramerius/releases/tag/5.4.2)
