### ISSUE TITLE
Problém se spouštěním procesů

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#238]
V poslední době se stává, že se přestanou spouštět procesy. Zůstanou ve stavu Planned a to se změní až po otočení kontejneru s Krameriem. Teď tam bylo pár procesů naplánovaných, všechny se po otočení spustily, ale následně spadly.

**Comment by LenkaKravecova** [comment]
Už s tím problémy byly, viz https://github.com/moravianlibrary/kramerius/issues/135 a můj poslední koment. Nepodařilo se nám přijít na to, proč se procesy nespouštěly (stav Planned), ale pak to přestalo. Teď je to tu po roce zas, takže nějaké nápady?

**Comment by leiblix** [comment]
Můj odhad je, že trvá moc dlouho dotaz do tabulky procesů (mělo by to být vidět v logách databáze, dlouhé dotazy se logují). 

Mělo by stačit nad tou tabulkou pustit vaacum (Maroš s tím už má nějakou zkušenost).

**Comment by LenkaKravecova** [comment]
@MartinRumanek Díky, vyzkoušíme.

**Comment by LenkaKravecova** [comment]
Pročištěna databáze. Uvidíme, jestli pomohlo.

**Comment by LenkaKravecova** [comment]
Pomohlo.

**Comment by MarosGrm** [comment]
Chyba sa po dlhej dobe začala opäť vyskytovať.
