### ISSUE TITLE
Statistiky Krameria - prázdný csv soubor

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#239]
Statistiky nevrací žádné výsledky, např. u monografií za období 1.1.-31.12.2017 se vygeneruje jen prázdný csv soubor. Myslím, že se jedná o drobné nastavení, které se musí někde upravit, ale dávám to sem pro informaci na příští rok. Teď prosím o zprovoznění. Díky.

**Comment by MarosGrm** [comment]
Primárne problém s timeoutom. V budúcnosti, pri generovaní štatistík stačí v konfiguračnom súbore tomcatu  (search.xml) odmazať removeAbandonedTimeout a removeAbandoned. Po úspešnom vygenerovaní štatistík (môže trvať desiatky minút), je nutné to tam opäť pridať.
