### ISSUE TITLE
Zvukove streamy nefunguji.

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#24]
Napr. http://kramerius.mzk.cz/search/api/v5.0/item/uuid:03c9b89b-868b-4b71-b76e-11098965a732/streams/
Ma mit MP3, WAV a OGG, ale vsechny streamy vraci internal error, napr.
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:03c9b89b-868b-4b71-b76e-11098965a732/streams/MP3

Je to lokalni chyba v MZK jeko minule s MP3 nebo se neco zaneslo do Krameria a je to vsude?

**Comment by leiblix** [comment]
Zaslal jsem do upstreamu opravu https://github.com/ceskaexpedice/kramerius/pull/258

Večer Krameria s touto opravou nasadíme na kramerius.mzk.cz

**Comment by honza-rychtar** [comment]
Jak to teda vypada s timto? Zvukove streamy porad nefunguji.

**Comment by LenkaKravecova** [comment]
Tak už by měly fungovat.
