### ISSUE TITLE
Nasadit novou funkci statistik

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#240]
Do statistik bylo přidána funkce vygenerovat roční report dle https://github.com/ceskaexpedice/kramerius/issues/515. Prosím nasadit, potřebuju to zkoušet na ostrých datech..

**Comment by MarosGrm** [comment]
Nasadené spolu s novou verziou Krameria.

**Comment by LenkaKravecova** [comment]
Vrácena stará verze kvůli nefunkčnosti vyhledávání na digitalniknihovna.cz. Se statistikami asi nesouvisí, ale nová funkce tam tedy momentálně není. Pak bude potřeba znovu nasadit.

**Comment by LenkaKravecova** [comment]
Nevím, co s tímto. Asi tam teď tu novou funkci nenasadíme, když modul Statistiky víceméně nemůžeme používat, že? Resp. ta nová funkce v Krameriu momentálně už je, ale nedostaneme se k ní, co?

**Comment by MarosGrm** [comment]
Nová funkcionalita funguje, pozostáva problém so spúštaním generovania: https://github.com/moravianlibrary/kramerius/issues/289
Toto issue sa môže zatvoriť.

**Comment by MarosGrm** [comment]
Generovanie štatistík spôsobuje preťaženie databázy. Nepoužívať!

**Comment by zabak** [comment]
Nebylo by teda lepší ty údaje potřebné pro statistiky ukládat třeba do elasticu?

**Comment by jkremlacek** [comment]
Vzhledem k objemu dat za rok by tam podle mě nebyl ten rozdíl tak závratný. Co se týče přetížení databáze, tak tam mě napadají varianty (seřazeno podle náročnosti/praktičnosti):

- přidat dostupnou výpočetní sílu serveru `dk-db`, ten stroj má momentálně pouze 2 CPU jádra a 2 GB RAM, což na každodenní aktivitu stačí, ale na vyjímečné situace už ne
- mít separátně databázi pro statistiky, u které by přetížení neohrožovalo hlavní činnost ostatních systémů
- omezit výkon konkrétních dotazů (postgres to ale neumožňuje, takže by vyžadovalo použití [neoficiálních pluginů](https://www.bignerdranch.com/blog/lowering-the-priority-of-a-postgresql-query/) / "hacků" anebo placené enterprise db [[1](https://dba.stackexchange.com/questions/188577/can-you-slow-down-queries-for-a-specific-user-in-a-postgres-database)])

**Comment by zabak** [comment]
Mimochodem, nepomohlo by vytvořit v té databázi nějaké klíče, indexy? Nebo něco denormalizovat? Samostatná databáze pro statistiky by to řešila, ale jestli se nepletu, tak se kvůli dnnt stejně uvažovalo o elk stacku..?

Petr

**Comment by fstepanovsky** [comment]
@zabak 

> Samostatná databáze pro statistiky by to řešila, ale jestli se nepletu, tak se kvůli dnnt stejně uvažovalo o elk stacku..?

Koukal jsem se do zápisu z 9.1.2019 a logování bude prováděno do souboru (dnnt) o Elasticu jsme uvažovali my, protože to jde jednoduše integrovat do naší infrastruktury.

**Comment by jkremlacek** [comment]
@zabak co se týče uspořádání dat, tak klíče použité jsou - čímž pádem nad ním postgres i vytváří index. 

Denormalizace provedená taky je (tabulky  `statistics_access_log` a `statistic_access_log_detail` `statistic_access_log_detail_authors`, ve kterých jsou záznamy identifikovány pomocí `record_ID`).

Další řídké indexy by zpomalily vkládání záznamů, což je z hlediska výkonu Krameria kritičtější než generování statistik jednou za rok.

**Comment by zabak** [comment]
V tom případě natvrdo přejít na ukládání do souboru podobně jako dnnt? Pro to jedno roční využití by stačilo napsat krátký skript, který by ten soubor prošel a to jedno (nebo několik) čísel vypočítal.

Petr

**Comment by jkremlacek** [comment]
Je to hodně drsný řešení, osobně bych byl radši pro druhou instanci databáze, která bude pouze pro statistiky, ale dá se to samozřejmě řešit i souborem. 

Pokud by mělo jít o obecné řešení pro všechny uživatele, pak jsou samozřejmě ty priority jinde. Pro instituce, které nemají docker a spuštění další databáze pro ně není otázkou 2 minut, by už varianta se statistikami v souboru byla lepší.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
