### ISSUE TITLE
Exporty polí mods:text a mods:note z Lidových novin

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#243]
Bude potřeba udělat 2 seznamy z obou Lidových novin uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6 a uuid:bdc06f50-6ec9-11dd-85fc-000d606f5dc6 

1. pro ročníky 2 údaje - mods:date (číslo ročníku), mods:text (poznámka k ročníku)
2. pro výtisky 3 údaje - mods:date (číslo výtisku), mods:number (datum), mods:note (poznámka k výtisku)

**Comment by kazooo** [comment]
[uuid:bdc06f50-6ec9-11dd-85fc-000d606f5dc6_items.txt](https://github.com/moravianlibrary/kramerius/files/1664235/uuid.bdc06f50-6ec9-11dd-85fc-000d606f5dc6_items.txt)
[uuid:bdc06f50-6ec9-11dd-85fc-000d606f5dc6_volumes.txt](https://github.com/moravianlibrary/kramerius/files/1664236/uuid.bdc06f50-6ec9-11dd-85fc-000d606f5dc6_volumes.txt)
[uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_items.txt](https://github.com/moravianlibrary/kramerius/files/1664237/uuid.bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_items.txt)
[uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_volumes.txt](https://github.com/moravianlibrary/kramerius/files/1664238/uuid.bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_volumes.txt)

**Comment by LenkaKravecova** [comment]
Díky, ale můžeš ty údaje dát do sloupců bez prázdných řádků? Zkrátka aby jedno číslo nebo ročník bylo na jednom řádku. A ještě dodatečně poprosím, aby v 1. sloupci byl celý odkaz na ročník/číslo (http://www.digitalniknihovna.cz/mzk/periodical/uuid:b231a40c-435d-11dd-b505-00145e5790ea).

**Comment by zabak** [comment]
Stačí upravit vždy ten delší dokument kde jsou jednotlivá čísla. Ten dokument s ročníky je OK tak jak je

**Comment by kazooo** [comment]
Omlouvam se za zpozdeni

[uuid.bdc06f50-6ec9-11dd-85fc-000d606f5dc6_items.txt](https://github.com/moravianlibrary/kramerius/files/1673648/uuid.bdc06f50-6ec9-11dd-85fc-000d606f5dc6_items.txt)
[uuid.bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_items.txt](https://github.com/moravianlibrary/kramerius/files/1673649/uuid.bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_items.txt)
 hodi to?

**Comment by LenkaKravecova** [comment]
Asi jsme se nepochopili. Jde o to, aby údaje k jednomu issue/číslu/výtisku byly na 1 řádku a byly oddělené třeba středníkem. V excelu si to pak necháme oddělit do sloupců, ale je potřeba, aby to bylo na jednom řádku.

**Comment by kazooo** [comment]
Takze takto ano?
```
http://www.digitalniknihovna.cz/mzk/view/uuid:b8286f42-435d-11dd-b505-00145e5790ea;2.1.1894;1;nekvalitní předloha;
http://www.digitalniknihovna.cz/mzk/view/uuid:b8289653-435d-11dd-b505-00145e5790ea;2.1.1894;1;nekvalitní předloha;
```

**Comment by zabak** [comment]
ano, dík

**Comment by kazooo** [comment]
[uuid_bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_items.txt](https://github.com/moravianlibrary/kramerius/files/1684500/uuid_bdc405b0-e5f9-11dc-bfb2-000d606f5dc6_items.txt)
[uuid_bdc06f50-6ec9-11dd-85fc-000d606f5dc6_items.txt](https://github.com/moravianlibrary/kramerius/files/1684501/uuid_bdc06f50-6ec9-11dd-85fc-000d606f5dc6_items.txt)

**Comment by zabak** [comment]
OK, takhle to stačí. Kdyby se to dělalo příště pro jiné noviny, tak pro volumes by bylo lepší udělat to taky jeden ročník na jeden řádek, místo uuid dát link na digitální knihovnu a text samotný nezalamovat ale nechat ho jako jeden údaj v uvozovkách.
U items dávat text taky do uvozovek.
