### ISSUE TITLE
Migrace Solru

### ISSUE THREAD

**Issue by kazooo** [moravianlibrary/kramerius#246]
V současné době řešíme migrace indexu Solru na nový s novém schématem. Nasadit přímo nové schéma se nepodařilo, vzníkají konflikty mezi schématem a zaindexovanými daty. V tomto připadě řešením mohla by byt optimalizace indexu, která by ty konflikty odstranila, ale bude trvat přiliš dlouho a během toho Solr bude pomalý, skoro nebude fungovat vůbec.
Proto bylo řešeno vytvořit nový index a všechny data ze starého Solru překopirovat na nový pomocí procesu migrace, a následně spustit Solr na novém indexu.
Po migraci Solru bude nasazen nový Kramerius, který už je kompatibilní s novým schématem. Před migraci to nejde, protože Kramerius se bude snažit indexovat poli, které ješte nejsou ve starém schématu a to bude nám způsobovat různé chyby.
Migrace bude běžet přibližně 2-3 týdnů, a velikost výsledného indexu bude přibližně 1,6-1,8 TB, což je skoro 4 krát větší něž původní index (kvůli lematizovanému text, kterého přibude moc).

**Comment by LenkaKravecova** [comment]
S tímto nejspíš souvisí issues, kde je potřebná nějaká reindexace/aktualizace solru:
#229 
#186 
#190 
#187 
#83 

@xermak00, můžeš prosím projít tato issues a pohlídat je v souvislosti s migrací solru? V případě potřeby komentuj zde nebo u jednotlivých issue. Díky.

**Comment by kazooo** [comment]
#186  reindexace do toho patří, ale nevidím že problem byl řešen, i v novém Solru je dost dokumentů, kde se tato chyba objevuje
```
"PID":"uuid:3dc3bc10-cd5c-11e3-85ae-001018b5eb5c",
"datum_begin":0,
"datum_end":0,
"datum_str":"[1996]"
```
#187 dokažu ověřit až Kramerius bude využívat nový Solr, zatím komunikuje se starým.
Ostatní issue potřebují reindexace, takže jsou v souvislosti s migrací.

**Comment by LenkaKravecova** [comment]
Jaký je stav migrace? Prosím, napsat stručně sem. Díky.

**Comment by kazooo** [comment]
Migrace ještě stále běží, zbývá cca 4,5 milionů a bude hotovo.

**Comment by kazooo** [comment]
S časem Solr se zpomaluje, proto trvá už dost dlouho. Příčinou je Deep paging.
Dotaz na Solr požívá offset  **rows=x&start=y** aby načíst počet dokumentů **rows** od pozice **start**.
Když potřebuje načíst 500 dokumentů od např. 47.552.142 dokumentu v indexu, tak Solr akumuluje informace ne jen o tých 500 dokumentech, ale i o předchozích 47.552.142 dokumentech.
Pro budoucnost bude potřeba opravit na strankování pomocí kurzoru.

Více info: [dokumentace](https://archive.apache.org/dist/lucene/solr/ref-guide/apache-solr-ref-guide-6.3.pdf) str. 363, a [článek](https://solr.pl/en/2011/07/18/deep-paging-problem/)

**Comment by kazooo** [comment]
Migrace nakonec doběhla, nový index zabírá kolem 960 Gb. Před tím než připojím Kramerius na nový index, počkám až David zapné snapshoty (abychom v případě problemů neztratili celý index) a zkusím otestovat komunikace s Krameriem u sebe. Ještě bude potřeba zmigrovat ty dokumenty, které přibyly do starého indexu v průběhu migraci a můžeme ten index pouzívat. Issue zatim nechám otevřené až udělám zbývající věci.

**Comment by kazooo** [comment]
Solr s novým indexem komunikuje s Krameriem velmi pomalu. Dotazy s použitím lematizovaných textu trvají strašně dlouho, a ve většině případů končí s timeoutem. Solr zpracuje dotaz ale při timeoutu už nepošle odpoved, uloží do cache a při opakovaném dotazu rychle vratí výsledek. Bylo zkoušeno přímé dotazování a dotazování přes Kramerius a to pomoci dotazů různé složitostí. Testy ukazaly, že problem je na stráně Solra a pravděpodobně kvůli velikosti indexu, jeden nejjednoduchý dotaz trvá minimálně 10 sek. Byly take zkoušeny různé konfigurace cache, ale moc nezlepšily rychlost, dotazy trvají minimálně 7-8 sek.
Použití Solr 7 s Krameriem 5.4.1 nejde, potřeba opravit kod Krameria na mnoha místech.
Pro účely testování vyhledávání podle geografických názvů a souřadnic byl vytvořen nový index, který obsahuje jenom mapy.

**EDIT**: přikládám zadokumentovaný výsledek z testování
[testovani_rychlosti_solra.pdf](https://github.com/moravianlibrary/kramerius/files/2053586/testovani_rychlosti_solra.pdf)

**Comment by kazooo** [comment]
Nuní produkční Kramerius beží na Solru 7.5.0 s lemmatizovanými textami. V konečné verzi ze schematu byly odstraněny pole **text_lemmatized_nostopwords** a **text_ocr_lemmatized_nostopwords** (stop slova budou řešena na úrovni Krameria), uložení lemmatizovaných pole bylo vypnuto (Solr indexuje lemm. texty, ale nevrací je). Velikost výsledného indexu je ~420 GB, index byl zoptimalizován a sloučen do jednoho segmentu, což umožnilo rychlé vyhledávání.
