### ISSUE TITLE
Přidání nového typu policy?

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#247]
Momentálně je možné nastavit u dokumentu jeden ze dvou stavů - public nebo private. Jak náročné by bylo přidat další stav, který bude mít trochu jiné vlastnosti/parametry než ty dva stávající? Kde se typ policy vůbec definuje?

**Comment by kazooo** [comment]
Policy se definuje ve FOXML dokumentů, přidaní dalšího stavu, podle mě, by nemělo byt náročné, ale je třeba upravit Kramerius tak, aby reagoval na ten nový stav jak checeme. А takový Kramerius by měl byt u všech knihoven, aby nevznikaly konflikty, např. OAI provider přeposíla policy a přijímající strana musí to vhodně zpracovat #218

**Comment by honza-rychtar** [comment]
@LenkaDamborska jen dotaz, jaky treti stav chcete pridat? Co by vyjadroval?

**Comment by zabak** [comment]
Autorsky chráněné, ale přístupné díky smlouvě s autorskými ochrannými svazy.

**Comment by zabak** [comment]
tj. budou tam jiné podmínky zpřístupnění než u zcela volných dokumentů, ale jiné než u těch, na které se taková smlouva nebude vztahovat.

**Comment by LenkaKravecova** [comment]
@hlavacekrene dej sem, prosím, co jsi zjistil, ať to nevyšumí

**Comment by hlavacekrene** [comment]
tady jsem se pokusil neco trochu rozrebrat.
https://docs.google.com/document/d/1caEIRYRN4mX1i7IJwmt09c0kbsYGaFOwgPHTNug6QzE/edit?usp=sharing

**Comment by leiblix** [comment]
> jiné podmínky zpřístupnění?
Co to přesně znamená? Projednával se konkrétní usecase na nějaké schůzce?

Patří to vůbec do policy, nejedná se o jen nějakou licenci (s nějakými atributy). Současné dva stavy jsou samopopisné, bude třetí taky takový? Kde bude definované jeho chování? Natvrdo v kódu?

**Comment by zabak** [comment]
Cílem je zpřístupnit dokumenty splňující určité podmínky specifickým způsobem. Nejsou volné, ale nejsou ani omezené ani pouze na počítače v knihovně. Bude se to ale týkat poloviny až tří čtvrtin neveřejných dokumentů. Ty budou moci být zpřístupňovány za dodržení specifických podmínek  v knihovnách a registrovaní uživatelé knihoven budou mít přístup i z vlastních zařízení mimo knihovny. Jako problém vidím potřebu hromadné změny údajů u významné části dokumentů v Krameriu, což by mohlo trvat příliš dlouho. Proto jako varianta by mohla být využita proxy, která by zajišťovala zpřístupnění na základě dotazů do seznamu povolených uuid, který by byl mimo Fedoru.

**Comment by jkremlacek** [comment]
Bude řešeno pomocí DNNT.
