### ISSUE TITLE
Chyba v datech?

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#249]
Ahoj, viz. https://github.com/ceskaexpedice/kramerius-web-client/issues/61 - vzhledem k tomu, že jsem vyhledávaný termín bral z Lidovek, tak bych očekával, že ho v lidovkách i najdu. Můžete to prosím zkontrolovat?

**Comment by MarosGrm** [comment]
OCR je správne zaindexované a je aj správne vo Fedore. Ide o nejakú náhodnú chybu pretože pri hľadaní "pořádný akademik" čo som tiež vybral z tej istej strany to našlo v poriadku a stranu šlo aj normálne otvoriť ale zase mi to nenašlo tú konkrétnu stranu v novom klientovy.

**Comment by LenkaKravecova** [comment]
Je to tak. Když hledám "pořádný akademik" v roce 1896, na digitalniknihovna.cz se to najde, v novém klientovi se to nenajde. Co se týče "novézvolení poslanci", toto spojení opravdu nic nenajde (nový klient) nebo se nezobrazí stránka (digitalniknihovna.cz). Ale když dám jen "novézvolení", tak už je to v obou klientech ok. Přitom, jak píše Maroš, OCR je v pořádku. Hmm.. Nebude to kombinovaný problém nový klient, náš index?

**Comment by zabak** [comment]
Vyřešeno, zavírám
