### ISSUE TITLE
Monografie na kontrolu

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#250]
Potřebovala bych u těchto uuid zjistit, zda patří k úrovni monograph nebo page. Pokud tam budou nějaké page, najít a nahradit kořenem. Pak vše zveřejnit. Děkuji. 
[monographs_setpublic.txt](https://github.com/moravianlibrary/kramerius/files/1841385/monographs_setpublic.txt)

**Comment by LenkaKravecova** [comment]
Tady další stejný případ. Zkontrolovat, jaké úrovně uuid jsou, a pak zveřejnit na úrovni monografie. Díky.

[kontrola_monografie_setpublic.txt](https://github.com/moravianlibrary/kramerius/files/1841707/kontrola_monografie_setpublic.txt)

**Comment by LenkaKravecova** [comment]
Jo a vždy potřebuju vrátit seznam, kde budou ta uuid pro page nahrazena uuid pro monograph. Prostě zkrátka potřebuju seznam uuid na úrovni titulu.

Ještě tu mám další monografie, které je potřeba zkontrolovat na úrovni page/titulu, vrátit mi seznam pouze uuid titulů, ale nezveřejňovat!! 
[kontrola_monografie_nezverejnovat.txt](https://github.com/moravianlibrary/kramerius/files/1841742/kontrola_monografie_nezverejnovat.txt)

**Comment by LenkaKravecova** [comment]
Další :/ 
Tady už je vše zveřejněno, ale některá uuid patří ke stranám, takže byly zveřejněny jen strany. Najít uuid pro page, najít k tomu titul, vrátit mi opravený seznam a dané tituly zveřejnit:
[kontrola_monografie_setpublic2.txt](https://github.com/moravianlibrary/kramerius/files/1841790/kontrola_monografie_setpublic2.txt)

Tak a tady je další dlouhý seznam uuid, které taky zkontrolovat na úrovni page/monograph, nahradit, vrátit mi opravený seznam, ale nezveřejňovat! 
[kontrola_monografie_nezverejnovat2.txt](https://github.com/moravianlibrary/kramerius/files/1841812/kontrola_monografie_nezverejnovat2.txt)

**Comment by MarosGrm** [comment]
kontrola_monografie_setpublic.txt a kontrola_monografie_nezverejnovat.txt sú totožné.
objekt uuid:2df345f0-67bb-11e3-856005056827e521 neexistuje vo fedore.
zatiaľ som nič z toho nezverejňoval.
[blok1.txt](https://github.com/moravianlibrary/kramerius/files/1841869/blok1.txt)
[blok2-3.txt](https://github.com/moravianlibrary/kramerius/files/1841871/blok2-3.txt)
[blok4.txt](https://github.com/moravianlibrary/kramerius/files/1841872/blok4.txt)
[blok5.txt](https://github.com/moravianlibrary/kramerius/files/1841874/blok5.txt)

**Comment by LenkaKravecova** [comment]
Prosím, můžeš mi překontrolovat tato uuid zase na té úrovni page/monograph? Potřebuju uuid nejvyšší úrovně (tj. monografie), může se stát, že tu budou uuid stránky, což je špatně. Díky. Zatím nezveřejňovat.
[2_praxe_listopad2016-neverejne-kontrola_urovne.txt](https://github.com/moravianlibrary/kramerius/files/2249340/2_praxe_listopad2016-neverejne-kontrola_urovne.txt)

**Comment by MarosGrm** [comment]
Zoznam s objektmi najvyššej úrovne:
[uuid.txt](https://github.com/moravianlibrary/kramerius/files/2261771/uuid.txt)

Objekt [uuid:34791800-8b4e-11e6-bf08-001018b5eb5] neexistuje
