### ISSUE TITLE
Chyba importu METS baliku

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#251]
Import vyletí na `java.lang.OutOfMemoryError: Java heap space` zkusil jsem zvednout tomcatu paměť na 10GB z defaultu a nepomohlo.

Kompletní log je zde: https://gist.github.com/jkremlacek/116b342c5a7b8ddd1094e967893a1399

Chybující soubor je na cestě `convert/ProArcPSP/mzk-0000yc`

**Comment by jkremlacek** [comment]
Importní procesy nepřebírají nastavení rodičovského procesu, bude potřeba překompilovat kramerius.infra s upravenými hodnotami v https://github.com/ceskaexpedice/kramerius/blob/1ff2b58004c2c8381d072942a96922382c92d71c/common/src/main/java/cz/incad/kramerius/processes/res/lp.st#L295

**Comment by jkremlacek** [comment]
6GB heap limit z původních 2GB nestačilo. Řešeno v rámci https://github.com/ceskaexpedice/kramerius/issues/596 . 16GB heap limit už stačí na JP2 o velikosti 467MB.

**Comment by pavel-stastny** [comment]
Dobry den, 

jenom par poznamek: 

> Import vyletí na java.lang.OutOfMemoryError: Java heap space zkusil jsem zvednout tomcatu paměť na > 10GB z defaultu a nepomohlo.

Vsechno, co je v krameriovi definovane jako proces (to co se objevi po spusteni ve sprave administratorskych procesu) je implementovano jako samostatny jvm proces.  Neni to tedy thread a   nastaveni tomcatu na to nema zadny vliv. 

> Importní procesy nepřebírají nastavení rodičovského procesu, bude potřeba překompilovat 
> kramerius.infra s upravenými hodnotami v
>https://github.com/ceskaexpedice/kramerius/blob/1ff2b58004c2c8381d072942a96922382c92d71c/co
> mmon/src/main/java/cz/incad/kramerius/processes/res/lp.st#L295

Neprebira, ani nevim, jak by to slo udelat.  (Maximalne ze bych si nechal vypsat spousteci parametry procesu a pak to znovu parsoval).  Nicmene zadna prekompilace neni potreba. K tomu ucelu je tam `lp.xml`, kde ten proces staci predefinovat a kramerius bude primarne brat definici odtud a az pokud ji tam nenajde, bere tu, ktera je v lp.st.   

Neco o tom je i na wiki [1](https://github.com/ceskaexpedice/kramerius/wiki/Processes),[2](https://github.com/ceskaexpedice/kramerius/wiki/MenuAdministrace#definice-procesu)

> 6GB heap limit z původních 2GB nestačilo. Řešeno v rámci ceskaexpedice#596 . 16GB heap limit už
>  stačí na JP2 o velikosti 467MB.

Asi by slo debugovat a zjisit, jake jsou skutecne pametove pozadavky toho souboru pri natazeni do pameti ale nema to zadny smysl. ( Je tam komprese, vyuziva se knihova ImageIO, tezko rict, jestli natahuje jenom jednu urven z te pyramidy nebo vsechny ale i kdyby jenom jednu, musi se natahnout v nezkomprimovnae forme  - klasicka bitmapa a pak podle rozliseni na kazdy pixel pripadnou 3 bajty. S  tim se pak manipuluje pri zmenosvani.  Dalsi naklady na rezii vzniknou pri vytvareni FOXML, kdy tech necelych 500 MB se zakoduje do base64 a ulozi do FOXML a nasledne naparsuje do DOM modelu  - pri ingestu). 

A ted proc si myslim, ze to nema smysl:  Predpokladam, ze davate ty JP2 soubory primo do Fedory. 
Pokud ano, tak to nedejete  :-) .   Fedora ani Kramerius si s tim neporadi.   Jediny, kdo umi podavat bud dlazdice nebo zmensene obrazky z toho pyramidoveho formatu je IIP server.

**Comment by jkremlacek** [comment]
@pavel-stastny Díky za poznámky. 

Chyba byla původně detekována na K5 s IIP, kde padla na procesu mets import během načítání do paměti JVM.

Před ohlášením issue jsme balík raději testovali i na K6, kdyby náhodou šlo o chybu v K6 již opravenou (v rámci testování nemá IIP), proto následně došlo k ingestu JP2 do Fedory a ne k nahrání na IIP. V rámci produkce K6 bude mít IIP.

**Comment by leiblix** [comment]
> Import vyletí na java.lang.OutOfMemoryError: Java heap space zkusil jsem zvednout tomcatu paměť na 10GB z defaultu a nepomohlo.

To nepomohlo, protože procesy se spouští ve vlastní JVM - mimo Tomcat.  (přes ProcessBuilder).Musíš to rekonfigurovat v lp.xml, jak už bylo zmíněno. Btw. do toho parametru se dá přidat i remotedebug  a zjistit co se děje.

**Comment by MarosGrm** [comment]
V lp.xml sme pamäť navyšovali tiež a nepomohlo to.

**Comment by pavel-stastny** [comment]
to je divny... Kdyz si vypisete vsechny procesy (klasicky pres `ps`), ten navyseny parametr pameti  tam vidite?

**Comment by leiblix** [comment]
Neprojevilo se to? Nebo to nestačilo?

Běžně jsme v lp.xml měnili JAVA_OPTS a přidávali parametry na remote debug....

**Comment by jkremlacek** [comment]
Vzniklo tu nedorozumění, takže uvádím vše na pravou míru:

> To nepomohlo, protože procesy se spouští ve vlastní JVM - mimo Tomcat. (přes ProcessBuilder).Musíš to rekonfigurovat v lp.xml, jak už bylo zmíněno. Btw. do toho parametru se dá přidat i remotedebug a zjistit co se děje.

už vyřešeno v rámci ceskaexpedice#596

> V lp.xml sme pamäť navyšovali tiež a nepomohlo to.

myšleno na 6 a 8GB, dále už řešil @zafan, kde pomohlo 16GB

> to je divny... Kdyz si vypisete vsechny procesy (klasicky pres ps), ten navyseny parametr pameti tam vidite?

> Neprojevilo se to? Nebo to nestačilo?
Běžně jsme v lp.xml měnili JAVA_OPTS a přidávali parametry na remote debug....

viz předchozí vysvětlení

**Comment by kazooo** [comment]
Velikost hromady na kramerius.infra je nastavena na 16GB pro procesy importu a reindexace.
