### ISSUE TITLE
Generování PDF trvá dlouho

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#252]
Generování PDF trvá velmi dlouho. Souvisí se zátěží, kterou s největší pravděpodobností způsobuje migrace SOLRu. Je potřeba s tím něco udělat. Generování PDF je základní služba, která musí fungovat.
Nějaký nápad?

**Comment by jkremlacek** [comment]
Asi by stálo za to zkusit vygenerovat PDF skrz kramerius.infra, abychom s jistotou mohli říct, že na nízkou rychlost nemá vliv ostrý kramerius. Je totiž klidně možné, že celková "pomalost" toho procesu je důsledek více chyb a ne pouze zátěž na dk-back.  

Další varianta by byla pauznout migraci solru a ostrý solr otočit.

**Comment by LenkaKravecova** [comment]
Na kramerius.infra to jde bez problémů.

**Comment by LenkaKravecova** [comment]
Už to jde i na "normálním" krameriovi. @jkremlacek, @kenji1322 vypnuli jste dočasně generování 2vrstvého PDF? Prosím o komentář, jak to vypadá.

**Comment by MarosGrm** [comment]
Áno, dočasne je vypnuté generovanie dvojvsrtvového PDF, kým neprídeme na to, prečo to tak spomaľovalo.

**Comment by LenkaKravecova** [comment]
Teď čekáme, až doběhne migrace solru. Pak by se na to mohl @kenji1322 podívat.

**Comment by MarosGrm** [comment]
Kramerius nedokázal prečítať konfiguračnú premennú z configuration.properties a natom sa to cyklilo, problém už je vyriešený a generovanie dvojvsrtvového PDF je opäť zapnuté.
