### ISSUE TITLE
Pravidelné požadavky na neexistující virtuální sbírky

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#253]
V 5-ti minutových intervalech (vč. noci) chodí dotazy do fedory na virtuální sbírky:

vc:756500c4-5f16-4b23-878f-2ce378a18b64
vc:7252befa-0e8c-4875-af64-882b6ed328ef
vc:40995932-98ff-41ca-a74f-c0637fa99f2f
vc:17909b1e-5acf-47f1-bb4d-d5907ca71c44

Tři existují v KNAV-u:

http://www.digitalniknihovna.cz/knav/search/?collections=vc:756500c4-5f16-4b23-878f-2ce378a18b64
poslední publikace Estetika je i v naší Fedoře - uuid:05559566-d56b-11e1-a706-005056a60003

http://www.digitalniknihovna.cz/knav/search/?collections=vc:7252befa-0e8c-4875-af64-882b6ed328ef
žádný z hlavních objektů v naší Fedoře není (připojené objekty nižší úrovně ale mohou být)

http://www.digitalniknihovna.cz/knav/search/?collections=vc:40995932-98ff-41ca-a74f-c0637fa99f2f
publikace Soudobé dějiny je i v naší Fedoře - uuid:31bef440-539a-11e1-b712-005056a60003

Pravidelné intervaly dotazů znamenají, že je původcem nějaký automatizovaný proces - bude potřeba jej identifikovat a opravit/zastavit. Pokud neběží u nás, tak by chtělo zjistit původce a chybu zahlásit.

Pozn.: 
chyba má podobu:
```
ERROR 2018-04-16 07:52:00.398 [http-nio-8080-exec-37454] (FedoraAccessServlet) Object or datastream not found for request: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:756500c4-5f16-4b23-878f-2ce378a18b64/DC (actionLabel=Access)
```

pokud člověk přistupuje na neexistující sbírku napřímo do Fedory, tak dostává jinou (ač podobnou hlášku):
```
WARN 2018-04-16 07:54:39.634 [http-nio-8080-exec-37468] (BaseRestResource) Resource not found: no path in db registry for [vc:40995932-98ff-41ca-a74f-c0637fa99f2f]; unable to fulfill REST API request
```

pokud ovšem zkusí sbírku zadat do Krameria, tak už vyletí stejná chyba (s rozdílem, že zároveň vyletí i chyba chybějícího RELS-EXT datastreamu):
```
ERROR 2018-04-16 07:58:03.970 [http-nio-8080-exec-37430] (FedoraAccessServlet) Object or datastream not found for request: http://fedora.dk-back.infra.mzk.cz/fedora/get/vc:40995932-98ff-41ca-a74f-c0637fa99f2f/DC (actionLabel=Access)
```

na sbírky je tedy přistupováno skrze Servlet a ne skrz REST API

**Comment by jkremlacek** [comment]
@honza-rychtar Dotaz, neběží v rámci digitální knihovny nějaký pravidelný proces, který pracuje s virtuálními sbírkami?

**Comment by honza-rychtar** [comment]
Ne. Pravidelne se ptam jen na /search/api/v5.0/info kvuli sledovani vypadku a pak jeste par dotazu pro Registr Krameriu - ale to se pousti jen dvakrat za den.

**Comment by zabak** [comment]
Dá se vysledovat z jaké IP adresy ty dotazy chodí?

**Comment by jkremlacek** [comment]
Už je na cestě oprava, @xermak00 zapnul monitorování těch požadavků a zjistil, že jdou z krameriusndktest.mzk.cz . 

Ten server má oddělenou databázi (ostatní krameriové používají dk-db), takže ze solru sice byly ty vazby na neexistující sbírky smazané už dřív, ale v té databázi zůstaly, takže @kenji1322 je musí odmazat, protože k tomu serveru má přístup jen on.

**Comment by MarosGrm** [comment]
Čistý build Krameria (krameriusndktest) a odstránenie nepotrebných líšt pomohlo, takže v logoch sa už hláška s neexistujúcimi zbierkami neobjavuje.

**Comment by LenkaKravecova** [comment]
:+1:
