### ISSUE TITLE
Chybné odkazy do imageserveru ve fedoře

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#254]
Stránky publikací:

uuid:c63594b0-4432-11e2-9b88-005056827e51
uuid:5c2c78b0-4435-11e2-b246-005056827e52
uuid:821a3fd0-4435-11e2-b246-005056827e52
uuid:4deb2df0-4435-11e2-b246-005056827e52
uuid:6db39fa0-4435-11e2-b246-005056827e52
uuid:91851670-4435-11e2-b246-005056827e52
uuid:3b1e1980-4435-11e2-9b88-005056827e51
uuid:3e5109f0-4435-11e2-9b88-005056827e51
uuid:cfc3f3d0-4434-11e2-9b88-005056827e51
uuid:43a07fa0-8dad-11e7-9950-005056827e52

mají chybné odkazy do imageserveru, bude je potřeba u všech stran opravit.

Edit: Spustil jsem kontrolu všech objektů ve Fedoře, po dokončení (cca 23.4.2018) doplním kompletní seznam.

Edit2: Proces se citelně zpomalil, hrubý odhad dokončení je 1.5.2018.

Celkový počet objektů: 49 117 757
dokončeno k 25.4.2018: 28 010 602
dokončeno k 26.4.2018: 31 336 828

Edit3: Výpadek proudu 29.4. shodil kontrolní proces. Upravil jsem ho, aby ihned zaznamenával každou nalezenou chybu - některé nadřazené objekty budou ve výsledném seznamu vícekrát, ale proces díky tomu bude schopný navázat v případě chyby.

spuštěno 2.5.2018
dokončeno k 3.5.2018: 14 664 008
_Výpadek kvůli problémům s firewallem (4.5.2018 - 9.5.2018)_
dokončeno k 9.5.2018: 16 672 596
dokončeno k 10.5.2018: 24 083 993

**Comment by jkremlacek** [comment]
Kontrola byla dokončena. Přiložené soubory jsou ve formátu .csv, koncovku .txt mají jen kvůli omezením se strany githubu.

91499 stránek má alespoň jeden obrazový datastream interní namísto odkazu do imageserveru (součástí jsou i dokumenty, kterým chybí tiles-url)

~~[internal.txt](https://github.com/moravianlibrary/kramerius/files/2012682/internal.txt)~~ (podrobnější rozdělení souboru níže)
_formát: lineNum, UUID strany_
___
16487 stránek (původem od nás + muzeum brněnska + další) má rozbité odkazy na obrázky

~~[brokenuuids.txt](https://github.com/moravianlibrary/kramerius/files/2012475/brokenuuids.txt)~~ (verze souboru bez cesty k DS)
~~[brokenuuids.txt](https://github.com/moravianlibrary/kramerius/files/2044981/paths_without_info.txt)~~ (podrobnější rozdělení souboru níže)

_formát: lineNum, UUID strany, cesta full datastreamu_
___
12948 stránek (původem z NDK) má rozbité odkazy na obrázky

[parents.txt](https://github.com/moravianlibrary/kramerius/files/2012458/parents.txt)
_formát: lineNum, datastream link (obsahuje uuid rodiče - musí být zkontrolovány všechny jeho stránky)_

___

Aktuální stav zpracování:

```
+-+internal.txt
| |
| +-+klokan_link.log (sirotci s duplicitou, po ujištění smazat)
| | 
| +-+internal_filtered.log
|   |
|   +-+internal_filtered_imageserver.txt (thumbnail ve fedoře, opraveno, ?preview?)
|   |
|   +-+internal_filtered_img_full (sirotci s neověřitelnou duplicitou)
|
+-+-brokenuuids.txt
| |
| +-+brokenUUIDS_tif_big.txt
| | |
| | +-+tif_big_missing.txt (sirotci, ke kterým nejde z risearche najít rodič)
| | |
| | +-+reimportParents.txt (rozbité obrázky na IS, po odstranění rozbitých dojde k reimportu z LTP)
| |
| +-+brokenUUIDS_not_tif_big.txt
|   |
|   +-+brokenUUIDS_jp2_big.txt (odkaz do IS obsahuje jp2, bude potřeba odebrat z cest jpg obrázků)
|   |
|   +-+brokenUUIDS_not_tif_jp2_big.txt 
|       |
|       +-+bu_ntj2b_missing_UC.txt (chybějící předpona "UC_" u obrázků)
|       |
|       +-+bu_ntj2b_wUC.txt (ostatní)
|
+-+-parents.txt
```

**Comment by jkremlacek** [comment]
Pro interní datastreamy nachystám skript, který zkontroluje zda mají data na imageserveru a následně upraví datastreamy na externí.

**Comment by jkremlacek** [comment]
Interní datastreamy, které obsahovaly odkaz na jp2 do imageserveru (tiles-url v RELS-EXT), opraveny.

~~[internal_pre_filtered.txt](https://github.com/moravianlibrary/kramerius/files/2013777/missingTilesURL.txt)~~ (podrobnější rozdělení viz zafan)
_formát: lineNum, UUID strany_

Ostatní strany bude potřeba dohledat, zda mají jp2 na IS - pokud mají, tak bude potřeba jen opravit odkaz + doplnit tiles-url do RELS-EXT, pokud nemají tak bude potřeba podle situace jiné řešení (zatím jsem narazil na jp2 ve IMG_FULL datastreamu - tedy musel by se vykopírovat do IS a opravit datastream na externí)

**Comment by fstepanovsky** [comment]
Seznamy odkazů v datastreamech: 

* klokan.mzk.cz: [klokan_link.log](https://github.com/moravianlibrary/kramerius/files/2021753/klokan_link.log)

* ostatní: [internal_filtered.log](https://github.com/moravianlibrary/kramerius/files/2021754/internal_filtered.log)

**Comment by jkremlacek** [comment]
- [x] **Ke klokan.mzk.cz:**

 v cestě se odkazuje na čk:

2619320319
2619312827
2619312828

a dále na sysna:

001052304 - patří k 2619298360
001050316 - patří k 2619298390
001050655 - patří k 2619298371

Strany jsou nicméně sirotci (kontrolováno v risearchi, na strany nevede žádná vazba). Dané ČK odkazují na nadřazené objekty, které mají připojené jiné strany (jak nadřazené objekty, tak strany jsou vpořádku).

U daných ČK jsem ověřil, zda nemají nějaké strany ve "skupině" rozbitých obrázků a zdají se být vpořádku, sirotci odkazující na klokan.mzk.cz by tedy měli být smazatelní.

---
**K internal_filtered.log:**
- [x] část objektů obsahovala funkční odkaz do imageserveru 
[internal_filtered_imageserver.txt](https://github.com/moravianlibrary/kramerius/files/2035170/internal_filtered_imageserver.txt) a pouze měla thumbnail uložený ve fedoře, tyto dokumenty jsem opravil, aby se i thumbnail načítal z imageserveru

- [ ] namátková kontrola ostatních 
[internal_filtered_img_full.txt](https://github.com/moravianlibrary/kramerius/files/2035169/internal_filtered_img_full.txt)
 odhalila, že jsou mezi nimi sirotci (ze skenu šlo zjistit, že jde o Rovnosť, ročník 7)
Edit: řeší se v https://github.com/moravianlibrary/kramerius/issues/277
  - [x] stranám, které mají rodiče, budou obrázky přesunuty do IS a datastreamy přesměrovány tam
  - [ ] u sirotků bude potřeba manuální kontrola každé strany, zda jde o duplicitu, či nikoliv Edit: řeší se v https://github.com/moravianlibrary/kramerius/issues/274

**Comment by jkremlacek** [comment]
**K brokenuuids.txt:**
- mezi rozbitými obrázky jsou duplicity objektů, př: 

  _uuid:8db93eb9-a379-459c-9c7d-f4fabfe29540_ (jeho stránky jsou v brokenuuids.txt) a
  _uuid:9ccb377d-af47-43c6-9da5-58ac7358cd04_

  - obsahují stejné sysno **001134919** a stejná metadata, s tím, že v 9ccb... obsahují více údajů (jsou novější o 5 měsíců) a připojené stránky mají funkční obrázky - chyba pravděpodobně vznikla v Meditoru, kdy úprava metadat vytvořila nový objekt (nové uuid), a staré objekty nechal ve Fedoře s již nefunkčními obrázky.

  - stránky dále neobsahují datastream PREVIEW
- některé stránky sice jsou na imageserveru, ale jejich velikost je 0, př:
  - mzk03/001/183/466, uuid:22ded3bb-1c08-4c39-bf80-af0b49a2476d

---

- část objektů obsahuje cestu do imageserveru ve formátu .tif.jp2, tyto obrázky jsou na imageserveru rozbité a bude je potřeba znovu nahrát z LTP
~~[brokenUUIDS_tif_big.txt](https://github.com/moravianlibrary/kramerius/files/2045024/brokenUUIDS_tif_big.txt)~~

  - [x] bohužel se mezi nimi našli sirotci, které nepůjde nahrát z LTP
[tif_big_missing.txt](https://github.com/moravianlibrary/kramerius/files/2047477/missing.txt)
Edit: z foxml cest na obrázky šel vyčíst rodič `uuid:e98a4120-24c7-11e2-8579-005056827e52`, má připojené strany s jinými UUID a jsou v adresáři roku 2013, rozbité byly 2014, rozbité budou smazány

  - [ ] rodiče na nahrání z LTP jsou ~~(až po odstranění rozbitých obrázků na imageserveru, provádí @zafan )~~:
[reimportParents.txt](https://github.com/moravianlibrary/kramerius/files/2047489/reimportParents.txt)
řeší se v: #262




--- 

- zbytek objektů bez tif.jp2 je zde 
~~[brokenUUIDS_not_tif_big.txt](https://github.com/moravianlibrary/kramerius/files/2045027/brokenUUIDS_not_tif_big.txt)~~ (níže jsou podrobnější soubory)

  - [x] zde je skupina objektů z muzea brněnska, která má v cestě na imageserver koncovku .jp2, bude potřeba cesty ve fedoře přepsat, aby obsahovaly pouze .jp2
[brokenUUIDS_jp2_big.txt](https://github.com/moravianlibrary/kramerius/files/2045058/brokenUUIDS_jp2_big.txt)

  - [ ] zbytek objektů bez .tif.jp2 a .jp2 je zde
[brokenUUIDS_not_tif_jp2_big.txt](https://github.com/moravianlibrary/kramerius/files/2045062/brokenUUIDS_not_tif_jp2_big.txt)
    - [x] obrázky bez předpony UC_
[bu_ntj2b_missingUC.txt](https://github.com/moravianlibrary/kramerius/files/2067387/bu_ntj2b_missingUC.txt)

    - [ ] ostatní
[bu_ntj2b_wUC.txt](https://github.com/moravianlibrary/kramerius/files/2067389/bu_ntj2b_wUC.txt)
Edit: řeší se prostřednictvím tabulky https://docs.google.com/spreadsheets/d/1jNf7rhqOrhfori4Im22o8E-SrWyXLTjhrcANofT5Iug/edit#gid=0

**Comment by jkremlacek** [comment]
Detailnější rozpis bu_ntj2b_wUC.txt (obsahuje jednotkové chyby) [zde](https://docs.google.com/spreadsheets/d/1jNf7rhqOrhfori4Im22o8E-SrWyXLTjhrcANofT5Iug/edit?usp=sharing).

Část je řešena v rámci https://github.com/moravianlibrary/kramerius/issues/273 a https://github.com/moravianlibrary/kramerius/issues/274.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
