### ISSUE TITLE
Čin - problém s reindexací

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#255]
Stránky v Činu uuid:c3318d70-6f69-11e2-b9fa-005056827e52 jsou náhodně veřejné a neveřejné a reindexace mi spadla. PID procesu 307. Nemůže být problém s vazbami na obrázky?

Plus může to mít nějakou souvislost s tímto zavřeným issue https://github.com/moravianlibrary/kramerius/issues/82 ?

**Comment by kazooo** [comment]
Reindexace padá protože ze všech ročníků co má Čin v RELS-EXT,
```
uuid:49f1ad70-8ae7-11e2-8593-005056827e52
uuid:f555f250-b622-11e2-9592-5ef3fc9bb22f
uuid:0ade45c0-7f26-11e2-a455-005056827e52
uuid:59812ca0-8af3-11e2-bf69-001018b5eb5c
uuid:fda6d520-87d1-11e2-b6e7-001018b5eb5c
```
existuje jen uuid:49f1ad70-8ae7-11e2-8593-005056827e52, ostatní nejsou ani v Solru ani ve Fedoře.
Poslední modifikace ročníku uuid:49f1ad70-8ae7-11e2-8593-005056827e52, podle Solru,
2017-02-10 (může to byt i nějaká reindexace)

**Comment by LenkaKravecova** [comment]
Aha.. tak to nezbývá nic jiného než reimport z LTP.. Díky. Otázka, jestli se to nesmazalo právě proto, že dělali nějakou opravu a reimport se nevydařil. Zjistím.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
