### ISSUE TITLE
Náš domov - rozbité obrázky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#256]
U dokumentu Náš domov uuid:a398e0d8-5f29-478c-87a0-2369fb3e5649 se nezobrazuje asi polovina obrázků. Na imageserveru se taky nezobrazí. @zafan, podíváš se na to, prosím?

**Comment by fstepanovsky** [comment]
@LenkaDamborska podívám se na to.

**Comment by fstepanovsky** [comment]
@LenkaDamborska, soubory, které nelze zobrazit jsou nevalidní/porušené.

**Comment by MarosGrm** [comment]
Jedná sa o MZK produkciu, takže reimport z LTP nepôjde. Bude nutný rescan.

**Comment by annie-cz** [comment]
Zařídím to.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
