### ISSUE TITLE
Mährisch-schlesischer Correspondent - ročník 1878

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#257]
Ročník 1878 uuid:7a18c630-fa27-11e4-8ded-5ef3fc9ae867 obsahuje čísla a přílohy z roku 1878 i 1886. Potřebovala bych seznam těch příloh a čísel z roku 1886. Stačí uuid a dateIssued. Pak to nahlásím do LTP.
Díky.

**Comment by kazooo** [comment]
[1886.txt](https://github.com/moravianlibrary/kramerius/files/1963346/1886.txt)
Jde takto?

**Comment by LenkaKravecova** [comment]
Stačí. Díky.
