### ISSUE TITLE
Pestrý týden - chybí ročníky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#258]
V periodiku Pestrý týden uuid:ae722b4f-435d-11dd-b505-00145e5790ea chybí ročníky 1930-36. Určitě jsme je tam měli. Kam zmizeli a hlavně proč? 
Prověřte taky, jestli jsou obrázky na imageserveru.

**Comment by MarosGrm** [comment]
Podľa Fedory to vyzerá všetko v poriadku, posledný dátum úpravy je december 2014 a na imagesrvru tiež niesu. Je to divné, pretože aj keby sa to omylom zmazalo tak na by IS tie obrázky zostali.

**Comment by LenkaKravecova** [comment]
Díky. Hmm, dívala jsem se do staršího seznamu replikací, podle kterého se měly k nám replikovat všechny ročníky, z čehož jsem usoudila, že jsme je v Krameriu měli... Takže dobrá zpráva, že nedošlo ke smazání. Tím pádem zavírám, nejde o chybu. Dodatečný import ostatních ročníků pak pořešíme samostatně.
