### ISSUE TITLE
Chybějící obrázky ročníku 1912 - Wissenschaftliche Studien und Mittheilungen

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#260]
Stránky vydání **uuid:fe693aa0-49df-11e2-9c70-5ef3fc9bb22f** mají rozbité odkazy do imageserveru, s tím, že dokonce odkazují na chybného (neexistujícího) rodiče **uuid:c656c720-1db8-11e2-a61d-005056827e52**.

Podle risearch-e má ročník 1912 (**uuid:8dbdfa30-34bc-11e2-adb0-005056827e52**) pouze jedno vydání, proto je projistotu požadavek na celý ročník a ne pouze na dané číslo.

**Comment by LenkaKravecova** [comment]
V LTP se archivuje po číslech, takže se obávám, že reimportují přímo to číslo. Některé ročníky mají taky jen jedno číslo, takže to snad není chyba. Tak já to nahlásím na reimport.

**Comment by marketakrutska** [comment]
Reimport z LTP proběhl v pořádku, ročník 1912 je již v pořádku.
