### ISSUE TITLE
Reimport kvůli poškozeným obrázkům

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#262]
U každé publikace bylo několik rozbitých obrázků s velikostí 0. Rozbité obrázky byly smazány.

Seznam rodičů, které je potřeba zadat na reimport je zde:
https://github.com/moravianlibrary/kramerius/files/2047489/reimportParents.txt

**Comment by LenkaKravecova** [comment]
Kubo, máš někde přehled, které obrázky byly smazány? Teď se dívám např. na uuid:59561d00-24c1-11e2-8579-005056827e52 a nevidím nějaké chybějící stránky, zdá se mi to kompletní.
Jinak dám vše na reimport.

**Comment by jkremlacek** [comment]
V rámci zmíněného uuid je rozbitá strana s uuid:04648bbc757143d3ec0002cd0313e3b7.

Dobře je to vidět v [digitalni knihovne](http://www.digitalniknihovna.cz/mzk/view/uuid:59561d00-24c1-11e2-8579-005056827e52), strana 191

Veškerý postup je evidován v rámci https://github.com/moravianlibrary/kramerius/issues/254 - jen už je toho hodně, takže se v tom nedá dobře vyznat.

Konkrétně tenhle problém se řešil na základě souboru
https://github.com/moravianlibrary/kramerius/files/2045024/brokenUUIDS_tif_big.txt
dá se v něm relativně dobře hledat pomocí uuid bez předpony "uuid:"
pro danou monografii vyleze řádek:
```
3.4785838E7,uuid:04648bbc757143d3ec0002cd0313e3b7,http://imageserver.mzk.cz/NDK/2012/59561d00-24c1-11e2-8579-005056827e52/1_scan0191.tif/big.jpg
```

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
