### ISSUE TITLE
Chybějící obrázky ke stranám

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#264]
UUID rodičů: 

- **uuid:4b73d040-6707-11e3-8fee-005056827e51** od strany 197 dál
- **uuid:4dcd78d0-bfc9-11e3-aec3-005056827e52** 
- **uuid:241c4190-cac0-11e3-b110-005056827e51** 
- **uuid:8fac8830-dce4-11e3-b110-005056827e51** 
- **uuid:45863370-e0a7-11e3-b110-005056827e51** 
- **uuid:8eb101e0-3195-11e3-a5bb-005056827e52** 
- **uuid:d0d137d0-7ea6-11e3-86b3-005056827e52** 
- **uuid:942509f0-f6ac-11e3-812a-005056827e52** 
- **uuid:1696b6d0-d994-11e3-b110-005056827e51** 
- **uuid:35a96f80-d693-11e3-b110-005056827e51** 
- **uuid:27a0a040-d69b-11e3-b110-005056827e51** 
- **uuid:0a123430-f2e3-11e3-a2c6-005056827e51**
- **uuid:0b918130-f2e3-11e3-a2c6-005056827e51**
- **uuid:dafefb90-e6f0-11e3-a2c6-005056827e51**
- **uuid:8dbd2530-f2e6-11e3-a2c6-005056827e51**
- **uuid:e71cb480-f12c-11e3-b72e-005056827e52**
- **uuid:ed2df580-f2c8-11e3-b72e-005056827e52**

Obrázky stran chybí na IS.

**Comment by LenkaKravecova** [comment]
Díky, nahlásím na reimport.

**Comment by jkremlacek** [comment]
Posílám druhou várku, ať nezakládám další issue:

- **uuid:43a07fa0-8dad-11e7-9950-005056827e52**
- **uuid:fb4c59e0-7048-11e6-a429-001018b5eb5c**
- **uuid:91a9dcb0-a4f5-11e6-840e-005056827e52**
- **uuid:bf4309f0-24d2-11e2-85be-005056827e51**
- **uuid:5c2c78b0-4435-11e2-b246-005056827e52**
- **uuid:4deb2df0-4435-11e2-b246-005056827e52**
- **uuid:821a3fd0-4435-11e2-b246-005056827e52**
- **uuid:3b1e1980-4435-11e2-9b88-005056827e51**
- **uuid:91851670-4435-11e2-b246-005056827e52**
- **uuid:f6398890-4434-11e2-9b88-005056827e51**
- **uuid:3e5109f0-4435-11e2-9b88-005056827e51**
- **uuid:a5fc5870-4435-11e2-b246-005056827e52**
- **uuid:c63594b0-4432-11e2-9b88-005056827e51**
- **uuid:e30c0e40-437c-11e2-b246-005056827e52**
- **uuid:588d5c80-3abf-11e2-b19a-005056827e52**
- **uuid:0ddc8fc0-1e7d-11e2-a61d-005056827e52**
- **uuid:aa5284d0-3fa3-11e2-9b88-005056827e51**
- **uuid:c3b78b00-ab2d-11e2-b6da-005056827e52**
- **uuid:a6297b00-4de6-11e3-9c86-005056827e51**
- **uuid:fd4b9ba0-7ce2-11e2-b212-005056827e52**
- **uuid:acdec6b0-37dc-11e2-b19a-005056827e52**
- **uuid:e1596ab0-80d1-11e2-aa2b-005056827e51**

**Comment by vjirousek** [comment]
Z LTP bylo vše aktualizováno, prosím nicméně o důkladnou kontrolu, zda došlo k nápravě - část chyb může být podobného charakteru jako v https://github.com/moravianlibrary/kramerius/issues/319 a samotná aktualizace tedy problém nevyřeší. Kde chyba přetrvá, nechám znovu vytvořit chybné UC a pošleme další aktualizaci. Díky.

**Comment by marketakrutska** [comment]
Tak jsem to zkontrolovala. Všechno je v pořádku, jen:
uuid:4dcd78d0-bfc9-11e3-aec3-005056827e52 - chybí v našem Krameriu, v NK to je. Prosím tedy @vjirousek ještě o reimport.
uuid:27a0a040-d69b-11e3-b110-005056827e51 - chybí v našem i v NK Krameriu, možná se to deaktivovalo (?)

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
