### ISSUE TITLE
Brünner Zeitung, 02.01.1874, 1, chybějící obrázky tří stran

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#265]
Ve Fedoře odkazují na krameriusndktest.mzk.cz namísto do imageserveru.

UUID rodiče: uuid:2b06cbf0-0e91-11e4-8e0d-005056827e51

**Comment by leiblix** [comment]
Jo, dříve byl imageserver nainstalovaný vedle krameria na stejné URL (krameriusndktest.mzk.cz/imageserver). 

Později jsem to s Danem spojoval a nahrazoval jsem to natvrdo v datech Fedory, ten skript vypadal nějak takto (dohledal jsem ho v mailu :D). Je možné že tomu něco uniklo. 

Nebo byl prostě chvíli špatně nakonfigurovaný transformační modul.

```
#!/bin/bash
# usage find . -type f -exec /path/imageserverreplace.sh {}
TILES=`xmlstarlet sel -N kramerius4="http://www.nsdl.org/ontologies/relationships#" -t -v "//kramerius4:tiles-url" $1`
if [ ! -n "$TILES" ]; then
echo $1";nopage"
else
NEWTILES=${TILES/http:\/\/krameriusndktest.mzk.cz\/imageserver/http:\/\/imageserver.mzk.cz}
THUMB=$NEWTILES/thumb.jpg
PREVIEW=$NEWTILES/preview.jpg
BIG=$NEWTILES/big.jpg
echo $1";"$NEWTILES
xmlstarlet ed --inplace --pf -N kramerius4="http://www.nsdl.org/ontologies/relationships#" \
-N foxml="info:fedora/fedora-system:def/foxml#" \
-u "//kramerius4:tiles-url" -v $NEWTILES \
-u "//foxml:datastream[@ID='IMG_THUMB']//foxml:contentLocation/@REF" -v $THUMB \
-u "//foxml:datastream[@ID='IMG_PREVIEW']//foxml:contentLocation/@REF" -v $PREVIEW \
-u "//foxml:datastream[@ID='IMG_FULL']//foxml:contentLocation/@REF" -v $BIG \
$1
```

**Comment by jkremlacek** [comment]
Chyba nezůstala u jedné publikace:

**uuid:4ba3a670-cc12-11e2-a712-005056827e51** odkazuje taky na krameriusndktest

**Comment by LenkaKravecova** [comment]
Blbý dotaz - takže to znamená, že ty obrázky teda nemáme? Tzn. bude potřeba reimport z LTP?

**Comment by jkremlacek** [comment]
Podle mě by neměl být potřeba - jen bude potřeba zkontrolovat, že ty obrázky jsou na imageserveru a potom přepsat ty odkazy na něj. 

Pokud by se ukázalo, že něco chybí, tak bude potřeba reimport z LTP - dal bych vědět + přidal label na reimport.

**Comment by jkremlacek** [comment]
uuid:2b06cbf0-0e91-11e4-8e0d-005056827e51 opraveno,

uuid:4ba3a670-cc12-11e2-a712-005056827e51 odkazy do IS taky, ale ukázalo se, že část stránek je šeredně poškozených ve fedoře (do takové míry, že fedora ani není schopná ohlásit chybu uživateli při pokusu o zobrazení)

Chyba v logu je `org.fcrepo.server.errors.ObjectIntegrityException`

Edit:
 
Nejspíš došlo k poškození vnitřních souborů fedory - mají nevalidní odkaz v `contentLocation` u datastreamů (neobsahuje ani http://).

Skrz REST API je oprava nemožná, protože u stránek neodpovídá. Přes filesystem je možné v objectstore-u v hlavním souboru upravit cesty, čímž začne objekt fungovat i v REST API. U několika stránek jsem si všiml, že v RELS-EXT chybí tiles-url, po opravě bude potřeba přidat.

**Comment by jkremlacek** [comment]
Ad uuid:4ba3a670-cc12-11e2-a712-005056827e51:
- interním souborům stránek (odkazovány v `objectStore` tabulce v db) opraveny odkazy
- stránkám doplněn tiles-url
- dokument jsem reindexoval (v krameriovi se zobrazoval jako jednostránkový dokument)
