### ISSUE TITLE
Rozpadlé monografie

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#266]
Objekt monografie s uuid:c656c720-1db8-11e2-a61d-005056827e52 chybí ve fedoře.

Všechny stránky dané monografie jsou ve fedoře jako sirotci (852 stran), obrázky do IS nefungují, ale obsahují OCR. 

[seznam sirotků](https://github.com/moravianlibrary/kramerius/files/2123015/orphanage852.txt)

Nejsem si jistý jestli reimport z LTP projde, možná bude potřeba nejdřív smazat sirotky z Fedory.

**Comment by jkremlacek** [comment]
Další stejně rozpadlá monografie je: uuid:fe7e3c10-609b-11e3-ac69-005056827e51

**Comment by vjirousek** [comment]
Psal jsem již v prosinci k ticketu u nás v servicedesku - ta dvě UUID neexistují v rámci LTP/WF NDK, zkuste tedy ověřit co je to za data. O NDK data se podle všeho nejedná, z LTP tedy neumíme pomoci.

**Comment by marketakrutska** [comment]
Dívám se do ServiceDesku a koukám, že tam jsou tři stejné tikety ohledně této opravy. Lenka poslala dva tikety (6790 a 7551) a pak došlo k nedorozumění a já to poslala potřetí (7946). Za tohle se vám všem @vjirousek  do LTP moc omlouvám, to by se opravdu stávat nemělo.

Prosíme o reimport čísla 1 ročníku 1912 (ročník 33) periodika Wissenschaftliche Studien und Mittheilungen aus dem Benedictiner...: **uuid:fe693aa0-49df-11e2-9c70-5ef3fc9bb22f** 

Vypadá to, že uuid:c656c720-1db8-11e2-a61d-005056827e52 bylo změněno na uuid:fe693aa0-49df-11e2-9c70-5ef3fc9bb22f.
V tiketu 6790 Lenka ještě psala: "Číslo odkazuje na neexistujícího rodiče uuid:c656c720-1db8-11e2-a61d-005056827e52 místo na ročník 1912 uuid:8dbdfa30-34bc-11e2-adb0-005056827e52. Prosím tedy o opravu uuid na úrovni ročníku pro dané číslo."

EDIT: U toho uuid:fe7e3c10-609b-11e3-ac69-005056827e51 vůbec nevím, co to je za dokument. @kenji1322 prosím, nepodíval by ses na to?

**Comment by marketakrutska** [comment]
Jak jsem psala dříve, uuid:c656c720-1db8-11e2-a61d-005056827e52 bylo změněno na uuid:fe693aa0-49df-11e2-9c70-5ef3fc9bb22f. V LTP to již opravili, řešilo se to i v issue 260 (již je zavřené).

Dokument uuid:fe7e3c10-609b-11e3-ac69-005056827e51 jsem nakonec dohledala ve workflow. Jedná se o knihu "Angličtina pro jazykové školy : nové upravené vydání s klíčem" - 3. díl, ČK: 2610460134
Tento dokument řešila už Lenka, napsala k tomu, že byl manuálně přeskočen import do LTP a musí se digitalizovat znovu. Už je to nově zdigitalizované pod uuid:34b78860-3b4b-11e9-a543-005056827e52, je to součástí vícesvazku uuid:95e283e0-670e-11e3-99ab-005056825209

Když jsem v Digitální knihovně vyhledávala název "Angličtina pro jazykové školy : nové upravené vydání s klíčem", tak se tam zobrazoval nějaký starý záznam ze Solru uuid:a784f070-670d-11e3-8fee-005056827e51, který v sobě nic neobsahoval. Alex záznam smazal.

Vše už je tedy vyřešené.
