### ISSUE TITLE
Chybějící obrázky původem z MZK

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#267]
Na imageserveru chybí skeny, které nejsou původem z NDK, nejspíš je bude potřeba znovu naskenovat.

Publikace, kterým chybí obrázky 
(_cesta_na_imageserveru/sysno, uuid_rodiče, počet_stran_):
- mzk01/001/207/407, `uuid:26d5c4e7-406f-46b1-b1d3-8ef008cc76d2`, (všech 308 stran)
- mzk01/001/117/433, `uuid:6486fd8f-1d00-42ad-9ba1-1b88f4113fc3`, (všech 184 stran)
- mzk01/001/119/510, `uuid:13247578-f2e4-4e59-bda9-466337e64c15`, (všech 514 stran)
- mzk01/001/207/118, `uuid:7524a495-daa4-4658-9ab4-08c7330d81df`, (všech 128 stran)
- mzk01/001/207/019, `uuid:f4390038-2cc2-4b62-bf02-2afd878048f1`, (všech 122 stran)
- mzk01/001/116/690, `uuid:ba95c027-153e-4b98-9913-7725d04b2bdb`, (všech 160 stran)
- mzk01/001/176/231, `uuid:092e9cf5-dab7-4722-bffa-6c65db02d3b2`, (všech 78 stran)
- mzk01/001/176/233, `uuid:b6a0a4e1-fe8e-432e-b4e6-22442fe8bf15`, (všech 62 stran)
- mzk03/001/185/741, `uuid:da516356-0d7c-4e20-a2cb-adbcf837bc72`, (169 z 694 stran) (Rajhrad)

**Comment by LenkaKravecova** [comment]
Nejdřív se musíme podívat do archivu, jestli tam obrázky nejsou. @zafan podíváš se na to? Díky.

**Comment by fstepanovsky** [comment]
@LenkaKravecova V archivu bohužel tyto obrázky nemáme.

**Comment by LenkaKravecova** [comment]
Aha :(

**Comment by LenkaKravecova** [comment]
Ani to poslední (Rajhrad)? To by někde mělo být. Můžu to zjistit.

**Comment by fstepanovsky** [comment]
Ani bohužel to poslední, ani u nás, ani digit, ani samotný rajhrad (má zcela jinou strukturu dat).

**Comment by jkremlacek** [comment]
Přidávám další záznamy s chybějícími skeny:
- mzk01/000/915/123, `uuid:411f114d-cffd-4e77-a42b-0ba2ac99d602`, strana 144 s `uuid:ac6141b9-53f0-4b90-9537-bac3db1e2d0e`
- mzk03/001/036/129, `uuid:d66b6f2c-846d-4857-bd10-5f29a862bd45`, strany 5, 49, 83, 192, 212, 280, XLVIII, LXXVII, CIV
- mzk03/001/183/466, `uuid:6be3d27e-f18d-4107-bd2e-a391a071e4c2`, strany 17-23, 44, 45
- mzk01/001/208/180, `uuid:3b6f6706-6b48-4efb-8867-6cbe2644b181`, strany 19, 23, 35, 40, 50, 80, 98, 156, 216, 224
- mzk03/001/185/925, `uuid:d4713f20-3e27-4eee-9e9b-79eafc008261`, strany 7 a 29 
- mzk03/001/175/081, `uuid:9d584f61-71c9-4559-a5b8-6e09329efc8f`, strana 41
- mzk03/001/225/553, `uuid:0e495112-288a-4404-9d55-6994ee89e292`, strana 1170
- mzk03/001/213/713, `uuid:b308cc2e-f4d6-472c-b418-e51cf23229c2`, strana 612

**Comment by LenkaKravecova** [comment]
Jen se zeptám k tomu poslednímu komentáři, nedívali jste se na ty chybějící strany, zda je máme v archivu, @zafan ? Zvlášť ty z mzk03. díky.

**Comment by fstepanovsky** [comment]
@LenkaKravecova bohužel tam také nejsou. V archivu neexistuje nic z druhé a třetí části sysna, platí to pro všechny položky v tomto issue.

**Comment by LenkaKravecova** [comment]
Ok, díky, zkusila jsem to :) Mzk01 nebude asi problém naskenovat, mzk03 ještě pohledají ve starých tiscích někde na svém disku..

**Comment by LenkaKravecova** [comment]
Ty mzk01 věci už se udělaly nově přes NDK, takže ty už jsou ok. Jsou ty chybné ještě ve Fedoře? Pokud ano, můžou se celé smazat.

Ty mzk03 věci jsou v řešení.

**Comment by jkremlacek** [comment]
věci z mzk01 zůstaly v krameriovi a fedoře (v solru už nebyly), takže smazáno

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
