### ISSUE TITLE
Svobodné slovo 15.09.1956

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#268]
4. strana s uuid: `uuid:8b9d3f3c-d5e4-4814-b802-adb951715cc5` má nefunkční odkaz na obrázek v fsv.cuni.cz

uuid čísla je: `uuid:245bb355-108a-413f-baf4-ee663ea851c5`

**Comment by LenkaKravecova** [comment]
Souvisí s https://github.com/moravianlibrary/kramerius/issues/279. Mělo by to vyřešit tento problém.

**Comment by jkremlacek** [comment]
Chyba se replikací nevyřešila. Odkaz nově ukazuje na [imageserver](http://imageserver.mzk.cz/mzk01/000/181/899/1956/224/8b9d3f3c-d5e4-4814-b802-adb951715cc5/big.jpg), kde ale obrázek chybí taky.

**Comment by annie-cz** [comment]
@hlavacekrene René, podívej se na to prosím, kde se stala chyba.

**Comment by hlavacekrene** [comment]
O tomto obrazku vim, poznamenal jsem si ho, vubec jsem jej od nich nedostal a u nich chybi taky. Je to volume 1956 issue 224  čtvrtý obrazek. U nich to chybí taky. http://kramerius.fsv.cuni.cz/search/i.jsp?pid=uuid:8b9d3f3c-d5e4-4814-b802-adb951715cc5&q=#periodical-periodicalvolume-periodicalitem-page_uuid:8b9d3f3c-d5e4-4814-b802-adb951715cc5        Museji to doskenovat a pak poslat, ja to pak u nas doplnim.

**Comment by annie-cz** [comment]
Super, díky za informace, budeme tedy čekat.

**Comment by annie-cz** [comment]
Vyřešeno, zavíráme.
