### ISSUE TITLE
rozbitý OAI záznam periodika

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius#269]
Tohle obsahuje v metadata error:
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.cz:uuid:ae7add91-435d-11dd-b505-00145e5790ea

http://www.digitalniknihovna.cz/mzk/uuid/uuid:ae7add91-435d-11dd-b505-00145e5790ea
Možná nějaký pozůstatek něčeho už neexistujícího, ale stále v solru?

**Comment by rzeh4n** [comment]
Týká se i monografií:
https://kramerius.mzk.cz/oai/?verb=GetRecord&metadataPrefix=drkramerius4&identifier=oai:kramerius.mzk.cz:uuid:10cfb93a-4ee0-49da-9122-c549bd4f85ba

**Comment by jkremlacek** [comment]
Ve fedoře **uuid:ae7add91-435d-11dd-b505-00145e5790ea** a **uuid:10cfb93a-4ee0-49da-9122-c549bd4f85ba** neexistuje. 

Podle záznamu v SOLRu a Alephu jsem dohledal funkční uuid:

- uuid:10cfb93a-4ee0-49da-9122-c549bd4f85ba s ČK 2619320335: 
**uuid:d0041c00-e17f-4d8a-9ee4-a8bee7a375c5**
- uuid:ae7add91-435d-11dd-b505-00145e5790ea s ISSN issn:0023-5849
**uuid:1c869c00-535b-11e3-9ea2-5ef3fc9ae867**

Došlo tedy ke změně UUID a ta nesmazala starý záznam v SOLRu.

edit: Ze SOLRu záznamy na neexistující UUID smažeme.

**Comment by kazooo** [comment]
Nevalidni zaznamy jsou odstraneny ze SOLRu.
