### ISSUE TITLE
Změnit hudebniny na model sheetmusic

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#27]
Mezi sheetmusic jsou i monografie, změnit jim model na sheetmusic.

http://kramerius.mzk.cz/search/r.jsp?offset=0&forProfile=facet&fq=document_type:%22sheetmusic%22

**Comment by leiblix** [comment]
uuid:5d462155-7e3c-11e1-a68c-0050569d679d
uuid:632edaed-9852-11e0-bd44-0050569d679d
uuid:7dff6f13-9dad-11e0-8578-0050569d679d
uuid:fbc60c92-5fc2-11e1-ae74-0050569d679d
uuid:44d12952-0492-11e1-8cf2-0050569d679d
uuid:f4f9cf08-26e0-4bfe-bf64-89e2d8e58845
uuid:98f82e26-7e3a-11e1-a68c-0050569d679d
uuid:17fe155d-a975-11e0-a5e1-0050569d679d
uuid:4fddfb52-9e68-11e0-b8ae-0050569d679d
uuid:45596a69-9e68-11e0-b8ae-0050569d679d
uuid:66a32507-9e68-11e0-b8ae-0050569d679d
uuid:7f8eff48-9e68-11e0-b8ae-0050569d679d
uuid:0c4a09ca-9e6c-11e0-b8ae-0050569d679d
uuid:9ddf2546-7e3c-11e1-a68c-0050569d679d
uuid:19d23dc7-9e6c-11e0-b8ae-0050569d679d
uuid:2c031248-9e6c-11e0-b8ae-0050569d679d
uuid:fa79663c-9e7f-11e0-b8ae-0050569d679d
uuid:04d00955-9e80-11e0-b8ae-0050569d679d
uuid:04d00955-9e80-11e0-b8ae-0050569d679d

**Comment by leiblix** [comment]
Kromě DC se ještě bude muset měnit RELS-EXT

`<fedora-model:hasModel rdf:resource="info:fedora/model:monograph"></fedora-model:hasModel>`

na 

`<fedora-model:hasModel rdf:resource="info:fedora/model:monograph"></fedora-model:sheetmusic>`

**Comment by jirkadev** [comment]
Vyřešeno commitem https://github.com/moravianlibrary/K4-tools/commit/e4d25d219acd5c6a5ef9389ed4ca45ed1494f4ac spuštěno. Model se změnil
