### ISSUE TITLE
Egypt mzk01/000/265/425 chybí data vč. odkazu v alephu

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#270]
uuid:d3025c34-d549-40e7-ac07-7fc6da8eede0 postrádá veškerá data (obrázky, zvuky) a záznam v alephu pod mzk01/000/265/425 postrádá informaci o tom, že byl zdigitalizován (odkaz do krameria/digitalni knihovna).

Jde o zrušený objekt, nebo o chybu v datech?

**Comment by LenkaKravecova** [comment]
@indrakm, podařilo se ti, prosím, se na tento zvukáč podívat?

**Comment by indrakm** [comment]
@LenkaKravecova ještě ne. Teď v týdnu to pohledám na lokále na 307 - snad ještě dneska.

**Comment by indrakm** [comment]
nalezeno, předáno

**Comment by jkremlacek** [comment]
Opraveno: www.digitalniknihovna.cz/mzk/view/uuid:d3025c34-d549-40e7-ac07-7fc6da8eede0

Zůstává problém s alephem, kde chybí url na digitální knihovnu, tam ale nemám právo na změny.

**Comment by LenkaKravecova** [comment]
To není problém. Dám to tam ;)
