### ISSUE TITLE
Národní listy - 1922 Volume 62 - Vzdělávací příloha Národních listů - rozbitý sken

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#271]
Jedna strana (uuid:3bc27839-435e-11dd-b505-00145e5790ea) má rozbitý obrázek (o velikosti 0) na imageserveru. Bude potřeba obrázek získat od zdroje (České Budějovice) a nahrát na imageserver.

**Comment by MarosGrm** [comment]
Opravené
