### ISSUE TITLE
[Statuta synodalia] chybí skeny 

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#273]
strany:

- uuid:8a74ecbb-9cb1-41f4-ac22-694cf73a4f5b
- uuid:f7d9b52e-0eb4-4285-9ff9-2a65b15308aa

publikace uuid:733866f7-681e-43d9-a8a5-42e06cde9362 postrádají obrázky na imageserveru. Jde o STT a jména chybějících skenů jsou:

- MK086_00382.jp2
- MK086_00383.jp2

Sysno je mzk03/001/046/715

Bude potřeba se podívat do archivu, zda tam jsou uloženy.

**Comment by fstepanovsky** [comment]
Tyto skeny bohužel v archivu nejsou:
* MK086_00382.jp2
* MK086_00383.jp2

**Comment by jkremlacek** [comment]
Takže teď otázka jestli jsou ty skeny uložené ještě někde jinde, anebo bude potřeba ty 2 strany doskenovat.

**Comment by indrakm** [comment]
Zkuste se zeptat Jirky Dufky, jestli se to nemůže válet u někoho na disku někde. Jinak budeme muset doskenovat.

**Comment by jkremlacek** [comment]
Napsal jsem mu, uvidíme jestli ta záloha existuje...

**Comment by jkremlacek** [comment]
Jirka Dufka našel disky s touto dávkou - v pondělí obrázky doplním na imageserver.

**Comment by indrakm** [comment]
well done :)

**Comment by jkremlacek** [comment]
Na discích jsou skeny do MK086_00381, takže to co na imageserveru je.

Tak mě napadá jestli je skutečně chyba s chybějícími skeny, nestalo se, že při zpracování metadat se tam vytvořily dvě stránky, které ve fyzické variantě neexistují?

**Comment by jkremlacek** [comment]
Chtělo by to určit osobu, která by mohla v originále zkontrolovat, zda tam existují stránky 382 a 383, které by (v případě jejich existence) bylo potřeba doskenovat - v opačném případě bychom odmazali objekty zmíněných stran.

**Comment by zabak** [comment]
Ahoj, tohle vypadá na chybu v metadatech, obrázky nechybí. Zařídím. Ale nestačí jen odmazat objekty, musí se v každém případě opravit názvy stran a typ strany: IIr - strana má být správně BS - zadní přídeští a IIv - strana má být správně BC - zadní desky.

**Comment by zabak** [comment]
ještě upřesním - myslím si, že chyba je už na začátku svazku protože číslování stran v metadatech je o 1 větší než čísla listů napsaná tužkou přímo na nich.

**Comment by annie-cz** [comment]
Chyba vznikla zřejmě úplně na začátku, kde je první dvojstrana popsaná tužkou jako 1 označená jako strana IIIr a IIIv. Pak je 2 a ta je označená jako Ir a Iv.

**Comment by annie-cz** [comment]
Vyřešeno s Erikou, opraveno a znovu nahráno do Krameria. Zde zavírám.

**Comment by jkremlacek** [comment]
Ještě koukám, že se opravou změnilo uuid, takže pro úplnost: nové uuid je `uuid:6bb7a768-4afc-48bb-aa81-81abc2d69ce4`.
