### ISSUE TITLE
Osiřelé objekty ve Fedoře bez obrázků

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#274]
V rámci řešení https://github.com/moravianlibrary/kramerius/issues/254 vypadlo 76 stran původem z MZK, které nemají rodiče ani obrazová data. K dispozici jsou pouze metadata, která ovšem obsahují v rámci strany pouze label s číslem strany. 

Z odkazu na data v imageserveru se dá ve většině případů zjistit sysno bývalého rodiče - manuálně spolu s číslem strany by se teoreticky dalo alespoň u monografií zjistit, zda jde o duplikát nebo ne. U periodik je nepraktické použít tento postup, protože stran s daným číslem je mnoho.

https://gist.github.com/jkremlacek/4fdbb58996045f9320046b4a7a8f554d

Je možnost sirotky vyexportovat z fedory (ve formátu FOXML), uložit někam pro případ, že by se zjistilo, že je potřeba z metadat něco vyčíst, a z fedory je následně smazat, aby nebránili migraci na F4.

**Comment by zabak** [comment]
Bylo by dobré zjistit odkud ta metadata pocházejí i u periodik. Ne že bychom dohledávali konkrétní stránku, ale abychom aspoň viděli, která periodika byla "zasažena". Na základě výsledků zkoumíní u monografií můžeme pak odhadnout, jestli je to problém nebo ne.

**Comment by jkremlacek** [comment]
U periodik to je:
- mzk01
  - **Rovnost** 
uuid:f1c7c08d-8f64-4b66-be28-5f209c2c7021
  - **Sdružení knihoven České republiky** 
uuid:14e188f0-ef85-11e2-9923-005056827e52
  - **Moravský jih : týdeník měst a obcí jižní Moravy**
uuid:dca4a5f4-7516-4712-b5b0-7fd4f5683771
- mzk03
  - **Journal für Freymaurer** 
uuid:5ac50e29-2790-4a62-90f9-dd7a33b0aad1
  - **Verzeichniss der Grossen Landes-Loge von Deutschland zu Berlin**
uuid:12e40562-dc07-4bec-8e8b-3b819ece2f63

S tím, že boe801-0003o5 se mi nepodařilo dohledat

**Comment by zabak** [comment]
to boe801 je něco z Rajhradu, takže jestli bude někdo něco tušit tak Jindra.

**Comment by indrakm** [comment]
Je docela možné, že Rajhrad bude mít Jindra nebo její holky někde na discích. Na mzk03 bych se poptal Jirky Dufky, jestli to někde nemají bokem. Mohl by případně i na potenciálního držitele externího disku nasměrovat :)

**Comment by jkremlacek** [comment]
Každopádně nejdřív bude potřeba manuálně ověřit ty duplicity, abysme zbytečně nehledali něco co máme, jen s jiným UUID.

**Comment by LenkaKravecova** [comment]
Už jsem domluvená s Luckou H., že se podívá po jiných chybějících dokumentech z Rajhradu, tak jí řeknu i toto. Jirka Dufka má prý jen mapy a grafiky.

**Comment by jkremlacek** [comment]
Až bude probíhat kontrola sirotků, tak vznikl další seznam uuid (které mají k dispozici obrázky ve Fedoře, takže je půjde dohledat podle nich) viz https://github.com/moravianlibrary/kramerius/issues/277#issuecomment-414225754

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
