### ISSUE TITLE
Seznam volných dokumentů dle Alephu

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#275]
Mám tady seznam, který obsahuje údajně volné dokumenty dle Alephu. Je potřeba z toho seznamu odstranit položky s odkazem na kramerius.nkp.cz a položky, které už jsou v Krameriu jako veřejné (tedy prohnat nějakým kontrolním procesem). Zůstanou neveřejné dokumenty, které pak může někdo hlavoručně zkontrolovat a zveřejnit. Díky.

[dig-volne.txt](https://github.com/moravianlibrary/kramerius/files/2269539/dig-volne.txt)

**Comment by hlavacekrene** [comment]
takze vyradit ze seznamu, co neni kramerius.mzk.cz 
pak projit vsechna uuid, co bude private, tak zmenit na public.

**Comment by LenkaKravecova** [comment]
Vyřadit ze seznamu, co není kramerius.mzk.cz (resp. digitalniknihovna.cz/mzk) - ANO
Projit vsechna uuid, co bude private, tak zmenit na public - NE !! Potřebuju jen zkontrolovat, co v tom seznamu už je public a to z toho seznamu dát pryč. 

Změnu na public u private dokumentů musí udělat někdo po kontrole autorů. To bude dělat už někdo hlavoručně. Automaticky se to udělat nedá.

**Comment by LenkaKravecova** [comment]
Takže to, co zůstane, bude seznam private dokumentů dle Krameria.

**Comment by hlavacekrene** [comment]
dam Ti pak dva seznamy, jeden public.txt, druhy private.txt a menit nebudu nic.

**Comment by LenkaKravecova** [comment]
jasně, může být.

**Comment by hlavacekrene** [comment]
tak jsem to dal do tabulky sem.
https://docs.google.com/spreadsheets/d/14nrKSkhntc-X2ZY32_ba5TRNLqlCXjAAtlWLcPJ8AvQ/edit#gid=31265196
nejdriv je private, pak public a nakonec, co nejsou vubec - fedora  404 not found.
Ve vstupnim souboru txt to bylo tříděno podle sloupečku B. Sloupeček B je sysno?

**Comment by LenkaKravecova** [comment]
Super, díky. Na ty 404 se podívám, moc jich není. Ano, sloupec B je sysno.

**Comment by LenkaKravecova** [comment]
Tak ty 404 byly buď zastaralé odkazy v Alephu, které už neexistují, nebo porouchané dokumenty, které jsem nahlásila na reimport z LTP.
