### ISSUE TITLE
Reindexace dokumentů, které jsou jazykové překlady

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#276]
V souvislosti s https://github.com/ceskaexpedice/kramerius/issues/436 bude potřeba dohledat všechny dokumenty, které mají v mods <mods:language objectPart="translation"> a reindexovat je. Cílem je, aby v případě překladů byl v solru pouze jeden jazyk.

**Comment by kazooo** [comment]
Aktualne v Solru je 112 962 dokumentu, ktere maji zaindexovano vice nez jeden jazyk. Spustim reindexace na krameriusbatch.mzk.cz po castech.
[several_languages.txt](https://github.com/moravianlibrary/kramerius/files/2273469/several_languages.txt)

**Comment by LenkaKravecova** [comment]
@xermak00 napiš sem, prosím, aktuální stav, jak se to teď dělá, v jakém je to stavu atp. Díky.

**Comment by kazooo** [comment]
Všechny dokumenty jsou reindexované a to už na ostrém Solru. Ted' dokumenty ze seznamu nemají v Solru jazyky s atributem "translation" v MODSu.
