### ISSUE TITLE
Záznamy neexistujících dokumentů

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#278]
`uuid:98c686f0-09bb-11e5-b269-5ef3fc9bb22f` existuje v SOLR-u, ale ve Fedoře ne, po kontrole @kenji1322 zjistil, že jde o duplicitu

Taky by stálo za zvážení zkontrolovat SOLR na další takové záznamy.

Edit:
další takové záznamy, na které někdo pokoušel přistoupit:
`uuid:f33be040-5aee-11e2-bcaf-005056827e52`
`uuid:fdff74b0-1a06-11e3-b79f-5ef3fc9bb22f`
`uuid:91b49e81-19e7-11e3-b79f-5ef3fc9bb22f`

**Comment by kazooo** [comment]
Kontrola Solru doběhla, celkem je 449012 špatných záznamů. Dále spustím kontrolu duplicit, a všechny duplicity odmažu. Z toho co zůstane udělám seznam s id kořenů (pokud je) a všemi id špatných záznamu, které tem kořenům patří, aby všechno bylo dohromady.

**Comment by jkremlacek** [comment]
Neodmazaly se i záznamy, které měly protikus ve fedoře poškozený?

uuid:ba95c027-153e-4b98-9913-7725d04b2bdb ještě 26.června šlo v krameriu/digitalní knihovně načíst a teď ne...

Namátkově jsem zkusil další UUID z https://github.com/moravianlibrary/kramerius/issues/267 (první post) a taky nejdou už zobrazit.

**Comment by kazooo** [comment]
Když dokument má poškozené údaje ve Fedoře (které mají vliv na index) a někdo ho zreindexuje, tak zmizné z Krameria a Solru, do té doby ještě může byt v indexu a zobrazovat se.
Ale špatné cesty k obrázkam nemůžou to ovlivnit, index nedrží žadné info o tom (max. mime type imagu).

uuid:ba95c027-153e-4b98-9913-7725d04b2bdb opravdu nebyl v Solru, jen ve Fedoře, to jsem reindexoval, proběhlo to bez chyb a už jde ho otevřit, ale nemá to obrázky...

V seznamu jsou jenom dokumenty, které ve Fedoře nemají nic (a nejsou tam ani UUID z issue 267), takže to co je poškozeno neodmažu.

**Comment by kazooo** [comment]
Příkladám seznamy neexistujících dokumentů:
 - [duplicity.txt](https://github.com/moravianlibrary/kramerius/files/2662828/duplicity.txt)
   Kopie dokumentů, struktura:
    - root_title kořene (uuid kořene)
           uuid kopie -> uuid originálu (model kopie, % shody podle parametrů, % shody textu)
 - [not_deleted_residue.txt](https://github.com/moravianlibrary/kramerius/files/2662864/not_deleted_residue.txt)
  Zbytky vymazaných ze Solru dokumentů, struktura:
    - root_title vymazaného kořene (uuid kořene)
      uuid siroty (model)
 - [deleted_parts.txt](https://github.com/moravianlibrary/kramerius/files/2662890/deleted_parts.txt)
  Vymazané z Fedory části existujících dokumentů, struktura:
     - root_title existujícího kořene (uuid kořene)
       uuid vymazané části (model)

Dále vymažu duplicity, zkontroluju vymazané kořeny jde-li o duplicity celých dokumentů, a zkontroluju kořeny s třetího seznamu, některé z nich jsem viděl rozbité.

**Comment by LenkaKravecova** [comment]
Ten třetí seznam jsme řešili s Alexem přes mail. Co šlo, tak jsem nahlásila na reimport z LTP.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
