### ISSUE TITLE
Nelze spustit Administrace virt. sbírek

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#281]
Týká se to kramerius.mzk.cz.. Je tam "Prosím počkejte.." a po několika hodinách se nic nestane.

**Comment by jkremlacek** [comment]
Čekání na kramerius.mzk.cz nad 1 minutu je zbytečné, ty dotazy se automaticky ukončují, pokud se do jedné minuty nedokončí.

Žádné chyby na hlavním krameriovi nejsou, pouze je vysoká zátěž na databázi - musíme zjistit proč. (alternativou je, že něco někde zamrzlo a brzdí to provoz)

Prozatím je kdyžtak možné k administraci VS přistoupit skrze kramerius.infra.mzk.cz, tam se načte za (hrozných) 5,5 minuty.

Pomalý dotaz v rámci načítání je:
`http://kramerius.infra.mzk.cz/search/inc/admin/_collection_actions_content.jsp?_=1538388965178`

**Comment by LenkaKravecova** [comment]
Já vím, že infra je "ok", ale ráda bych, aby to šlo i na "běžném" Krameriovi, protože do toho bude zasahovat víc lidí pod svými účty.. Probereme to na poradě, kdo se na to může podívat.

**Comment by jkremlacek** [comment]
Po nočním updatu serverů trval dotaz (i opakovaně) do administrace VS podstatně rychleji (těžko říct proč):

Klient: 71s, 88s, 85s, 83s
API: 81s, 69s, 81s, 78s

**Comment by LenkaKravecova** [comment]
A co když se zruší ten timeout?

**Comment by jkremlacek** [comment]
Založeno issue na master-u https://github.com/ceskaexpedice/kramerius/issues/621

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
