### ISSUE TITLE
Obálky knih - u některých dokumentů se neuplatní filtr pro zveřejnění

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#282]
V Krameriu je nastavený filtr obálek a obsahů, který by měl umožnit prohlížení obálek a obsahů, i když jde o neveřejný dokument. Ale u těch, co jsme v poslední době zneveřejnili (ze set public nastavili na set private), to zveřejnění obálek nefunguje. V dokumentu jako takovém se viditelnost neupravuje, měl by to dělat ten filtr.. Co s tím může být?
Týká se to např. Dvanácti pohádek http://www.digitalniknihovna.cz/mzk/view/uuid:e044d220-b0c1-4f15-95a0-0fd86747cc24

**Comment by LenkaKravecova** [comment]
Pro zajímavost, teď jsem zkušebně zrušila ten filtr obálek a obsahů a znovu ho nastavila a žádná změna nenastala. Data, která jsme změnili (třeba těch Dvanáct pohádek), na ten filtr pořád nereagují. Na ostatní data to funguje standardně.. 
Tak kdo se hlásí, že se na to podívá?

**Comment by LenkaKravecova** [comment]
Jinak ani na infra to nefunguje, jak má :) Dvanáct pohádek odolává i tam..

**Comment by kazooo** [comment]
Filtr umožňuje prohlížení obálek a obsahů pro ty stránky, které mají v MODSu element "mods:part" typu "FrontCover", "TableOfContents", "FrontJacket". Obálky z "Dvanáct pohádek" mají v MODSu typ "jacket", proto prohlížení nefunguje jak má. @LenkaKravecova máš nejaký seznam s uuid dokumetů, u kterých to nefunguje?

**Comment by LenkaKravecova** [comment]
Jo, aha, tak to bude problém u starších dat. Nová data by měla mít v popisu "frontcover" a "frontjacket". Nedá se do toho filtru teda přidat i "jacket"? Seznam bohužel nemáme.

**Comment by kazooo** [comment]
Dá se, ale je to oprava kódu a bude potřeba updatovat minimálně ty Krameria, ve kterých chceme takové obálky vidět.

**Comment by LenkaKravecova** [comment]
To nevadí. Jde zejména o produkčního Krameria.

**Comment by kazooo** [comment]
Dobře, opravím to, možna znáš jaké by mohly byt ještě typy, abych to dal pohromadě?

**Comment by LenkaKravecova** [comment]
Obecně se dávalo "jacket", teď se dává "frontjacket" nebo to "frontcover". Myslím, že další typy pro označení začátku knihy už nejsou.

**Comment by zabak** [comment]
Pak to prosím pošli i do upstreamu.

**Comment by kazooo** [comment]
Změna je na produkci a upstreamu.
