### ISSUE TITLE
Pohyblivá zeď do r. 1900 - zpřístupní i novější dokumenty

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#283]
Mám tu ještě jednu věc.. Někdo se musí podívat na funkci Pohyblivá zeď v nastavení Krameria. Jde o tu pohyblivou zeď, která zpřístupní i neveřejné dokumenty podle určitých kritérií (bez změny příznaku viditelnosti). V Krameriu by měla být nastavena na dokumenty, které mají rok vydání do 1900 včetně. Ale teď jsme si všimli, že zpřístupní i novější dokumenty, třeba uuid:695d35c0-9a10-11e7-920d-005056827e51 (1903), což je špatně. Takže je to něco v nastavení té pohybl. zdi.. 
Kdo se hlásí?

**Comment by hlavacekrene** [comment]
Vyreseno. Pohybliva zed nastavena do roku 1900.

**Comment by LenkaKravecova** [comment]
Pohyblivá zeď měla nastavenou hodnotu 114 (let od vydání), teď to bylo upraveno na 118, takže je to vyřešeno. 
Jinak dle @hlavacekrene:
databaze kramerius:
tabulka - criterium_param_entity - tady je ulozena hodnota, v nasem pripade ted cislo 118.
a s ni jsou svazane dalsi tabulky right_entity, rights_criterium_entity
