### ISSUE TITLE
Změna viditelnosti - u některých dokumentů neprojde

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#284]
Jde o občasný problém. U některých dokumentů skončí proces změny viditelnosti s chybou a to i při opětovném pokusu. Dělá to v instalacích kramerius nebo krameriusadmin. Na krameriu infra ten problém není.. Maroš už se na to dřív díval, tak to svěřím jemu. Díky..
Dnes se mi to stalo u uuid:9c27c230-22af-11e4-a8ab-001018b5eb5c, zveřejnila jsem to na infra.

**Comment by LenkaKravecova** [comment]
Další - uuid:1ad9c320-8be5-11e7-927c-001018b5eb5c, pro příklad nezveřejňuju na infra.

**Comment by kazooo** [comment]
U uuid:9c27c230-22af-11e4-a8ab-001018b5eb5c předpokladám, že to bylo spojeno s indexací geo. názvu, která zasahla do prod. Krameria a bylo opraveno v 3231c90, jinak podle logů změna viditelnosti spadla na chybě SOLRu. Kramerius infra to neměl, proto šlo zveřejnit tam.

**Comment by LenkaKravecova** [comment]
@xermak00 Podíváš se, prosím tě, i na tohle uuid:1ad9c320-8be5-11e7-927c-001018b5eb5c? Tam je kořen zveřejněný, ale nechtějí se zveřejnit i ty svazky (monographunit).

**Comment by kazooo** [comment]
Indexace geo. názvu byla opravena na začátku listopadu, do té doby změna viditelnosti nešla u některých dokumentu. U uuid:1ad9c320-8be5-11e7-927c-001018b5eb5c měnila se viditelnost 16/10/2018 a skončila s chybou v Solru. Dneska jsem znovu zveřejnil a všechno proběhlo bez chyb a v Solru je to ted' take public.
