### ISSUE TITLE
Import chybějících ročníků/čísel Volksfreund

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#285]
Jde o tato čísla/ročníky, data jsou u mě:
1921 - č. 98-296
1932 - č. 11-308, 5 příloh
1933 - celý ročník, čísla 1-305
1937 - č. 58-307

**Comment by LenkaKravecova** [comment]
Potřebuji někomu ta data předat, takže to dávám na @hlavacekrene a posílám mu skeny :) Kdo to pak udělá, je na dohodě. Díky.

**Comment by hlavacekrene** [comment]
Vyřešeno - 2019-05-17

**Comment by MarosGrm** [comment]
Pri týchto ročníkoch bude ešte treba zmeniť Datastream MIME type z image/jp2 na image/jpeg aby to bolo konzistetné s ostatnými stránkami, síce sa obrázky zobrazujú v poriadku, ale v budúcnosti by to mohlo spôsobiť problémy (napr. pri migrácii). V Krameriovy to spôsobuje, že týmto stranám chyba ikonka obrázku.
![Výběr_022](https://user-images.githubusercontent.com/16135340/58313599-3e37d880-7e0e-11e9-84e3-e968071207d1.png)

**Comment by annie-cz** [comment]
@hlavacekrene Ahoj, dořeš to ještě prosím.

**Comment by hlavacekrene** [comment]
prepsano z image/jp2 na image/jpeg  -  vyreseno.
