### ISSUE TITLE
Chybějící obrázky původem z NDK

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#286]
`uuid:05231380-834f-11e8-bb44-5ef3fc9ae867` nemá obrázky a potažmo celý nadřazený objekt `uuid:e2c27920-4866-11e8-afec-005056827e51` 

na IS na cestě:  `/storage/ndk04/2018/07/e2c27920-4866-11e8-afec-005056827e51` nejsou žádné skeny

**Comment by MarosGrm** [comment]
Pardon, ze sa k tomu vyjadrujem az teraz. Import prebehol v poriadku a v NK su obrazky vidiet, takze data by mali byt tiez ok. Bud sa nejako tie obrazky zmazali zo servra, alebo nastala chyba pri kopirovani dat z WF. V kazdom pripade bude treba reimport z LTP.

**Comment by LenkaKravecova** [comment]
Nahlásím na reimport.

**Comment by marketakrutska** [comment]
V LTP už reimportovali.
