### ISSUE TITLE
Nefunkční administrace popisů a obrázků ve virtuálních sbírkách

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#287]
Sbírku lze založit a vkládat do ní dokumenty, nelze ji ale dále editovat, co se týče popisů (změna se neuloží, pouze donekonečna běží "prosím vyčkejte") ani obrázků (nelze ani nahrát, nedojde to ani do fáze vyčkávání). Odpovídá pravděpodobně již uzavřenému issue #234

**Comment by LenkaKravecova** [comment]
@xermak00 můžeš se na to podívat? Minule jsi to taky řešil ty. Díky moc!

**Comment by annie-cz** [comment]
Nevím, jestli s tím někdo něco už dělal, ale teď se mi podařilo úspěšně nahrát jak popisy, tak obrázky. Nicméně je hodně zvláštní, že to dva dny nejde (nahrávala jsem např. obrázky pokusně přes noc a neprošlo to) a pak to zázračně najednou projde.

**Comment by jkremlacek** [comment]
Ta chyba byla v seznamu virtuálních sbírek, kde se Kramerius pokoušel načítat neexistující sbírku `vc:7252befa-0e8c-4875-af64-882b6ed328ef` ve Fedoře (viz gitter), která se do našeho SOLRu zavlekla nejspíš s nějakým importem.

Řešil jsem to s Martinem a ten problém byl dříve i u replikací https://github.com/ceskaexpedice/kramerius/issues/495, kde se to opravilo, ale nejspíš se ta oprava nedotkla importu FOXML, takže to budeme muset otestovat a pokud se to potvrdí, tak dát issue/udělat opravu, aby se to nedělo.

**Comment by annie-cz** [comment]
Zajímavé. Každopádně update: do čtvrtka to nefungovalo, v pátek to zas jelo v pořádku, dneska to nejede znovu.

**Comment by jkremlacek** [comment]
Při importu foxml, které obsahuje odkaz na neexistující virtuální sbírku, k zaindexování do solru nedojde vůbec, protože proces reindexu padne. Do fedory se dostane foxml včetně odkazu na neexistující virtuální sbírku. Pro tento problém jsem založil issue: https://github.com/ceskaexpedice/kramerius/issues/630

Náš problém na ostrém solru je ale jiného původu, protože ve fedoře odkaz není a v solru byl (než se ho @xermak00 zbavil spuštěním reindexu na dotčených dokumentech).

**Comment by jkremlacek** [comment]
Co se týče chyby editace, tak chyba nastane okamžitě, server vrací chybový kód 500 a chybovou hlášku:
https://gist.github.com/jkremlacek/c3e6a8d8c42f26917cf8ccf82ed9ab8b 

Chyba je v tom, že není nalezen dočasný soubor virtuální sbírky, proč se to děje ale zatím nevím.

Edit:
- Na **kramerius.infra.mzk.cz** se to děje, protože server nemá sdílené úložiště se serverem fedory, takže si nejsou schopni předávat soubory. Pokud bychom tedy chtěli správu VS na infra, tak bude potřeba s Davidem domluvit propojení těch serverů (jen předem varuju, že sdílené úložiště nemá velkou rezervu, takže čím víc krameriu takto spojíme, tak tím větší bude riziko, že se ucpe - má potom za následek nefunkčnost generování pdf a jpg z krameria/digitalni knihovny, alternativou je zvětšit to místo, ale otázka jestli na to je kapacita a dost možná by to vyžadovalo zastavení všech našich služeb)

- Na **kramerius.mzk.cz** je to problém s timeout-em, kdy "normálně" ta operace trvá 2 minuty, v případě velké zátěže na serverech to ale může trvat déle a v případě překročení té časové hranice už uživatel nedostane zpětnou vazbu o dokončení operace a zůstane tam viset "prosím vyčkejte". (kontroloval jsem zátěž pátek, kdy to šlo, a ponděli, kdy to nešlo a rozdíl tam byl) - další zdroj této chyby může být ucpání sdíleného úložiště (viz popis u infra), ale k tomu za poslední týden nedošlo.

Jádro pudla zůstává stejné jako u https://github.com/moravianlibrary/kramerius/issues/281, MPT store je pomalý a náhrada za něj příjde až s K6.

**Comment by annie-cz** [comment]
Sbírky se nyní již editovat dají, je potřeba tu něco ještě dodělat nebo to můžeme zavřít?

**Comment by jkremlacek** [comment]
Na **kramerius.mzk.cz** / **krameriusadmin** se problém bude vracet v případě velké zátěže na Fedoře (a/nebo Solr-u), pokud se neupraví kód krameria, aby uměl pracovat s timeout-em (nebo se nenasadí K6/7).

Na **kramerius.infra** by se problém dít už neměl (na 90% nikdy), protože:
- bylo zařízené sdílené úložiště (share adresář) mezi Fedorou a Krameriem 
- timeout na kramerius.infra je dostatečně velký

---

Bez ohledu na změnu repozitáře v K6/7 bych ale doporučoval, aby se kód administrátorského rozhraní Krameria zlepšil tak, aby si uměl poradit s timeout-em serverové části. K5 se při timeout-u jenom zasekne, což zcela zjevně není správné řešení.

**Comment by annie-cz** [comment]
Díky moc Kubo, necháme tedy zatím otevřené.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
