### ISSUE TITLE
Export monografií pro SVKOS

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#288]
Prosím vyexportovat foxml a obrázky pro tato uuid:

uuid:96f32d60-5df8-11e5-b7d6-5ef3fc9bb22f
uuid:dce08210-5e12-11e3-bc9f-5ef3fc9bb22f
uuid:985eb7c0-088e-11e4-a61e-5ef3fc9bb22f
uuid:0531ca1c8ffb6e8bcec22c2c02e62efa
uuid:a2aa4030-f7d8-11e3-b4ad-005056827e51
uuid:966b3f20-5801-11e4-97e9-5ef3fc9bb22f
uuid:e863ca40-457d-11e4-a450-5ef3fc9bb22f
uuid:bdeb51f9051df1418ffd92c80f22077c
uuid:455877b0-751b-11e4-b2f6-005056827e51
uuid:066dc420-2815-11e6-b821-5ef3fc9bb22f
uuid:7971a800-676f-11e4-be62-005056825209
uuid:2e6a2720-580f-11e4-a6f0-5ef3fc9ae867
uuid:593eb5a0-ecb0-11e6-a8e7-001018b5eb5c
uuid:48b28a90-cf3b-11e7-80e7-5ef3fc9bb22f
uuid:fb6aec71-4082-11e1-ac09-0050569d679d
uuid:40d24740-2684-11e6-8145-5ef3fc9bb22f
uuid:8afb0840-f87f-11e4-8936-005056827e51
uuid:1b961010-d971-11e6-9964-005056825209 (pro nadrazenou uroven dvojsvazku)
uuid:2cc91f60-dbe9-11e6-9964-005056825209 (1. Dil)
uuid:3737a450-dbf6-11e6-9e7e-001018b5eb5c (2. Dil)

**Comment by jkremlacek** [comment]
Jen se ujistím, záměrně jde jen o první strany a ne o celé publikace? (vyjma poslednich 3 uuid) Nebo se má exportovat nadřazený objekt stránky?

**Comment by LenkaKravecova** [comment]
Achjo :( Jde o celé publikace. Ten seznam jsem nevytvářela já ;)
