### ISSUE TITLE
Statistiky Krameria - nelze spustit

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#289]
Už jsem asi trapná, ale nejdou spustit Statistiky v Krameriu. Na infra to naštěstí jde, ale tam to končí na tom, že např. prohlížených monografií za uplynulých 9 měsíců je 223 položek. Což neodpovídá realitě.. 
Takže další lahůdka.

**Comment by jkremlacek** [comment]
Ty statistiky by měly být pro daného klienta, takže čísla na kramerius.mzk.cz a kramerius.infra.mzk.cz budou rozdílné a 223 položek zobrazených na infra by sedět mohlo, protože na to chodíme jen občas my...

Proč to ale nejede kramerius.mzk.cz musím zjistit.

**Comment by LenkaKravecova** [comment]
Ajo, to je vlastně fakt :( No, tak v tom případě je modul Statistiky v Krameriu nefunkční.. Je potřeba zjistit, proč se nespouští..

**Comment by LenkaKravecova** [comment]
Vzpomínám si, že Statistiky blbly už dřív, ale myslím, že šly vždy spustit. Byl tam problém s timeoutem, že seznam dokumentů se nestihl vygenerovat. Víc by věděl @kenji1322

**Comment by jkremlacek** [comment]
Zkusil jsem se na to podívat a chyba je ve spojení s DB, kdy se to spojení zavře než dokončí činnost, takže tam bude nějaký work-around.

Každopádně ta chyba by se uživateli měla zobrazit a ne vyhodit jen prázdný report, takže jsem založil issue https://github.com/ceskaexpedice/kramerius/issues/633

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
