### ISSUE TITLE
Oprava data vydání čísla (Právo lidu)

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#29]
U čísla periodika uuid:f9aa748e-435d-11dd-b505-00145e5790ea (Právo lidu) nebyla provedena změna data vydání. Je tam 04.02.1898, ale správně je to 02.04.1898. Opravovala jsem to několikrát přes editor (přímo v MODS Origin, Part i v DC), ale zůstává tam stále to špatné datum.

**Comment by leiblix** [comment]
V DC je to dobře, ale v MODsu se to asi neuložilo. To bude chyba editoru, kouknu na to.

**Comment by leiblix** [comment]
Chyba editoru, bug https://github.com/moravianlibrary/MEditor/issues/14
