### ISSUE TITLE
Rašple - prázdný ročník 1917-1921

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#290]
V Rašpli je prázdný ročník 1917-1921 - to je nějaká chyba v datech?

**Comment by jkremlacek** [comment]
Jde o chybu v datech, už se to řeší, generoval jsem @LenkaKravecova seznam uuid, které jsou tímto dotčené:

[out_clean.txt](https://github.com/moravianlibrary/kramerius/files/2626929/out_clean.txt)

Edit: Jen pro upřesnění: Chyba je v tom, že chybí data ve Fedoře.V Solr-u jsou pozůstatky, dají se podle uuid ze seznamu najít.

**Comment by annie-cz** [comment]
Vím o tom a hlásila jsem to jako tiket LTP v Service Desku s žádostí o reimport (TI 7079, 13.10.). Pokud se to ale podaří vyřešit jinak, tiket stáhnu.

**Comment by annie-cz** [comment]
Problém stále trvá, otevírám, aby to sem někdo omylem nezadal znovu. Čeká se na LTP.

**Comment by indrakm** [comment]
jak to s tím vypadá

**Comment by MarosGrm** [comment]
Reimport periodík z LTP ešte stále nie je povolený. Reimportuje sa to po nasadení nového Krameria na importy z NDK, momentálne dokončujem posledné testy a bude sa to môcť nasadiť.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
