### ISSUE TITLE
krameriusndk.mzk.cz - přesměrování na dk

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#291]
NK má v Alephu ve svých záznamech odkazy typu http://krameriusndk.mzk.cz/search/handle/uuid:a4d30470-769a-11e2-abbe-005056827e51
mohli bychom zprovoznit přesměrování těchto záznamů na digitální knihovnu?

**Comment by annie-cz** [comment]
Přesměrování funguje, neděje se tak pouze, když si to otevřeme my v MZK síti.

**Comment by jkremlacek** [comment]
@zabak : je to tak jak popisuje @annie-cz vpořádku, nebo má přesměrování proběhnout na MZK síti?

**Comment by zabak** [comment]
Je ještě nějaký důvod to uvnitř MZK nepřesměrovávat? Na admin. rozhraní se dostaneme jinou cestou, API se to netýká, takže bychom to myslím přesměrovat mohli i uvnitř MZK - případně si to můžeme potvrdit na poradě.

**Comment by jkremlacek** [comment]
Mě žádný důvod nenapadá, snad jen pokud by potřeboval přístup @kenji1322 třeba kvůli nějakým skriptům obsluhujícím krameria pro NDK importy - pokud ne, tak tomu asi nic nebrání.

**Comment by MarosGrm** [comment]
Ja myslím, že sa to môže presmerovať aj v MZK sieti, neviem o ničom, kde by toto bolo potrebné pre importy z NDK.

**Comment by drobkova** [comment]
Přesměrování na digitální knihovnu už funguje i uvnitř MZK sítě (rekonfigurace v reverzní proxy).
