### ISSUE TITLE
Na bojišti slavkovském - s. 10

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#292]
Tento dokument uuid:13095456-3492-4204-af96-8f1828c70ff4 má jako první stranu č. 10. Nejde to seřadit pomocí funkce Sort. @xermak00 můžeš se podívat, jestli je problém v solru nebo příp. i ve Fedoře, a opravit to? Díky.

**Comment by LenkaKravecova** [comment]
Tak už je to seřazené. Dělal jsi s tím něco, @xermak00 ? :)

**Comment by kazooo** [comment]
@LenkaKravecova ano, metadata ve Fedoře u té knižky jsou v pořádku, ale v Solru byly špatné hodnoty položky **rels_ext_index** (podle které jde řázení při zobrazení v Krameriu) pro všechny stránky kromě č. 10. Stránka č. 10 měla ten index **10** ale ostatní byly číslované od **208** a proto 10-tá stránka vždy byla první. Takže reindex celé knižky opravil hodnoty u stránek a je to už seřazené.
