### ISSUE TITLE
Hromadné zveřejnění/zneveřejnění UUID

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#293]
Prosím o hromadné zveřejnění/zneveřejnění UUID viz seznam zde: https://docs.google.com/spreadsheets/d/1h3xvlQSbrLXgb8xafu0DwgNtulnkLspmLRWqVkk76Yo/edit?usp=sharing. Díky :)

**Comment by kazooo** [comment]
Zveřejněno a zneveřejněno :)
