### ISSUE TITLE
nedostupný OAI Provider

### ISSUE THREAD

**Issue by rzeh4n** [moravianlibrary/kramerius#294]
OAI-PMH Provider byl na https://kramerius.mzk.cz/oai/, teď vrací https://kramerius.mzk.cz/oai/?verb=Identify chybu. Vypadá to, jako by se při přechodu na novější solr zapomnělo na oai4solr.

**Comment by kazooo** [comment]
Podle autora OAI provideru, verze pro Solr 7.x se [neplanuje](https://github.com/IISH/oai4solr/issues/16), a bude potřeba vymyslet nějakou alternativu misto něj.

**Comment by annie-cz** [comment]
Již není aktuální, zavíráme.
