### ISSUE TITLE
Chybějící obrázky na imageserveru

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#295]
Vše pochází z NDK, v Imageserveru jsou pouze prázdné adresáře (jde o nadřazené objekty, ne o strany).

```
uuid:e2c27920-4866-11e8-afec-005056827e51
uuid:45808e80-6b0d-11e8-a583-005056827e51
uuid:4907fc20-4eb4-11e8-afec-005056827e51
uuid:7e026e40-6a95-11e8-828b-005056825209
uuid:ebf74df0-6a93-11e8-828b-005056825209
uuid:ad33a5a0-6a93-11e8-828b-005056825209
uuid:56a36920-626c-11e8-be96-005056827e52
uuid:ba9189b0-6a9d-11e8-943b-5ef3fc9ae867
uuid:84efa3a0-73c1-11e8-9588-5ef3fc9bb22f
uuid:28faa3e0-5433-11e8-9a44-005056827e52
uuid:a9b30820-4dfc-11e8-9a44-005056827e52
uuid:0c470c80-6a9e-11e8-943b-5ef3fc9ae867
uuid:1d6af3e0-6a95-11e8-828b-005056825209
uuid:ea9b7490-54f4-11e8-9a44-005056827e52
uuid:4d42a3e0-3bc1-11e8-8142-005056827e51
uuid:cf195a50-4dfd-11e8-afec-005056827e51
uuid:bb181150-789f-11e8-ad64-005056825209

uuid:748cee60-90df-11e8-bb44-5ef3fc9ae867
uuid:1ff760a0-90e0-11e8-bb44-5ef3fc9ae867
uuid:6da760c0-90e0-11e8-bb44-5ef3fc9ae867
uuid:268a3d90-90e3-11e8-bb44-5ef3fc9ae867
```

vše k nám bylo importováno v červenci a srpnu 2018. Kontroloval jsem i adresáře pro červen a září, ale tam k této chybě nedošlo.

**Comment by LenkaKravecova** [comment]
Ok, nahlásím vše na reimport z LTP.

**Comment by marketakrutska** [comment]
Reimport už proběhl. Vše je v pořádku.

**Comment by jkremlacek** [comment]
http://www.digitalniknihovna.cz/mzk/view/uuid:7e026e40-6a95-11e8-828b-005056825209?page=uuid:92b567d0-834e-11e8-be68-5ef3fc9bb22f stále odmítá zobrazit obrázky.

Edit: Je toho víc, co stále nejde:

uuid:ebf74df0-6a93-11e8-828b-005056825209
uuid:ad33a5a0-6a93-11e8-828b-005056825209
uuid:ba9189b0-6a9d-11e8-943b-5ef3fc9ae867
uuid:84efa3a0-73c1-11e8-9588-5ef3fc9bb22f
uuid:0c470c80-6a9e-11e8-943b-5ef3fc9ae867
uuid:1d6af3e0-6a95-11e8-828b-005056825209
uuid:bb181150-789f-11e8-ad64-005056825209
uuid:748cee60-90df-11e8-bb44-5ef3fc9ae867
uuid:1ff760a0-90e0-11e8-bb44-5ef3fc9ae867
uuid:6da760c0-90e0-11e8-bb44-5ef3fc9ae867
uuid:268a3d90-90e3-11e8-bb44-5ef3fc9ae867

**Comment by jkremlacek** [comment]
Zdá se, že reimport neproběhl podle očekávání u chyb v periodikách, monografie se opravily správně.

**Comment by marketakrutska** [comment]
Moc se omlouvám za zmatky. Všechny ty uuid, co jsi Kubo uvedl, ještě LTP nevyřídilo. Jak píšeš, jsou to všechno periodika.

**Comment by kazooo** [comment]
**Rovnost**: číslům ročníku 1957 také chybí obrázky
číslo 248: https://kramerius.mzk.cz/search/handle/uuid:ebf74df0-6a93-11e8-828b-005056825209
číslo 298: https://kramerius.mzk.cz/search/handle/uuid:ad33a5a0-6a93-11e8-828b-005056825209
číslo 269: https://kramerius.mzk.cz/search/handle/uuid:7e026e40-6a95-11e8-828b-005056825209
číslo 265: https://kramerius.mzk.cz/search/handle/uuid:1d6af3e0-6a95-11e8-828b-005056825209

**Comment by marketakrutska** [comment]
Díky za info, tahle 4 čísla ročníku 1957 do LTP na reimport poslala Lenka v lednu.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
