### ISSUE TITLE
Křesťanská revue - ročník 1982

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#296]
Jednotlivá čísla ročníku 1982 se chybně vřadily do ročníku 1929 uuid:5e14c500-b5be-11e3-b74a-5ef3fc9ae867. Obrázky tohoto ročníku nefungují a samotná úroveň ročníku se nevytvořila. Můžeme si to nějak opravit sami nebo je nutné to řešit přes LTP?

**Comment by jkremlacek** [comment]
Chybějící objekt ročníku nemáme jak vytvořit, takže minimálně musí proběhnout import toho objektu a potom už jsme schopni připojit čísla kam patří.

**Comment by LenkaKravecova** [comment]
Jeste otazka, co ty obrazky. Je problem pouze s odkazy nebo s obrazky jako takovymi?

**Comment by jkremlacek** [comment]
Tak je to projistotu ještě víc zamotané:

Ta čísla ročníku 82 nejsou vůbec ve fedoře (tj. ne jen obrázky ale komplet i jejich metadata chybí) a je to pouze v Solr-u, takže to bude potřeba reimportovat.

**Comment by kazooo** [comment]
Křesťanská revue je take v tom seznamu rozbitych casti, co jsem posilal pri reseni #278

**Comment by LenkaKravecova** [comment]
Oki, necham to reimportovat.

**Comment by marketakrutska** [comment]
Reimport z LTP proběhl v pořádku, Křesťanská revue je opravená.
