### ISSUE TITLE
(Nejen) Davidova houpačka - chybné řazení čísel v ročnících - Digitální knihovna vs. Kramerius

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#298]
V (nejen) periodiku Davidova houpačka je problém s řazením čísel v Digitální knihovně a to nezávisle na stavu v Krameriovi. Tam je to seřazené správně, nicméně Digitální knihovna si s tím neumí poradit a ani nový klient. Navazuje to na Petrovu žádost, abychom se začali podobnými problémy více zabývat. Pro porovnání:

https://krameriusadmin.mzk.cz/search/handle/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6
http://www.digitalniknihovna.cz/mzk/uuid/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6
http://kramerius.rychtar.cloud/mzk/uuid/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6

Další věc je, že nějaká data se zobrazují v kalendáři a některá ne. Zde to bude absencí přesných dat vydání jednotlivých čísel (v kalendáři a správně se zobrazuje jen ročník 1931, která ta data má), takže s tím asi nic neuděláme, nicméně by bylo dobré, aby se nám aspoň ta čísla řadila správně po sobě. Na některé takové dokumenty zabírá reindexace, zde bohužel ani to. 

Už jsme podobný problém hlásily s Lenkou Honzovi na web-clienta a na Ceskou expedici, viz https://github.com/ceskaexpedice/kramerius-web-client/issues/116, nicméně co myslíte, byli bychom schopni s tím udělat něco sami? Všimla jsem si totiž, že ty dvě čísla, kde se včera prohazovaly ty skeny (č. 1 a 9. v ročníku 1926), se totiž po dokončení v seznamu čísel v Digitální knihovně posunuly na jiné místo, tak to vypadá jako taková jiskřička naděje.

**Comment by annie-cz** [comment]
#297

**Comment by zabak** [comment]
Jako první krok bychom se měli naučit rozumět komunikaci mezi klientem a API, tj. vědět, na základě jakých údajů klient čísla řadí. Na základě toho se můžeme podívat co tam fakticky posíláme a to můžeme určitě ovlivnit. Kdo do toho pronikne?

**Comment by annie-cz** [comment]
@hlavacekrene podívej se na to prosím

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
