### ISSUE TITLE
Chyby v názvech s citáty při vyhledávání v Digitální knihovně

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#299]
Kniha "Zrcadlo kořalečníků, čili, "Likér de bluj", Kořalka pfuj!" se zobrazuje ve výsledku vyhledávání v Digitální knihovně s chybou v názvu. Totéž se děje i v novém klientovi.

http://www.digitalniknihovna.cz/mzk/uuid/uuid:b02c6577-5fbe-11e1-ae74-0050569d679d

![image](https://user-images.githubusercontent.com/43028501/51913726-789ce600-23d7-11e9-9b15-8ed8036eea34.png)
![image](https://user-images.githubusercontent.com/43028501/51913942-ff51c300-23d7-11e9-96fc-bb9809798ce6.png)

**Comment by annie-cz** [comment]
Chyba se objevuje i u dalších dokumentů, které mají v názvu nějaký citát. Např.:

Městská hudební škola "Dvořák" ve Zlíně
http://www.digitalniknihovna.cz/mzk/uuid/uuid:ab9d8c50-bbd4-11e8-9480-5ef3fc9ae867
![image](https://user-images.githubusercontent.com/43028501/51914641-9ff4b280-23d9-11e9-85e4-2c7ab44c0f89.png)

**Comment by kazooo** [comment]
Jsou to špatné zaindexovaná data, zreindexoval jsem obě knižky а názvy jsou opravené. Vytvořím seznam podobných dokumentů, a postupně je zreindexuju.

**EDIT**:
tady jsou uuid knižek, které mají zaindexované &quote a &apos
[quotes&apos.txt](https://github.com/moravianlibrary/kramerius/files/2812352/quotes.apos.txt)

**Comment by annie-cz** [comment]
Koukám, že se to týká i nejen dvojitých uvozovek ", ale i apostrovů ' ... viz: http://www.digitalniknihovna.cz/mzk/uuid/uuid:59e708b6-c462-4610-90c5-ac5ca030050a
![image](https://user-images.githubusercontent.com/43028501/51982434-4900e300-2496-11e9-87ac-18469465b0fc.png)

**Comment by zabak** [comment]
Stálo by za to otestovat i další podobné podezřelé znaky - &,# apod.

**Comment by annie-cz** [comment]
Tak SOLR má bezpečně problém se speciálními znaky. Ve výsledcích vyhledávání se zobrazují špatně i další znaky, např. < a >, viz:
http://www.digitalniknihovna.cz/mzk/uuid/uuid:85f191d0-e3e4-11e8-9984-005056825209
![image](https://user-images.githubusercontent.com/43028501/52056889-ce9e9480-2563-11e9-9f15-43ab3824011f.png)

**Comment by kazooo** [comment]
Příkladám seznam uuid kořenových dokumentů, kde se objevily takové chyby v názvech a jmenach autorů
[bad_chars.txt](https://github.com/moravianlibrary/kramerius/files/2821536/bad_chars.txt)

**Comment by kazooo** [comment]
Záznamy s chybami v názvech a jmenach autorů jsou opraveny, ale ty chyby mají také full text pole a to u ~16 mil. záznamů. Napsal jsem skript na opravu těch záznamů, který za pomoci částečného updatu dokaže všechno opravit relativně rychle (~0.5-0.7 mil. denně). Problem je, že při částečném updatu Solr označuje staré záznamy jako odmazané (nehledá mezi nimi, ale jsou stále na disku) a nahrazuje je novými, takže po opravě v Solru bude o ~16 mil. fizicky uložených záznamů víc, což zabere nějakých X Gb. Ted' velikost Solru je ~470 Gb a je tam ještě 0.7 Tb volných, ale pozor, ještě potřeba mit místo na optimalizace indexu (aby se zbavit vymazaných záznamů), "odmazané" záznamy mohou ten prostor zabrat. Popřemýšlím nad tím, jak by se to dalo řešit bezbolestně.

**Comment by zabak** [comment]
Ahoj, David říkal, že už by mělo být k dispozici SSD pole, takže doporučuju nejprve se s ním domluvit aby přidělil dostatek místa, přemístit index na ssd, pak spustit tento proces a pak optimalizaci indexu, vše už na SSD.

**Comment by kazooo** [comment]
Kopie produkčního indexu byla přenesena na SSD pole (volume 2 Tb), kde proběhla oprava dokumentů. Oprava běžela 3-4 dní, a konečně index наrůstl o ~180 Gb. Po optimalizaci (1 den) index zabira ~440 Gb. V prubehu optimalizaci Solr spotreboval ~74% volumu.

**Comment by kazooo** [comment]
Produkční index nyni běží na SSD pole s opravenými znaky.
