### ISSUE TITLE
Chybná hodnota atributu "type" v placeTerm v MODS

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#3]
Některé dokumenty v NDK Krameriovi mají chybně nastavenou hodnotu atributu "type" v subelementu placeTerm (originInfo) v MODS. Místo "code" je tam hodnota "text". Kramerius pak zobrazuje v místu vydání "xr" (kód země) a ne konkrétní místo. Potřeba opravit v MZK Krameriovi, když replikujeme něco z Krameria NDK. Oprava v NDK Krameriovi bude muset jít přes LTP v Praze?

**Comment by zabak** [comment]
Jo, ale hlavně prosím zjisti proč to vzniká, bude potřeba odstranit chybu už ve workflow - pokud teda už odstraněna nebyla a tohle nejsou jen pozůstatky.

P.

**Comment by Jenyk** [comment]
Zobrazování opraveno v xsl šabloně (po vzoru NK), ale pořád je potřeba odstanit chybu v TM a v datech.

**Comment by leiblix** [comment]
Budeme to teda nějak předávat dál? Kdy to budeme moci zavřít?

**Comment by LenkaKravecova** [comment]
Info z NK: metadata se v LTP opravovat nebudou, protože jde o velké množství dat, v kterých se ta chyba vyskytuje (prý to několikrát reklamovali Incadu, ti to opravili, ale pak s další aktualizací konverzní šablony se to tam zase vyskytlo). Bude se to řešit jen správným zobrazením v Krameriu. Tak je na nás, jestli si to v našem Krameriu budeme chtít opravit. V NDK to můžeme nechat, ale stejně vznikne nekonzistentnost mezi našimi metadaty a těmi v LTP.

**Comment by leiblix** [comment]
Vyřešeno pomocí upravené XSL šablony.
