### ISSUE TITLE
"null" v root_title

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#30]
Spousta dokumentu (resp. jejich stranek) ma v SOLR root_title=null
root_title je potreba pri fulltextovem vyhledavani.
Napr. http://localhost/kramerius/#/mzk/search/?q=slun%C3%A9%C4%8Dko
Prvni vysledek je cela monografie, kde se retezec "slunéčko" nasel v nazvu. 
Dal nasleduji vysledky ve fulltextu, hned prvni je znova ta sama monografie, ale nazev je "null", protoze se prebira ze stranky z root_title. Kdyz zascrollujete niz, tak je tam spousta dalsich vysledku s "null"
Klient od INCADU se chova stejne - http://kramerius.mzk.cz/client/index.vm?q=slun%C3%A9%C4%8Dko&page=search&start=&rows=

"null" potom samozrejme nahradim bud prazdnym retezcem nebo necim pochopitelnym, ale jde o chybu v datech a mela by se opravit v datech, ne na urovni prezentace (kde to stejne opravit nepujde, muzu jen skryt skaredy nazev "null")

Priklad. http://kramerius.mzk.cz/search/api/v5.0/search?q=PID:%22uuid:a56d5e12-e7ec-43ca-acfa-1dbe12e47de5%22

**Comment by LenkaKravecova** [comment]
Opravili to: ceskaexpedice#298 Budem muset aktualizovat našeho Krameria a reindexovat vše, čeho se to týká. Týká se to bohužel i Lidovek (u těch se teď vytváří ALTO soubory a během dvou týdnů se udělala tak pětina, takže to bude ještě na dlouho..).

**Comment by leiblix** [comment]
seznam se špatnými dokumenty je zde (od Honzy) https://www.dropbox.com/s/5102iqtcb4thfm4/root_title_null.txt

a něco je špatně, i s novou verzí po reindexaci tam asi null zůstává
zkoušel jsem http://kramerius.mzk.cz/search/api/v5.0/item/uuid:15e77643-02e7-4a43-9e7e-d04b8a30c246

**Comment by Jenyk** [comment]
Ten link vypadá ok

**Comment by leiblix** [comment]
@Jenyk Už vím proč se to neprojevilo hned, v API používají třídu SolrMemoization, která funguje jako cache pro dotazy do SOLRu.

**Comment by Jenyk** [comment]
Opraveno až na Lidové noviny (ty se budou indexovat až časem, indexace trvá moc dlouho)

Kontrola: http://kramerius.mzk.cz/search/api/v5.0/search?fl=root_pid&q=root_title:%22null%22&group=true&group.field=root_pid&group.ngroups=true
