### ISSUE TITLE
Hromadné zveřejnění dokumentů vydaných do roku 1900

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#300]
Prosím o hromadné zveřejnění všech dokumentů, které byly vydány do roku 1900 (včetně). V Krameriovi je momentálně přes 600 takových dokumentů, ve většině případů se jedná o data z Národní knihovny a dokumenty s daty vydání v hranatých závorkách. Díky!

**Comment by LenkaKravecova** [comment]
@xermak00 Už je to zveřejněno, že? Ještě tam byly ty chybky v datu vydání v solru, že některé dokumenty se zobrazovaly mezi starými, i když byly novější.

**Comment by kazooo** [comment]
Ano, je to už zveřejněno, chyby byly opraveny, ale zobrazují se periodika u kterých rok vydání 18xx - 19xx, ale mají privatní ročníky z roků 1901 a novější.

**Comment by kazooo** [comment]
Kromě novějších ročníků vše je zveřejněno.
