### ISSUE TITLE
Import zbylých grafik do Krameria

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#301]
Na imageserveru se stále nachází grafiky, které nejsou v Krameriu, např. tyto https://vufind.mzk.cz/Search/Results?lookfor=richter%2C+franti%C5%A1ek&type=Author&filter%5B%5D=format%3A%22Photo%22&filter%5B%5D=statuses%3A%22available_online%22

Chceme je mít v Krameriu komplet. Postup bude následující:
1) Zjistit, co z Alephu stále odkazuje na imageserver.
2) Prověřit, zda to opravdu není v Krameriu.
3) Postupovat dle tohoto zavřeného issue (kroky 1-5, co psal M. Rumánek) - https://github.com/moravianlibrary/kramerius/issues/41

**Comment by annie-cz** [comment]
@hlavacekrene mrkni na to prosím :)

**Comment by zabak** [comment]
Ty grafiky byly v minulosti zpřístupněné z https://mapy.mzk.cz/ostatni-sbirky-v-mzk/
Na serveru jsou pořád html stránky s odkazy na jednotlivé mapy. Ale proto, že došlo k nějakým změnám linků, tak nejsou viditelné, @zafan ti ale může ukázat kde je najdeš.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
