### ISSUE TITLE
Chyby v názvu místa uložení

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#302]
http://kramerius.rychtar.cloud/mzk/browse?sort=alphabetical&category=locations
první dvě položky jsou sigly místo názvu knihovny, celkem 4 dokumenty - mají siglu místo místa, navíc ty se siglou ABD065 mají ve skutečnosti signaturu MZK, takže jde asi o nějakou chybu. Zároveň navrhuji opravit 19x Moravská zemská knihovna - Pedagogická knihovna na
Moravská zemská knihovna v Brně

**Comment by LenkaKravecova** [comment]
To vypadá na stará MZK data, co prošla Meditorem (dívala jsem se na pár), opraví se přímo ve Fedoře.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
