### ISSUE TITLE
Viditelnost neveřejných PDF v klientech

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#303]
U jednoho PDF (uuid:7f0f5c57-2e62-4033-b439-76e47636a223) nastala nekonzistence viditelnosti.
Fedora, Solr a Kramerius dokument označovaly jako private. Zobrazení v digitální knihovně se chovalo jako u neveřejného dokumentu, nicméně v klientech krameria (novém i starém) se PDF zobrazilo.

Po spuštění procesu na nastavení private a reindexaci se už PDF nezobrazí na žádném z klientů, nicméně klient digitální knihovny (černý) byl schopen tuto chybu maskovat, proto by bylo vhodné zjistit odkud tahal nastavení viditelnosti starý a nový klient. 

@honza-rychtar mohl bych poprosit o další info ohledně čerpání informace o viditelnosti v klientovi digitalni knihovny a novem klientovi?

**Comment by annie-cz** [comment]
Našla jsem podobnou nekonzistenci a to u monografie Amerika, kulturní obrázky z Ameriky severní, uuid:aef5bcc0-42de-11e3-ad8c-005056827e52.

https://krameriusadmin.mzk.cz/search/handle/uuid:aef5bcc0-42de-11e3-ad8c-005056827e52
http://www.digitalniknihovna.cz/mzk/uuid/uuid:a318feb0-88d6-11e3-bbb0-5ef3fc9bb22f
http://localhost:4200/mzk/uuid/uuid:a417aa00-88d6-11e3-bbb0-5ef3fc9bb22f

Kramerius to zobrazuje jako veřejné (což je správně) a Digitální knihovna a nový klient to zobrazují jako zavřené.

@honza-rychtar Honzo prosím tě, kde může být chyba?

**Comment by honza-rychtar** [comment]
Pro zobrazení zámečků a fitrování podle dostupnosti používá klient pole **dostupnost** ze _solru_.
Zobrazení varování o neveřejnosti dokumentu se dělá pak na základě status kódu, který vrátí Kramerius při requestu na určitou stránku - konkrétně u dlaždic při requestu na _ImageProperties.xml_. Pokud vrátí **403**, tak se zobrazí varování o neveřejnosti.

Nekonzistence můžou být buď v tom, že celý dokument má jiný příznak dostupnosti než jeho stránky a nebo tím, že příznak **dostupnost** v solru neodpovídá příznaku **policy** v _resl-ext_ vazbě, podle čehož se (myslím) rohoduje Kramerius.

**Comment by natal1H** [comment]
Bola vykonaná kontrola všetkých dokumentov, pri ktorej sa kontrolovali nezhody v poliach dostupnost zo solr a policy v rels-ext. Dokumenty, ktoré obsahovali takéto nekonzistentnosti boli zreindexované, čim sa do poľa dostupnost priradila hodnota z poľa policy a dokumenty sa už zobrazujú rovnako v Krameriovi aj v digitální knihovně.
