### ISSUE TITLE
Zobrazení ročníků a čísel v novém klientovi - mřížka nebo kalendář? 

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#304]
V MZK teď probíhá diskuze nad tím, zda při zobrazení ročníků a čísel defaultně zobrazovat mřížku nebo kalendář. Momentálně se zobrazí kalendář a dá se to změnit na mřížku. S Martinou se přikláníme k tomu jako výchozí dát mřížku (zobrazí se hezky obálky s datem vydání a číslem ročníku/čísla) s tím, že do kalendáře si to může každý přepnout sám. Ten kalendář nebo výpis roků (v případě ročníku) více lidem prostě přijde neintuitivní.

Např. Země světa - http://digitalniknihovnanew.mzk.cz/mzk/periodical/uuid:e55fb7c0-711a-11e2-b9fa-005056827e52 (mřížka a kalendář se přepínají vpravo nahoře nad kartami/kalendářem) 

Dle issue https://github.com/ceskaexpedice/kramerius-web-client/issues/46 by toto mělo být konfigurovatelné jak pro ročníky, tak pro čísla.

**Comment by annie-cz** [comment]
Z pohledu uživatelského mi ty obálky připadají i lepší z důvodu atraktivity. Uživatel si z principu raději otevře k přečtení nějakou zajímavou obálku, než aby klikal na náhodná čísla v kalendáři a pak byl příjemně překvapen, že to vypadá zajímavě.

**Comment by erikamirova** [comment]
Já jsem taky pro mřížky. Vypadá to líp.

**Comment by indrakm** [comment]
já jsem taky pro mřížku

**Comment by kazooo** [comment]
Taky pro mřížku, je nej :+1:

**Comment by LenkaKravecova** [comment]
Díky za reakce. Teď už jen to chce dobrovolníka, který to nastaví na mřížku :)

**Comment by jkremlacek** [comment]
Přehodil jsem to (stránka si ale pamatuje poslední volbu, takže pokud to chcete vidět ve výchozí podobě, tak je potřeba použít anonymní režim internetového prohlížeče).

**Comment by LenkaKravecova** [comment]
No, já nevím. Mám tam stále výchozí kalendář i v anonymním režimu.

**Comment by jkremlacek** [comment]
Otázka jestli se to nechová různě na rozdílných periodikách...

http://digitalniknihovnanew.mzk.cz/mzk/periodical/uuid:e55fb7c0-711a-11e2-b9fa-005056827e52 se načetlo mě i @zafan s mřížkou

**Comment by LenkaKravecova** [comment]
To je právě možné, ale ta konfigurace by to měla přebít, ať už jde o jakákoliv data. Měla by se tam vždy zobrazit mřížka.

**Comment by jkremlacek** [comment]
pak se to asi neděje a bude to potřeba řešit u čeho to nejde, protože to periodikum se už díky té konfiguraci zobrazuje s mřížkou, což předtím nedělalo.

**Comment by LenkaKravecova** [comment]
Dobře, tak třeba Rovnost 1915 (a jiné ročníky) - http://www.digitalniknihovna.cz/mzk/periodical/uuid:92d81c71-69ab-4352-af05-57ecf2e1d288

**Comment by jkremlacek** [comment]
Tak šlo o oddělenou konfiguraci pro čísla, nicméně jako vedlejší efekt je citelně pomalejší načítání, protože těch čísel je řádově víc než ročníků... chce to tedy ještě zvážit jestli hezká prezentace stojí za čekání.

Edit: Za mě je na úrovni seznamu ročníků mřížka smysluplná, na úrovni seznamu čísel už ne (kde je až nepříjemná - musím čekat a ke konkrétnímu číslu se musím prokousávat dlouhým seznamem).

**Comment by LenkaKravecova** [comment]
Hm, nevím, co dělám špatně, ale já u některých ročníků furt vidím kalendář. 

Jinak právě na úrovni čísel byla mřížka žádaná.. Zatím bych to nechala tak, že to za to čekání stojí. Uvidíme, jestli si někdo bude stěžovat. Ještě teda, aby se  ta mřížka opravdu zobrazovala jako první. Nevím, jak bych lidem vysvětlovala, že si to musí zapnout v anonymním režimu (mně to teda nejde ani v něm).

**Comment by LenkaKravecova** [comment]
No, tak jsem si pohrála s prohlížečem a už to jde. Nevím, co to zas bylo :D Rychlost mi přijde v pohodě.. Takže to máme hotovo. Díky moc.
