### ISSUE TITLE
Časová osa v Krameriu - divné chování při zadávání roků

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#305]
Mám tu divné chování Krameria, nejspíš jde o bug. Když si např. vyhledám dokumenty podle autora a pak na časové ose zadám do kolonky "do" nějaký rok vydání a pak to chci upravit, tak tam zůstane určitý rok, který už pak nejde přenastavit, ani kalendář další roky nenabízí.

Např. https://krameriusadmin.mzk.cz/search/r.jsp?forProfile=dateaxis&forProfile_sorting_dir=&debug=&sort=&q=&issn=&title=&keywords=&author=bass&rok=&udc=&ddc=&shelfLocator=&physicalLocation=&offset=0&da_od=01.01.1910&da_do=31.12.1950&exactDay=false
Chci zadat čas do roku 31.12.1970, ale furt v té časové ose mám rok 31.12.1949 a nenabízí mi to pozdější roky. Když to v té kolonce "do" přepíšu ručně, tak se to zase vrátí na 1949. Jde to změnit přímo v url, pak to funguje, ale v té kolonce v časové ose by to mělo jít taky nastavit.

Tu časovou osu ještě poměrně často používají praktikanti nebo další pracovníci, kteří dělají kontrolu autorských práv. Můžete se na to někdo podívat?

**Comment by LenkaKravecova** [comment]
Jo a špatné je, že se kvůli tomu nepřenastavitelnému roku vyhledá méně dokumentů. Neinformovaný člověk to bude pokládat za kompletní výsledek, ale kompletní to opravdu není. V případě toho odkazu nahoře, když to změním v url na rok 1970, tak se mi vyhledá o 25 knížek víc. 
Poprosila bych Alexe, aby na to mrkl.

**Comment by jkremlacek** [comment]
Ta úprava filtru je spíš rozšíření funkcionality než bug.  Osa se přizpůsobuje výsledkům filtrů, a umožňuje dál omezovat ty výsledky. 

Pokud by osa měla umožňovat úpravu filtru, tak by se rozhraní muselo přepracovat (klient totiž neví jaký je plný rozsah vyhovujících dat výsledku za předpokladu, že ignorujeme "datumový" filtr).

Je tu možnost odebrat to přepisování roku v případě, že ho uživatel "natvrdo" ručně zadá do pole, akorát nemá jistotu, že vybral dostatečně velký interval, aby v něm bylo "vše".

**Comment by kazooo** [comment]
Kramerius funguje tak, že při vyhledávání načítá ze Solru facety s roky a kolik daným rokům patří požadovaných dokumentů, ve tvaru:
```
...
<int name='2016'>60<int>
<int name='2017'>30<int>
...
```

Při dotazu Kramerius nastavuje parametr facet.rok.mincount=0, který říká Solru, aby ten vracel i roky, které nemají žadný dokument, specifikovány dotazem. Například, když položím dotaz na dokumenty v intevalu od 1905 do 2000 roku, Kramerius nastaví facet.rok.mincount=0 a Solr vrátí seznam úplně všech roků:
```
<int name='1400'>0<int> # 0 dokumentů protože rok 1400 nepatří rozsahu 1905-2000
<int name='1401'>0<int>
...
<int name='1904'>0<int>
<int name='1905'>100<int>
<int name='1906'>200<int>
...
<int name='2000'>135<int>
<int name='2001'>0<int>
...
```
Dale Kramerius zparsuje odpoved' a uloží všechny ty roky do kalendáře, proto pak po vyhledávání můžeme (resp. mohli) nastavit i jiný interval. V našem případě problém je na straně Solra.

Při migraci na Solr 7.5 byly změněné zastaralé datové typy na aktuální (Point based). Na ty Point-based datové typy byla zmigrována všechna data z minulého Solru, a jak jsem zjistil pri řešení issue, ty datové typy nepodporují 0 jako hodnotu pole, na které aplikujeme facety. Při pokusu nastavit facet.rok.mincount (rok je Point-based) Solr zvyšuje hodnotu z 0 na 1 a vratí Krameriovi jen částečný seznam roků specifikovány dotazem. 27/10/2017 byl založen [request](https://issues.apache.org/jira/browse/SOLR-11174) na podporu facet.mincount=0 v Poin-based typech, ale zatím žadný progres.

**Comment by zabak** [comment]
@xermak00 jestli to chápu dobře, tak to co popisuješ je ještě jiná chyba, než kterou popisuje @LenkaKravecova - ta původní chyba je chyba UI - protože pokud to opravíš v URL, tak to funguje správně. Problém je tedy v tom, že se nedá do formuláře časové osy vyplnit jiný rok, když už jsem tam před tím nějaký zadal. To je bug, který by se opravit měl. Pak je tam další problém, který popisuješ ty, ale jestli to dobře chápu, tak ten se týká jen zobrazení na časové ose, ale nemá vliv na celkové výsledky hledání. Chápu to dobře?

**Comment by kazooo** [comment]
@zabak ano, přesně tak, co popisuju ja nemá vliv na vysledky, ale na kalendař v UI, který nedovoluje nastavit libovolný rok pokud nemá plný rozsah roků.

**Comment by zabak** [comment]
Aha. Dal by se udělat rychlý fix tak, že by se v tom formuláři úplně zrušila podmínka na kontrolu roků? Nebo by se tam dalo jen něco volného - např. minimum je větší než 1000 a maximum je menší než 2025?

Petr

**Comment by annie-cz** [comment]
Nerelevantní problém, v DK se problém již neprojevuje.
