### ISSUE TITLE
Chybějící typ stránky u rukopisů

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#307]
U některých rukopisů jsou všechny stránky jako NormalPage. Bylo by potřeba tyto rukopisy najít a opravit. Stránky jsou u nich číslované dle konvencí Manuscriptoria, takže se na základě "čísla" stránky dá doplnit i její typ - viz. - viz. https://github.com/ceskaexpedice/kramerius-web-client/issues/175
Poprosil jsem @pavluska aby se na to podívala, ale možná bude potřebovat, aby někdo pomohl ty problematické rukopisy nalézt, například tak, že jejich první strana je typu NormalPage a její číslo je FC.

**Comment by honza-rychtar** [comment]
26x FC + NormalPage - https://kramerius.mzk.cz/search/api/v5.0/search?q=details:FC*NormalPage&fl=root_title,details&rows=100
24x SP + NormalPage - https://kramerius.mzk.cz/search/api/v5.0/search?q=details:SP*NormalPage&fl=root_title,details&rows=100

**Comment by annie-cz** [comment]
Ahoj Petře, jak to prosím vypadá? Řeší toto Pavla, nebo máme do toho zapojit ještě někoho dalšího?

**Comment by zabak** [comment]
@pavluska Jak to vypadá? Co je potřeba udělat, aby se to pohnulo?

**Comment by honza-rychtar** [comment]
Rukopisů, jejichž první strana má název FC a typ strany NormalPage, je těchto 23
https://kramerius.mzk.cz/search/api/v5.0/search?q=model_path:manuscript/page%20AND%20rels_ext_index:0%20AND%20details:*NormalPage*%20AND%20dc.title:FC&fl=PID,root_title,root_pid&rows=100
Když vynecháme podmíniku, že je to první strana, pak jich je 25
https://kramerius.mzk.cz/search/api/v5.0/search?q=model_path:manuscript/page%20AND%20details:*NormalPage*%20AND%20dc.title:FC&fl=PID,root_title,root_pid&rows=100
Ty dvě navíc mají přední desky jako poslední stránku

Stejných (pravděpodobně, nekontroloval jsem) 25 má stránku s názvem FS a typ NormalPage.
24 z nich má stránku s názvem SP a typem NormalPage

**Comment by drobkova** [comment]
Opraveno přizpůsobením [skriptu ZmenaMetadat z K4-tools](https://github.com/moravianlibrary/K4-tools/blob/ecb389b9a0c87599a42612d16af4e3a64d9e3532/src/main/java/cz/mzk/k4/tools/scripts/ZmenaMetadat.java), všechny strany rukopisů, které měly název FC, FS, SP, BS nebo BC a typ strany NormalPage, by měly mít nyní příslušný typ ([https://kramerius.mzk.cz/search/api/v5.0/search?q=model_path:manuscript/page%20AND%20details:*NormalPage*%20AND%20dc.title:(FC%20OR%20FS%20OR%20SP%20OR%20BL%20OR%20BS%20OR%20BC)&fl=PID,root_title,root_pid&rows=100](https://kramerius.mzk.cz/search/api/v5.0/search?q=model_path:manuscript/page%20AND%20details:*NormalPage*%20AND%20dc.title:(FC%20OR%20FS%20OR%20SP%20OR%20BL%20OR%20BS%20OR%20BC)&fl=PID,root_title,root_pid&rows=100)).
