### ISSUE TITLE
Osiřelé články + nekonzistence jejich metadat

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#309]
Vyskytl se problém s osiřelými články v krameriovi. (např.: uuid:141abe7b-2d44-4a18-a2cf-bd8ad92dacc2) Chybí jim vazba `<http://www.nsdl.org/ontologies/relationships#hasIntCompPart>` v tripletech.

Vazba patří ke konkrétnímu vydání (periodicalissue). Problém je, že k danému vydání se bez vazby dá dostat dvěma způsoby prostřednictvím MODS-u:

ukázka MODS prvního zmíněného uuid:

```
<mods:relatedItem type="host">
	<mods:titleInfo>
		<mods:title>Lidové noviny</mods:title>
	</mods:titleInfo>
	<mods:identifier type="uuid">bdc405b0-e5f9-11dc-bfb2-000d606f5dc6</mods:identifier>
	<mods:identifier type="issn">1802-6265</mods:identifier>
	<mods:location>
		<mods:url>http://kramerius4.mzk.cz/search/handle/uuid:bdc405b0-e5f9-11dc-bfb2-000d606f5dc6</mods:url>
	</mods:location>
	<mods:part type="article">
		<mods:detail type="volume">
			<mods:number>3</mods:number>
			<mods:caption>ročník</mods:caption>
		</mods:detail>
		<mods:detail type="issue">
			<mods:number>228</mods:number>
			<mods:caption>číslo</mods:caption>
		</mods:detail>
		<mods:extent unit="page">
			<mods:start>5</mods:start>
			<mods:end>5</mods:end>
			<mods:total>1</mods:total>
		</mods:extent>
	</mods:part>
</mods:relatedItem>
```

- pročtení `mods:part`:
  - postupně se dostaneme k `uuid:b8142476-435d-11dd-b505-00145e5790ea`, které ovšem podle metadat článku má mít 5 stran (přičemž na 5. má být zmíněný článek), ale vlastní číslo má jen 4 strany

- použití `mods:url`:
  - nemáme ale údaj, které straně článek patří, protože `mods:part` není "důvěryhodné"

Otázkou tedy je jak problém řešit... dost možná bude potřeba osiřelé články projít ručně a určit, ke kterému objektu článek skutečně patří a zda je v MODS nějaká chyba a jak případně má MODS vypadat po opravě

**Comment by jkremlacek** [comment]
Vytvořil jsem seznam článků, které postrádají vazbu k objektu ve kterém se mají vyskytovat.

[articlesOut.txt](https://github.com/moravianlibrary/kramerius/files/2965559/articlesOut.txt)

**Comment by annie-cz** [comment]
@pavluska Nevybavuješ si prosím v souvislosti s tímto issue něco? Dle @zabak by mělo jít o nějaká přepsaná data od paní Jiránové z roku 2011. Mělo jít o nějaký projekt ohledně Lidových novin, kterých se toto issue týká především. Případně nevzpomněl by si @rzeh4n ?

Aktuálně jsme se domluvili, že zjistíme co nejvíce informací, vyfiltrují se duplicity a pak se uvidí, co uděláme se zbytkem. Nepotřebné se smaže.

**Comment by rzeh4n** [comment]
Jo, byly to hlavně Lidovky, možná ještě něco menšího k tomu.
Zpracovával jsem to v 2010/2011, původní data (xsl/csv) byla z roku 2008 a 2009, takže si ti pamatuju jen matně. Ten MODS záznam jsem vytvářel z csv a pak jsem pro každý objekt článku vytvářel foxml s rels-ext vazbami isOnPage na konkrétní stránky. Už si přesně nepamatuju, jak jsem získal mapování na issue,page -> uuid, asi jsem si to vytáhl s resource index a solr. 
Pokud jde o vazbu hasIntCompPart z periodika/rocniku/cisla na clanek, tak to se da dogenerovat zpetne, kdyz clanek se odkazuje na stranky pres isOnPage.
Pokud  jde o nesoulad MODSu, a odkazovanych stranek, tak mohlo treba dojit dodatecne ke smazani stranek a vsech odkazu na ne, vcetne article:isOnPage. Anebo skutecne uz pri vytvareni foxml kvuli chybam v csv/chybe v datech mapovani na uuid tam ten nesoulad s modsem byl od zacatku. Ale myslim, ze tohle jsem hlidal.
Kazdopadne mam pocit, ze tech clanku bylo celkove dost vic, nez nejakych 3500.

**Comment by hlavacekrene** [comment]
Seznam přiřazených článků:
[Issue-309-osirele-clanky-Lidove-noviny.xlsx](https://github.com/moravianlibrary/kramerius/files/3450635/Issue-309-osirele-clanky-Lidove-noviny.xlsx)

**Comment by annie-cz** [comment]
Super, díky, zavíráme :)
