### ISSUE TITLE
Prazdny JSON jako response

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius#31]
Po requestu 
http://kramerius.mzk.cz/search/api/v5.0/item/vc:6c323045-d869-4d65-928d-3d52f34440a0/children 
dostanu prazdne pole - resp json s praznym obsahem

**Comment by honza-rychtar** [comment]
Obsah sbirky se pres API takto dostat neda.
Musi se pouzit SOLR. 

Pro sbirku to udelas takto:
http://kramerius.mzk.cz/search/api/v5.0/search?q=collection:"vc:6c323045-d869-4d65-928d-3d52f34440a0"
Tohle je zakladni dotaz, ktery vraci vsechny plne zaznamy ze sbirky (i stranky), celkem 14672. Vrati to prvnich 10 zaznamu, strankuje se pak pres parametry start a rows

Tobe se bude hodit tento dotaz:
http://kramerius.mzk.cz/search/api/v5.0/search?fl=PID,dostupnost,dc.creator,dc.title,fedora.model,img_full_mime&q=collection:%22vc:6c323045-d869-4d65-928d-3d52f34440a0%22%20AND%20(fedora.model:monograph%20OR%20fedora.model:periodical%20OR%20fedora.model:soundrecording%20OR%20fedora.model:map%20OR%20fedora.model:graphic%20OR%20fedora.model:sheetmusic%20OR%20fedora.model:archive%20OR%20fedora.model:manuscript)&sort=created_date%20desc&rows=30&start=0

Pres fl vyjmenujes pole ktere chces vratit. 
Je tam omezeni jen pro typy dokumenty na nejvyssi urovni (aby to nevracelo stranky, clanky, ...). Seradi se to od nejnovejsich.
A pres rows=30&start=0 to vrati prvnich 30 zaznamu, rows=30&start=30 by vratilo dalsich 30 zaznamu - takto to projedes, dokud nebude vysledek prazdny.
V result.numFound vidis celkovy pocet nalezenych zaznamu, v tomto pripade 35

Pokud zadas dotaz v prohlizeci, tak ti to vrati XML. Podle SOLR specifikace by se melo dat pres parametr wt=json prepnout response na JSON. Tohle ale SOLR Krameria neumi.
Pokud budes chtit radeji zpracovat JSON, tak to jde pres request header Accept: application/json

SOLR budes potrebovat na vice mistech (ve webovem klientovi je vic nez polovina dotazu pres SOLR).

Napis mi cokoli budes potrebovat pres SOLR, ja ti ty dotazy sepisu.
Nebo si proklikej klienta http://janrychtar.cz/kramerius/ a podivej se co vse se da zobrazit a potrebne chovani pro aplikaci bych ti napsal jak se dela.
Vyhledavani, prochazeni, naseptavani, obsah sbirek, filtrovani, pocty dokumentu podle kriterii, kontext fulltextoveho vyhledavani, fultextove seskupovani .... vse je pres SOLR

**Comment by ovyhlidal** [comment]
Super, diky moc. Mrknu na to a dam vedet.

**Comment by leiblix** [comment]
Pokud by byl ten SOLR dotaz nevyhovující, tak to issue znovu otevři prosím :)
