### ISSUE TITLE
Chybné zobrazování některých znaků v admin. rozhraní

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#310]
Některá písmena a znaky, jako např. u slova "příloha" se zobrazuje v administrátorském rozhraní špatně, viz obrázek. Neděje se nějaká neplecha se solrem nebo něčím na pozadí? V adminovi s tímhle takový problém není, my jako správci víme, o co se jedná, ale aby nám to nerozhodilo ještě něco dalšího.

![image](https://user-images.githubusercontent.com/43028501/54528039-04fd6b00-497c-11e9-9406-5de533134682.png)

**Comment by jkremlacek** [comment]
Toto je problém se znakovou sadou, který se děje na cestě Kramerius <---> počítač uživatele, se Solrem to naštěstí souviset nebude. Je potřeba ale zjistit, proč se tyhle texty rozsypávají.

**Comment by annie-cz** [comment]
Horší se to :( Víceméně jdu jen u některých voleb jen po paměti. Před cca měsícem a kousek jsem zakládala poslední sbírku, tak tam toto nebylo.

![image](https://user-images.githubusercontent.com/43028501/55493590-84a45e80-5639-11e9-92ad-d7c0d5f5f96d.png)

**Comment by jkremlacek** [comment]
To mohlo být zacachované bez té chyby a až teď se ti načetla aktuální verze.

Co jsem to procházel, tak chyba je ve všem, co je obsaženo v javascriptu, statické věci jsou vpořádku.

Kontroloval jsem stav v krameriích ostatních institucí a problém se děje jen u nás.

Zkusil jsem tedy testovat různé nastavení builder-u a vylezlo z toho:
```
verze krameria, verze javy, verze tomcatu, stav

expedice,          oracle,     8,             ok
expedice,          oracle,     9,             ok
expedice,          openjdk,    9,             nejde sestavit
expedice (+oprava),oracle,     9,             ok
expedice (+oprava),openjdk,    9,             ok
mzk,               oracle,     9,             nok
mzk,               openjdk,    9,             nok
```

**Comment by hlavacekrene** [comment]
Mame properties soubor /usr/local/tomcat/webapps/search/WEB-INF/classes/labels_cs.properties
v nem se popisky s diakritikou zapisuji pomoci utf8 entit \u????
Kdyz je diakritické pismenko zapsane pomoci jedne entity, zobrazi se v poradku. Kdyz je zapsane pomoci dvou entit, zobrazi se spatne.
Pokusove jsem zkusil napsat Pohyblivá zeď, pismeno ď bez entity - proslo to take.
Diakriticke pismenko slozene ze dvou entit je potreba nahradit pomoci jedne entity (nebo zkusit bez)

**Comment by jkremlacek** [comment]
Chyba byla zavlečena úpravou, která ještě není součástí oficiální verze. Vytvořeno issue https://github.com/ceskaexpedice/kramerius/issues/672

Edit: Pro potřeby MZK dočasně záplatováno commitem https://github.com/moravianlibrary/kramerius/commit/156bdf1f4eb117db922c0c45abbfa5db147a53bb, aby bylo admin. rozhraní použitelné. Po opravě výše zmíněného issue bude zapotřebí záplatu odebrat a použít řádnou opravu.
