### ISSUE TITLE
Chybející částí dokumentů

### ISSUE THREAD

**Issue by kazooo** [moravianlibrary/kramerius#311]
Periodiku chybí ročník 1820, zbytky čísel tohoto ročníku visí ve Fedoře, příkladám jejich uuid aby se neztratily:
```
uuid:6a395a90-631a-11e3-9ea2-5ef3fc9ae867
uuid:a3930c30-6330-11e3-9ea2-5ef3fc9ae867
uuid:a985eab0-6356-11e3-9ea2-5ef3fc9ae867
uuid:09c543e0-6360-11e3-9ea2-5ef3fc9ae867
uuid:b0dcbc40-634b-11e3-9ea2-5ef3fc9ae867
uuid:b0dcbc40-634b-11e3-9ea2-5ef3fc9ae867
uuid:4a764370-6343-11e3-9ea2-5ef3fc9ae867
uuid:cd023110-6360-11e3-9ea2-5ef3fc9ae867
```
Asi tady jenom reimport...

**Comment by kazooo** [comment]
Uuid ztraceného ročníku: uuid:4e4f4990-616f-11e3-8c6a-005056825209

**Comment by annie-cz** [comment]
Díky, víme o tom, již je nahlášeno v LTP.

**Comment by kazooo** [comment]
**Revolver revue**: periodiku chybí číslo 66 ročníku 2007, uuid:df17c160-e6a0-11e5-8d5f-005056827e51, seznam odpojených stránek: https://gist.github.com/xermak00/dc7c0c559cd3b1c27d1fc3f58159db13

**Comment by marketakrutska** [comment]
Děkujeme, nahlásila jsem to do LTP.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
