### ISSUE TITLE
Topičův almanach

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#312]
Náhodou jsem narazil na monografii zpracovanou z neznámého důvodu jako periodikum. 
http://kramerius.rychtar.cloud/mzk/view/uuid:ab48a100-2f5b-11e3-a5bb-005056827e52?page=uuid:bc830360-81a0-11e3-a70e-005056822549
Je to z NK, ale není mi jasné, jak někdo přišel na to, že jde o periodikum, když je to jednorázově vydaná kniha. Navíc v metadatech ani není skutečný název ale jen v hranatých závorkách nějaký vymyšlený. Šlo by s tím něco udělat? Pochází to z NK.

**Comment by marketakrutska** [comment]
Poslala jsem to jako tiket do LTP. Špatně je už záznam v katalogu NK, takže si to musí opravit. Požádala jsem o opravu v EM (aby z toho udělali monografii) a o aktualizaci metadat z Alephu.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
