### ISSUE TITLE
Chybějící skeny z NDK

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#314]
seznam objektů nadřazených stranám:
```
uuid, importováno
uuid:dd0bb610-ee40-11e8-a5a4-005056827e52, 01,2019
uuid:8e67cc40-b71a-11e8-bbaa-005056827e52, 04.2019
uuid:47fa0ae0-f863-11e8-bc37-005056827e51, 04.2019
uuid:1961a070-ebd5-11e8-bc37-005056827e51, 01.2019
uuid:df4255f0-f242-11e8-bc37-005056827e51, 01.2019
uuid:b169da80-ed93-11e8-a5a4-005056827e52, 01.2019
```

chybí skeny všech stran, importováno v rámci NDK

Edit:

další UUID:

```
uuid:e5428760-042e-11e9-9984-005056825209, 04.2019
```

dokumentů bude zjevně víc a bude zcela zapotřebí zkontrolovat vše co bylo importováno v dubnu 2019

**Comment by jkremlacek** [comment]
Chybné dokumenty byly nalezeny prostřednictvím Kibany (tím, že se je pokusil zobrazit uživatel). Soudě podle datumu ale půjde o systémovou chybu v konkrétních dnech, bude proto potřeba udělat kontrolu všeho co bylo v té době importováno z NDK.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
