### ISSUE TITLE
Rovnost - 1928, chyby v datech

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#316]
V Rovnosti v ročníku 1928 jsou dvě chyby - tváří se jako duplicita, je ale pouze chyba v čísle ročníku v metadatech.

č. 57/1928 = č. 239 z 29.8. 1928 - viz https://krameriusadmin.mzk.cz/search/handle/uuid:58b6200b-6b97-467d-913d-cc948db976eb
č. 130/1928 = č. 230 z 20.8. 1928 - viz https://krameriusadmin.mzk.cz/search/handle/uuid:3486de1d-808b-48c8-bf5b-0dc4c6d49073

@xermak00 , mrkni na to prosím :)

**Comment by kazooo** [comment]
Čísla a pořadí čísel jsou opraveny.
