### ISSUE TITLE
Chybějící uuid periodika Hlídka

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#317]
Při přístupu na http://www.digitalniknihovna.cz/mzk/search?accessibility=public&q=hl%C3%ADdka&sort=relevance&doctypes=periodical

vyletí v logu chyba:
```
WARN 2019-05-09 10:20:37.749 [http-nio-8080-exec-1673] (BaseRestResource) Resource not found: no path in db registry for [uuid:524c41d3-a842-4d94-a557-f8a2e7d751fb]; unable to fulfill REST API request
```

Tedy, že chybí `uuid:524c41d3-a842-4d94-a557-f8a2e7d751fb`.

Hledáním uuid mám podezření jestli se nezměnilo uuid periodika, protože na stránce Krameria České Třebové:

https://k5.digiknihovna.cz/search/i.jsp?pid=uuid:ad1a05d2-feb4-47f0-b090-d8d40cd3eefa&q=&fq=document_type:%22periodicalvolume%22

má periodikum Hlídka zmíněné uuid.

**Comment by MarosGrm** [comment]
Periodikum sa nachádza v indexe. Vyzerá to ako keby sa mazalo a pri procese sa úspešne vymazalo z Fedory no zlyhalo mazanie z indexu. Bude to potrebné ručne vymazať z indexu.

**Comment by kazooo** [comment]
Všechny zaznamy s kořenem ```uuid:524c41d3-a842-4d94-a557-f8a2e7d751fb``` jsou vymazany z indexu. Celkem těch bylo 1810, kdyby něco příkladám soubor všech vymazaných uuid. Periodikum už se ve vyhledevání nezobrazuje.
[hlidka.txt](https://github.com/moravianlibrary/kramerius/files/3165345/hlidka.txt)
