### ISSUE TITLE
Ročník 1905 periodika Hlídka

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#318]
Periodikum Hlídka 

http://www.digitalniknihovna.cz/mzk/periodical/uuid:c56dce20-1cf1-11e2-bec6-005056827e51 

bylo zpracováváno NDK linkou, nicméně chybí ročník 1905.

Při pohledu do České Třebové je ale ročník 1905 digitalizovaný a soudě podle razítek na stránkách (v obrázcích)

http://www.digitalniknihovna.cz/mkct/view/uuid:a5ec2b42-d698-4e46-90aa-42d86c50f7fa?page=uuid:1eaa0fec-e3df-46be-9798-25569120f002

pochází z MZK, je tedy možné, že jen selhal import z NDK k nám a proto chybí v našem Krameriovi? 

@marketakrutska / @annie-cz je možné se prosím podívat do LTP jestli tam je zmíněný ročník?

**Comment by marketakrutska** [comment]
Tak jsem se dívala, že dokument uuid:524c41d3-a842-4d94-a557-f8a2e7d751fb jsem smazala z Fedory já (20. 3. 2019). Je to vlastní digitalizace MZK a bylo to duplicitní vůči té NDK digitalizaci uuid:c56dce20-1cf1-11e2-bec6-005056827e51.
Bohužel, asi jsem přehlédla, že v NDK není ročník 1905 :( Moje chyba, omlouvám se. Myslíš @jkremlacek , že by bylo ještě možné získat skeny ročníku 1905? Pak by se to dalo poslat přes NDK a doplnit to k tomu dokumentu uuid:c56dce20-1cf1-11e2-bec6-005056827e51.

Jinak ještě jsem žádala o reimport ročníku 1939 v dokumentu uuid:c56dce20-1cf1-11e2-bec6-005056827e51, celý nám chybí. Také tam je několik ročníků dvakrát, ale to už poslal do LTP někdo z NK.

Omlouvám se za komplikace. Ale nějak nechápu, proč se to pořád ukazuje ve výsledcích vyhledávání.

**Comment by jkremlacek** [comment]
To mazání asi v nějaké fázi padlo, takže to po sobě nechalo nepořádek v Solr-u, ale to se v rámci https://github.com/moravianlibrary/kramerius/issues/317 uklidí.

Ten ročník 1905 má ještě Česká Třebová, takže bude potřeba je požádat o Foxml export z Krameria od nich a pak už to k nám dostaneme - případně z toho foxml exportu vylámeme skeny a prožene se to ndk linkou.

**Comment by zabak** [comment]
No jo, ale z ČT nedostaneme archivní kopii. Ta by teoreticky měla být někde uložená.

**Comment by indrakm** [comment]
no, jestli obrázky nejsou, tak jedině poprosit Věru, ať to donese znovu. Btw ČT něco digitalizuje i sama nebo tam mají jenom replikace.

**Comment by jkremlacek** [comment]
Zkusil jsem namátkově najít jednu ze stránek ročníku 1905 podle uuid, které má ČT.

Konkrétně: http://www.digitalniknihovna.cz/mkct/view/uuid:a5ec2b42-d698-4e46-90aa-42d86c50f7fa?page=uuid:c263c943-2902-4db0-b995-d3dbf5fa3963

což odpovídá cestě na imageserver:

http://imageserver.mzk.cz/mzk01/000/220/951/c263c943-2902-4db0-b995-d3dbf5fa3963

což funguje, takže to u nás v nějaký moment bylo. V našich systémech chybí jen popisné záznamy ve Fedoře a Solr-u. Stačí je tedy od ČT vyžádat a připojíme to pod deduplikované periodikum a bude to opravené.

**Comment by zabak** [comment]
@black23 mohl bys nám prosím dát metadata k časopisu Hlídka?

**Comment by jkremlacek** [comment]
Ročník 1905 jsem doplnil a periodikum zreindexoval. Opraveno.
