### ISSUE TITLE
Deadwood rozbité skeny 2 stran

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#319]
publikaci původem z ndk:
 
http://www.digitalniknihovna.cz/mzk/view/uuid:2e0eb820-2190-11e2-9e88-005056827e51?page=uuid:06d9b0d0-900b-11e8-86d2-005056822549

nefungují obrázky stránek 281 a 291, na imageserveru jejich soubory jsou ale mají velikost 1 - nejspíš došlo k chybě během kopírování na imageserver

import proběhl 25.7.2018

bude potřeba obrázky zmíněných stran smazat a nahradit funkčními kopiemi

na IS jsou pod názvy:
```
uc_2e0eb820-2190-11e2-9e88-005056827e51_0283.jp2
uc_2e0eb820-2190-11e2-9e88-005056827e51_0293.jp2
```

na cestě:

```
ndk04/2018/07/2e0eb820-2190-11e2-9e88-005056827e51
```

**Comment by zabak** [comment]
Mimochodem, hledali jsme už obrázky velikosti od 0 do 1 bytu, případně do nějaké malé velikosti, kdy ještě nejde o obrázek ale o chybu? Jinými slovy najít nejmenší soubor který je doopravdy obrázek a vše menší opravit?

**Comment by jkremlacek** [comment]
V minulosti mám pocit, že takové hledání už proběhlo a nálezy se opravily. Možná bude potřeba tyhle kontroly dělat na pravidelné bázi (např. jednou za půl až rok).

**Comment by annie-cz** [comment]
Odeslán tiket do LTP.

**Comment by MarosGrm** [comment]
Reimport prebehol v poriadku, no problém pretrváva.
Na prvý pohľad to vyzerá, že chybné skeny sú aj v LTP, ale v NK je to v poriadku podľa náhľadov z ich Krameria.
http://kramerius4.nkp.cz/search/handle/uuid:529a6707d33a1f3e03a68a59e42e90e7

**Comment by jkremlacek** [comment]
Je možné, že náhledy mají interně ve fedoře, takže full obrázek chybí i tam - @annie-cz jsme schopní někoho v NK sehnat, kdo by se podíval, jestli tam mají ty obrázky v plné kvalitě, nebo jestli to chybí i tam?

**Comment by annie-cz** [comment]
Zrovna to řeší Václav Jiroušek, chyba je prý v user copy v archivním balíčku. Master copy je ale v pořádku, tj. se bude generovat jiná a pak by ten reimport měl snad v pohodě proběhnout.

**Comment by MarosGrm** [comment]
Opravene
