### ISSUE TITLE
IIIPimage s použitím čtečky Seadragon

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#32]
Při použití čtečky Seadragon se na pravé straně u některých obrázků objevují artefakty. Dlaždice putují přes IIIF Image API 2.0.

Přikládám jednotlivé ukázky:

**Čtečka napojená přímo na náš imageserver:**
_protože imageserver neposílá cors hlavičky je nutné zkoušet v chromu, který je zaplý s volbou --disable-web-security_
http://jsfiddle.net/02gqmagy/3/embedded/result/

**Prohlížečka napojená na kramerius:**
http://jsfiddle.net/eLq4crLy/1/embedded/result/

**Prohlížečka napojená na imageserver Loris**
_tady je nastavený endpoint na obrázek z nějakého dema, kde je nasazen imageserver Loris_
http://jsfiddle.net/30gd46w2/embedded/result/

Endpointy (info.json) jsou vidět ve zdrojovém kódu, je v nich vidět konfigurace dlaždic. Ty dva imageservery se liší velikostí posílaných dlaždic. 

Potřeboval bych vědět, jestli je tato chyba způsobená chybou imageserveru nebo prohlížečky.

**Comment by dsecik** [comment]
Problem nastava pri zmene velkosti pozadovaneho vyseku obrazku na strane imageservru.
Ide o parameter size. "The size parameter determines the dimensions to which the extracted region is to be scaled." viac na: http://iiif.io/api/image/2.0/#size

**Vysek v originalnej velkosti:**
ma rozmery 31x766
2048,2048,**31,766**/ **full**/0/default.jpg
http://imageserver.mzk.cz/mzk01/000/329/646/5b93cdc8-6f6e-4d54-ace0-f084a99e610f/2048,2048,31,766/full/0/default.jpg

**Rovnaky vysledok vrati aj dotaz s absolutne nastavenou vyskou a sirkou:**
2048,2048,**31,766**/ **31,766**/0/default.jpg
http://imageserver.mzk.cz/mzk01/000/329/646/5b93cdc8-6f6e-4d54-ace0-f084a99e610f/2048,2048,31,766/31,766/0/default.jpg

**Problem nastane ked definujeme len jeden rozmer (sirku alebo vysku) a druhy by mal byt dopocitany tak, aby bol zachovany pomer stran:**
2048,2048,31,766/**31,**/0/default.jpg
http://imageserver.mzk.cz/mzk01/000/329/646/5b93cdc8-6f6e-4d54-ace0-f084a99e610f/2048,2048,31,766/31,/0/default.jpg

Vysledny obrazok nema ocakavane rozmery **31x766** ale **31x42** a zaroven je v spodnej casti viditelny artefakt.

**Comment by dsecik** [comment]
Vyriesene v novsej verzii iipimage vid: https://github.com/ruven/iipsrv/issues/21
