### ISSUE TITLE
Nezvýraznění výsledků při fulltextovém vyhledávání v DK

### ISSUE THREAD

**Issue by marketakrutska** [moravianlibrary/kramerius#320]
Při fulltextovém vyhledávání v DK není u některých dokumentů vyhledané slovo barevně zvýrazněné. Zobrazí se stránka, kde se slovo nachází, ale slovo není barevně zvýrazněné. Viz následující příklad:
http://www.digitalniknihovna.cz/mzk/view/uuid:f17292ab-435d-11dd-b505-00145e5790ea?page=uuid:637a3485-435f-11dd-b505-00145e5790ea&fulltext=telegramy

U některých dokumentů to funguje, takže klient to umí:
http://www.digitalniknihovna.cz/mzk/view/uuid:3cfc6db0-d350-11e7-a536-5ef3fc9ae867?page=uuid:7a3af110-d35a-11e7-a536-5ef3fc9ae867&fulltext=nad%C4%9Bje

Není to pak problém našeho OCR?

**Comment by zabak** [comment]
Národní listy jsou replikované z NK a nemají ALTO. Proto tam nefunguje zvýrazňování. Museli bychom udělat ALTO i pro replikované tituly, což můžeme, ale bez koordinace s NK to budeme v nějaké fázi dělat my i oni. Počkal bych na OCR z projektu PERO.

**Comment by marketakrutska** [comment]
Dobře, moc děkuju za info. Ptal se na to jeden uživatel, tak teď aspoň vím, co odepisovat.
