### ISSUE TITLE
Opravit objekty s nevalidním uuid

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#321]
V systému se nachází nemalé množství nevalidních uuid (nesplňující formát 8-4-4-4-12 a další pravidla - viz https://en.wikipedia.org/wiki/Universally_unique_identifier).

Např:
`uuid:4615d905bf09a8603ea0e2d54615c972`

Nevalidní uuid ztěžují práci svojí nekonzistencí při parsování, stejně tak znemožňují použití některých funkcí Krameria, např:

https://github.com/ceskaexpedice/kramerius/blob/285b210975fd2223860d51b6d6fe7d3ca39ca117/search/src/java/cz/incad/Kramerius/imaging/IiifServlet.java#L66-L69

Je zapotřebí dohledat ve Fedoře všechny tyto případy, čímž vznikne seznam nevalidních uuid. Bude potřeba dohledat všechny objekty, které na tyto nevalidní uuid odkazují, protože po vytvoření nového objektu s validním uuid bude zapotřebí tyto odkazy správně opravit a následně provést reindexaci všech dotčených objektů.

Souvisí s https://github.com/moravianlibrary/kramerius/issues/39

**Comment by annie-cz** [comment]
Jelikož se jedná pouze o data NDK, informovala jsem o tomhle problému LTP. Čekáme, až se seznámí s problematikou a něco přímo v LTP otestují. Pak se domluvíme na společném postupu.

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
