### ISSUE TITLE
Výpadky spojení mezi krameriem a databází

### ISSUE THREAD

**Issue by jkremlacek** [moravianlibrary/kramerius#322]
V posledních dnech často nastává rozpadení spojení mezi hlavním krameriem a jeho databází.

V logu se chyba projevuje (řádově stovky za minutu) jako: 
https://gist.github.com/jkremlacek/6c2114ea49f22e28035589565b24e536

Chyba se zatím z neznámých důvodů občas opraví sama (může jít o časově nedefinované operace, např. GC), nicméně nejde na to spoléhat, protože k tomu může dojít i po dlouhé době - řádově hodiny).

Manuálně je možné problém vyřešit restartem Krameria.

Úprava konfigurace Tomcatu doplněním `validationQuery` nepomohlo.

Bude zapotřebí udělat skript, který v případě nastání této chyby Krameria restartuje a dále spustí diagnostiku (kterou bude také potřeba vytvořit) testující dostupnost serveru databáze, dostupnost databáze jako takové a případně další metriky.

**Comment by fstepanovsky** [comment]
Cron skript byl vytvořen, v případě rozpadu spojení zasáhne.

Z pohledu metrik:

- ping OK
- navázání spojení a komunikace s DB bez problému

**Comment by jahhoo** [comment]
@zafan Zdravím, bylo by možné od vás script získat pro účely NK?

**Comment by fstepanovsky** [comment]
Dobrý den @jahhoo,  
skript pracuje s Dockerem, je šitý na míru naší infrastruktury a počítá s jejím rozvržením a vlastnostmi, které z toho plynou.
Pokud máte přesto zájem, skript vám poskytneme.

**Comment by JanMeritus** [comment]
@zafan Dobry den, bolo by to super. My si to uz pripadne kustomizujeme. Zdravim, Z.

**Comment by annie-cz** [comment]
@JanMeritus Zdenko, vám se podobná chyba děje také?

**Comment by fstepanovsky** [comment]
Skriptík odeslán emailem.

**Comment by JanMeritus** [comment]
V poslednom case nam nejak blbne spojenie medzi Kram bazou a klientom. Ale vzhladom k odlisnosti infra a implementacie si netrufam povedat ze ide o rovnaku vec

Diki moc!

**Comment by annie-cz** [comment]
@JanMeritus I tak by možná stálo za to o tom někdy hodit řeč. Není zač.

**Comment by fstepanovsky** [comment]
Problém byl opravdu způsobován firewallem, kde bylo potřeba přidat pravidlo, které zajistí, aby db sessions vydržely minimálně 24 hodin.

Uzavírám...

**Comment by indrakm** [comment]
díky!
