### ISSUE TITLE
Osiřelé obrázky periodika Rovnost

### ISSUE THREAD

**Issue by kazooo** [moravianlibrary/kramerius#323]
Složka /mnt/imageserver/meditor/rovnost obsahující obrázky periodika [Rovnost](http://www.digitalniknihovna.cz/mzk/periodical/uuid:f1c7c08d-8f64-4b66-be28-5f209c2c7021) obsahuje také obrázky, na které neodkazuje žadný FOXML periodika. Zkusil jsem vyhledat stejné obrázky stránek v periodiku, ale na obrázcích obyčejných stránek je vidět jen číslo, takže je těžkě říct jakým ročníkům patří. Podařilo se mi najit pár obrázků titulních stránek, jak jsem zjistil později, periodikum je už má, takže jde o duplicity. 

Například: [osiřelý obrázek](http://imageserver.mzk.cz/meditor/rovnost/19fe412e-4b7f-4ad8-8997-bcf90d2cfcd0) (**19fe412e-4b7f-4ad8-8997-bcf90d2cfcd0.jp2**) je kopie obrázku titulní stránky [čísla 88 ročníku 1917](http://www.digitalniknihovna.cz/mzk/view/uuid:deb39c99-f4d2-40fa-8012-ff573ac7649b?page=uuid:40b93054-9d00-4550-aede-97c64e367dda) (**40b93054-9d00-4550-aede-97c64e367dda.jp2**).

Celkem těch je 14130, automacky zkontrolovat každý z nich by asi nešlo. U periodiku ještě zkontroluju přitomnost všech obřázků stránek. Pokud nikdo k tomu nemá poznámky tak ty osiřelé smažu.

[rovnost_obrazky.txt](https://github.com/moravianlibrary/kramerius/files/3232123/rovnost_obrazky.txt)

**Comment by zabak** [comment]
Zkus u těch dvou stejných obrázků spočítat kontrolní součet (md5). Pokud jsou identické, mohl bys tímto způsobem najít všechny duplicitní obrázky.

**Comment by annie-cz** [comment]
Může souviset s #309. Pokud se jedná o duplicity, určitě smazat.

**Comment by kazooo** [comment]
Zkontroloval jsem všechny stránky periodika aby měly obrázky a odhalil několik čísel, které ty obrázky nemají (chybí obrázky pro ~23 stránky). Seznam čísel dám do jiného issue.

Podle kontrolního součtu se podařilo najit originální obrázky k 12357 duplictam ze seznamu výše. Zbývající (1773) mají unikatní md5, nenapadá mě jakým způsobem by je ještě šlo zkontrolovat. Nemate-li k tomu další poznamky tak ty obrázky smažu.

[duplicity.txt](https://github.com/moravianlibrary/kramerius/files/3296174/duplicity.txt)
[zbytek.txt](https://github.com/moravianlibrary/kramerius/files/3296182/zbytek.txt)

**Comment by kazooo** [comment]
@natal1H posbírala obrázky a předala je na reimport

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
