### ISSUE TITLE
Kramerius nevidí na PDF server

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#324]
Kramerius.mzk.cz nevidí na pdfserver.mzk.cz, díky tomu nelze načítat PDFka ve studovnách (zde to nejvíc hoří). Prosím v první linii @xermak00  a @hlavacekrene aby se na to podívali, ve druhé pak případně @kenji1322 .

**Comment by hlavacekrene** [comment]
/docker-compose/kramerius.mzk.cz/docker-compose.yml

    networks:
     default:
       aliases:
         - imageserver.mzk.cz
         - kramerius.mzk.cz
         - audioserver.mzk.cz
         - pdfserver.mzk.cz
#### do aliasu se musi pdfserver.mzk.cz pridat

    extra_hosts:
     - "fedora.dk-back.infra.mzk.cz:10.19.9.11"
     - "solr.dk-back.infra.mzk.cz:10.19.9.12"
     - "kramerius.infra.mzk.cz:10.19.9.20"
###  - "pdfserver.mzk.cz:195.113.155.146"
### tady to ale byt nema, protoze to propisuje v kontejneru jeho /etc/hosts a to pak prekryje bridge s privatni adresou 172.18.....

**Comment by hlavacekrene** [comment]
a proto kramerius pdfserver nevidel.

**Comment by annie-cz** [comment]
Díky moc, zavírám tedy :)
