### ISSUE TITLE
přidat DiFMOE

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#325]
Domluvili jsme se s pány z DiFMOE, že přidáme jejich Krameria do DK, tak ho tam prosím někdo přidejte (na konec seznamu). Konfigurace viz. registr Krameriů.

**Comment by annie-cz** [comment]
Tohle můžeme udělat sami? Když se takto hlásila paní za Krameria UMPRUM, tak to tam musel přidávat Honza.

**Comment by zabak** [comment]
@honza-rychtar Honzo, přidáš je tam?

**Comment by annie-cz** [comment]
Difmoe je v seznamu. Zavírám.
