### ISSUE TITLE
100+1 - chybně seřazené ročníky

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#327]
V časopisu 100+1 je několik chybně seřazených ročníků. V Krameriovi je to v pořádku, v Digitální knihovně ne. Problém je v chybějících metadatech, dle kterých DK srovnává dokumenty. Podobně jako je to #298 

1972 je číslo 22 hned na druhé pozici
1973 číslo 12 na první pozici
1979 tam je toho více
1993 – 22, obsah, 26, 25, 23, 24 atd

https://krameriusadmin.mzk.cz/search/handle/uuid:83ecf6c0-bb9e-11e5-b5dc-005056827e51
http://www.digitalniknihovna.cz/mzk/periodical/uuid:67577750-700d-11e6-81ec-005056827e51

V minulosti někdo (tuším Kuba) srovnával nějakým způsobem čísla u jednoho ročníku Davidovy houpačky, mohl by se na to prosím tady někdo podobně podívat?

**Comment by hlavacekrene** [comment]
Vsimnete si, ze se mne podarilo u Davidovy houpacky v rocniku 1926 (druhé) cislo 1 priradit na zacatek.
Dopsal jsem do něho vymyšlené fiktivní datum 01.02.1926.
Dopsal jsem ho do modsu 
<mods:part type="PeriodicalIssue">
...
<mods:date>01.02.1926</mods:date>
</mods:part>

Solr si to ulozi do "details": "datum_str": a "datum":  odtud to novy klient setriduje.
Takže je otázka, nemají se míchat issue s celým datumem a jenom rocníkem bez datumu? Když uz to zacina celym datumem, tak by ta celá data měla být asi všude.
Proc se novy klient vyhradne neridi "rels_ext_index":[cislo_poradi] ? (setridovani do kalendare az v dalsim kroku, pokud jsou k dispozici cele datumy) ?

**Comment by hlavacekrene** [comment]
... ty datumy jsem musel kvuli ctenarum zase vymazat (takze uz zmeny nejsou videt), nelze si datumy nejak jako vymýšlet. A když se cele datum odmaže, tak se cislo presune vždy nakonec na posledni pozici. Tzn, ze kdyz klient nenajde cele datum, tak to seradi podle PID procesu.

**Comment by zabak** [comment]
Nebylo by tedy koncepčně lepší přiřazovat místo čísla pořadí něco jako čas pořadí, tj. že by se převzala reálná data kde existují a pak by se doplnily fiktivní data nebo časy? Resp. že by "rels_ext_index":[cislo_poradi] nebylo číslo ale časový údaj. Tím by odpadl problém přečíslovávání všeho když potřebuju přesunout jednu věc a byla by snadnější kontrola správného řazení. Dalo by se tak uhlídat i pořadí vydání v rámci dne.

**Comment by hlavacekrene** [comment]
a co kdyz dve veci budou  mit stejny casovy udaj a Ty je budes chtit prohodit?

**Comment by zabak** [comment]
změníš u jedné z nich hodinu vydání na dřívější.

**Comment by annie-cz** [comment]
Že by?

https://github.com/ceskaexpedice/kramerius-web-client/issues/250#issuecomment-513311178

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
