### ISSUE TITLE
chybný typ stran u mnografie

### ISSUE THREAD

**Issue by MarosGrm** [moravianlibrary/kramerius#328]
https://kramerius.mzk.cz/search/handle/uuid:ab810b10-a839-11e3-b833-005056827e52

http://www.digitalniknihovna.cz/mzk/view/uuid:ab810b10-a839-11e3-b833-005056827e52?page=uuid:e472d3e0-bc6b-11e3-b74a-5ef3fc9ae867

Monografia má každu stranu označenú typom desky (<mods:part type="Cover">).
Rovnaká chyba je aj v Krameriovy NK.
Bude treba typ strán opraviť v LTP a následne monografiu reimportovať.

**Comment by marketakrutska** [comment]
Ahoj, moc díky za upozornění. Poslala jsem to do LTP na opravu.

**Comment by annie-cz** [comment]
Přesunuto na interní gitlab.
