### ISSUE TITLE
Duplicita posledného 12-číslia v uuid

### ISSUE THREAD

**Issue by MarosGrm** [moravianlibrary/kramerius#329]
Periodikum s uuid: uuid:ed1809a0-1e62-11e2-bec6-005056827e51-005056827e51
má zduplikované posledné 12-číslie, tj. formát uuid je chybový. Zlé uuid je aj v Krameriovy NK, bude treba chybu opraviť aj v LTP a reimport.

**Comment by MarosGrm** [comment]
Problém sa hromadne rieši v https://github.com/moravianlibrary/kramerius/issues/321
Issue zatváram

**Comment by vjirousek** [comment]
V LTP máme opraveno. Jakmile smažete, můžeme zkusit opravené balíčky doplnit.

**Comment by annie-cz** [comment]
@vjirousek Díky za info. Generujeme seznam nevalidních uuid z issue #321 a #39 , pak se ozveme.
