### ISSUE TITLE
Generování deepzoomcache

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#33]
Přijde mi matoucí tlačítko na generování DeepZoom cache, rozhodně by mělo jít tuto volbu přes konfigurační soubor vypnout - v případě externího imageserveru je tato volba zbytečná, či dokonce kontraproduktivní (je možné, že se smaže odkaz na tiles).

**Comment by leiblix** [comment]
@Jenyk Nepodařilo se mi zreplikovat to mazání tiles, nevíš čím to měli na FSV speciální? Mi ten proces generování dlaždic vždy hodí chybu...

**Comment by Jenyk** [comment]
Jakou? Jde tu cache smazat? Dělá to buď generování a nebo (spíš) mazání

**Comment by leiblix** [comment]
Můžeš se na to podívat na krameriustest.mzk.cz, případně si to na libovolném dokumentu zkusit. Zkoušel jsem to nad sluníčkem a generování cache spadlo.
![vytvareni_deepzoom](http://i.imgur.com/vVoeUvY.png)
A naopak to mazání cache projde - ale pokud jsem se podíval dobře,tak to dokument nijak nepoškodilo.

**Comment by leiblix** [comment]
@Jenyk Pokud by sis někdy všiml, že to ten odkaz na tiles fakt smaže, tak toto issue prosím otevři.

**Comment by leiblix** [comment]
Na FSV se to fakt smazalo, ale není tam aktuální verze K5.
