### ISSUE TITLE
Kramerius odmítá některým dříve funkčním účtům přístup

### ISSUE THREAD

**Issue by annie-cz** [moravianlibrary/kramerius#330]
Kramerius odmítá přístup k některým dříve funkčním účtům. Jedna externistka si v pondělí (2.9.) založila účet v Krameriovi (účet Shanna) a normálně v něm byla schopná pracovat. Dostala z počátku oprávnění "can read all", aby se naučila s Krameriem pracovat. Další den jsem jí chtěla dát "change visibility", až ji Markét zaškolí. Druhý den pak ale hlásila, že jí Kramerius neumožňuje se přihlásit (chyba autentizace). Pokoušely jsme se o znovuposlání hesla, změny v oprávnění, ale nic nepomohlo. Nakonec jsem starý účet smazala a ona si založila nový (Shanna2). Tam už vše funguje.

Ve stejný den hlásila problémy i naše další externistka, které jsem na účet nijak nesahala a která pro nás vzdáleně pracuje na stejný účet již dlouho (LenkaSuki). Dnes psala mail, že se do Krameria stále nemůže dostat.

Mohl by se na to prosím někdo podívat?

**Comment by MarosGrm** [comment]
S najvecsou pravdepodobnosťou sa jednalo o dočasnú stratu spojenie Krameria s DB, čo by vysvetlovalo nemožnosť prihlásiť sa.
Problém je už neaktuálny, ak sa bude opakovať issue sa znova otvorí.

**Comment by JanMeritus** [comment]
@kenji1322 nam sa to stava tiez, zda sa ze je to DB connection poolom ktory byva obcas vyrezervovany. Ak by sa to i u vas stavalo castejsie, malo by sa to riesit obecne

**Comment by MarosGrm** [comment]
@JanMeritus U nás bolo toto prvý krát a odvtedy sa to na štastie nezopakovalo, ale podobný problém som zaznamel na inej inštancii Krameria a vtedy pomáha iba otočenie kontajnera. Ako to riešite vy a ako často sa to stáva?
