### ISSUE TITLE
Spojení imageserverů

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#36]
Hromadně změnit linky na krameriusndktest.mzk.cz, tak, aby odkazoval do jednotného MZK imageserveru, který už podporuje IIIF.

**Comment by leiblix** [comment]
Spojování zatím proběhli na roce 2012 a částečně na roce 2013. Ale IIIF tak úplně nefunguje http://krameriusndktest.mzk.cz/search/iiif/uuid:69877462322d770dea054f5b5850f5c2/info.json. Musíme zjistit proč.

**Comment by jirkadev** [comment]
V balíčku search v souboru [IiifServlet.java](https://github.com/moravianlibrary/kramerius/blob/master/search/src/java/cz/incad/Kramerius/imaging/IiifServlet.java) je na řádku 66 kontrola správnosti uuid pomocí regulárního výrazu. 

při zakomentování ifu, [odkaz na krameriusTest](http://krameriustest.mzk.cz/search/iiif/uuid:69877462322d770dea054f5b5850f5c2/info.json) funguje a stáhne se info.json 

/*
        if (!pid.matches("uuid:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}")) {
            resp.sendError(HttpServletResponse.SC_NOT_FOUND);
            return;
        }
*/

**Comment by leiblix** [comment]
Aha, takže v Krameriu NDK máme i nevalidní UUID :-( Upravím kód tak, aby to nevalidoval.

**Comment by leiblix** [comment]
Po rok 2014 je spojeno, nyní počkáme na změnu konfigurace TM modulu.

**Comment by leiblix** [comment]
TM modul byl pravdebodobne nakonfigurovan s chybou, do fedory se cpou odkazy na obrazky s "protokolem", http://// (tri lomitka). Je potreba ASAP prekonfigurovat TM modul.

Zpetne se to da oparvit skriptem, ktery jsem ted napsal
`find /data/fedora-data/objects/2015/1208/ -type f -exec /data/vyreseno/spojovaniimageserver/imageserverrepairhttp.sh {} \;`
