### ISSUE TITLE
Import balicku podle starých standardů do K5 

### ISSUE THREAD

**Issue by Drahotussky** [moravianlibrary/kramerius#38]
Dobry den,
chci se zeptat, zda lze bez problemu importovat do K 5 balicky vytvorene dle standardu verze 1.0 (mono) a 1.4 (perio) z roku 2012?

Dekuji

A. Drahotussky, MSVK Ostrava

**Comment by leiblix** [comment]
Issue tracker v tomto repozitáři slouží pouze pro interní potřeby MZK. Nedokážu vám odpovědět lépe než vám odpověděl pan Lahoda z Incadu. Není důvod aby to nešlo, ale zkušenosti s tím v MZK nemáme.

Můžete zkusit ještě už zmiňovanou neoficiální diskusi na https://gitter.im/moravianlibrary/kramerius, diskuse tam se účastní více správců a je možné, že někdo NDK balíčky řešil.
