### ISSUE TITLE
Nevalidní UUID

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#39]
Během řešení https://github.com/moravianlibrary/kramerius/issues/36 jsme přišli na to, že (minimálně) zezačátku do NDK Krameria protekly nevalidní uuid.

Tyto špatné uuid se týkají asi pouze stran, které se pravděpodobně generují až v  transformačním modulu. Do LTP se asi cpou METS balíčky a ty neobsahují UUID stran. @popelkatomas Uměl bys to prosím ověřit?

_Ukázka špatného UUID_
 MZK: http://krameriusndktest.mzk.cz/search/api/v5.0/item/uuid:69877462322d770dea054f5b5850f5c2

NKP ekvivalent: http://kramerius4.nkp.cz/search/api/v5.0/item/uuid:e5c2020d08e64cf43aef8a46ed4bfb95

(uuid se mezi MZK a NKP shodují pouze na úrovni titulů a dalších vnitřních uzlů, stránky už ne, to je plně ok a vyplývá to právě ze struktury METS balíčku).

Funkčnost Krameria to asi neomezuje, ale na https://github.com/ceskaexpedice/kramerius/wiki/Data#identifik%C3%A1tor-digit%C3%A1ln%C3%ADch-objekt%C5%AF se píše, že `Každý digitální objekt systému Kramerius 4 má jednoznačný identifikátor UUID`, což teda nemáme splněno. 

Minimálně bychom pro začátek měli zjistit, jestli se to týká fakt jenom roku 2012.

**Comment by leiblix** [comment]
A samozřejmě by bylo vhodné, aby Kramerius tyto identifikátory při importu do Fedory validoval.

**Comment by leiblix** [comment]
Hlášení od @Jenyk: Ve fedoře je objekt s identifikátorem "uuid: 738a6390-b936-11e5-b5dc-005056827e51" (tab, ne mezera)

**Comment by leiblix** [comment]
Celkem máme takovýchto dokumentů ve Fedoře 2241445.

Týka se to bohužel i jiných let, např. 2015:

```
fedora3=# SELECT * FROM objectpaths WHERE token NOT SIMILAR TO '(uuid:|vc:)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' LIMIT 100;
 tokendbid |                 token                 |                                   path                                    
-----------+---------------------------------------+---------------------------------------------------------------------------
  29678769 | uuid:ee1ea1c15ff22d1144e27856788d2316 | /mnt/fedora/objects/2015/0429/13/33/uuid_ee1ea1c15ff22d1144e27856788d2316
```

Většinou Kramerius pracuje s PIDy jako Stringy a je mu jedno, jestli dostane validní UUID. Výjimkou je IIIF image api, které validní UUID očekává, to opravím. Ale otázkou zůstává jestli to takto necháme v repozitáři.

**Comment by leiblix** [comment]
Kromě UUID bez pomlčky je chyb podstatně míň:

```
 tokendbid |                         token                          |                                            path                                            
-----------+--------------------------------------------------------+--------------------------------------------------------------------------------------------
    999795 | uuid:000200246                                         | /mnt/fedora/objects/2011/0810/17/51/uuid_000200246
   1152782 | uuid:000722763                                         | /mnt/fedora/objects/2012/0116/22/29/uuid_000722763
   1162994 | uuid:000648000                                         | /mnt/fedora/objects/2012/0225/13/54/uuid_000648000
   1243402 | uuid:000724323                                         | /mnt/fedora/objects/2012/0404/11/41/uuid_000724323
   1841301 | uuid:123                                               | /mnt/fedora/objects/2012/0904/17/50/uuid_123
   2394074 | uuid:8dbb1770-42c7-11e2-9b88-0050568727e51             | /mnt/fedora/objects/2012/1220/22/00/uuid_8dbb1770-42c7-11e2-9b88-0050568727e51
   3437672 | uuid:bcc97590-87c6-11e2-b238-005056827e5               | /mnt/fedora/objects/2013/0426/15/45/uuid_bcc97590-87c6-11e2-b238-005056827e5
   8481859 | uuid:ed1809a0-1e62-11e2-bec6-005056827e51-005056827e51 | /mnt/fedora/objects/2013/0131/11/12/uuid_ed1809a0-1e62-11e2-bec6-005056827e51-005056827e51
   9192642 | uuid:2fdd0b0-8c83-11e2-8593-005056827e52               | /mnt/fedora/objects/2013/0316/07/47/uuid_2fdd0b0-8c83-11e2-8593-005056827e52
  22408191 | uuid:cbf25620-624c-11e3-9ea2-5ef3fc9ae8                | /mnt/fedora/objects/2014/1201/23/05/uuid_cbf25620-624c-11e3-9ea2-5ef3fc9ae8
```

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
