### ISSUE TITLE
Mazání z imageserveru

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#40]
Proces mazání v K5 maže data z fedory a solr, ale nechává obrázky na imageserveru.
Chtělo by to projít imageserver a zjistit, co je tam navíc, případně upravit proces mazání v K5.
Potenciální problém: v imageserveru nejsou jen obrázky pro Krameria.

**Comment by zabak** [comment]
Nicméně cílem je, aby všechny obrázky v imageserveru byly v Krameriu, takže minimálně bychom našli všechny kandidáty (a ano, bude tam spousta map a grafik)

**Comment by Jenyk** [comment]
Najdeme, co se liší, a potom to bude potřeba protřídit - určitě jsou tam i pohrobky ze smazaných dokumentů

**Comment by honza-rychtar** [comment]
Nez zacnete cpat vsechny mapy a grafiky do Krameria, tak se zamyslete nad struktorou trochu. Uz ted mapy v Krameriovi MZK, Olomouce nebo Budejovic jsou naprosto neprehledne. Stovky jednostrankovych dokumentu - nema to strukturu a v kazdem klientovi je prochazeni map nepohodlne - nesouvisle dokumenty na nejvyssi urovni chovajici se jako jednostrankove monografie, byt s modelem map.
Prochazeni je pak taky neprehledne, kdyz se do Krameria prida 300 map, tak se pres ne clovek ani nedoklika k nejake knize, pritom by se tech 300 map dalo sbalit do jednoho dokumentu (pokud spolu nejak souvisi).

A pokud budete chtit pridat Mollovu sbirku, tak to mate 12 tisic obrazku - pokud by se Krameria vsechny pridaly jako samostatne dokumentu s modelem map nebo graphic, tak ho zahltite. Pritom by Mollova sbirka mohla byt vedena jako jeden dokument.

Dala by se pouzit struktura pro periodika.
periodical - Mollova mapova sbirka
periodicalvolume - Ceske Zeme, Burgundsky kraj, Rakousky Kraj, ....
periodicalitem - Cechy, Morava, Slezsko, ...
Pak na urovni prohlizecky vsechny mapy ze Slezska

Lepsi by bylo pridat do Krameria podporu obecneho modelu, kde by byl korenovy model, ktery by obsahoval vnitrni model a vnitrni model by zase obsahoval bud vnitrni model nebo stranku.
Aby se dal nasimulovat libovolny strom o libovolne hloubce, ktery by nebyl vazany na konkretni typ dokumentu (periodika, zvukove nahravky, ...).
Ono uz i ta Mollova sbirka potrebuje jeste o jednu uroven navic nez u periodik - jeste je tam cleneni na Atlas Austriacu a Atlas Germanicus.

V klientech by se takovyto model prochazel po vrstvach. Podobne jako periodika, jen by to nebylo pojmenovane (rocnik, cislo) a bylo by to obecne.
Takto si i Mollovu sbirku s 12 tisici dokumenty dokazu predstavi v Krameriovi s prehlednym a pohodlnym prochzenim bez toho, aby to zastinilo ostatni dokumenty.

**Comment by leiblix** [comment]
@honza-rychtar @zabak Dovolil jsem si k importu map a grafik napsat nové issue https://github.com/moravianlibrary/kramerius/issues/41, ať se to tady moc nezaplevelí.

**Comment by leiblix** [comment]
Kromě smazání současných pohrobků se musíme domluvit (které nebudeme provádět před vyřešením issue https://github.com/moravianlibrary/kramerius/issues/41) jak zamezit vznikání dalších.

Momentálně má Kramerius do stromu imageserveru právo pouze pro čtení (kromě jedné malé teď nepodstatné výjimky) a myslím, že to není vhodné z bezpečnostních důvodů měnit.

Jediný server, kdo může v imageserveru objekty měnit/mazat je pouze nový server editoru, který je dostupný pouze z vnitřní sítě MZK. Editor mazat objekty z Fedory umí, ale nepoužíváme to.

**Comment by FoxKyong** [comment]
Stejný problém je, když, kvůli jakýmkoli problémům v balíků pro import, ten import spadne. Ani v tomto případě si to Kramerius po sobě "neuklidí" a nechá vše, jak v podstatě nechal.

**Comment by leiblix** [comment]
@FoxKyong Ano, na to je potřeba si dávat pozor. Proto v MZK vždy
1. provedeme prvně konverzi bez importu (dá se to odkškrtnout v GUI) - během toho se nakopírují obrazová data do imageserveru a vytvoří FOXML - během tohoto procesu se obvykle chyby nevytvoří
2. následně už jenom importujeme FOXML, přes klasický foxml-import. Tady to je pravděpodobnost pádu častější, tak je vhodné, že se to dá pouštět opakovaně.

Kromě toho obrazová data z těchto importů obvykle importujeme do zvláštního adresáře, např. když je v konfiguračním souboru `migration.properties`

```
convert.useImageServer=true
convert.imageServerTilesURLPrefix=http://imageserver.mzk.cz/other/priklad
convert.imageServerImagesURLPrefix=http://imageserver.mzk.cz/other/priklad
convert.imageServerSuffix.tiles=
convert.imageServerSuffix.big=/big.jpg
convert.imageServerSuffix.thumb=/thumb.jpg
convert.imageServerSuffix.preview=/preview.jpg
convert.imageServerDirectory=/data/imageserver_other/priklad
convert.imageServerSuffix.removeFilenameExtensions=true
```

tak mám zaručeno, že všechno nové importované bude v adresáři /data/imageserver_other/priklad a můžu si to už kontrolovat (a případně smazat).

**Comment by jkremlacek** [comment]
V ceske expedici bylo na toto téma otevřeno issue na rozšíření funkcionality:

https://github.com/ceskaexpedice/kramerius/issues/679

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
