### ISSUE TITLE
Import grafik a map do Krameria

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#41]
Spousta dokumentů je pouze v imageserveru (a přímo do něj je linkováno z Alephu), ale už nejsou v Krameriu, což @pavluska chtěla vyřešit, přikládám popis úkolu:

Jde mi o grafiky (a možná i mapy), tedy obvykle jednoobrázkové maximálně dvojobrázkové veci. V imageserveru uz jsou. Takže potřebuju: 1. Stáhnout záznam z Alephu a zkonvertovat do MODS a DC (nebo to brát z OAI, kde by už měl být zkonvertovaný?) Případně doplnit - ať je tam i místo uložení a signatura.
2. Poznat na základě záznamu, jestli to bude model mapa nebo grafika (ale to není nutné, můžu to napsat sama jako vstupní info tomu skriptu).
3. Vytvořit FOXML s tím, že odkazy na obrázky najdu v imageserveru, strukturální metadata budou prostě podle pořadí čísla stránek 1,2 (víc by němelo ani být) a typ normalPage.
4. Vzniklá FOXML naimportovat a zaindexovat
5. Vytvořit dokument, který může Tomáš Prachař naimportovat do Alephu, kde budou sysna/čárové kódy a odkazy na ty digitální dokumenty v K4 a další věci, co jsou potřeba. Přesnou podobu by ti Tomáš řekl, posílají mu to tak i z NDK, je to tušim nějaké xml. Mně to zároveň poslouží k tomu, abych naimportované dokumenty prošla a zkontrolovala pořadí stránek atd.

Také máme od Pavly mějaký seznam https://docs.google.com/a/mzk.cz/spreadsheet/ccc?key=0AlhyhqrXs6dtdFhtcnJWVEFXMHRVT3B3LWRCS3VmcXc (nevím jak je moc kompletní, asi nebude obsahovat dále zmiňovanou Mollovu sbírku).

K tomuto měl @honza-rychtar velmi cennou připomínku: 
Nez zacnete cpat vsechny mapy a grafiky do Krameria, tak se zamyslete nad struktorou trochu. Uz ted mapy v Krameriovi MZK, Olomouce nebo Budejovic jsou naprosto neprehledne. Stovky jednostrankovych dokumentu - nema to strukturu a v kazdem klientovi je prochazeni map nepohodlne - nesouvisle dokumenty na nejvyssi urovni chovajici se jako jednostrankove monografie, byt s modelem map.
Prochazeni je pak taky neprehledne, kdyz se do Krameria prida 300 map, tak se pres ne clovek ani nedoklika k nejake knize, pritom by se tech 300 map dalo sbalit do jednoho dokumentu (pokud spolu nejak souvisi).

A pokud budete chtit pridat Mollovu sbirku, tak to mate 12 tisic obrazku - pokud by se Krameria vsechny pridaly jako samostatne dokumentu s modelem map nebo graphic, tak ho zahltite. Pritom by Mollova sbirka mohla byt vedena jako jeden dokument.

Dala by se pouzit struktura pro periodika.
periodical - Mollova mapova sbirka
periodicalvolume - Ceske Zeme, Burgundsky kraj, Rakousky Kraj, ....
periodicalitem - Cechy, Morava, Slezsko, ...
Pak na urovni prohlizecky vsechny mapy ze Slezska

Lepsi by bylo pridat do Krameria podporu obecneho modelu, kde by byl korenovy model, ktery by obsahoval vnitrni model a vnitrni model by zase obsahoval bud vnitrni model nebo stranku.
Aby se dal nasimulovat libovolny strom o libovolne hloubce, ktery by nebyl vazany na konkretni typ dokumentu (periodika, zvukove nahravky, ...).
Ono uz i ta Mollova sbirka potrebuje jeste o jednu uroven navic nez u periodik - jeste je tam cleneni na Atlas Austriacu a Atlas Germanicus.

V klientech by se takovyto model prochazel po vrstvach. Podobne jako periodika, jen by to nebylo pojmenovane (rocnik, cislo) a bylo by to obecne.
Takto si i Mollovu sbirku s 12 tisici dokumenty dokazu predstavi v Krameriovi s prehlednym a pohodlnym prochzenim bez toho, aby to zastinilo ostatni dokumenty.

**Comment by zabak** [comment]
Je tam minimálně ještě jedna úroveň a to úroveň mapy na více listech, resp. občas i knihy/atlasu, který byl rozebrán na jednotlivé listy, které jsou nesvázané součástí sbírky ale mělo by se s nimi pracovat jako s jednou entitou. No a v případě map na více listech by vůbec nebylo od věci moct zoomovat nad všemi listy, seskládanými správně dle kladu listů najednou.

Co se týče struktury mapové sbírky, Mollova sbírka je jen část celkové sbírky a máme na ni separátní prezentaci. V Krameriu by mělo být vše prezentováno dohromady, ať už v rozšířené struktuře vycházející z Mollovy sbírky, nebo jinak. Ale mimo geografického hlediska je i hledisko časové: chceme jakoukoli takovou strukturu mít i pro mapy 20 století?

Neberu ale argument o přidání 300 map přes které se neproklikám ke knížkám (předpokládám že se jedná o "nejnovější", protože to je holt život. Jindy se tam zase přidá 200 gramodesek...

**Comment by LenkaKravecova** [comment]
Ten seznam je neaktuální. Seznam grafik, které jsme dohledali (tzn. víme, kde je máme), je tady: https://docs.google.com/spreadsheets/d/12n-ag5ZwQMZj0aDsditSNingHNuzMcK95DW5vjZK2wc/edit#gid=416480557 (Skř.1, Skř.2, BKB). Je jich kolem 3200. V tabulce by měl být celkový přehled o digitalizovaných hist. fondech.

**Comment by jirduf** [comment]
Ahoj všem,

další skupinou budou jistě série map - jde o soubory řádově o velikosti stovek (vojenská mapování, turistické mapy apod.), kde by bylo dobré, aby byly dané k sobě podle pole 490 (830), což je název edice. Ten by tvořil první úroveň a pod ní by se to členilo dál. Co se grafik týče, mám v plánu je v druhé půlce příštího roku nechat doskenovat a následně začít staré i nové vytvořené skeny nalévat do Krameria. Vedle toho vznikne web grafiky.mzk.cz jako obdoba mapy.mzk.cz, tj. velký soubor grafik dostane nějakou strukturu, aby se k nim dalo dostat jinak než vyhledáním podle názvu/autora. Možná bych teda s přeléváním z imageserveru počkal až to bude hotové. Mimo to ještě zbude docela dost map, které nespadnou ani do sérií, ani do Molla - zde bude třeba ještě přemýšlet, jak s nima naložit.

jd

**Comment by LenkaKravecova** [comment]
@honza-rychtar :
"Neberu ale argument o přidání 300 map přes které se neproklikám ke knížkám (předpokládám že se jedná o "nejnovější", protože to je holt život. Jindy se tam zase přidá 200 gramodesek..." ( @zabak )
300 byl jen priklad (to uz je bezne ted), slo mi spis o 18 tisic - pokud by se to nestrukturovalo, tak by to v klientech mohl byt problem - nejde jen o nejnovejsi, ale i prazdne hledani, prochazeni (autori, keywords, jazyk pak prebiji vsechny ostatni dokumenty), filtrovani pres facety (jsou serazeny podle vyskytu a zase by tady autori, keywors a jazyk tech grafik a map vytlacily zbyle (aktualni) nekam nakonec) a vlastne i samotne hledani, kdyz mi napr. na hledany retezec vybehne 500 grafik z jedne sbirky, ktere musim vsechny projet, nez se dostanu na hledanou knihu za nima.

Par veci, ktere muzou byt uzitecne (neco resila Pavla, neco ja a nevim jestli se ted tim nekdo dalsi zabyval). K te tabulce s grafikama v imageserveru od Pavly co zminoval Martin. Resili jsme to nekdy pred 4 roky. Nikdo moc nevedel co tam vsechno mate, tak jsem pro ruzne signatury s obrazky tenkrat vygeneroval stranky ve stylu mapy.mzk.cz.

Z webu se na to proklikat neda, ale pres primy link http://mapy.mzk.cz/ostatni-sbirky-v-mzk/schramova-sbirka/ se na to stale da dostat. Je to Schramova sbirka a pak dalsi grafiky, mapy, fotky, pohlednice, ... z dalsich signatur. Ty signatury jsem jeste rozclenoval podle geografickeho klice, at to nejsou jen dlouhe seznamy.

Tenkrat se to nejak zazdilo - verejne jste to zpristupnit nechteli a bylo v planu to projit, opravit a vytvorit pro to specialni web grafiky.mzk.cz. Nevim jestli se to za ty 4 roky nekam pohnulo. Pokud ne, tak ten link se vam muze hodit, at vidite co v tom imageserveru (krom mollovy sbirky a STMpa) vlastne je - nejen jako seznamy sysen a signatur.

V bazi MZK03 je cca 26 tisic zaznamu s linkem do imageserveru (tech linku je celkem skoro 30 tisic).
Predpokladam, ze tohle jsou prave ty zaznamy, ktere by se mely dostat do Krameria. Pokud odectu Rajhrad, zustane 18 tisic zaznamu, pokud odectu i Mollovu sbirku, tak zustane neco pres 5 tisic zaznamu a 6 tisic linku do imageserveru. Jsou to STMpa (soucast mapy.mzk.cz), signatury pro ktere je ta ukazkova prezentace (http://mapy.mzk.cz/ostatni-sbirky-v-mzk/schramova-sbirka/) a navic je tam jeste nekolik signatur (STS, Ks, ...).

Celkem tedy 18 tisic zaznamu (19439 obrazku k 27.8.2015) - pocitano bez Rajhradu, coz jsou vetsinou titulni listy, ty nemaji v Krameriovi smysl.

**Comment by LenkaKravecova** [comment]
@zabak :
U nejnovějších si vždycky můžeme dát tu práci a přihodit po importu map pár knih (to stejně zajistí NDK, jakmile Kramerie sloucime). Co se týče faset, tak Mollova sbírka ovlivňuje jejich podobu i ve VuFindu. V Krameriu při vyhledávání by se dalo zapracovat na relevanci (třeba o fous snížit relevanci u map a grafik, aby se před ně dostaly knížky, jsou-li). Navíc k odfiltrování grafik a map můžeš použít fasetu s typem dokumentu. Ale tím nezavrhuju tvůj návrh univerzální hierarchie, jen si nejsem jistý, jestli to není spíš impuls k vylepšení struktury virtuálních sbírek - Mollova sbírka by měla být prezentovatelná přes virtuální sbírky, což teď rozhodně nejde.

Ta grafika je pořád v plánu (na příští rok).

**Comment by LenkaKravecova** [comment]
@jirduf :
Ještě k Mollovi - je tam nekorektní věcné třídění napříč celou sbírkou, kdy je všude nasekané  historické knihovní fondy" a "mapové sbírky". Nejde samozřejmě o popis obsahu těch map (= věcný popis, pole 650), spíš by to patřilo mezi formální deskriptory (pole 655, které bohužel vufind ve fasetách nemá). Nejčistější cestou by tedy bylo záznamy upravit. Automatický převod by byl jednoduchý, ale aby nedošlo k nejednotnosti zpracování v rámci celé MZK03, museli bychom ho provést nad celým starým fondem. To by určitě vygenerovalo spoustu chyb, o kterých jsme netušili a
které můžou být dost časově náročné na manuální opravy. Optimistický pohled je, že na to budu mít čas ca za rok :-(

**Comment by LenkaKravecova** [comment]
Členit mapy dle edice mi přijde jako dobrý nápad. @jirduf budeme rádi za různé tipy, jaké celky u map vytvořit, pokud se teda dohodneme na tom, že by mapy nešly do Krameria po jednom obrázku. Ty vícestránkové mapy se můžou členit samostatně, ale nevím. Dohromady v jednom stromě s ostatními si to taky dokážu představit.

Co se týče grafik, těžko říct, to by stálo za to pak zkonzultovat např. s Jitkou Machovou, jak by se daly pospojovat v nějaké celky. Grafiky jsou uložené na min. 20 signaturách, tématicky to rozdělené ale nejspíš není. Pro vyhledávání by to bylo určitě příjemnější, než tam mít 4500-5000 samostatných dokumentů (když počítám i ty grafiky, co se ještě bude digitalizovat). Zároveň je tu ale otázka prohlížení.

**Comment by jirduf** [comment]
ty mapy by bylo třeba dělat ručně, až to bude aktuální, tak připravím návrh. Grafiky budu mít na starosti příští rok asi taky já, zatím ale pořádně nevím, co v tom souboru vlastně všechno je a jak je rostlý. Navíc Jitka M. říká, že jich bude třeba něco přes 1000 ještě naskenovat - teprve potom uvidíme, co bude patřit k sobě a můžeme se pohnout dál.

Je ale vytváření takových vrstev, které byly původně stavěné na periodika, korektní? Taková ohnutí pravidel použití se často vracejí jako bumerang. Jak by vypadala metadata?

**Comment by LenkaKravecova** [comment]
Grafiky a mapy už jsou v Krameriu. Zavírám.
