### ISSUE TITLE
TLS (https://) certifikáty

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#43]
Vygenerovat a nastavit TLS certifikáty pro všechny "vnější" služby.

Tzn:
- kramerius.mzk.cz
- editor.staff.mzk.cz
- medit.mzk.cz

Pro kramerius.mzk.cz potřebuji mít jistotu, že nerozbiji žádného klienta (@honza-rychtar @ovyhlidal)
 . Je možno testovat oproti https://docker.mzk.cz 

Nareplikoval jsem pár veřejných dokumentů.

periodikum:
https://docker.mzk.cz/search/handle/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6

monografie:
https://docker.mzk.cz/search/handle/uuid:9af9b660-fd9f-11e2-9923-005056827e52

soundunit:
https://docker.mzk.cz/search/handle/uuid:59e708b6-c462-4610-90c5-ac5ca030050a

V případě potřeby přidám další dokumenty pro otestování.

**Comment by leiblix** [comment]
iOS je dle @ovyhlidal v pohodě (Connecting to a URL via TLS is trivial. When you create an NSURLRequest object to provide to the initWithRequest:delegate: method, specify https as the scheme of the URL instead of http. The connection uses TLS automatically with no additional configuration.)

**Comment by leiblix** [comment]
Pro:
    editor.staff.mzk.cz
    medit.mzk.cz
je potřeba nastavit certifikát přímo v tomcatu (nejsou za reverzní proxy) - je potřeba nastavit keystore.

**Comment by jirikrepl** [comment]
Vaše žádost o vydání certifikátu s předmětem ... byla schválena.
Žádost nyní čeká na zpracování certifikační autoritou.

**Comment by jirkadev** [comment]
Vygeneroval jsem žádost znovu, správně pro všechny 3 servery. V potvrzovacím mailu je odkaz na stažení certifikátu (jakmile bude vygenerován) Nevšiml jsem si ho a čekal jsem na další mail.

takže certifikát by měl být vygenerován rychle

**Comment by jirkadev** [comment]
Certifikát byl nasazen na medit.mzk.cz a editor.staff.cz, ještě chybí kramerius (zatím jen testovací). Budu to dál řešit zde https://github.com/moravianlibrary/MEditor/issues/44
