### ISSUE TITLE
Mikulov import FOXML, špatné cesty

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#45]
Při importu Mikulova se do Krameria dostaly špatné FOXML

odkazy na thumbnaily jsou se suffixem jpg
https://gist.github.com/MartinRumanek/9dafebfdf0ff4e38829d

a tiles je tam dvakrát.

problem se bude týkat podmnožiny dokumentů z procesu http://kramerius.mzk.cz/search/inc/admin/_processes_outputs.jsp?uuid=2835829c-1f68-4402-a3ae-f0fb616d0ae7 (nutná autentizace)

**Comment by Jenyk** [comment]
Proces Import FOXML je od verze K5.0.0 doplněn o booleovský parametr updateExisting. Při hodnotě false se importní proces chová dosavadním způsobem (existující soubory jsou zachovány a pouze doplněny RDF vazbami z nově imporotvaných objektů) , při hodnotě true budou FOXML objekty se stejným PID, které již existují v úložišti Fedora, smazány a nahrazeny nově importovanými, včetně všech RDF vazeb.
viz https://github.com/ceskaexpedice/kramerius/wiki/MenuAdministrace#import-dokument%C5%AF-ve-form%C3%A1tu-foxml-krameria-4

**Comment by jirkadev** [comment]
Mělo by to být OK.

S parametrem ingest.updateExisting=true je záznamy ve fedoře přepsaly, proces importu foxml "Mikulova" proběhl bez chyb.

http://fedora.mzk.cz/fedora/objects/uuid:f2a604e0-f16d-11df-9ba0-000d606f5dc6/objectXML

http://kramerius.mzk.cz/search/inc/admin/_processes_outputs.jsp?uuid=6ab99eb4-a8a6-44d8-9dcc-10d2a79c5f12
