### ISSUE TITLE
Hromadné opravy v Krameriu

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#46]
Opravy dle dokumentu od Pavly 

https://docs.google.com/spreadsheets/d/1wyslvJa1vOLUwOSQ7s3kRnKB82A08mq1ITK5lXII_9Y/edit#gid=850398819

**Comment by Jenyk** [comment]
A seznam haluzí (postupně doplňovat): https://docs.google.com/spreadsheets/d/1Ol-vLStaHDhjeznJAtQ8-7aV0ISw2DzvyPU5Lq9QqTY/edit#gid=0

**Comment by jirkadev** [comment]
# Periodika, která nemají přiřazený ročník

http://kramerius.mzk.cz/search/handle/uuid:3abab84f-aa4b-11e1-8a52-0050569d679d 
http://fedora.dk-back.infra.mzk.cz/fedora/get/uuid:3abab84f-aa4b-11e1-8a52-0050569d679d 

http://kramerius.mzk.cz/search/handle/uuid:8435e20b-b789-41eb-b35c-192255a15590 
http://fedora.dk-back.infra.mzk.cz/fedora/get/uuid:8435e20b-b789-41eb-b35c-192255a15590
