### ISSUE TITLE
Oaiprovider

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#48]
Zprovoznit oaiprovider pro oba Kramerie (na zvláštním stroji).

**Comment by Jenyk** [comment]
OAI už sbírá (v docker-compose.yml byla databáze fedora3 místo ritriples)

**Comment by leiblix** [comment]
Starý OAI-PMH provider už používat nebudeme, nahrazuje ho https://github.com/ceskaexpedice/kramerius/tree/master/installation/oai
