### ISSUE TITLE
Neúplný dokument

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#5]
uuid:4a477cf8-31f3-4a42-9e81-3a43e77fcc32

Ve fedoře jsou odkazy na stránky, ale foxml chybí (jsou jen foxml příloh)

**Comment by leiblix** [comment]
U tohoto čekáme na obnovu dat?

**Comment by Jenyk** [comment]
Těžko říct. Netuším, kdy a jak k tomu došlo. Podívám se potom, jak to v té záloze vypadá, ale nejspíš to budeme muset prostě smazat.

**Comment by Jenyk** [comment]
Tak v záloze je to to samý. Budeme to muset smazat.

**Comment by LenkaKravecova** [comment]
Pokud s tím nejde nic dělat, můžeme obrázky naimportovat do Krameria znovu (jinak v imageserveru už jsou u tohoto sysna 001046768 obrázky dvakrát, tak by se to mělo smáznout).

**Comment by Jenyk** [comment]
Tak to bude potřeba vytvořit celé znova.
Foxml kořene (rukopis): https://gist.github.com/Jenyk/c048b7829e1326c310dc
Obrázky jsou tu:  http://imageserver.mzk.cz/mzk03/001/046/768/
A o adresář níž znova dokonce ve správném pořadí: http://imageserver.mzk.cz/mzk03/001/046/768/2610397694/

**Comment by LenkaKravecova** [comment]
Toto byl asi nějaký nepovedený pokus. Kompletní dokument je zde: http://kramerius.mzk.cz/search/handle/uuid:96e01098-d9dd-4e33-b72c-4190068b383d. Takže zavírám.
