### ISSUE TITLE
Chybné URL obrázků (Jan Amon: Janua lingurum..), nestandardní cesty v imageserveru?

### ISSUE THREAD

**Issue by jirkadev** [moravianlibrary/kramerius#53]
Nefunkční odkaz:
http://imageserver.mzk.cz/2619298350/001/050/681/2619298350/1050681_00008/big.jpg

Takto by měl vypadat:
http://imageserver.mzk.cz/mzk03/001/050/681/2619298350/1050681_00008/big.jpg

**Comment by leiblix** [comment]
Obrazové datastreamy by měly být ve struktuře 
http://imageserver.mzk.cz/báze/XX/XX/XXX/jménoobrázku/*

kde XXX/XXX/XXX je nasekané SYSNO

takže by se to mělo přesunout na adresu http://imageserver.mzk.cz/mzk03/001/050/681/1050681_00008/*

a z ní se to linkovat.

Stačí měnit datastream rels-ext, není nutno reindexovat.

**Comment by jirkadev** [comment]
Napsán groovy skript. Obrázky přesunuty na imageserveru, foxml opraveno. Odkaz na knihu v krameriu http://kramerius.mzk.cz/search/i.jsp?pid=uuid:16dbc04a-3884-4385-9820-8ab4d2cca497
