### ISSUE TITLE
Title v response /children ma jiny typ

### ISSUE THREAD

**Issue by ovyhlidal** [moravianlibrary/kramerius#54]
Pokud poslu request na /children pro monograph dostanu v response title jako array. Pokud ovsem poslu stejny request pro soundrecording, tak je v response title jako string. Z logickeho uhlu pohledu by tento typ mel byt u obou requestu stejny. 

Request pro monograph:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22/children

Request pro soundrecording:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:59e708b6-c462-4610-90c5-ac5ca030050a/children

**Comment by Jenyk** [comment]
To není otázka modelu dokumentu, ale bug krameria při vracení odpovědi v json.
Viz https://github.com/ceskaexpedice/kramerius/issues/211

**Comment by leiblix** [comment]
Už je to opravené. Nasadil jsem aktuální verzi na test http://krameriustest.mzk.cz/search/api/v5.0/item/uuid:530719f5-ee95-4449-8ce7-12b0f4cadb22/children

Zítra to dáme na produkci.

**Comment by leiblix** [comment]
Domluvil jsem se s @ovyhlidal, že zatím to nasazení odložíme, rozbili bysme mu tím jeho testovací release (počkáme na další).

**Comment by zabak** [comment]
Nerozbije to náhodou i klienta pro Android?

**Comment by leiblix** [comment]
@zabak V pátek jsme to s @honza-rychtar zkoušeli a bylo to v pohodě.

**Comment by ovyhlidal** [comment]
Tak pokud to nerozbije klienta pro Android, tak bych osobne navrhnul to nasadit co nejdriv a ja hned vydam novou testovaci verzi iOS klienta, kde tohle bude upravene, at na to nemusime porad myslet. 
Co na to @zabak @MartinRumanek ?

**Comment by leiblix** [comment]
Honza zjistil, že v upstreamu nefunguje korektně volání reindexací přes remote api (starší verze je ok), bude vhodné to před nasazením vyřešit.

@Jenyk dopíšeš prosím stručně podrobnosti?

**Comment by leiblix** [comment]
Blokováno https://github.com/ceskaexpedice/kramerius/issues/324

**Comment by leiblix** [comment]
Vyřešeno aktualizací.
