### ISSUE TITLE
Některé ročníky jsou připojeny do více periodik, případně nejsou připojeny nikam

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#55]
Kazdy volume by mel byt ve Fedore pripojeny prave k jednomu periodiku.

Vypis ze skriptu https://gist.github.com/MartinRumanek/3fd15c7e0d2ccb9f9e45:

volume uuid:894b6c30-70c3-11e0-9c4e-000bdb925259 je pripojeno do vice objektu
volume uuid:eec0bb10-7177-11e0-869f-000bdb925259 je pripojeno do vice objektu
volume uuid:d39c0910-7191-11e0-af80-000bdb925259 je pripojeno do vice objektu
volume uuid:10b6ac90-71a3-11e0-99dc-000bdb925259 je pripojeno do vice objektu
volume uuid:992eb190-724c-11e0-abfb-000bdb925259 je pripojeno do vice objektu
volume uuid:b10bafe0-71b4-11e0-8870-000bdb925259 je pripojeno do vice objektu
volume uuid:acb36280-9293-11e0-88fa-000bdb925259 je pripojeno do vice objektu
volume uuid:f58fa9f0-7a6a-11e0-91ea-000bdb925259 je pripojeno do vice objektu
volume uuid:4fe3ca20-7a6c-11e0-b10b-000bdb925259 je pripojeno do vice objektu
volume uuid:9b8bbeb0-92a9-11e0-b622-000bdb925259 je pripojeno do vice objektu
volume uuid:b186486d-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b186486b-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b1862156-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b1862157-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b1862158-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b1862159-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b186215a-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:b186486c-435d-11dd-b505-00145e5790ea je pripojeno do vice objektu
volume uuid:321a0cb0-7f52-11e2-8d9d-5ef3fc9bb22f je sirotek
volume uuid:3455d5af-e23b-4699-9d7b-6aad709e3880 je sirotek
volume uuid:32c0baf5-f7ad-4e69-80c5-c5e306b2e3a3 je pripojeno do vice objektu
volume uuid:2a52d71a-c9f6-450d-8acc-7bd5e199bd0e je sirotek
volume uuid:bcf484ba-a225-48cb-a33d-a0e7e8c41d85 je sirotek
volume uuid:e264435a-a6db-4356-8632-64981f71f2f6 je sirotek
volume uuid:7679bb90-c4cd-45bd-adf9-687d857da528 je sirotek
volume uuid:80f9ecdb-334e-4378-981d-60792148a9d0 je sirotek
volume uuid:d5141175-18d3-4fbd-9de2-e32837e406bb je sirotek
volume uuid:a3cc5955-c1a7-4224-a99d-bc493d007a39 je pripojeno do vice objektu
volume uuid:eccbed0a-4c38-43b6-ac86-977f34897a58 je sirotek
volume uuid:f198ac36-f50b-49c5-9bc4-68c497bacf36 je sirotek
volume uuid:c910fc76-0160-4218-8eb5-3318c2143221 je sirotek
volume uuid:a7e8ec93-4a9c-4af0-9a11-9a7f75992567 je sirotek
volume uuid:72368992-fd48-4085-a162-bec3eb5860d9 je sirotek
volume uuid:20d29eaf-4ae8-419b-ad1c-da311e4b5d56 je sirotek
volume uuid:c9852638-aaca-4d8b-b964-6016e57e0d65 je sirotek
volume uuid:66abd590-66d5-4bca-ae08-2ac27b366d61 je sirotek
volume uuid:2a7d3f9c-d5f6-4a9b-aa50-d19f9e845204 je sirotek
volume uuid:a87698f2-79dd-4413-9d4d-b0838318f65a je sirotek
volume uuid:e239a111-9369-407d-b3a8-0857a5a1694f je sirotek
volume uuid:7e339099-43fc-4cbd-97e0-5380955bd1df je sirotek
volume uuid:bdfeb00c-9f79-4f9e-9e02-bc7f8e3a9bcc je sirotek
volume uuid:09ef9d83-fb42-46f1-9a19-71de275d24fd je sirotek
volume uuid:963bb9e8-458a-47f3-96ea-6dff5b7826b1 je sirotek
volume uuid:260f6533-6b5f-447c-b46b-0b6eff79fe9b je sirotek
volume uuid:13525a03-edd0-11e1-89ef-0050569d679d je sirotek
volume uuid:7bc15620-ed9a-11e1-b9b5-0050569d679d je sirotek
volume uuid:d2907210-ed94-11e1-b9b5-0050569d679d je sirotek
volume uuid:25203057-ed92-11e1-b9b5-0050569d679d je sirotek
volume uuid:0864fb74-ed8e-11e1-b9b5-0050569d679d je sirotek
volume uuid:1f6a1133-ed8a-11e1-b9b5-0050569d679d je sirotek
volume uuid:c2f3aa22-ed84-11e1-b9b5-0050569d679d je sirotek
volume uuid:f90db86f-ed83-11e1-b9b5-0050569d679d je sirotek
volume uuid:27d514c8-ed83-11e1-b9b5-0050569d679d je sirotek
volume uuid:56eb0651-ed82-11e1-b9b5-0050569d679d je sirotek
volume uuid:7ae0c32a-ed81-11e1-b9b5-0050569d679d je sirotek
volume uuid:13ab365b-ed80-11e1-b9b5-0050569d679d je sirotek
volume uuid:053f9d76-ed7f-11e1-b9b5-0050569d679d je sirotek
volume uuid:0e2407ff-ed7e-11e1-b9b5-0050569d679d je sirotek
volume uuid:27476244-ed7d-11e1-b9b5-0050569d679d je sirotek
volume uuid:1d4b0a4f-ed7c-11e1-b9b5-0050569d679d je sirotek
volume uuid:e856055e-ed7a-11e1-b9b5-0050569d679d je sirotek
volume uuid:d1200db9-ed79-11e1-b9b5-0050569d679d je sirotek
volume uuid:adbfec72-ed78-11e1-b9b5-0050569d679d je sirotek
volume uuid:87e1d1d7-ed77-11e1-b9b5-0050569d679d je sirotek
volume uuid:6251620a-ed76-11e1-b9b5-0050569d679d je sirotek
volume uuid:52bfcfed-d86e-11e1-967e-0050569d679d je sirotek
volume uuid:bb73f54c-d869-11e1-967e-0050569d679d je sirotek
volume uuid:9ed9c7eb-d863-11e1-967e-0050569d679d je sirotek
volume uuid:ba849058-d862-11e1-967e-0050569d679d je sirotek
volume uuid:ccb051f1-d861-11e1-967e-0050569d679d je sirotek
volume uuid:e0810ffa-d860-11e1-967e-0050569d679d je sirotek
volume uuid:e8386c43-d85f-11e1-967e-0050569d679d je sirotek
volume uuid:4f9f70b4-d85e-11e1-967e-0050569d679d je sirotek
volume uuid:14d161bf-d85d-11e1-967e-0050569d679d je sirotek
volume uuid:f9605968-d85b-11e1-967e-0050569d679d je sirotek
volume uuid:f2c5541d-d85a-11e1-967e-0050569d679d je sirotek
volume uuid:9f94dc16-d858-11e1-967e-0050569d679d je sirotek
volume uuid:3b457ed5-d857-11e1-967e-0050569d679d je sirotek
volume uuid:fc5ba610-d855-11e1-967e-0050569d679d je sirotek
volume uuid:b39a6d49-d854-11e1-967e-0050569d679d je sirotek
volume uuid:62c46a1e-d853-11e1-967e-0050569d679d je sirotek
volume uuid:17e4bd21-d852-11e1-967e-0050569d679d je sirotek
volume uuid:ecae894a-d850-11e1-967e-0050569d679d je sirotek
volume uuid:2e0f351d-d84f-11e1-967e-0050569d679d je sirotek
volume uuid:67290c06-d84d-11e1-967e-0050569d679d je sirotek
volume uuid:104c37cf-d84c-11e1-967e-0050569d679d je sirotek
volume uuid:e13b60a8-d84a-11e1-967e-0050569d679d je sirotek
volume uuid:d6a4766c-d849-11e1-967e-0050569d679d je sirotek
volume uuid:d5ae72f9-d848-11e1-967e-0050569d679d je sirotek
volume uuid:93fe7533-d847-11e1-967e-0050569d679d je sirotek
volume uuid:ee51b286-d845-11e1-967e-0050569d679d je sirotek
volume uuid:7429397f-d844-11e1-967e-0050569d679d je sirotek
volume uuid:549b5612-d843-11e1-967e-0050569d679d je sirotek
volume uuid:20ae249b-d842-11e1-967e-0050569d679d je sirotek
volume uuid:52ff4362-d841-11e1-967e-0050569d679d je sirotek
volume uuid:ead51e01-d83f-11e1-967e-0050569d679d je sirotek
volume uuid:f5630fdb-d83d-11e1-967e-0050569d679d je sirotek
volume uuid:f03703dc-d83c-11e1-967e-0050569d679d je sirotek
volume uuid:0bd87da7-d83c-11e1-967e-0050569d679d je sirotek
volume uuid:134897f8-d83b-11e1-967e-0050569d679d je sirotek
volume uuid:5150fb31-d83a-11e1-967e-0050569d679d je sirotek
volume uuid:aa15b3f0-d839-11e1-967e-0050569d679d je sirotek
volume uuid:072cd6d1-d839-11e1-967e-0050569d679d je sirotek
volume uuid:bad13553-8911-479a-9f13-7395afc385c9 je sirotek
volume uuid:a5e40e54-d838-11e1-967e-0050569d679d je sirotek
volume uuid:5ec1c20b-d838-11e1-967e-0050569d679d je sirotek
volume uuid:18eba4c9-d838-11e1-967e-0050569d679d je sirotek
volume uuid:bff8a636-d837-11e1-967e-0050569d679d je sirotek
volume uuid:7c382276-d837-11e1-967e-0050569d679d je sirotek
volume uuid:369ee80e-d837-11e1-967e-0050569d679d je sirotek
volume uuid:fcbb1c90-d836-11e1-967e-0050569d679d je sirotek
volume uuid:c3959802-d836-11e1-967e-0050569d679d je sirotek
volume uuid:27d2ac9e-d835-11e1-967e-0050569d679d je sirotek
volume uuid:769f7a37-d833-11e1-967e-0050569d679d je sirotek
volume uuid:1006efce-d832-11e1-967e-0050569d679d je sirotek
volume uuid:712efc42-d830-11e1-967e-0050569d679d je sirotek
volume uuid:4d32736c-d82f-11e1-967e-0050569d679d je sirotek
volume uuid:8834a3a4-d82b-11e1-967e-0050569d679d je sirotek
volume uuid:d2302405-d827-11e1-967e-0050569d679d je sirotek
volume uuid:440f9736-d824-11e1-967e-0050569d679d je sirotek
volume uuid:b0903854-d820-11e1-967e-0050569d679d je sirotek
volume uuid:f91e1f0d-d81c-11e1-967e-0050569d679d je sirotek
volume uuid:07cca74e-d819-11e1-967e-0050569d679d je sirotek
volume uuid:b901047e-d815-11e1-967e-0050569d679d je sirotek
volume uuid:4596cd68-d811-11e1-967e-0050569d679d je sirotek
volume uuid:9d0afc4b-d80e-11e1-967e-0050569d679d je sirotek
volume uuid:523b4aec-d80c-11e1-967e-0050569d679d je sirotek
volume uuid:4567bc0a-bde2-40a8-b7ea-601738b81390 je sirotek
volume uuid:1c43ce93-8338-4987-aa29-ed5f3483dc7d je sirotek
volume uuid:37294579-5c86-4434-9554-6deaadb951de je sirotek
volume uuid:626a0cc2-5402-4d8d-aaf9-d2f6d2b165b2 je sirotek
volume uuid:e0700c31-aae7-4266-afd6-87af2b8c9a11 je sirotek
volume uuid:580a4493-ed75-11e1-b9b5-0050569d679d je sirotek
volume uuid:c6f6f256-ed73-11e1-b9b5-0050569d679d je sirotek
volume uuid:3358ae6f-ed72-11e1-b9b5-0050569d679d je sirotek
volume uuid:01057e78-ed71-11e1-b9b5-0050569d679d je sirotek
volume uuid:f74c48f1-ed6f-11e1-b9b5-0050569d679d je sirotek
volume uuid:0ce1e965-ed6f-11e1-b9b5-0050569d679d je sirotek
volume uuid:2be4dd82-ed6e-11e1-b9b5-0050569d679d je sirotek
volume uuid:11182a6c-ed6d-11e1-b9b5-0050569d679d je sirotek
volume uuid:9e0d22df-ed6b-11e1-b9b5-0050569d679d je sirotek
volume uuid:4f416eb8-ed6a-11e1-b9b5-0050569d679d je sirotek
volume uuid:55e7822b-ed69-11e1-b9b5-0050569d679d je sirotek
volume uuid:47125144-ed68-11e1-b9b5-0050569d679d je sirotek
volume uuid:94c7c54b-ed67-11e1-b9b5-0050569d679d je sirotek
volume uuid:57c487ba-ed66-11e1-b9b5-0050569d679d je sirotek
volume uuid:a20a9304-ed64-11e1-b9b5-0050569d679d je sirotek
volume uuid:d64a14f5-ed63-11e1-b9b5-0050569d679d je sirotek
volume uuid:1285f670-ed63-11e1-b9b5-0050569d679d je sirotek
volume uuid:3a67bac1-ed62-11e1-b9b5-0050569d679d je sirotek
volume uuid:9960bcfa-ed61-11e1-b9b5-0050569d679d je sirotek
volume uuid:06daab19-ed61-11e1-b9b5-0050569d679d je sirotek
volume uuid:78cba25a-ed60-11e1-b9b5-0050569d679d je sirotek
volume uuid:24b76e8d-ed60-11e1-b9b5-0050569d679d je sirotek
volume uuid:e575bd44-ed5f-11e1-b9b5-0050569d679d je sirotek
volume uuid:a777fca2-ed5f-11e1-b9b5-0050569d679d je sirotek
volume uuid:fe8a4a01-f070-473b-9ca6-ccd9b5ae82b6 je sirotek
volume uuid:03784fdb-f60c-4698-be36-24cb73bcbb42 je sirotek
volume uuid:082a943d-da81-11e1-995a-0050569d679d je sirotek
volume uuid:1ae8db89-da81-11e1-b232-0050569d679d je sirotek
volume uuid:245f743a-da80-11e1-995a-0050569d679d je sirotek
volume uuid:550455a5-da7d-11e1-b232-0050569d679d je sirotek
volume uuid:c4ed8b36-da7b-11e1-995a-0050569d679d je sirotek
volume uuid:b5232f6a-da7b-11e1-b232-0050569d679d je sirotek
volume uuid:0d661525-da78-11e1-b232-0050569d679d je sirotek
volume uuid:1c14eecb-da78-11e1-995a-0050569d679d je sirotek
volume uuid:db3aa300-da74-11e1-995a-0050569d679d je sirotek
volume uuid:78a98cfc-da72-11e1-b232-0050569d679d je sirotek
volume uuid:88b69711-da72-11e1-995a-0050569d679d je sirotek
volume uuid:1ffa9157-da71-11e1-b232-0050569d679d je sirotek
volume uuid:2f5cdc7c-da71-11e1-995a-0050569d679d je sirotek
volume uuid:6e2578da-da6f-11e1-b232-0050569d679d je sirotek
volume uuid:18a1cc4d-da6e-11e1-b232-0050569d679d je sirotek
volume uuid:2728f9af-da6e-11e1-995a-0050569d679d je sirotek
volume uuid:3fe26418-da6c-11e1-995a-0050569d679d je sirotek
volume uuid:2de8f356-da6c-11e1-b232-0050569d679d je sirotek
volume uuid:04dc7cbf-da6b-11e1-995a-0050569d679d je sirotek
volume uuid:f600036d-da6a-11e1-b232-0050569d679d je sirotek
volume uuid:131b0ff7-da68-11e1-b232-0050569d679d je sirotek
volume uuid:eacb0ae4-da66-11e1-995a-0050569d679d je sirotek
volume uuid:e2957316-da66-11e1-b232-0050569d679d je sirotek
volume uuid:2daa4b9f-da66-11e1-995a-0050569d679d je sirotek
volume uuid:5e9c28fd-da65-11e1-995a-0050569d679d je sirotek
volume uuid:19541bfb-da65-11e1-995a-0050569d679d je sirotek
volume uuid:cc83b87f-da62-11e1-b232-0050569d679d je sirotek
volume uuid:d81832b2-da62-11e1-995a-0050569d679d je sirotek
volume uuid:df91ca2b-da5e-11e1-995a-0050569d679d je sirotek
volume uuid:09f980b8-da5f-11e1-b232-0050569d679d je sirotek
volume uuid:bdfdc78c-da5b-11e1-995a-0050569d679d je sirotek
volume uuid:5ed42ec6-da53-11e1-995a-0050569d679d je sirotek
volume uuid:6c2777a7-da50-11e1-995a-0050569d679d je sirotek
volume uuid:e49755c0-d872-11e1-967e-0050569d679d je sirotek
volume uuid:8251e159-7627-4258-8ec6-bf847c752ef1 je sirotek
volume uuid:59f4641f-ed5f-11e1-b9b5-0050569d679d je sirotek
volume uuid:1e7beebf-ed5f-11e1-b9b5-0050569d679d je sirotek
volume uuid:df42c8d7-ed5e-11e1-b9b5-0050569d679d je sirotek
volume uuid:aafe59e9-ed5e-11e1-b9b5-0050569d679d je sirotek
volume uuid:77ac885b-ed5e-11e1-b9b5-0050569d679d je sirotek
volume uuid:008f0597-ed5d-11e1-b9b5-0050569d679d je sirotek
volume uuid:812c5aa0-ed5b-11e1-b9b5-0050569d679d je sirotek
volume uuid:48e43397-ed5a-11e1-b9b5-0050569d679d je sirotek
volume uuid:d9e7af3b-ed58-11e1-b9b5-0050569d679d je sirotek
volume uuid:d150da35-ed57-11e1-b9b5-0050569d679d je sirotek
volume uuid:6fbb580d-ed54-11e1-b9b5-0050569d679d je sirotek
volume uuid:2b15d33e-ed51-11e1-b9b5-0050569d679d je sirotek
volume uuid:0d70e51f-ed4e-11e1-b9b5-0050569d679d je sirotek
volume uuid:ecb7640d-ed4a-11e1-b9b5-0050569d679d je sirotek
volume uuid:a25d9b36-ed47-11e1-b9b5-0050569d679d je sirotek
volume uuid:4cb75d87-ed44-11e1-b9b5-0050569d679d je sirotek
volume uuid:5dece987-ed41-11e1-b9b5-0050569d679d je sirotek
volume uuid:6c6b3a51-ed3d-11e1-b9b5-0050569d679d je sirotek
volume uuid:39de2ae4-ed3b-11e1-b9b5-0050569d679d je sirotek
volume uuid:3284ac65-ed39-11e1-b9b5-0050569d679d je sirotek
volume uuid:18dc1bd7-6b99-4f62-a7ee-094339c90595 je sirotek
volume uuid:f13b7f78-debf-4a95-9af6-97f6a22d17eb je sirotek
volume uuid:fe3c3e57-82d4-4989-9813-a7b52736c8d5 je sirotek
volume uuid:b83d14a9-f4b6-11df-8172-0050569d679d je sirotek
volume uuid:cadd24cf-0eda-4f63-a1b6-9dd30b5d8010 je sirotek
volume uuid:ae3d43b8-ac05-11e1-9335-0050569d679d je sirotek
volume uuid:121789c9-ac02-11e1-9335-0050569d679d je sirotek
volume uuid:7537a79a-abfe-11e1-9335-0050569d679d je sirotek
volume uuid:ac576d98-abfa-11e1-9335-0050569d679d je sirotek
volume uuid:c0b57f21-abf6-11e1-9335-0050569d679d je sirotek
volume uuid:c971f6f2-abf2-11e1-9335-0050569d679d je sirotek
volume uuid:727ca432-abef-11e1-9335-0050569d679d je sirotek
volume uuid:faf4595c-abea-11e1-9335-0050569d679d je sirotek
volume uuid:6c38ceff-abe8-11e1-9335-0050569d679d je sirotek
volume uuid:25366df7-abe5-11e1-9335-0050569d679d je sirotek
volume uuid:1eb868be-292b-41e8-8b9f-c2f966814964 je sirotek
volume uuid:0851cc0b-a433-487e-86bb-065885c25856 je sirotek
volume uuid:74941f94-76fe-11e0-ab3d-0050569d679d je sirotek
volume uuid:4224b0a9-8250-11e0-b92b-0050569d679d je sirotek
volume uuid:4190f375-825e-11e0-b92b-0050569d679d je sirotek
volume uuid:e8c2019a-8632-11e0-ab08-0050569d679d je sirotek
volume uuid:b598ce38-cae4-4c06-ba14-670db47e9275 je sirotek
volume uuid:bc294660-54bc-11de-bebf-000d606f5dc6 je sirotek
volume uuid:80cb5759-929f-11e0-8b47-0050569d679d je sirotek
volume uuid:c3c7e01b-a259-11e0-be09-0050569d679d je sirotek
volume uuid:0d93fdc0-d923-11e0-b33a-0050569d679d je sirotek
volume uuid:58025556-d925-11e0-b33a-0050569d679d je sirotek
volume uuid:0fcd3282-d928-11e0-b33a-0050569d679d je sirotek
volume uuid:684941cb-d92a-11e0-b33a-0050569d679d je sirotek
volume uuid:1fdb0da2-d92d-11e0-b33a-0050569d679d je sirotek
volume uuid:0ec2052a-d9e1-11e0-8d52-0050569d679d je sirotek
volume uuid:9fe1ac8c-d9e5-11e0-8d52-0050569d679d je sirotek
volume uuid:4cadb1f0-d9e3-11e0-8d52-0050569d679d je sirotek
volume uuid:ab1493d5-d9e7-11e0-8d52-0050569d679d je sirotek
volume uuid:18023ffc-d9ea-11e0-8d52-0050569d679d je sirotek
volume uuid:44dfb49e-873c-48b0-b9b8-587d8f740a7f je sirotek
volume uuid:369fc8ed-b10a-4444-bc98-28eaeb8d7369 je sirotek
volume uuid:af85600a-fe05-11e0-ae61-0050569d679d je sirotek
volume uuid:c9ed04df-fe05-11e0-ae61-0050569d679d je sirotek
volume uuid:2aef0057-fe06-11e0-ae61-0050569d679d je sirotek
volume uuid:89a2c707-fe06-11e0-ae61-0050569d679d je sirotek
volume uuid:f833d45a-fe06-11e0-ae61-0050569d679d je sirotek
volume uuid:4f0079c5-06d4-11e1-aa24-0050569d679d je sirotek
volume uuid:b5bf44be-06d4-11e1-aa24-0050569d679d je sirotek
volume uuid:34c98c5b-06d5-11e1-aa24-0050569d679d je sirotek
volume uuid:1621621a-06d6-11e1-aa24-0050569d679d je sirotek
volume uuid:f3eab9db-06d6-11e1-aa24-0050569d679d je sirotek
volume uuid:183340d2-06d8-11e1-aa24-0050569d679d je sirotek
volume uuid:7312b021-06d9-11e1-aa24-0050569d679d je sirotek
volume uuid:97e3ef36-06da-11e1-aa24-0050569d679d je sirotek
volume uuid:020a8095-06dc-11e1-aa24-0050569d679d je sirotek
volume uuid:a5fbe31b-06de-11e1-aa24-0050569d679d je sirotek
volume uuid:8fda60fc-06e0-11e1-aa24-0050569d679d je sirotek
volume uuid:756bfdec-06e3-11e1-aa24-0050569d679d je sirotek
volume uuid:c50d3195-06e1-11e1-aa24-0050569d679d je sirotek
volume uuid:1534ba39-06e5-11e1-aa24-0050569d679d je sirotek
volume uuid:32e7a7c0-06e7-11e1-aa24-0050569d679d je sirotek
volume uuid:8f3dbcdd-06e9-11e1-aa24-0050569d679d je sirotek
volume uuid:517b4663-06eb-11e1-aa24-0050569d679d je sirotek
volume uuid:ccb83c86-06ec-11e1-aa24-0050569d679d je sirotek
volume uuid:566813e2-06ee-11e1-aa24-0050569d679d je sirotek
volume uuid:147efe29-06f0-11e1-aa24-0050569d679d je sirotek
volume uuid:52746e90-06f2-11e1-aa24-0050569d679d je sirotek
volume uuid:d510cba7-06f4-11e1-aa24-0050569d679d je sirotek
volume uuid:31d92b24-06f7-11e1-aa24-0050569d679d je sirotek
volume uuid:e1d6eaeb-06f8-11e1-aa24-0050569d679d je sirotek
volume uuid:bb337dd8-06fa-11e1-aa24-0050569d679d je sirotek
volume uuid:9befe203-06fc-11e1-aa24-0050569d679d je sirotek
volume uuid:6584d74a-06fe-11e1-aa24-0050569d679d je sirotek
volume uuid:2a50106f-0700-11e1-aa24-0050569d679d je sirotek
volume uuid:dcd80955-0702-11e1-aa24-0050569d679d je sirotek
volume uuid:52fad770-0704-11e1-aa24-0050569d679d je sirotek
volume uuid:e8677297-0705-11e1-aa24-0050569d679d je sirotek
volume uuid:ecbf1632-0711-11e1-aa24-0050569d679d je sirotek
volume uuid:24481691-0714-11e1-aa24-0050569d679d je sirotek
volume uuid:8dc76c98-0715-11e1-aa24-0050569d679d je sirotek
volume uuid:dfcc52af-0716-11e1-aa24-0050569d679d je sirotek
volume uuid:2902e366-0718-11e1-aa24-0050569d679d je sirotek
volume uuid:7f25e6df-361c-11e1-a363-0050569d679d je sirotek
volume uuid:08e2709e-36df-11e1-959a-0050569d679d je sirotek
volume uuid:97f27f59-36e8-11e1-959a-0050569d679d je sirotek
volume uuid:2b0ee13c-36ed-11e1-959a-0050569d679d je sirotek
volume uuid:5827a6e5-36f0-11e1-959a-0050569d679d je sirotek
volume uuid:ae7c45f5-36f6-11e1-959a-0050569d679d je sirotek

**Comment by leiblix** [comment]
Chyby v NDK:

```
volume uuid:5c894120-ea5b-11e4-b834-005056827e51 je pripojeno do vice objektu
volume null je sirotek
volume uuid:88813f10-1e0c-11e4-8e0d-005056827e51 je pripojeno do vice objektu
volume uuid:0c5f71c0-994d-11e3-a880-5ef3fc9ae867 je pripojeno do vice objektu
volume uuid:a8f1e7e0-792a-11e3-9be6-005056827e52 je pripojeno do vice objektu
volume uuid:46e27230-6710-11e3-8fee-005056827e51 je pripojeno do vice objektu
volume uuid:765cff50-5ce1-11e3-bc9f-5ef3fc9bb22f je pripojeno do vice objektu
volume uuid:cdefd2f0-6340-11e3-ae93-001018b5eb5c je pripojeno do vice objektu
volume uuid:2d96bde0-4889-11e3-98d6-001018b5eb5c je pripojeno do vice objektu
volume uuid:ab4e4330-1147-11e3-beb8-005056827e51 je sirotek
volume uuid:7c6638d0-035e-11e3-9584-001018b5eb5c je pripojeno do vice objektu
volume uuid:435cfea0-19e5-11e3-9319-005056827e51 je pripojeno do vice objektu
volume uuid:7ec5ae60-c6de-11e2-ada5-005056825209 je sirotek
volume uuid:c8dbe070-c371-11e2-8b87-005056827e51 je pripojeno do vice objektu
volume uuid:37bb3210-c36e-11e2-ada5-005056825209 je pripojeno do vice objektu
volume uuid:53c1c460-c2ab-11e2-9592-5ef3fc9bb22f je pripojeno do vice objektu
volume uuid:5a994301-c380-11e2-b48c-001018b5eb5c je pripojeno do vice objektu
volume uuid:e6046c40-c2a8-11e2-b48c-001018b5eb5c je pripojeno do vice objektu
volume uuid:a9ffeb30-6c49-11e2-b55f-5ef3fc9bb22f je sirotek
volume uuid:36bed850-7bff-11e2-b9c7-5ef3fc9bb22f je sirotek
volume uuid:987e56a0-824f-11e2-bdc3-5ef3fc9bb22f je sirotek
volume uuid:a898dd70-8d40-11e2-b5bd-5ef3fc9bb22f je sirotek
volume uuid:c2f17c20-8d42-11e2-a920-005056827e51 je pripojeno do vice objektu
volume null je sirotek
volume uuid:7a2cbf90-8707-11e2-91d0-5ef3fc9ae867 je sirotek
volume uuid:01315c50-75c7-11e2-86a5-005056827e52 je sirotek
volume uuid:6b671cb0-75bb-11e2-9916-5ef3fc9ae867 je sirotek
volume uuid:cb8023e0-b6d8-11e2-8b87-005056827e51 je sirotek
volume uuid:2ff24830-969f-11e2-bc29-005056825209 je sirotek
volume uuid:f2f5d8b0-71ba-11e2-bf7c-5ef3fc9ae867 je sirotek
volume uuid:1019d300-6c44-11e2-bb2a-005056827e51 je sirotek
volume uuid:a5c65c10-706e-11e2-bc4b-001018b5eb5c je sirotek
volume uuid:f893d810-6f7d-11e2-bc4b-001018b5eb5c je sirotek
volume uuid:418d8140-5e55-11e2-aee2-5ef3fc9ae867 je sirotek
volume uuid:f12551a0-be1d-11e2-b48c-001018b5eb5c je pripojeno do vice objektu
volume uuid:475de930-7bff-11e2-88d1-005056825209 je sirotek
volume uuid:f774fc10-7a69-11e2-88d1-005056825209 je sirotek
volume uuid:220bdc00-7b32-11e2-87d4-5ef3fc9ae867 je sirotek
volume uuid:b8fd29d0-7a69-11e2-88d1-005056825209 je sirotek
volume uuid:741adb60-7b30-11e2-b212-005056827e52 je sirotek
volume uuid:8df83ba0-7779-11e2-9916-5ef3fc9ae867 je sirotek
volume uuid:ad2534c0-75c5-11e2-8c8d-5ef3fc9bb22f je sirotek
volume uuid:c4755340-54ea-11e2-af1a-005056825209 je sirotek
volume uuid:09cb13c0-8647-11e2-91d0-5ef3fc9ae867 je sirotek
volume uuid:0c4b9620-6c06-11e2-bb2a-005056827e51 je sirotek
volume uuid:9d8435f0-7cf7-11e2-b212-005056827e52 je sirotek
volume uuid:65931270-816a-11e2-80e3-005056825209 je sirotek
volume uuid:b076fc30-5b08-11e2-865f-005056822549 je sirotek
volume uuid:440f2050-3938-11e2-9688-005056827e51 je pripojeno do vice objektu
volume uuid:8f2cd320-8181-11e2-80e3-005056825209 je pripojeno do vice objektu
volume uuid:60a08b50-7cc2-11e2-b212-005056827e52 je sirotek
volume uuid:ada8af90-7bfa-11e2-b930-005056827e51 je sirotek
volume uuid:be3fa0b0-7cd7-11e2-88d1-005056825209 je sirotek
volume uuid:321a0cb0-7f52-11e2-8d9d-5ef3fc9bb22f je pripojeno do vice objektu
volume uuid:02f3cff0-5e25-11e2-9ead-001018b5eb5c je pripojeno do vice objektu
volume uuid:72b3b580-2e69-11e2-a240-005056825209 je pripojeno do vice objektu
```

**Comment by leiblix** [comment]
Seznam špatných issues v kramerius.mzk.cz

https://gist.github.com/MartinRumanek/9e7945f17d2c1e599cb2/edit

**Comment by Jenyk** [comment]
Tohle by bylo dobré prohledat a opravit i pro jiné modely (periodicalitem, page,..).
V K4-tools je skript AttachPeriodicalsNDK, co vyhledat sirotky libovolného modelu a případně je opravovat (když je to z NDK - rodiče hledá v K4 NKČR). Akorát hledá v solr a ne ve fedoře + nedá se použít na stránky (uuid stran v Brně a v Praze se liší).

Link na seznam špatných issues už nefunguje.

**Comment by LenkaKravecova** [comment]
@xermak00 Aleksei, můžeš, prosím, zkontrolovat, jestli jsi tato uuid opravil v rámci https://github.com/moravianlibrary/kramerius/issues/199? Předpokládám, že ano, ale radši se ptám, než to zavřu.

**Comment by kazooo** [comment]
Část volumů ze seznamů je opravená, druhá je smazaná jako duplicity. Odkaz na issue nefunguje, ale mají byt také opravené.

**Comment by LenkaKravecova** [comment]
Díky, zavírám.
