### ISSUE TITLE
Špatné obrázky

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#56]
Nahrávky 
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:07db6391-3adc-4d88-a1b1-35e8bc656ba9
a
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:0750ed1c-e36d-46d3-baea-5668e591e677 
mají na imageserveru obrázky s nulovou velikostí.
Víz http://imageserver.mzk.cz/mzk01/000/298/032/

**Comment by Jenyk** [comment]
Monografie http://kramerius.mzk.cz/search/i.jsp?pid=uuid:29c1bbf0-8b72-4aac-94fd-dc6338248360 vůbec nemá obrázky (na imageserveru chybí adresář s obrázky na cestě, kam se odkazuje z foxml: http://imageserver.mzk.cz/mzk01/001/207/119/)

**Comment by leiblix** [comment]
Podobné jako issue https://github.com/moravianlibrary/kramerius/issues/93, chybějící obrazová data
