### ISSUE TITLE
Travis build pro Kramerius a pro K5-api knihovnu

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#57]
Po úspěšném buildu Krameria se nahrají binárky (které jsou nutné pro build docker obrazu) na ftp-devel.mzk.cz

Pustí se následně rebuild docker-obrazu. Když to postupně celé projde, tak bude pod tagem devel aktuální build z master větve našeho kramerius repozitáře.

Něco podobného udělat pro K4-tools, při jeho buildu se vygeneruje jar, které je nutné nahrát sem http://ftp-devel.mzk.cz/mvnrepo/cz/mzk/k5/api/K5-API/1.0/

Btw. prosím vygeneruj pro to FTP jiné bezpečné heslo.

**Comment by jirkadev** [comment]
nastaveno nové heslo

**Comment by jirkadev** [comment]
Vyřešeno https://github.com/moravianlibrary/K4-tools/commit/f812bc40320fa05994341dbb543b5c12d8502de0 a https://travis-ci.org/moravianlibrary/K4-tools/builds/92244301
