### ISSUE TITLE
Optimalizace Postgres pro rychlý zápis

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#58]
"spin-off" z issue #52 . Je nutné zrychlit rebuild Fedory, čili optimalizovat Postgres pro co nejrychlejší zápis.

Pro začátek bude vhodné se odlepit z toho co sám postgres radí, to je:

```
LOG:  checkpoints are occurring too frequently (25 seconds apart)
HINT:  Consider increasing the configuration parameter "checkpoint_segments".
```
- věřím, že na internatu budou nějaká howto, co se dá dělat. Má smysl hledat optimalizace, které mají smysl pro SSD disk - ten nám bude někdy začátku pro účel spojení Fedor zapůjčen.

**Comment by MartinRumanek** [comment]
Prebal jsem si to, protoze Tomas na tom neudelal nic.
