### ISSUE TITLE
Dětský čin - opravit název v záložce prohlížeče

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#6]
Čin: uuid:c3318d70-6f69-11e2-b9fa-005056827e52 - v záložce v prohlížeči se objevuje název Dětský čin, což je alternativní název těchto periodik. Je to matoucí, musí tam být Čin. MODS se zdá být v pořádku, záleží, odkud to bere prohlížeč.

**Comment by Jenyk** [comment]
Tohle bude pravděpodobně bug Krameria

**Comment by Jenyk** [comment]
Založeno issue https://github.com/ceskaexpedice/kramerius/issues/242

**Comment by Jenyk** [comment]
No tak na ten problém už existuje issue https://github.com/ceskaexpedice/kramerius/issues/122 ze září 2014..

**Comment by leiblix** [comment]
Bylo opraveno. Už je to ok http://kramerius.mzk.cz/search/i.jsp?pid=uuid:c3318d70-6f69-11e2-b9fa-005056827e52

**Comment by honza-rychtar** [comment]
Nebylo opraveno.
Porad je v root_title Dětský čin.
Takze ve vsech klientech se to bude nekde zobrazovat. Napr. v K5 INCAD klientovi se root_title pouziva vsude. Zkuste tam vyhledat čin, ve vysledcich hledani je hned Dětský čin.
Problem je v tom jak se do root_title alternativni nazev dostal.

**Comment by honza-rychtar** [comment]
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:c3318d70-6f69-11e2-b9fa-005056827e52

**Comment by leiblix** [comment]
Máš pravdu, opravili pouze mírným "hackem" staré rozhraní, API jsem zapomněl zkontrolovat. Otevřu jim na to nové issue.

**Comment by leiblix** [comment]
Ve "starém" UI Krameria byla chyba vyřešena tím, že se místo root_title nyní používá vždy title.

Od dubna roku 2014 proběhla změna v indexeru, který chybný root_title minimálně u tohoto dokumentu vyřeší. 

Nicméně nebere se to vůbec z MODS, ale vezme se vždy první DC.title. Teoreticky může nastat situace, že v DC.title bude jako první uveden alternativní název a pak by se to zase zreindexovalo špatně. Budeme to brát jako chybu?

Samozřejmě musíme zjistit kolika dokumentů se tato chyba týká a zreindexovat to.

**Comment by honza-rychtar** [comment]
To ze se to bere z DC, kde by teoreticky mohl byt alternativni nazev na prvnim miste je jedna vec - v tom pripade chyba, otazka je jestli zmenit plneni DC nebo ziskavani title/root_title

Druha vec je, ze pres API nebo SOLR dostanu zaznam na nejvyssi urovni, u ktereho se lisi title a root_title - tohle by melo byt VZDY stejne.
Taky me zajimalo jak moc se to lisi a moc toho neni.
Tady https://docs.google.com/spreadsheets/d/193QbORBNcImC7-Lm7rcyvKBaDb19xB3-U94fXiq6Bxc/edit?usp=sharing
jsem nasdilel tabulku, kde je celkem 64 dokumentu (na nejvyssi urovni), kde se lisi title a root_title.
Je to brano ze SOLR ne z item pres API - ono je to stejne a klienti pro zobrazeni pouzivaji spis SOLR.
V te tabulce jsou 4 typy zaznamu.
typ 0: root_title je "null"
typ 1: root_title v sobe obsahuje title
typ 2: title v sobe obsahuje root_title
typ 3: title a root_title se lisi a jeden neobsahuje druhy

Typ 0 se opravi reindexaci.
Typy 1 a 2 by nemely nastat, ale je to dano jen komplexitou nazvu (jeden je sestaveny z vice casti nez druhy), takze to zas tak moc nevadi.
Typ 3 je problem - tady se title a root_title bere od jinud a lisi se hodne.

**Comment by honza-rychtar** [comment]
btw. v NDK Krameriovi je tech dokumentu 19 tisic. Z toho 7338 typu 3

**Comment by leiblix** [comment]
Toto je teda detektivní práce :-(

Nareplikoval jsem si pro testy dokument http://krameriustest.mzk.cz/search/i.jsp?pid=uuid:0e66f0f3-08c8-42e2-8d9a-b19e33ade62e

a po reindexaci se title a root_title rozjel:
- atribut title se do indexu dostává přes indexační šablonu K4.xslt, která bere vždy první DC.title v poslední verzi
- v aktuální verzi indexeru (https://github.com/ceskaexpedice/kramerius/blob/4ecfc50b650d55170e8ceed5f93a9d607df9cd24/indexer/src/cz/incad/kramerius/indexer/ExtendedFields.java#L250) se vezme první DC.title v první verzi (prostě starý neaktuální DC)

Nicméně tyto verzované datastreamy by v krameriusndktest.mzk.cz neměly vůbec být - dokument vznikne a už se needituje (rozhodně jich nikdo needitoval tisíce).

Jak si prosím získal ten seznam? Napsal sis skript nebo je možné v SOLR provést něco jako "not equal" pro dvě pole :)?

**Comment by honza-rychtar** [comment]
Stejna tabulka pro NDK: https://docs.google.com/spreadsheets/d/1E9K6LE8vQvGIUHD87fSfr9DBjoJmv9IVJXgSKeNKLcM/edit?usp=sharing

Ruby skript generujici tu tabulku:
https://gist.github.com/honza-rychtar/d9ffda3ee5bfe7b3fac4
Nahore pres `host` mozne zmenit Krameria.

Je toho fakt hodne, podivejte se na ty dole (typ 3). Vypada to na alternativni nazvy, casto je to v jednom anglicky a v druhem cesky. Taky jsou tam pripady, ze je to jednou s gramatickou chybou a jednou spravne.

Napada te, jak je mozne ze je toho v krameriusndktest.mzk.cz  19 tisic?

**Comment by leiblix** [comment]
Nevím, proč se to stalo a po pravdě se mi moc nechce vrtat ve starých zdrojácích a zjišťovat jak to kdy bylo a proč chyba vznikla. Postarám se akorát o to, aby se to opravilo v aktuální verzi a všechno to reindexujem (je toho moc, ale nějak si s tím poradíme).

Btw. teď mi došlo, že vlastně tou reindexací přesouváme dokumenty typu 0 do těch dalších skuptin, protože ta implementace reindexace do  root_title je implmentována špatně :-( Sepíšu na to dnes issue.
