### ISSUE TITLE
Instalace ostrého krameria na produkční docker

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#61]
Adresa produkčního dockeru 195.113.155.76 (stejná jako imageserver.mzk.cz)

Napojit na současný solr, fedoru....moźno se inspirovat z docker.mzk.cz:/docker-compose/krameriustest2.mzk.cz.

Prozatím použít hostname: kramerius-new.mzk.cz, které si dáš do /etc/hosts

Zbavíme se tím konečně apache a bude se nám to logovat do Kibany.

**Comment by leiblix** [comment]
-  použij obraz s tagem MZK (vzhled)
- přemigruj konfigurační soubory z kramerius.mzk.cz, ale budeš možná muset poupravit spojení do databáze (porovnej si to se současným mini konfiguračním souborem). Jediná významná změna bude, že nastavíš v configuration.properties activeProcesses=0 (to aby tento "veřejný" kramerius do budoucna nepouštěl procesy).

**Comment by jirkadev** [comment]
Pro oba kontejnery jak na docker.mzk.cz tak na imageserveru jsou téměř shodné dokcer-compose.yml

Na serveru imageserver.mzk.cz pro kontejener kramerius-new.mzk.cz
- funguje tag devel
- nefunguje mzkgrafika

Na serveru docker.mzk.cz pro kontejner kramerius-new.mzk.cz
- funguje tag mzkgrafika
- nefunguje tag devel
- funguje tag latest

docker-compose logs nic moc neřekne. WTF?

**Comment by leiblix** [comment]
Na imageserver.mzk.cz jsem udělal `docker-compose pull`, natáhl se nový obraz...v logách se mi objevilo, že se nemůže připojit do databáze - tak jsem opravil firewall na fedora.mzk.cz. No a už to jede :-)

**Comment by jirkadev** [comment]
Ok tak to bylo způsobeno nastavením firewallu.

**Comment by jirkadev** [comment]
Ještě je potřeba doplnit konfigurační soubory do kramerius-new.mzk.cz tak aby odpovídaly kramerius.mzk.cz

**Comment by leiblix** [comment]
Issue zrušeno. Místo produkčního Dockeru se použije Openshift.
