### ISSUE TITLE
Špatný formát u zvukového dokumentu

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#62]
Špatný mimetype u zvukového dokumentu http://kramerius.mzk.cz/search/api/v5.0/item/uuid:acde6bf0-c53b-43ac-8323-a6df6f589c34/streams/WAV

Protekl nám do Krameria nějaký AIFF/Amiga/Mac audio

```
assert "audio/x-wav" == detectMimetype(recordingWav)
                     |  |              |
                     |  audio/x-aiff   retrofit.ExceptionCatchingTypedInput$ExceptionCatchingInputStream@552518c3
                     false
```

**Comment by leiblix** [comment]
Seznam nalezených chyb v mimetypech nahrávek:

https://gist.github.com/MartinRumanek/016fb961263ec9b25728

**Comment by annie-cz** [comment]
Přesunuto na interní Gitlab MZK.
