### ISSUE TITLE
Smazaná mapa v nejnovějších 

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#65]
V nejnovějších Krameria MZK je mapa Austrálie, která nemá náhled a při prokliku to háže chybu HTTP status 500. Ve vyhledaných výsledcích není a ve Fedoře taky ne. Jak ji odstranit ze SOLRu?

**Comment by Jenyk** [comment]
Přes navigaci se dá vyfiltrovat daný model, v seznamu ho zaškrtnout a potom reindexovat nebo odstranit z indexu.
