### ISSUE TITLE
krameriusndktest.mzk.cz redirect

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#67]
Napsat do apache pravidla 301 Moved Permanently redirect, tak aby se vsechny odkazy presmerovaly na kramerius.mzk.cz.

S vyjimkou:
- TM modulu
- s vyjimkou staff vlan (nebo vycet adres naseho SDK kanclu)

Kazdy provedeny redirect se zaloguje s hodnotou REFERER (abysme vedeli odkud navstevnik prisel a mohli provest nejake kroky k zmene puvodniho linku).

**Comment by Jenyk** [comment]
Trochu problém s tím refererem =/
Server to nemůže prohlížeči nařídit - jen pošle nové URL a prohlížeč vyrobí nový request. 
Našel jsem nějaký průzkum, podle kterého v případě přesměrování 301 všechny 4 nejčastější prohlížeče zachovají původního referera. Ale je to z roku 2011, takže to samozřejmě dávno nemusí platit. Navíc se to může v čase měnit.
Jako jediný jistý způsob vypadá možnost přidání původního referera jako parametr do nového url (kramerius.mzk.cz/....?ref=...), ale to nevím, jestli se u nás dá použít.
Teď ještě hledám, jestli by se to nedalo logovat na ndk krameriu zároveň s přesměrováním.

**Comment by Jenyk** [comment]
Přesměrovává se všechno kromě 195.113.155.102 (brána zaměstnanecné sítě), 195.113.134.9 (TM) a loopback rozsahu
Hlavičku REFERER většinou prohlížeče zachovávají, případně je ta informace s spolu s návratovým status kódem v logu access.log -> stačí grepovat kód 301. Referer je předposlední hodnota, poslední je User-Agent. Prázdný referer se loguje jako "-".
