### ISSUE TITLE
Dokumentace serverů

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#68]

**Comment by Jenyk** [comment]
Přidat ke všem (produkčním) serverům lodní deník s popisem účelu, rozložení adresářů / disků / služeb + dát výraznou informaci do MOTD

**Comment by leiblix** [comment]
Toto je už zastaralé, dokumentace je na naší interní wiki - včetně nakreslené infrastruktury s diskovými úložišti ;)
