### ISSUE TITLE
Lišící se počet dokumentů na webu a v Android aplikaci

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#69]
Ve webové aplikaci se zobrazuje větší počet dokumentů než v mobilním klientovi (123715 monografií vs 123666). Každý pokládá trochu jiný dotaz do SOLR.

Android aplikace se ptá na fedora modely:
http://kramerius.mzk.cz/search/api/v5.0/search?q=fedora.model:monograph&start=0&rows=30

Webová aplikace na typ dokumentu:
http://kramerius.mzk.cz/search/api/v5.0/search?q=document_type:monograph&start=0&rows=30

Není myslím důvod, aby byly případy, kdy se document_type liší od modelu, proto to zařazuji jako chybu v datech.

**Comment by LenkaKravecova** [comment]
Nebudeme řešit. Možná v budoucnu otevřeme.

**Comment by rzeh4n** [comment]
Ty situace, že se document_type liší od modelu, obecně nastávat asi budou. Nevím, jak v MZK, ale třeba pro DiFMOE se uvažuje o rozlišení model:periodical na noviny a časopisy právě podle document_type.
@honza-rychtar
