### ISSUE TITLE
Zelené čtverečky u monografie, která je private

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#7]
http://krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:ed1a5170-e8e4-11e4-b834-005056827e51

zámečky to asi vyřeší

**Comment by honza-rychtar** [comment]
Problem neni to problem v datech - prvni stranka DC: http://krameriusndktest.mzk.cz/search/api/v5.0/item/uuid:ed1a5170-e8e4-11e4-b834-005056827e51/streams/DC
Ani problem v API - vcechny stranky:  http://krameriusndktest.mzk.cz/search/api/v5.0/item/uuid:ed1a5170-e8e4-11e4-b834-005056827e51/children

Je to chyba klienta. Dival jsem se na zdrojaky a staci opravit jeden radek.
Kdyz si zobrazite zdrojaky: krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:b48beb70-ed76-11e4-b834-005056827e51
Tak na radku 514 je: 
var p = isPrivate(uuid);
Aby to fungovalo, tak to musi byt:
var p = isPrivate(ext_uuid);
Pak by to fungovat melo.

To isPrivate najde li element ze seznamu vlevo a pta se na pritomnost class "private"
Prodobne isPublic na pritomnost class "public"
Ted isPrivate i isPublic vraci false, protoze se snazi ten li element referencovat pres id rovno uuid, ale ty elementy maji id jako uuid i s tim prefixem, tj. ext_uuid.

Konkretni misto ve zdrojacich Krameria je tady:
https://github.com/ceskaexpedice/kramerius/blob/master/search/web/inc/details/thumbs.jsp
Radek 207, misto uuid dat ext_uuid.

Zkusis to Martine?

**Comment by leiblix** [comment]
Díky, po té opravě to funguje :+1:, ty studuješ kód Incadu?. Pošlu jim to ještě dnes jako pull-request. Díky. 

Ale stejně jsem krameriusndktest.mzk.cz přepl na :lock:, jsou lepší a hlavně ať je to u nás konzistentní. (přepíná se to direktivou `search.policy.public=false`)

**Comment by leiblix** [comment]
Zatím jsem vrátil zelené čtverečky, aby byla vidět chyba, než bude schválen ten pull-request....
