### ISSUE TITLE
Spojení uživatelských účtů

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#70]
Přemigrování uživatelských účtů z instalace krameriusndktest.mzk.cz. Při této příležitosti promazat staré administrátorské účty (pokud existují, editor uživatelů sám o sobě neumožňuje takové uživatele vypisovat).

**Comment by leiblix** [comment]
Tento dotaz vygeneruje csv soubor s uživateli, kteří mají větší než běžné oprávnění:

```
COPY (SELECT active_users.active_users_id, active_users.loginname, firstname, active_users.surname, gname, email FROM active_users NATURAL JOIN active_users_2_roles JOIN group_entity ON active_users_2_roles.role_id=group_entity.group_id JOIN user_entity ON active_users.loginname=user_entity.loginname WHERE group_entity.gname!='public_users' AND group_entity.gname!='common_users') TO '/tmp/krameriusadmins.csv' WITH CSV;
```

V následujícím dokumentu je seznam uživatelů, kteří mají větší oprávnění https://docs.google.com/a/mzk.cz/spreadsheets/d/1wVg7UPwZTWDg5cpwWsCWxZNki95cuJjP46jy_wjqfYk/edit?usp=sharing

Jsou tam dva taby jeden pro původní MZK kramerius, druhý pro NDK. Zazeleňme prosím políčka lidí, u kterých si myslíme, že by jim měl zůstat přístup. Ostatní před spojením smažu.

Plus některým uživatelům stačí can_read_all a nemusí být přímo admini - takové prosím označit v poznámce.

**Comment by LenkaKravecova** [comment]
Pooznačovala jsem na obou záložkách. Když má ale někdo účet v kramerius.mzk.cz, přenášet se to nemusí, ne?
