### ISSUE TITLE
Dělnická rovnost 1930 - nelze změnit policy

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#72]
Dělnická rovnost, ročník 1930 - uuid:68a2fb70-4a57-11e5-a525-5ef3fc9ae867 - neprovedla se změna viditelnosti u většiny čísel. Hlásí to toto:

WARNING: Cannot set policy for object uuid:5a2bb270-4e0e-11e5-a525-5ef3fc9ae867, skipping: java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException:  Caused by: failed to rename with .bak extension /mnt/fedora-merged/objects/2015/0831/14/16/uuid_5a2bb270-4e0e-11e5-a525-5ef3fc9ae867

**Comment by LenkaKravecova** [comment]
U těchto čtyř ročníků (Český svět) stejný problém:
uuid:8f3dccd0-73be-11e4-b2f6-005056827e51
uuid:3682ce70-79f8-11e4-8ce5-005056827e52
uuid:d3a0c940-7972-11e4-ad1c-005056827e51
uuid:d4339ac0-796f-11e4-964c-5ef3fc9bb22f

**Comment by leiblix** [comment]
Hlášení od Zdeňka
Při zpřístupnění periodika Český svět: illustrovaný čtrnáctidenník (uuid:9ee4d9f0-6a7a-11e4-9d98-005056825209) mi opakovaně nejdou zveřejnit roky 1913-1914, 1918-1919, 1919-1920, 1920-1921.

**Comment by LenkaKravecova** [comment]
To jsou ty ctyri, o kterych jsem tu psala pred 10 dny :) Takze tento problem uz fakt hori.

**Comment by leiblix** [comment]
Už na tom děláme. Možná problém způsobuje unionfs, který jsem použil po spojení Fedor. Migruji importní rok 2015, dnes by to mohlo doběhnout - budeme vědět jestli je to tím.

**Comment by LenkaKravecova** [comment]
Prosím, jak to vypadá? Už jsou ročníky zmigrované? Mám to zkusit přeindexovat?

**Comment by LenkaKravecova** [comment]
To samé uuid:abe060c0-aab8-11e3-a597-5ef3fc9bb22f (Křesťanská revue, ročník 3)

**Comment by leiblix** [comment]
Dělnická rovnost, ročník 1930 - uuid:68a2fb70-4a57-11e5-a525-5ef3fc9ae867 je spraveno. Migrace roku 2015 pomohla, tak ještě ty další importní roky...

**Comment by leiblix** [comment]
Celá Fedora je odmigrovaná z unionfs. Je to tedy vyřešené, změna viditelnosti nebude dále zlobit.
