### ISSUE TITLE
Archa - rozbité obrázky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#73]
Periodikum Archa má rozbité obrázky u ročníku 1912-1913 (č. 1 - uuid:c1c139f1-3ea8-11e2-acfc-5ef3fc9ae867) a 1913 (č. 1 - uuid:687a9cb1-3ea8-11e2-893a-001018b5eb5c). Každý má jedno číslo. 
Např.:
http://imageserver.mzk.cz/NDK/2012/09d1cbd0-2331-11e2-8579-005056827e52/1_00072.tif/big.jpg

Obrázky u ostatních ročníků se zdají být ok.

**Comment by leiblix** [comment]
Obrázky tam nejsou, nevím proč...
- narazil jsem teď na další nesrovnalost v roce 2015, budou rozbité obrázky v polovině roku 2015.

lrwxrwxrwx     1 1016 1016      30 Aug 19 15:58 01 -> /data3/imageserver/NDK/2015/01
drwxr-xr-x  3373 1011 1011  348160 Feb 28  2015 02
drwxr-xr-x  9187 1011 1011  942080 Mar 31  2015 03
drwxr-xr-x 12140 1011 1011 1245184 Apr 30  2015 04
drwxr-xr-x  9820 1011 1011 1007616 May 31  2015 05
drwxr-xr-x  4396 1011 1011  450560 Sep 12 10:08 06
lrwxrwxrwx     1 1016 1016      30 Dec  5 13:10 07 -> /data3/imageserver/NDK/2015/07
lrwxrwxrwx     1 1016 1016      30 Aug 19 23:00 08 -> /data3/imageserver/NDK/2015/08
lrwxrwxrwx     1 1016 1016      30 Dec  5 13:11 09 -> /data3/imageserver/NDK/2015/09
lrwxrwxrwx     1 1016 1016      30 Dec  5 13:11 10 -> /data3/imageserver/NDK/2015/10
lrwxrwxrwx     1 1016 1016      30 Oct 30 10:55 11 -> /data3/imageserver/NDK/2015/11
lrwxrwxrwx     1 1016 1016      30 Oct 30 10:55 12 -> /data3/imageserver/NDK/2015/12

**Comment by Jenyk** [comment]
Obrázky z roku 2015 jsou v pořádku, viz například http://imageserver.mzk.cz/NDK/2015/02/153e31d0-aea2-11e4-a7a2-005056827e51/UC_153e31d0-aea2-11e4-a7a2-005056827e51_0001/big.jpg

Obrázky z Archy tam fakt nejsou. Ale v NK je to v pořádku a ve WF nevidím žádnou podezřelost. Zkouším je ještě najít mezi všema, ale asi bude potřeba to smazat a znova naimportovat z LTP.

**Comment by leiblix** [comment]
Ok, copypaste nepřenáší barvy :-D

![rozbitelinky](http://i.imgur.com/oKMdBro.png)

...únor je zrovna v pohodě

**Comment by Jenyk** [comment]
No podle mě to funguje všechno:
http://imageserver.mzk.cz/NDK/2015/01/2c83d670-6d01-11e4-8c6e-001018b5eb5c/UC_2c83d670-6d01-11e4-8c6e-001018b5eb5c_0001/big.jpg

Ty symlinky jsou v pořádku při pohledu z krameriusndktest.mzk.cz.

Jinak find doběhl bez výsledku, takže fakt bude potřeba to smazat a znova importovat z LTP. A potom při hledání haluzí se určitě musí kontrolovat i existence obrázků.

**Comment by leiblix** [comment]
Aha! Ono to funguje, protože v docker-compose.yml máme tento hack:
 `/mnt/ndk03:/data3`

zevnitř kontejneru to pak funguje, na tento hack jsem úplně zapomněl :horse:, sorry.

**Comment by LenkaKravecova** [comment]
Takže je potřeba to nechat z LTP importovat znovu? @Jenyk zadával jsi ticket nebo to mám udělat?

**Comment by LenkaKravecova** [comment]
sorry nechtěla jsem to zavřít

**Comment by Jenyk** [comment]
Zadal jsem ticket (id 3943)

**Comment by LenkaKravecova** [comment]
Opraveno. Zavírám.
