### ISSUE TITLE
Zveřejnit tato uuid

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#75]
Prosím dávkově zveřejnit těchto 89 uuid. Jde o monografie a mělo by to být vždy kořenové uuid.
[uuid na zpristupneni.txt](https://github.com/moravianlibrary/kramerius/files/118469/uuid.na.zpristupneni.txt)

**Comment by LenkaKravecova** [comment]
A tady dalších 331 na zveřejnění.
[K4_zverejnit.xlsx](https://github.com/moravianlibrary/kramerius/files/118471/K4_zverejnit.xlsx)

**Comment by Jenyk** [comment]
Některé procesy skončily warningem kvůli https://github.com/moravianlibrary/kramerius/issues/72

**Comment by LenkaKravecova** [comment]
:-(

**Comment by Jenyk** [comment]
[zverejnit_uuid_z_NK.txt](https://github.com/moravianlibrary/kramerius/files/155293/zverejnit_uuid_z_NK.txt)
Přidávám ten nový seznam sem, ať je to pohromadě. Zveřejním to všechno včetně těch neúspěšných až @MartinRumanek dokončí migraci fedor. To by mělo být začátkem příštího týdne, vyřeší se tím issue 72

**Comment by leiblix** [comment]
Co tady je tady ten proces?

http://kramerius.mzk.cz/search/inc/admin/_processes_outputs.jsp?uuid=517ef9b7-3064-4ef7-b6d1-c9d8426032d9

**Comment by Jenyk** [comment]
Takových případů bylo celkem 15, včera jsem je prošel a zveřejnění spustil znova ručně. Proběhlo to bez problému.
Způsobily to duplicity v těch seznamech - proces běžel zároveň nad svazkem i kořenem vícesvazkového díla.
