### ISSUE TITLE
Docker kontejner s verzí 5.3.1

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#77]
Potřeboval jsem vyzkoušet novou verzi Krameria a v tagu 5.3.1_mzkgrafika je obsažena verze 5.2.0. 

Prosím tedy o opravu tohoto tagu + vytvoření tagu 5.3.1 bez grafiky.

Není potřeba to dělat na hub.docker, ale asi na našem openshiftu (ale bylo by vhodné nastavit propagaci až do hubu)

**Comment by jirkadev** [comment]
zatím mám image 5.3.1 na hubu https://hub.docker.com/r/moravianlibrary/kramerius/builds/bguagoz6nucdtqnn9gxqfth/

**Comment by leiblix** [comment]
do budoucna řeší openshift a s2i
