### ISSUE TITLE
Stavy rachotí - uuid:858d2b50-c486-11e3-b110-005056827e51

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#78]
UUID této monografie je ve Fedoře, ale nic pod ním není. Dala jsem ji reindexovat z Krameria, ale pak jsem zjistila, že se tam ani nemá co indexovat. V minulosti proběhla aktualizace z LTP. Takže asi neúspěšně a je třeba to poslat z LTP znovu? Je třeba ještě něco prověřit na naší straně?

**Comment by leiblix** [comment]
Taky je divné, že přes REStový požadavek http://*****:8080/fedora/get/uuid:858d2b50-c486-11e3-b110-005056827e51 se vrátí 403? @Jenyk Viděl si už někdy něco takového?

**Comment by LenkaKravecova** [comment]
@Jenyk Podíváš se na to, prosím?

**Comment by Jenyk** [comment]
http://fedora-spojena.mzk.cz:8080/fedora/objects/uuid:858d2b50-c486-11e3-b110-005056827e51
vrací 401 Unauthorized ale neptá se na jméno/heslo. 
Ale s basic auth hlavičkou to jde.

**Comment by Jenyk** [comment]
FOXML toho objektu: https://gist.github.com/Jenyk/3dc107ad04ea1592878d

**Comment by LenkaKravecova** [comment]
Takže opět LTP nebo si s tím ještě chceš pohrát?

**Comment by Jenyk** [comment]
No podle mě to z LTP nepůjde, protože to ve fedoře je

**Comment by leiblix** [comment]
@Jenyk Tak bychom to mohli smáznout, ale zatím to nech. Ten objekt se mi vůbec nelíbí a musíme zjistit, jestli je to ojedinělý případ.

**Comment by Jenyk** [comment]
V tomhle stavu by se to právě mazalo celkem těžko

**Comment by leiblix** [comment]
Ono to jakože smazané je: "audit:justificationMarked as deleted/audit:justification".

Každopádně zajímavé, že podstránky ve Fedoře (i v indexu jsou). Jak se to do tohoto stavu mohlo dostat? Co to "mazalo"? TM?

**Comment by LenkaKravecova** [comment]
Takže co navrhujete?

**Comment by LenkaKravecova** [comment]
@MartinRumanek @Jenyk Jestli k tomu máte něco nového nebo už víte jak to řešit, můžete to dát sem? Díky.

**Comment by leiblix** [comment]
Buď se to smaže nějakým skriptem, který by napsal @Jenyk, nebo se upraví Editor, aby si s tímto poradil (což stejně budeme muset možná řešit, viz referenced issue).

@Jenyk Máš k tomu nějaký další poznatek? Teď NDK z Krameria maže nebo označuje jako deleted?

**Comment by Jenyk** [comment]
Tohle už vypadá v pořádku, pravděpodobně to mělo prostě příznak DELETED a teď je to po hromadném mazání deleted dokumentů opravdu smazané. Zřejmě jsme zbytečně panikařili.
Může se to reimportovat z LTP. Dokonce je možné, že už to v LTP mají ve frontě a že jsem to mazal na jejich žádost (proto stav deleted) :)

@MartinRumanek Teď se v krameriu maže natvrdo.

**Comment by Jenyk** [comment]
@LenkaDamborska co s tímhle? Může se to zavřít?

**Comment by Jenyk** [comment]
Pahýl je odstraněný, byl zadán požadavek na reimport z LTP

**Comment by LenkaKravecova** [comment]
Dokument už je v pořádku v K5.
