### ISSUE TITLE
Čin - nejdou vidět obrázky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#82]
Nechápu, kramerius.mzk.cz neukazuje obrázky:
http://kramerius.mzk.cz/search/handle/uuid:c3318d70-6f69-11e2-b9fa-005056827e52
http://krameriusndktest.mzk.cz/search/handle/uuid:c3318d70-6f69-11e2-b9fa-005056827e52

Čin se hodně používá. Prosím o prioritní opravu.

**Comment by Jenyk** [comment]
Problém je v tom, že odkazy na obrázky jsou ve starém tvaru: http://krameriusndktest.mzk.cz/imageserver/NDK/2013/46af4780-4261-11e3-ac54-005056825209/UC_46af4780-4261-11e3-ac54-005056825209_0001/big.jpg

místo http://imageserver.mzk.cz/NDK/2013/46af4780-4261-11e3-ac54-005056825209/UC_46af4780-4261-11e3-ac54-005056825209_0001/big.jpg

Běží skript na opravu.

**Comment by LenkaKravecova** [comment]
@Jenyk je nějaký pokrok?

**Comment by leiblix** [comment]
Ten skript na opravu, asi selhal, že? Budeme ho muset pustit znovu, ale prosím až zítra - tuto noc běží migrace roku 2013 na nové úložiště.

**Comment by Jenyk** [comment]
Neselhal, doběhlo to dneska v noci. Jenže je to v roce 2015, takže už přemigrované.

**Comment by leiblix** [comment]
Aha! Takže to musíš pustit znova přímo na nové Fedoře v adresáři  /mnt/fedora-rsync/fedora/objects/2015 (a stejně tak pro 2014).

**Comment by Jenyk** [comment]
Tak už to běží nad 2015

**Comment by Jenyk** [comment]
Před chvílí to doběhlo nad 2015 a Čin je spravený, takže zavírám. Ještě to radši spustím nad 2014.
@MartinRumanek chceš z toho nechat logy? Jsou řádově v GB

**Comment by LenkaKravecova** [comment]
Bezva!
