### ISSUE TITLE
Chybejici 'datum vydani' v cisle periodika

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#83]
Jsou dve moznosti, jak mit tento udaj v MODSu ulozeny:
1) http://kramerius.mzk.cz/search/api/v5.0/item/uuid:b82784d7-435d-11dd-b505-00145e5790ea/streams/BIBLIO_MODS
part -> detail -> date
Tohle se propaguje do API:
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:b82784d7-435d-11dd-b505-00145e5790ea

2) http://kramerius.mzk.cz/search/api/v5.0/item/uuid:3d459a90-a40d-11e5-b404-005056825209/streams/BIBLIO_MODS
originInfo -> dateIssued
Toto se do API nepropaguje!
http://kramerius.mzk.cz/search/api/v5.0/item/uuid:3d459a90-a40d-11e5-b404-005056825209

V druhem pripade se v klientech nezobrazuje datum vydani u seznamu cisel a v detailu cisla. Pritom v datech je.

To stejne plati i pro item/uuid/children a item/uuid/siblings

**Comment by LenkaKravecova** [comment]
Podle možnosti 2) jede celé NDK a všechny další současné digitalizace, je to ve standardu. 
Podle možnosti 1) se zpracovávala starší digitalizace.
To by se do API mělo propagovat, když je to od začátku ve standardech...

**Comment by honza-rychtar** [comment]
@MartinRumanek podivas se na to?

**Comment by Jenyk** [comment]
Na (mj.) tohle existuje issue už skoro 2 roky: https://github.com/ceskaexpedice/kramerius/issues/92

**Comment by leiblix** [comment]
@Jenyk  Je to něco podobného, ale myslím, že se zobrazovací šablonou to nesouvisí.

Spíš je to podobné issue https://github.com/ceskaexpedice/kramerius/issues/217, kterým se opravilo číslo ročníku, ale nedořešila se úroveň čísla.

Podívám se na to.

**Comment by LenkaKravecova** [comment]
Je to opraveno, ale dokumenty se musí reindexovat. Máme v plánu do budoucna (až opraví datum vydání u příloh).

**Comment by xburda4** [comment]
Zoznam všetkých periodík, ktoré v Krameriu momentálne sú: https://docs.google.com/a/mzk.cz/spreadsheets/d/1qLug9jIJqc0SekyZS05araDGz_Gl9C6bhcsteGEye9w/edit?usp=sharing

Budem to reindexovať na Solr6 a postupne tabulku aktualizovať.

**Comment by zabak** [comment]
Jak to dopadlo? Potřeboval bych aby se mohlo pohnout s https://github.com/honza-rychtar/kramerius-web-client/issues/167
Předpokládám ale, že bude potřeba aby reindexovaly všechny knihovny kterých se to týká, že?

**Comment by leiblix** [comment]
No podle tabulky ještě nemáme reindexované všechno.

Jinak ano, knihovny si musí nasadit novější verzi Krameria a reindexovat.

**Comment by kazooo** [comment]
Všechny uuid z tabulky zreindexovany.
