### ISSUE TITLE
ČDK timeout

### ISSUE THREAD

**Issue by Jenyk** [moravianlibrary/kramerius#84]
Dotaz http://kramerius.mzk.cz/search/api/v4.6/cdk/prepare?rows=500&date=2015-06-10T10:55:02.777Z vrací 500 Read timed out.
(pod uživatelem s právem na replikaci)

**Comment by leiblix** [comment]
Spraveno konfigurační volbou v souboru `configuration.properties` http.timeout=15000 (=15 s). Dotaz obvykle trvá něco přes 4 s.
