### ISSUE TITLE
API: Datum ve vybranych

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#86]
Dotaz na nejnovejsi http://kramerius.mzk.cz/search/api/v5.0/feed/newest
obsahuje navic datum_str a issn oproti vybranym http://kramerius.mzk.cz/search/api/v5.0/feed/custom

Je mozne pridat datum_str i do vybranych?

**Comment by leiblix** [comment]
@honza-rychtar Je to dost staré issue :-(, chceš to ještě vůbec?

**Comment by honza-rychtar** [comment]
No jako to datum se hodi. V novinkach (beru pres solr, ne pres feed/newes) a ve vysledcich hledani zobrazuju autora a pokud neni autor vyplneny, tak zobrazim datum. Az pokud neni ani jedno, tak vypisu autor neuveden.
Ve vybranych (ktere nedostanu jinak nez pres feed/custom) nemam informaci o datu, takze "autor neuveden" pisu kdykoli, kdy neni autor.
Hodi se to hlavne u periodik, kde nebyva autor, tak zobrazim datum, coz je dobre info pro periodikum.

Takze ted kdyz si vyhledas Lidove noviny, tak na karte Lidove noviny mas datum.
Ale na karte Lidove noviny ve vybranych mas "autor neuveden", protoze nemam tu informaci o datu.

**Comment by xburda4** [comment]
Práve som nasadil verziu krameria, kde http://kramerius.mzk.cz/search/api/v5.0/feed/custom datum_str aj issn obsahuje rovnako ako v newest, ale stále tam píše "autor neuveden". @honza-rychtar Treba ešte dačo poriešiť na strane krameria alebo v klientovi ?

**Comment by honza-rychtar** [comment]
V soucasne verzi uz zase datum_str neni.

**Comment by leiblix** [comment]
Opravené a v MZK nasazené. Bude to součástí nové verze, která vyjde někdy příští týden - budou si to moc nasadit i jiné knihovny.
