### ISSUE TITLE
Album representantů - nové obrázky

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#87]
Máme nové obrázky k uuid:6d962368-9ce3-11e0-9ad4-0050569d679d, sysno 000936117 (mzk01). Jsou v tif a mají 31,8 GB. Je potřeba je zkonvertovat a nahrát na imageserver (@dsecik) a pak je spárovat se stávajícími uuid stran, vyměnit linky ve foxml a smazat staré obrázky z Fedory (@Jenyk). Strany by měly sedět.

**Comment by dsecik** [comment]
Obrazky su skonvertovane a nahrane na [imageserver ](http://imageserver.mzk.cz/mzk01/000/936/117/)
