### ISSUE TITLE
Dějiny národu českého v Čechách a v Moravy - rozbité obrázky

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#88]
http://kramerius.mzk.cz/search/i.jsp?pid=uuid:4ba3a670-cc12-11e2-a712-005056827e51

```
III 05, 2016 10:36:30 ODP. cz.incad.Kramerius.imaging.ImageStreamsServlet doGet
SEVERE: http://kramerius.mzk.cz/imageserver/NDK/2013/4ba3a670-cc12-11e2-a712-005056827e51/UC_4ba3a670-cc12-11e2-a712-005056827e51_0001/thumb.jpg
java.io.FileNotFoundException: http://kramerius.mzk.cz/imageserver/NDK/2013/4ba3a670-cc12-11e2-a712-005056827e51/UC_4ba3a670-cc12-11e2-a712-005056827e51_0001/thumb.jpg
```

**Comment by leiblix** [comment]
@Jenyk Co s tím, dá se to odněkud obnovit?

**Comment by Jenyk** [comment]
Zase stejný problém - obrázky jsou odkazované přes http://kramerius.mzk.cz/imageserver/ :-/ 
Nechal jsem znova projet 2013

**Comment by Jenyk** [comment]
Vracím se k tomu po době a je to v úplně jiném stavu.
Obrázky jsou odkazované takhle: `4ba3a670-cc12-11e2-a712-005056827e51_0001.jp2/big.jpg`, tzn. je potřeba odstranit koncovky .jp2 a přidat prefix `http://imageserver.mzk.cz/NDK/2013/4ba3a670-cc12-11e2-a712-005056827e51/UC_`.

To by nebyl problém, ale dotazy do fedory na jednotlivé stránky vrací 401, i když záznamy ve fedora3 i ritriples vypadají dobře a foxml existují.

**Comment by jkremlacek** [comment]
Na chybu jsem narazil v rámci https://github.com/moravianlibrary/kramerius/issues/265 (obsahuje i popis chyby a postup opravy). Strany jsem opravil.
