### ISSUE TITLE
Nefunkční uuid

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#90]
52 nefunkčních uuid, na které odkazuje Aleph. Třeba ověřit, jestli chybí v indexu nebo jsou úplně smazaná z Fedory.
Seznam od Petry:
[errorId.txt](https://github.com/moravianlibrary/kramerius/files/168954/errorId.txt)

**Comment by LenkaKravecova** [comment]
To poslední uuid bylo akorát chybně v Alephu, chyběl tam poslední znak. Funkční je, takže 51 nefunkčních uuid :)

**Comment by leiblix** [comment]
stavy:
404 - úplně chybí
403 - označená jako deleted
200 - možné reindexovat

Takjže 404 a 403 jsou prostě smazané, měly by se smazat z alephu - nebo se můžeme snažit o nějaký reimport z NDK.

uuid:00c23000-f5dd-11e2-9923-005056827e52:404
uuid:01f4e350-a1cd-11e2-9a9f-005056827e51:403
uuid:084e9c10-a5e9-11e4-a808-005056827e52:404
uuid:08bb9f50-75cf-11e2-abbe-005056827e51:404
uuid:0ab8cd20-a8e4-11e3-9d7d-005056827e51:404
uuid:0afcc850-4b8c-11e3-9c86-005056827e51:403
uuid:217b2130-c9b4-11e2-b6da-005056827e52:404
uuid:23117f50-ef69-11e2-9923-005056827e52:404
uuid:24278c10-2b26-11e3-a5bb-005056827e52:404
uuid:2b74c890-97b7-11e3-a880-5ef3fc9ae867:403
uuid:2d7e6ad0-d802-11e2-bcca-005056827e51:404
uuid:33480f20-73a7-11e3-a698-5ef3fc9bb22f:200
uuid:38f837e0-b40e-11e3-9d7d-005056827e51:404
uuid:4b6e53d0-24e1-11e3-9319-005056827e51:404
uuid:4c47a590-eade-11e3-b72e-005056827e52:404
uuid:571aa8a0-f359-11e2-9923-005056827e52:404
uuid:59a6aae0-68ae-11e3-8561-005056827e52:200
uuid:62faadf1-9fba-42cc-8c4b-eab13f9d403c:200
uuid:6ad4f0b0-97f5-11e5-ac67-005056827e51:200
uuid:6f139c20-9de3-11e3-8e84-005056827e51:404
uuid:752e6f80-b577-11e3-b833-005056827e52:404
uuid:756e8870-f5da-11e2-9923-005056827e52:404
uuid:820a3710-331a-11e2-824c-005056827e51:403
uuid:858d2b50-c486-11e3-b110-005056827e51:403
uuid:8c2b5140-1a03-11e3-a5bb-005056827e52:404
uuid:8e3c9cd0-f49c-11e4-88cd-005056827e52:403
uuid:925fecc0-4a2d-11e2-abe9-005056827e51:403
uuid:9a63ed40-4a2d-11e2-abe9-005056827e51:403
uuid:9db8a280-9f75-11e3-8e84-005056827e51:404
uuid:9f6e0370-7c19-11e2-b930-005056827e51:404
uuid:acdbd010-c42f-11e2-b6da-005056827e52:404
uuid:b013c370-2266-11e2-85be-005056827e51:403
uuid:b0851e20-9eda-11e3-a744-005056827e52:404
uuid:b1442920-a450-11e3-a597-5ef3fc9bb22f:404
uuid:b2149360-6bd0-11e4-9d98-005056825209:403
uuid:b5255f60-cf9c-11e3-94ef-5ef3fc9ae867:200
uuid:be562240-2736-11e3-a5bb-005056827e52:404
uuid:c2b0b460-d324-11e2-8f90-005056827e51:404
uuid:c8ac0f50-0316-11e3-9923-005056827e52:404
uuid:cd463be0-e2e0-11e2-9923-005056827e52:200
uuid:dccd3250-0598-11e3-9923-005056827e52:404
uuid:e1cdb1c0-ce6c-11e2-8c80-005056827e52:404
uuid:e75f65b0-b319-11e3-9d7d-005056827e51:404
uuid:f66790e0-4449-11e2-9b88-005056827e51:403
uuid:f89e1c90-7765-11e2-abbe-005056827e51:403
uuid:fad50fc0-87e3-11e3-997d-005056827e52:404
uuid:fc643000-dbfd-11e3-93a3-005056825209:200

**Comment by LenkaKravecova** [comment]
Co bylo potřeba reindexovat, jsem udělala. Zbytek jsem dala na odstranění z Alephu.
