### ISSUE TITLE
přeložit intro7 do angličtiny

### ISSUE THREAD

**Issue by zabak** [moravianlibrary/kramerius#92]
http://kramerius.mzk.cz/search/?language=en&#intro7

**Comment by LenkaKravecova** [comment]
Nepřišla jsem na to, jestli je na tohle napojený nějaký jiný textový soubor. Zdá se, že ne.

**Comment by LenkaKravecova** [comment]
Možná @zabak myslel intro8 (Informace)? 
@jirikrepl, potřebuju zjistit, v jakém souboru to je.. Mělo by to být pak i v novém klientovi.

**Comment by LenkaKravecova** [comment]
Jo, tak intro8 jsou Informace po přihlášení :) :)

**Comment by jirkadev** [comment]
Anglický text se nastavuje v souboru `intro` a český v souboru `intro_CZ_cs`

Nyní je potřeba to jen přeložit
