### ISSUE TITLE
Rozbitý obrázek uuid:f6c15dc7-b09e-4985-8905-f08abeee5b28

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#93]
Rozbitý obrázek - http://kramerius.mzk.cz/search/handle/uuid:f6c15dc7-b09e-4985-8905-f08abeee5b28

http://imageserver.mzk.cz/mzk01/000/332/179/f6c15dc7-b09e-4985-8905-f08abeee5b28/big.jpg
http://imageserver.mzk.cz/mzk01/000/332/179/f6c15dc7-b09e-4985-8905-f08abeee5b28/thumb.jpg

**Comment by Jenyk** [comment]
Ten obrázek v imageserveru chybí. Monografie má 174 stran, ale jen 173 obrázků.

**Comment by LenkaKravecova** [comment]
Prosba o dosken, následně stranu do dokumentu připojím.
