### ISSUE TITLE
Periodika - řazení příloh

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#94]
Je nutné vymyslet nějaký proces, který seřadí přílohy v Brněnských novinách a příp. i jinde. Čísla jsou seřazená v pořádku, ale přílohy seřadit nejdou (funkcí Třídit). 
Teď to vypadá takto divoce, přílohy se řadí asi podle přírustku: http://kramerius.mzk.cz/search/handle/uuid:a101de00-2119-11e3-a5bb-005056827e52
Půjde to? Nedělali jsme už něco takového, @Jenyk ?

**Comment by LenkaKravecova** [comment]
A ještě Brünner Zeitung.... http://kramerius.mzk.cz/search/handle/uuid:eb3adc60-dd58-11e2-9923-005056827e52 Tam je to vůbec divočina, protože těch druhů příloh je víc a bude potřeba je poskládat za sebe podle názvu a pak podle čísel.

**Comment by LenkaKravecova** [comment]
V podstatě to vyřešil @honza-rychtar v klientovi, takže zavírám. Jinak na řazení příloh jsem založila issue #426 v hlavní větvi.

**Comment by LenkaKravecova** [comment]
@jenyk postupoval podle instrukcí zde https://github.com/ceskaexpedice/kramerius/issues/426, ale pořád se to neřadí správně. Např. se neřadí správně přílohy ani čísla v tomto ročníku: http://kramerius.mzk.cz/search/handle/uuid:7a18c630-fa27-11e4-8ded-5ef3fc9ae867 (jak v Krameriu, tak i v klientovi, proto by byla potřeba to řešit už na úrovni Krameria).

**Comment by jirkadev** [comment]
[Brněnské noviny](http://kramerius.mzk.cz/search/handle/uuid:a101de00-2119-11e3-a5bb-005056827e52) mají špatně seřazené přílohy.

Udělal jsem replikaci [ročníku 1898](http://kramerius.mzk.cz/search/handle/uuid:4a10b180-640c-11e3-8c6a-005056825209) na [krameriusTest](http://krameriustest.mzk.cz/search/handle/uuid:4a10b180-640c-11e3-8c6a-005056825209). Na krameriuTest se přílohy seřadily správně. 

U stejného dokumentu (periodiukum) jsem na krameriuTest smazat index. Ve foxml [periodicalVolume](http://fedoratest.mzk.cz/fedora/get/uuid:4a10b180-640c-11e3-8c6a-005056825209) jsem přeházel přílohy a spustil třídění. Přílohy se v [KrameriuTest](http://krameriustest.mzk.cz/search/handle/uuid:4a10b180-640c-11e3-8c6a-005056825209) seřadily správně.

Na ostrém krameriu jsem smazal periodikum z indexu a spustil třídění. Přílohy se neseřadily správně. Přílohy ve foxml jsou seřazeny správně, v indexu nikoliv.

Konkrétně -  třídění správně seřadí přílohy (uuid) ve foxml dokumentu [periodicalVolume (ročník 1898)](http://10.2.0.75:8080/fedora/objects/uuid:4a10b180-640c-11e3-8c6a-005056825209/datastreams) Indexace neproběhne správně.

V [tomto gistu](https://gist.github.com/jirikrepl/8bea5208da077fd255b42ae9c58f7376) mám odkazy na zmiňované dokumenty

EDIT:
Vypadá to, že jsem našel bug. Ročník '1898' (nebo jiný libovolný ročník) nelze smazat z indexu [Krameria](http://kramerius.mzk.cz/search/i.jsp?pid=uuid:4a10b180-640c-11e3-8c6a-005056825209) ani [KrameriaTest](http://krameriustest.mzk.cz/search/i.jsp?pid=uuid:4a10b180-640c-11e3-8c6a-005056825209) (postup: zatržený ročník a volba smazat z indexu). Ročník "nezmizí" z Krameria.

**Comment by MarosGrm** [comment]
Radenie príloh už funguje ako má. Po zoradení a reindexácii sú prílohy v správnom poradí.
