### ISSUE TITLE
Nezobrazuje se celá signatura

### ISSUE THREAD

**Issue by jirduf** [moravianlibrary/kramerius#95]
V Krameriovi se zobrazuje jen začátek signatury ve tvaru LOKACE-XXXX.XXX a chybí vše, co následuje. Např. zde je signatura Skř.1T-1251.865,53 zkrácená: http://kramerius.mzk.cz/search/handle/uuid:ed01f8a5-57f0-4e8a-ba6b-c0b060c52490 (záložka popis) - úplný tvar je např. zde https://vufind.mzk.cz/Record/MZK03-001084045.

**Comment by leiblix** [comment]
V DublinCore je to dobře
dc:identifiersignature:Skř.1T-1251.865,53/dc:identifier

Ale v MODsu se to rozdělilo do dvou polí a proto to blbne.

```
<ns2:shelfLocator>Skř.1T-1251.865</ns2:shelfLocator>
<ns2:shelfLocator>53</ns2:shelfLocator>
```

Asi chyba šablony v editoru, prověříme.

**Comment by leiblix** [comment]
Chyba nahlášená v editoru https://github.com/moravianlibrary/MEditor/issues/74

Ale bude nutné opravit i data zpětně.

**Comment by LenkaKravecova** [comment]
Dokumenty z editoru jsou opraveny. Jirka se ještě podívá na NDK produkci.

**Comment by jirkadev** [comment]
Opravil jsem i NDK tímto [skriptem](https://github.com/moravianlibrary/K4-tools/blob/master/Groovy/src/modsShelfLocator/modsFixDuplicatedShelfLocator.groovy). Většina monografií je současným skriptem opravena. Další typy dokumentů jsou OK.

Skript funguje takto: pokud má MODS více než jeden element shelfLocator. Pak se dívá jestli element druhý až n-tý element obsahuje pouze čísla (s max čtyřmi řády). Pokud ano spojí takovéto elementy do jednoho elementu. Tohle odchytí většinu případů.

Případné vylepšení by bylo pro MODS více než jedím elementem shelfLocator se pomocí čárového kódu, nebo sysna podívat přímo na data v alephu pole 910 podpole b. A případně je opravit v Mods.
