### ISSUE TITLE
Davidova houpacka - chybna struktura

### ISSUE THREAD

**Issue by honza-rychtar** [moravianlibrary/kramerius#96]
http://www.digitalniknihovna.cz/mzk/periodical/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6
Prvni tri rocniky maji spatnou strukturu (jsou mimo strukturu), kdyz si je rozkliknu, tak nemaji metadata - nemaji spravne prirazeny root dokument. Nasledujici/predchozi rocnik listuje jen mezi temato trema.

Problem je tady - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:5a2dd690-54b9-11de-8bcd-000d606f5dc6/children
Seznam rocniku periodika - prvni tri rocniky maji spatny root_pid - neshoduje se s uuid, pres ktery dotaz zadavam. To je nesmysl - jak se muze neco dostat do stavu, ze je children od dokumentu X a zaroven ma parent Y, kde X != Y???
Tohle pak zpusobuje problem, protoze kdyz se rozkliknu do nektereho z prvnich 3 rocniku, tak se nactou data (metadata rootu a sourozenci) pro spatny dokument, takze metadata se nezobrazi, neda se prejit na dalsi rocnik mimo ty 3 spatne a zpet na seznam rocniku vede do prazdneho seznamu - ten spatny root_pid zadne rocniky neobsahuje.

Problem bude ve dvojim kontextu u tech 3 rocniku - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:303c91b0-490a-11de-921d-000d606f5dc6
Kde prvni kontext vede z neexitujiciho uuid a hlavne z jineho, nez z ktereho jsem se na uroven rocniku dostal!!

Dvoji kontext je na tehle urivni nesmysl tak ci tak (i kdyby prvni kontext bylo existujici periodikum), cesta dolu se neshoduje s cestou nahoru. I pokud najdete realny priklad, kdy rocnik patri do dvou periodik, tak je to imho spatne, protoze to nepujde rozumne zobrazit a mela by se struktura zmenit.

Kazdopadne v tomhle pripade jen u tech 3 rocniku umazte prvni kontext a nechte jen ten druhy. UUID toho prvniho kontextu vubec neexistuje - http://kramerius.mzk.cz/search/api/v5.0/item/uuid:5414a6f0-4904-11de-9ac7-000d606f5dc6

**Comment by LenkaKravecova** [comment]
Ahoj, čtu to až teď. Tohle periodikum jsem spojovala ručně přes editor. Bylo na dvou místech. Přesunula jsem ročníky pod jedno uuid a to druhé jsem smazala. To bude předpokládám to neexistující.

**Comment by honza-rychtar** [comment]
A co ted? Staci to preindexovat?

**Comment by Jenyk** [comment]
Omlouvám se za zpoždění. Ano, stačí reindexace. Už je to v pořádku.
