### ISSUE TITLE
Prozkoumání aktualizace SOLR

### ISSUE THREAD

**Issue by leiblix** [moravianlibrary/kramerius#97]
Prozkoumat co by obnášelo nasazení novější verze SOLR.

Minulý týden vyšel SOLR 6 a my jsme v Krameriu zaseklí na verzi 3. 

Hodila by se nám deep pagination (zmiňoval @Jenyk ), plus by bylo fajn mít možnost využít OpenShift imagestreamů od CPK a běžet SOLR ve více instancích.

**Comment by LenkaKravecova** [comment]
Nechat na Incad.
