### ISSUE TITLE
Přidání kolekce nahrávek do VS vyhodí nahrávky z Krameria

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/kramerius#98]
Do sbírky Zvukové nahrávky jsme s Filipem přidali 5 kolekcí a u všech zmizely zvukové stopy, zůstaly jen strany. Co s tím?

**Comment by leiblix** [comment]
Je pouze špatná reindexace, takže data se neztratila. A v nové verzi Krameria se to asi neprojevuje (z OpenShiftu to půjde spravit).

**Comment by honza-rychtar** [comment]
A kdy teda pojede Kramerius ostre v OpenShiftu? :)

**Comment by leiblix** [comment]
Obrazy máme nachystané, ještě to teď s @dsecik testujeme.

**Comment by LenkaKravecova** [comment]
Jak to vypadá s těmi rozbitými zvukovými nahrávkami??

**Comment by leiblix** [comment]
V Openshiftu se to neprojevuje, ale ten má teď jiné problémy, že .....

Takže to bude nutné opravit v současné instalaci, ale já na to čas asi nemám, vezme si to někdo jiný?

**Comment by LenkaKravecova** [comment]
Reindexace v 5.3.3 nepomohla. @jirikrepl, zkus to, prosím, prozkoumat.

**Comment by jirkadev** [comment]
Problém je v riSearch naší fedory. U některých audio nahrávek chybí vazby (triplety) hasSoundUnit a containsTrack. 

Jakmile se spustí indexace, indexační proces nanajde vazby sound_unit a containsTrack a do SOLR vloží  audio nahrávku bez vazby na sound_units a tracks

Dobře je toto vidět při [srovnání xml](https://www.diffchecker.com/hmazpjen), která se vkládají do SOLR. (elementy `<field name="parent_pid">` a `<field name="root_pid">` )

Budeme muset napsat skript, který ověří, že:
- každý objekt _sound_recording_ má vazbu na _sound_unit_
- každý objekt _sound_unit_ má vazbu na _track_

**Comment by Jenyk** [comment]
Tohle se nestává jen u nahrávek, už jsem na stejný problém narazil u periodik.
Lepší by bylo napsat skript, který pro kořenové uuid rekurzivně najde potomky z RELS-EXT ve fedoře a ověří, že jsou dané vazby i v ritriples. 
Tohle by se potom dalo využít při plánovaném "hledání haluzí" v datech.

Pro rychlou opravu by mělo stačit přepsat RELS-EXT novou verzí, např. v admin. menu fedory smazat obsah a dát ho tam znova. Fedora si to potom zpracuje správně.

**Comment by jirkadev** [comment]
OK, to by bylo fajn to napsat dost obecně rekurzivně. Zatím jsem napsal skript co znovu vytvoří vazby k sound_unit (buildRiTriples.grooovy) https://github.com/moravianlibrary/K4-tools/commit/953f9e2e66185f1f24374ba8c18791df469b7add 

> Pro rychlou opravu by mělo stačit přepsat RELS-EXT novou verzí, např. v admin. menu fedory smazat obsah a dát ho tam znova. Fedora si to potom zpracuje správně.

Fedora potom přidá vazbu do riTriples?

**Comment by LenkaKravecova** [comment]
Jinak vazby k sound_unit jsou opravené, nahrávky by už z Krameria indexací mizet neměly.
